### ISSUE TITLE
requires pinned dependency version pbr<1.7.0

### ISSUE THREAD

**Issue by anthraxx** [miguelgrinberg/python-socketio#10]
pbr has already released its 1.8.1 version, is the bug that made you pin pbr for socketio fixed there? If yes, could you please change the pinning of the required version? I'm planning to package this library for a distribution where we only ship the most current version of everything

**Comment by miguelgrinberg** [comment]
I removed the pin. Thanks.

**Comment by anthraxx** [comment]
wow, including a new release. super awesome :+1: :heart:
