### ISSUE TITLE
Logger=False Still Shows Some Shutdown Logs

### ISSUE THREAD

**Issue by frankgreco** [miguelgrinberg/python-socketio#1052]
Question 👇🏼 

When using the `AsyncClient` with both `logger` and `engineio_logger` set to `False`, I am still receiving these logs upon shutdown. How do I turn these off?

```
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10272b7c0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x10274cc40>, 526328.995571708)]']
connector: <aiohttp.connector.TCPConnector object at 0x10272bd30>
```

**Comment by miguelgrinberg** [comment]
These are coming from aiohttp, not from this package, and they are alerting you of a connection leak. If you are using an older version of this package, try upgrading to latest.

**Comment by frankgreco** [comment]
@miguelgrinberg Thanks for the quick reply. I'm using `aiohttp==3.8.3` which seems to be the latest. I can share my code but AFAIK i'm doing the standard teardown (close socket, wait for it to shutdown, etc) but perhaps there's something obvious i'm missing?

**Comment by frankgreco** [comment]
One thing I don't understand is why the client is still trying to poll (and receiving `failed with error Server disconnected.`) after I call `disconnect` (as shown by the `disconnected ` log that logs the server disconnect ack).

**Comment by miguelgrinberg** [comment]
I meant if you were using older versions of python-socketio and python-engineio.

I can't really comment on the polling attempt. I just checked what happens after a disconnect here (using the fiddle.py server and the fiddle_client.py examples in this repo) and I do not see double logs, or attempt to poll after disconnect, or aiohttp errors on exit. If you want to provide a small example that I can use to reproduce the problem I'm happy to take a more in depth look.
