### ISSUE TITLE
option for KeyboardInterrupt to not cause disconnect

### ISSUE THREAD

**Issue by TodAmon** [miguelgrinberg/python-socketio#1060]
It appears that I cannot write an application that does its own thing with KeyboardInterrupt, as the underlying engineio client interprets this as a disconnect.  There is no option when creating a client to tell it to ignore KeyboardInterrupt.  Thoughts?

**Comment by miguelgrinberg** [comment]
You can pass `handle_sigint=False` and then you are free to do what you want using a custom interrupt handler. Did you see that in the docs?

**Comment by TodAmon** [comment]
Sorry, I tried it but must have missed something, maybe I'm on an older version.  I saw it was an option for engineio
```
(Pdb) socketio.Client(handle_sigint=False)
*** TypeError: __init__() got an unexpected keyword argument 'handle_sigint'
```

**Comment by miguelgrinberg** [comment]
Yes, you must be on older code. I see it in the Client class in this repo [here](https://github.com/miguelgrinberg/python-socketio/blob/main/src/socketio/client.py#L100).
