### ISSUE TITLE
socketio server transport=websocket on mac m1 causes ConnectionError without any details

### ISSUE THREAD

**Issue by baseman** [miguelgrinberg/python-socketio#1061]
A client had a setup using _transport=websocket_ (code below) which encountered a raised [ConnectionError] with no explanation...

**To Reproduce**

using
- python v3.9 
- python-socketio 4.x -> currently v4.6.1

```
import asyncio
import os

import socketio

TOKEN = os.getenv("TOKEN")

sio = socketio.AsyncClient(
    logger=True,
    engineio_logger=True
)


@sio.event
async def message(data):
    print(f"I received a message!: {data}")


@sio.on("state")
async def on_state(data):
    print(f"I received a state: {data}")


if __name__ == "__main__":
    async def main():
        headers = {"Authorization": f"Bearer {TOKEN}"}
        await sio.connect(
            "wss://mysockethost:443",
            socketio_path="/events",
            namespaces=["state"],
            transports=["websocket"],
            headers=headers,
        )
        await sio.wait()


    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())

```

**Expected behavior**

Already confirmed the above code is working on non mac m1 computers. How to get this working on mac m1

**Stack**
code raises ConnectionError at line 194 -195 in ./package-path/engineio/client.py

```
return getattr(self, '_connect_' + self.transports[0])(
            url, headers or {}, engineio_path)
```

**Comment by miguelgrinberg** [comment]
Please provide server and client logs.

**Comment by miguelgrinberg** [comment]
Please provide server and client logs.

**Comment by baseman** [comment]
```
Attempting WebSocket connection to wss://client-host.io:443/socket.io/?transport=websocket&EIO=3
INFO:engineio.client:Attempting WebSocket connection to wss://client-host.io:443/socket.io/?transport=websocket&EIO=3
2022-10-13 09:34:23,095 - socket-connector - MainThread - INFO - initializing connection to web socket url [wss://client-host.io:443/events]: headers [{'Authorization': 'Bearer <auth>'}]
2022-10-13 09:34:23,882 - socket-connector - MainThread - ERROR - socket-connector websocket encountered error: error data [Connection error]
2022-10-13 09:34:23,883 - socket-connector - MainThread - ERROR - error initialized connection to web socket url [wss://client-host.io:443/events]: error [Connection error]
Traceback (most recent call last):
  File "/working/socket_connector/websocket_client", line 85, in connect
    sio.connect(
  File "/venv/lib/python3.9/site-packages/socketio/client.py", line 286, in connect
    six.raise_from(exceptions.ConnectionError(exc.args[0]), None)
  File "<string>", line 3, in raise_from
socketio.exceptions.ConnectionError: Connection error
Traceback (most recent call last):
  File "/working/socket_connector/app.py", line 33, in <module>
    client.connect(
  File "/working/socket_connector/websocket_client", line 94, in connect
    raise err
  File "/working/socket_connector/websocket_client", line 85, in connect
    sio.connect(
  File "/venv/lib/python3.9/site-packages/socketio/client.py", line 286, in connect
    six.raise_from(exceptions.ConnectionError(exc.args[0]), None)
  File "<string>", line 3, in raise_from
socketio.exceptions.ConnectionError: Connection error
```

**Comment by baseman** [comment]
Server logs cannot currently be provided as they are from a 3rd party client

**Comment by miguelgrinberg** [comment]
I can't tell you what's wrong. The server knows, but the information is not included in the HTTP response.

**Comment by baseman** [comment]
I found the error but it was related to the path. maybe a more descriptive error indicating connection can't be found?

**Comment by miguelgrinberg** [comment]
What was the actual mistake that you made? I don't understand how can a path work on Intel macs and not work on M1 macs.

**Comment by baseman** [comment]
the issue was the person who reported the problem left out the detail that he had changed the path. We got a connection error but had no details concerning the error. So would a message indicating that the error was cause because the socket couldn't be found?

**Comment by baseman** [comment]
I wasn't able to determine if the connection could be found or if there was a connection error that was encountered on route. eg. indicating that a path can be found when the host was able to be connected to would be really helpful.

**Comment by miguelgrinberg** [comment]
You attempted to make a WebSocket request, and the server rejected it. That's all the information that I have.

If you had used the Socket.IO protocol in the standard way, which is to first attempt a long-polling connection and only upgrade to WebSocket after long-polling is connected, then the HTTP response from the HTTP connection attempt would have given me more information. I really don't know what the issue was with your server exactly, but if this was a path not found problem, then the polling attempt would have returned with a 404 status code, and that number would have been included in your error message. Likewise, if the path was correct but your authentication credentials were incorrect, you would have seen a 401 (or maybe 403) status code in the error message, whatever the server decided to respond with.

**Comment by baseman** [comment]
so 
1. can it connect to the host: yes it can
2. can it connect to the path: no

Are you saying you can't check to see host connectivity vs path connectivity?

**Comment by miguelgrinberg** [comment]
What I'm saying is that this is a high-level protocol. I rely on third-party libraries to make connections to servers, I don't deal with the low-level stuff. When the 3rd party library provides details such as an HTTP status code, I include them in the error message. If I'm not told, then I provide the best error message I can generate with the information that I have.
