### ISSUE TITLE
Server throws sanic.exceptions.ServerError after disconected.

### ISSUE THREAD

**Issue by 4n1qz5skwv** [miguelgrinberg/python-socketio#1062]
This issue still exist https://github.com/miguelgrinberg/python-socketio/issues/711 |  https://github.com/miguelgrinberg/python-engineio/issues/221

Any chance for it to get fix? A warning in doc about this compatibility issue would have saved us today 😒

Love your python-socketio library. No matter what web frameworks we choose we always check if that is compatible with this lib. It is very helpful. I know this issue just going to get closed. But before that can you please share one insight... 
Among these frameworks (https://unit.nginx.org/howto/#frameworks) can you please tell, which async framework (except quart) is fully compatible with python-socketio (server) and also python-socketio (server) will have no issue with it when run by unit either?

Thank you.

**Comment by miguelgrinberg** [comment]
As I explained in the issue you referenced, the problem is caused by a Sanic limitation that has no workaround.

In terms of support, ASGI is probably the best option, instead of a tight integration with a web framework. This should even work with Sanic when you use it in ASGI mode.

**Comment by miguelgrinberg** [comment]
What I mean is that when you use ASGI there are no errors, because the Sanic and Socket.IO ASGI apps are completely independent.

**Comment by miguelgrinberg** [comment]
@4n1qz5skwv Look at the ASGI examples in this repository please. You are still using the Sanic integration, not ASGI.

**Comment by miguelgrinberg** [comment]
> Why a normal sanic user won't use sio = socketio.AsyncServer(async_mode='sanic') when it's clearly instructed by the doc.

Because the Sanic team broke this on their side. What I'm going to do is to recommend the ASGI integration above the Sanic one in the docs.

**Comment by CPrescher** [comment]
Could you please give a full example how to get sanic working with asgi app? The above code snippet does not work for me.

**Comment by miguelgrinberg** [comment]
@CPrescher the documentation section on ASGI shows how to do this. See https://python-socketio.readthedocs.io/en/latest/server.html#uvicorn-daphne-and-other-asgi-servers. Replace `other_app` with your Sanic/ASGI application.

**Comment by CPrescher** [comment]
@miguelgrinberg hi, but this only means the sanic server is used for normal http requests, but not for socketio, is this correct? Is there no way currently to use socketio with sanic (without the errors upon disconnect)? In my tests 1 year ago, Sanic was always the fastest of all possibilities for socketio.

**Comment by miguelgrinberg** [comment]
@CPrescher I don't really understand what you are saying. Sanic is never "used" for Socket.IO (I'm not even sure what do you mean by this). Sanic and Socket.IO always run as separate apps hosted under the same web server.

**Comment by CPrescher** [comment]
@miguelgrinberg Ok, sorry, I guess my understanding is limited about web servers, maybe framework is the better word here?

What I meant is, using:

```python
import socketio
from sanic import Sanic

sio = socketio.AsyncServer(async_mode='sanic', cors_allowed_origins="*")
app = Sanic("My Sanic App")
sio.attach(app)

if __name__ == '__main__':
     app.run()
```

basically, the example you are having on the documentation, was having the best performance for me.

When using sanic as other_app for the ASGIApp as the following:

```python
sio = socketio.AsyncServer(async_mode='asgi', cors_allowed_origins="*")
sanic_app = Sanic("Sanic App")

app = socketio.ASGIApp(sio, sanic_app)

if __name__ == '__main__':
    uvicorn.run(app, host="127.0.0.1", port=8000)
```

i get the following error:

```
sanic_routing.exceptions.FinalizationError: Cannot finalize with no routes defined.
ERROR:    Cannot finalize with no routes defined.
ERROR:    Application startup failed. Exiting.
```

but this would also not use the sanic 'framework' for socketio handling, correct? 

If I am missing the right vocabulary here, could you point me to some source, to understand these things better?

**Comment by CPrescher** [comment]
@miguelgrinberg Hi, thank you for the fast response! I did tests with large data blobs sent via socket.io locally (e.g. 16 Mb) and sanic was by far the fastest solution for a local backend with an electron app (4 times faster than with tornado). But maybe when deployed on the web, this will be different. I will try to measure and benchmark the other solutions when this time comes.

I think i understand now a bit more about the socketio integration into web servers. Thank you. 

The error is related to Sanic, because of the missing route, it just for me showed that there is no connection between socketIO and Sanic using this way. They are just living next to each other...
