### ISSUE TITLE
How to shorten 10 second timeout for .connect()

### ISSUE THREAD

**Issue by dcarr178** [miguelgrinberg/python-socketio#1070]
**Describe the bug**
When my python code tries to connect to my socket-io server but the server is not running, it takes 10 full seconds before the .connect() function times out. Using the code snippet shown below, the connect function starts at 01:18:02 and times out at 01:18:12. 

[2022-10-19 01:18:02.304] (/code/lib/src/cr/lib/connections.py:connections:get_socketio_client) - INFO - cr.lib - Connecting to socket-io server http://socket_io:3000
[2022-10-19 01:18:12.321] (/code/lib/src/cr/lib/connections.py:connections:get_socketio_client) - WARNING - cr.lib - Connection to socket-io server http://socket_io:3000 failed

**To Reproduce**
  
          import socketio
          SOCKETIO_SSL_VERIFY = False

            # the request timeout does nothing to stop library from waiting for 10 seconds before connection times out
            # I have not found any way to shorten the timeout.
            _socketio_client = socketio.Client(ssl_verify=SOCKETIO_SSL_VERIFY, request_timeout=1)

            auth = {"Authorization": "xxxx"}
            try:
                log.info("Connecting to socket-io server {}".format(SOCKETIO_URI))
                _socketio_client.connect(url=SOCKETIO_URI, auth=auth, wait_timeout=1)
            except socketio.exceptions.ConnectionError:
                # cannot connect to socket server
                message = "Connection to socket-io server {} failed".format(
                    SOCKETIO_URI
                )
                log.warning(message)
                _socketio_client = None

**Expected behavior**
When the socket server is not running or cannot be found, I would expect the connect function to time out almost immediately, within 1 second, or within some other user-defined timeout period.

**Logs**
See above

**Additional context**
After I start the socket-io server and retry, the connection gets established immediately. The problem is only when the target socket-io server is not running or otherwise not responding.

**Comment by miguelgrinberg** [comment]
The timeouts that are used at the network socket layer are not controlled by this package. If you want to use different defaults, you can provide an HTTP client instance that is initialized with your desired timeouts in the `http_session`.

The bad news is that the Requests package has refused to add support for globally setting timeouts in a `Session` object, so you'll have to resort to tricks to do it. Some options are explained in [this GitHub issue](https://github.com/psf/requests/issues/2011). Once you have a properly configured `Session` object, you can pass it to the Socket.IO client to use.
