### ISSUE TITLE
can't send bytes to server

### ISSUE THREAD

**Issue by jolahua** [miguelgrinberg/python-socketio#1071]
## version
python-socketio       5.7.1
python-engineio       4.3.4

I have a binary file, read it as rb and send to server:

### code
```
sio = socketio.AsyncClient(logger=True, engineio_logger=True)

await sio.connect('http://localhost:8080', auth={'token': token}, wait_timeout=10)
    path = r'C:\Users\*****.log'
    # async with aiofiles.open(path, 'rb') as f:
    #     res = await f.read()
    # print(type(res))
    with open(path, "rb") as f:
        await sio.emit('parse', {'file': f.read()})
    await sio.wait()

if __name__ == '__main__':
    # asyncio.get_event_loop().run_until_complete(main())
    asyncio.run(main())
```

and the log is 

### log

> Signal handler is unsupported
> Attempting polling connection to http://:8080/socket.io/?transport=polling&EIO=4
> Polling connection accepted with {'sid': 'BkUa53HOtSdKjlJlAAAA', 'upgrades': ['websocket'], 'pingTimeout': 20000, 'pingInterval': 25000}
> Engine.IO connection established
> Sending packet MESSAGE data 0{"token":""}
> Attempting WebSocket upgrade to ws://localhost:8080/socket.io/?transport=websocket&EIO=4
> WebSocket upgrade was successful
> Received packet NOOP data 
> Received packet MESSAGE data 2["connect",["yP61lQMUaqIzADFoAAAB",{"res":"\u8fde\u63a5\u6210\u529f"}]]
> Received event "connect" [/]
> Received packet MESSAGE data 0{"sid":"yP61lQMUaqIzADFoAAAB"}
> Namespace / is connected
> Emitting event "parse" [/]
> Sending packet MESSAGE data 51-["parse",{"file":{"_placeholder":true,"num":0}}]
> Sending packet MESSAGE data <binary>
> **Unexpected error decoding packet: "object of type 'int' has no len()", aborting**
> Waiting for write loop task to end
> Exiting write loop task
> Engine.IO connection dropped
> Exiting read loop task
> Connection failed, new attempt in 0.95 seconds
> (['yP61lQMUaqIzADFoAAAB', {'res': 'success'}],) {}
> () {}

and i just can't understand why i got this error, i see the document say that is support binary; and the emit func is support with bytes.
but when i read a normal txt file, it is correct
please help, ths

**Comment by miguelgrinberg** [comment]
Likely related to https://github.com/miguelgrinberg/python-engineio/issues/292.

Okay, so what I think is going here is that you are sending a binary packet that the server does not like. As a response the server closes the WebSocket connection. The client takes the close packet, and incorrectly treats it as a data packet. In normal data packets the data is string or bytes, but in a close packet, the data attribute contains an integer. So this is the reason of the error.

So my action item is to make the client more robust, by checking for close packets and acting appropriately when one is received. This won't solve the problem though, it would just make the client fail gracefully. You need to investigate why the server might not like your binary emit. One reason could be that it is larger than its configured maximum payload size.

**Comment by jolahua** [comment]
yes! is maximum payload size.but i have reach another question

i have set the `max_http_buffer_size = 1000000000` which i increase to 1G

the beyong file is 2M and it is success send to the server
when i use a 50M file and i failed again with the same question and has another bug:

### log

> Signal handler is unsupported
> Attempting polling connection to http://localhost:8000/socket.io/?transport=polling&EIO=4
> 1 2 {'hello': 'you'}
> connected to server
> Polling connection accepted with {'sid': 'D3yrZPEu8OgjBRLfAAAA', 'upgrades': ['websocket'], 'pingTimeout': 20000, 'pingInterval': 25000}
> Engine.IO connection established
> Sending packet MESSAGE data 0{"auth":"x-token"}
> Attempting WebSocket upgrade to ws://localhost:8000/socket.io/?transport=websocket&EIO=4
> WebSocket upgrade was successful
> Received packet NOOP data 
> Received packet MESSAGE data 2["hello",1,2,{"hello":"you"}]
> Received event "hello" [/]
> Received packet MESSAGE data 0{"sid":"pTkLIPfYVOTDchmVAAAB"}
> Namespace / is connected
> Emitting event "parse" [/]
> Sending packet MESSAGE data 51-["parse",{"_placeholder":true,"num":0}]
> Sending packet MESSAGE data <binary>
> Unexpected error decoding packet: "object of type 'int' has no len()", aborting
> Waiting for write loop task to end
> Exiting write loop task
> Engine.IO connection dropped
> Exiting read loop task
> Connection failed, new attempt in 0.90 seconds
> disconnected from server
> Attempting polling connection to http://localhost:8000/socket.io/?transport=polling&EIO=4
> Polling connection accepted with {'sid': '9k9IhWv5DAalxHxsAAAC', 'upgrades': ['websocket'], 'pingTimeout': 20000, 'pingInterval': 25000}
> Engine.IO connection established
> Sending packet MESSAGE data 0{"auth":"x-token"}
> Attempting WebSocket upgrade to ws://localhost:8000/socket.io/?transport=websocket&EIO=4
> WebSocket upgrade was successful
> Received packet NOOP data 
> Received packet MESSAGE data 2["hello",1,2,{"hello":"you"}]
> Received event "hello" [/]
> Received packet MESSAGE data 0{"sid":"KbRDHBERN_rSvhCwAAAD"}
> Namespace / is connected
> Reconnection successful
> 1 2 {'hello': 'you'}
> connected to server
> Unexpected error receiving packet: "", aborting
> Waiting for write loop task to end
> packet queue is empty, aborting
> Exiting write loop task
> Engine.IO connection dropped
> Exiting read loop task
> Connection failed, new attempt in 1.21 seconds
> Unclosed client session
> client_session: <aiohttp.client.ClientSession object at 0x0000022CB07B3208>
> Task was destroyed but it is pending!
> task: <Task pending coro=<AsyncClient._handle_reconnect() running at D:\Python\Env\mess\lib\site-packages\socketio\asyncio_client.py:470> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x0000022CB078FBE8>()]>>
> Exception ignored in: <function ClientResponse.__del__ at 0x0000022CB0668268>
> Traceback (most recent call last):
>   File "D:\Python\Env\mess\lib\site-packages\aiohttp\client_reqrep.py", line 811, in __del__
>   File "D:\Python\Env\mess\lib\site-packages\aiohttp\connector.py", line 179, in release
>   File "D:\Python\Env\mess\lib\site-packages\aiohttp\connector.py", line 663, in _release
>   File "D:\Python\Env\mess\lib\site-packages\aiohttp\client_proto.py", line 63, in close
>   File "d:\python\anaconda3\Lib\asyncio\selector_events.py", line 650, in close
>   File "d:\python\anaconda3\Lib\asyncio\base_events.py", line 688, in call_soon
>   File "d:\python\anaconda3\Lib\asyncio\base_events.py", line 480, in _check_closed
> RuntimeError: Event loop is closed
> Task was destroyed but it is pending!
> task: <Task pending coro=<Event.wait() running at d:\python\anaconda3\Lib\asyncio\locks.py:293> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x0000022CB078FBB8>()]> cb=[_release_waiter(<Future pendi...CB078FBE8>()]>)() at d:\python\anaconda3\Lib\asyncio\tasks.py:366]>
> disconnected from server
> 
> Process finished with exit code 0

so i wonder, is there has a example about file and big file transfer, can u give me some advise, and actually i don't how to print the server error info, i have open the log and the engine log, but i can't see any about the server why not like my binary emit
ths~

**Comment by miguelgrinberg** [comment]
Such large payloads are very uncommon, it is quite possible that the WebSocket library also has a maximum and blocks you from sending.

I recommend that you segment your data into chunks to have a more reliable solution.

**Comment by jolahua** [comment]
i can't find the client block from sending. 10M is my test result. when i have a bigger file, how can i define my chunk size?

**Comment by miguelgrinberg** [comment]
What I meant is that YOU segment the file into chunks and then send each chunk separately:

```python
chunk_size = 4096  # 4K chunks
with open(my_large_file, 'rb') as f:
    while True:
        data = f.read(chunk_size)
        if not data:
            break  # transfer is done
        await emit('file_chunk', data)
```

This is much more reliable, as you are not required to hold all the data in memory at one time.

**Comment by jolahua** [comment]
i know that i should use chunk
if i set the `chunk_size = 1M `, send a 89M file cost 9s
while i set the `chunk_size = 10M`, it only cost 0.6s
so while the file is bigger, i can't find the threshold if socketio configured maximum payload size is 10M.

**Comment by miguelgrinberg** [comment]
First of all, If you want to transfer a file in the most efficient way, then send it in a standard file upload form. Socket.IO isn't designed as a file transfer mechanism and is never going to be as fast as streaming the data over HTTP.

What threshold are you trying to find? I'm sorry but I don't understand.

**Comment by jolahua** [comment]
ths, you explained it clearly.And i should try another way to transfer file
