### ISSUE TITLE
Problem with memory-leak

### ISSUE THREAD

**Issue by MaxOvcharov** [miguelgrinberg/python-socketio#108]
We run our load tests with Socket.io and find something interesting:

1. Test case is: 10 mps(message per second) from users. This users connect to server -> emit message -> wait 4 sec for the answer ->  and disconnect. This case works for 10 hours. We test it in polling and web-sockets mode
The result of this tests are always the same:

- ![default](https://user-images.githubusercontent.com/13488059/27216213-61b4a090-527d-11e7-8d06-e9eed141684c.png)

- ![default](https://user-images.githubusercontent.com/13488059/27216252-99a6924c-527d-11e7-84e2-4c9b22a3cff0.png)

2. Server script: https://gist.github.com/MaxOvcharov/4d41300260e8bde0ecf8012b6e97f0c5

3. Java load test: https://gist.github.com/anonymous/742eaa71b769529c89040a440552cea4

4. Config file for load test:
`{
  "url": "http://10.2.2.4:8080/chat",
  "rps": 60.0,
  "connections": 500,
  "ttl": 4000,
  "duration": 30,
  "socketConf": ["polling"],
  "simulateReconnects": true,
  "waitForConnect": false,
  "rpsps": 0.0,
  "planning_threads": 8,
  "logdir": "logs-distrib"
}`

5. Binary file:
[boomsocket.jar.gz](https://github.com/miguelgrinberg/Flask-SocketIO/files/1080068/boomsocket.jar.gz)

6. Script for running test:
```start_time=$(date -d $2 +%s000)
end_time=$(date -d $3 +%s000)

if (( start_time > end_time )); then
    echo "your start time is bigger than the end time"
    exit 1
fi

function ct() {
    ct=$(date +%s000)
}

ct
while (( ct < end_time )); do
    java -jar boomsocket.jar $1 $start_time
    ct
done```

**Comment by MaxOvcharov** [comment]
Do you have your own stress tests? How many "mps" can handle Socket.io server?

**Comment by miguelgrinberg** [comment]
I am investigating an issue that is possibly related: https://github.com/miguelgrinberg/python-engineio/pull/51

The test that you are running could be exposing an issue that is also reported in link above, but note that what you are doing is not representative of the normal usage for Socket.IO. There is really no point to constantly connect and disconnect from the server, the idea is that clients establish long running connections to the server. The constant connections and disconnections are expensive, this is a protocol that is optimized for connection that last a long time.

Giving an absolute "mps" measure is really impossible, as there are a lot of factors that affect the performance of the server. There is a "latency.py" example in this repository that you can use to test the latency for a round-trip message from client to server and back. The idea is that you deploy this application to your production server and that way you can measure actual latency in your production configuration.

**Comment by MaxOvcharov** [comment]
Ok, I see. Sometimes in our logs we have this error:
```
socket.accept() out of system resource
socket: <socket.socket fd=8, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('0.0.0.0', 8080)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 161, in _accept_connection
  File "/usr/lib/python3.5/socket.py", line 195, in accept
OSError: [Errno 24] Too many open files 
``` 
Can this error bee related with previous problem? Is it possible to use more than 65535 open connection for one user?

**Comment by miguelgrinberg** [comment]
I think this is, again, a side effect of the "lazy" disconnects that this library does, as reported in the issue linked above. Once that is improved you will not have so many outstanding connections, as disconnected clients will be disposed more promptly.
