### ISSUE TITLE
Plans to support Socket.IO 2?

### ISSUE THREAD

**Issue by OneSman7** [miguelgrinberg/python-socketio#109]
There was an update to socket.io (https://socket.io/blog/socket-io-2-0-0/) which is not backward compatible with socket.io 1.
Do you have plans to support it?

Thanks

**Comment by miguelgrinberg** [comment]
I have tested the server with the 2.x JS clients and already addressed the only issue I've found, which is related to this item in their breaking changes list:

- a breaking change related to utf-8 encoding in engine.io-parser

I have not looked at the non-breaking changes to see if there are any optimizations that can be added yet, but I plan to.

**Comment by spumer** [comment]
I try to use with 2.0.3 client library version, and websocket protocol did not work.
With 1.7.4 all works fine.

**Comment by miguelgrinberg** [comment]
Did you see any errors? I have been using the 2.x releases of the Socket.IO client without problem here.

**Comment by spumer** [comment]
It's seems to be heizenbug. Cause on some systems websocket connection estabilshed, but client don't recevied socket.io `connect` message from the server and try to reconnect.

This occured when i force websocket through `transports` options.
If no `transports` set, browser try all transports, "ensure" websockets available and use it!

Bug occured on Win7 with Chrome, but not for all. For Socket.IO 1 and 2 versions.

I don't know what happend, really.

**Comment by kylegoetz** [comment]
For what it's worth, there's a second breaking change not mentioned in this issue's discussion so far: https://github.com/socketio/socket.io/releases has a list and the second issue is at https://github.com/socketio/socket.io-client/pull/1058

**Comment by miguelgrinberg** [comment]
That is not a protocol change, but something specific to the Javascript implementation. It has no bearing on this server.

**Comment by kylegoetz** [comment]
Is it? I just changed the server from using a custom namespace that extends BaseNamespace back to just using the default namespace and it went from JavaScript client not receiving messages to receiving messages. I didn't change the JS client at all.

**Comment by kylegoetz** [comment]
OK thank you. I just changed the Python server's namespace from my custom one to the default namespace and the JS client actually receives the messages. Thanks for letting me know.

**Comment by ramazanpolat** [comment]
I've tried [Firecamp](https://chrome.google.com/webstore/detail/firecamp-a-campsite-for-d/eajaahbjpnhghjcdaclbkeamlkepinbl) (a chrome extension that can connect and test a socket.io server) with the sample code and found out that if you use empty string as namespace, everything works fine.

**Comment by Ankita130889** [comment]
When I try to send binary data from the python-socketio client to a nodejs server which is using socketio 2.0 protocol the server closes the connection and reconnects to start a new session.

Sending text data from the python-socketio client to the nodejs server using the socketio 2.0 protocol works fine.

**Comment by miguelgrinberg** [comment]
I'm not aware of any issues with the Socket.IO 2.x protocol at this time. Please open a new issues for any compatibility problems you find.
