### ISSUE TITLE
docs: please make sticky sessions requirement louder

### ISSUE THREAD

**Issue by abe-winter** [miguelgrinberg/python-socketio#1099]
**Is your feature request related to a problem? Please describe.**
When run as a cluster, this library requires sticky sessions to be enabled. This wasn't obvious at first and so I deployed a buggy cluster.

Please improve the docs or errors to make this requirement clearer (and I'm happy to submit a docs / error message PR, if helpful).

(Also thank for for providing this library -- I am very happy to be able to run my socketio backend in my existing fastapi stack).

**Describe the solution you'd like**
**In the codebase**:
- remove the sticky sessions requirement if possible (I don't understand the internals of this project or the socketio protocol, but I assume the sticky sessions requirement is in here for a legit reason, and removing it would be a large project if possible)
- explain the situation in the error message, if possible. In my case the error is usually 'Invalid session', presumably from 2 places in [handle_request](https://github.com/miguelgrinberg/python-engineio/blob/3af6bf2b4b28dd1d3534ad21b78366ecb60d5503/src/engineio/server.py#L405)

**In docs**:
In the [using a message queue](https://python-socketio.readthedocs.io/en/latest/server.html#using-a-message-queue) section, can you link to the [scalability notes warning](https://python-socketio.readthedocs.io/en/latest/server.html#scalability-notes) (which says to use sticky sessions), and make it clear your cluster will fail if you don't meet the reqs?

**Describe alternatives you've considered**
The alternative I tried first was having my chat intermittently fail in prod. Because my cluster is small, it usually connected eventually, so for a while I assumed it was an error in the ordering of my authorization logic + socket connection.

**Logs**
n/a, but let me know if you want me to capture something

**Additional context**
Did a readthrough of other issues mentioning this:
- #371 'invalid session' with sanic in multiple workers mode
- #437, #219

**Comment by miguelgrinberg** [comment]
There is a section under Deployment that is specifically dedicated to scalability. How can it be more louder?

**Comment by abe-winter** [comment]
When I initially set up my cluster, I focused on the [using a message queue](https://python-socketio.readthedocs.io/en/latest/server.html#using-a-message-queue) section because it had the phrase 'horizontal scaling' in it, and because I expected that I would need to connect to a routing layer

I also focused on the [ASGI](https://python-socketio.readthedocs.io/en/latest/server.html#uvicorn-daphne-and-other-asgi-servers) section, but the rest of the deployment section was a list of alternate deployment methods. It didn't occur to me that the last item in that list would be a critical todo item for clustering.

Maybe:
- link to 'scalability notes' from the 'horizontal scaling' bullet point? (and say that 'you MUST do this')
- consider renaming from 'scalability notes' to 'clustering requirements'? 'notes' doesn't make this seem critical

**Comment by miguelgrinberg** [comment]
> and say that 'you MUST do this'
> 'notes' doesn't make this seem critical

Sticky sessions are optional.

Only required if you want to use the polling transport. It's very common to omit the sticky sessions requirement by configuring clients to connect directly through WebSocket, which is a single request, so no need for session affinity.

But the point is well taken, anyway. I will review how to organize the content better.

**Comment by abe-winter** [comment]
non urgent obviously, thanks for the attention
