### ISSUE TITLE
Emit in a room raises RuntimeError

### ISSUE THREAD

**Issue by arski** [miguelgrinberg/python-socketio#11]
Hi there, I've been running into the following recently, could you take a look please

        File "/Users/marty/site/flask-socketio/venv/lib/python3.4/site-packages/socketio/server.py", line 181, in emit
          self.manager.emit(event, data, namespace, room, skip_sid, callback)
        File "/Users/marty/site/flask-socketio/venv/lib/python3.4/site-packages/socketio/base_manager.py", line 97, in emit
          for sid in self.get_participants(namespace, room):
        File "/Users/marty/site/flask-socketio/venv/lib/python3.4/site-packages/socketio/base_manager.py", line 30, in get_participants
          for sid, active in six.iteritems(self.rooms[namespace][room]):
      RuntimeError: dictionary changed size during iteration

Seems to only happen when I need to run an .emit on 'disconnect' of a different client.

**Comment by muatik** [comment]
I am also having this issue. I think it occurs when I do some arbitrary operations onDisconnect event.

**Comment by ftomassetti** [comment]
Also having this issue. Any progress on this?

**Comment by miguelgrinberg** [comment]
This is one of the two main bugs that are going into the next release. Hoping for a release in a week or less.

**Comment by muatik** [comment]
when I dropped gevent* packages and switched to eventlet, frequency of this error message significantly decreased.

**Comment by miguelgrinberg** [comment]
@arski @muatik @ftomassetti could any of you share the exact `emit()` call you use to reproduce this issue? In particular, I'm interested to find out if you are emitting to an individual user, to a room, or a broadcast to everyone. Thanks!

**Comment by ftomassetti** [comment]
It is intermittent so it is difficult to say which emit is the actual cause
of this error but almost every emit in my program is directed to a room.

On 6 March 2016 at 04:14, Miguel Grinberg <notifications@github.com> wrote:

> @arski <https://github.com/arski> @muatik <https://github.com/muatik>
> @ftomassetti <https://github.com/ftomassetti> could any of you share the
> exact emit() call you use to reproduce this issue? In particular, I'm
> interested to find out if you are emitting to an individual user, to a
> room, or a broadcast to everyone. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/miguelgrinberg/python-socketio/issues/11#issuecomment-192788177>
> .
>



-- 
Website at http://tomassetti.me <http://www.federico-tomassetti.it>
GitHub https://github.com/ftomassetti

**Comment by miguelgrinberg** [comment]
Pretty sure I found the root cause of this problem. Please upgrade and let me know if this continues to happen.

**Comment by ftomassetti** [comment]
sure, will do. Thanks for your work!

**Comment by kaihil** [comment]
Seems to be fixed for me! Thanks a lot!
