### ISSUE TITLE
add ability to override the default json parser

### ISSUE THREAD

**Issue by tstriker** [miguelgrinberg/python-socketio#1106]
**Is your feature request related to a problem? Please describe.**

I've a custom json parser that takes care of date and datetime objects. 
When trying to send the message from server to client, python-socketio uses engineio's json function (https://github.com/miguelgrinberg/python-socketio/blob/main/src/socketio/packet.py#L2) that does not allow overriding

**Describe the solution you'd like**

It would be nice if python-socketio would allow some way to override the json provider, e.g. like flask does: https://flask.palletsprojects.com/en/2.2.x/api/#flask.Flask.json

**Describe alternatives you've considered**
At the absence of a central jsonifier, i have to pre-parse all objects to make sure that date and datetime objects are handled.

Hope this makes sense!

**Comment by miguelgrinberg** [comment]
The `Server` class has a `json` argument that you can use to pass your own JSON parser. From the [docs](https://python-socketio.readthedocs.io/en/latest/api.html#server-class):

![SCR-20221228-l2i](https://user-images.githubusercontent.com/2715854/209832548-315d8672-f6f9-49a0-b269-68a25a50ab98.png)

**Comment by tstriker** [comment]
ah, no idea how i missed that, thank you!
