### ISSUE TITLE
Emit from imported module

### ISSUE THREAD

**Issue by Nixellion** [miguelgrinberg/python-socketio#111]
Hello, I think I don't understand the concept here. 

How do I emit from child module? Imported one. Here's what I mean.

Structue:

- folder
  - folder_module.py
- app.py
- root_module.py

In `app.py` I create `socketio = SocketIO(app, async_mode=...)`. I can just use emit and it emits perfectly.
If I call function from `app.py` in `root_module.py` which uses `from flask_socketio import emit `- it works.

But if I call emit from `folder_module.py` - it does not work.

Is there a way to make this work somehow? What's the correct approach here?

I need to create a module structure for my program, and I'd like to be able to emit socket events from any module.

Thanks.

**Comment by miguelgrinberg** [comment]
What do you mean by "it does not work"? Does it fail with an error, or does it fail silently?

**Comment by Nixellion** [comment]
It just fails silently. I'll take a closer look at logs tomorrow. But I did not get any errors.

**Comment by miguelgrinberg** [comment]
Enable logging to see if that shows any more information. Add `logger=True, engineio_logger=True` to your `SocketIO()` constructor.

**Comment by Nixellion** [comment]
Ok, I'm sorry for confusion, false alarm. There was a minor error in my code, and emit was not called, just passed silently.

Again, sorry for trouble O.O Everything works, you're great :)
