### ISSUE TITLE
Invalid empty packet received, aborting // Potential issue with heartbeat

### ISSUE THREAD

**Issue by suchgpg** [miguelgrinberg/python-socketio#1111]
Hi all,

I'm making a simple script to log the messages from a socket.io server.

Every ~25sec I get the following error:
```
packet queue is empty, aborting
Exiting write loop task
Unexpected error decoding packet: "Invalid empty packet received", aborting
Waiting for write loop task to end
Engine.IO connection dropped
Disconnect
Connection failed, new attempt in 0.85 seconds
Exiting read loop task 
```

I get disconnected and reconnect after.

I believe this would be an issue regarding the hearbeat not getting parsed by EngineIO but I could be wrong. What do you think could be the cause of this issue?

My code is as follows:

```import socketio

sio = socketio.Client(logger=True, engineio_logger=True)


@sio.event
def connect():
    print('Connected with SID', sio.sid)

@sio.event
def connect_error(data):
    print("ERROR", data)
    # exit()
@sio.event
def disconnect():
    print('Disconnect')

@sio.on('*')
def catch_all(event, data):
    try:
        if event == 2 and type(data['message']) != list and data['room'] == "main":
            # print(data['room'], "-", data['message'],"\n\n")
            print(data['message']['uid'], "-", data['message']['content'])
        else:
            print(f"{event}\n\n")
    except Exception as e:
        print(e)
    
    # print(f"TEST111 - Event {event} - Data {data}")

if __name__ == '__main__':
    sio.connect('wss://website.cc/socket.io/?token=[JWT_TOKEN]&EIO=3',transports='websocket', wait_timeout=10)
    sio.wait()```

**Comment by miguelgrinberg** [comment]
Seems like your server isn't sending the heartbeat that it promised it would send. The client is just aborting because it thinks the server is not responsive.

Also, looking at your code, the connect call should not include internals of the Socket.IO protocol. It should be like this:

```python
sio.connect('wss://website.cc?token=[JWT_TOKEN]', transports='websocket')
```

If the above does not work, then you are probably using incompatible client and server versions. Check the compatibility table in the documentation to help you check this.

**Comment by suchgpg** [comment]
Thanks for the tip!

The issue was indeed a compatibility issue, the server is using revision 3 of the eio protocol (as you pointed out in my code) and I was using version 5x of socketio.

The ping mechanism works fine now.
