### ISSUE TITLE
How should I forward the received data to another object?

### ISSUE THREAD

**Issue by bakmario** [miguelgrinberg/python-socketio#112]
Hello!

I'm building a simple IoT application running on Raspberry Pi. This object oriented software is using a tons of different objects, some of those are representing my sensors, others are representing databases, etc.

I would like to integrate the socket.io package into my program because i would like to share the data coming from my sensor with different clients, e.g.: iPhone apps or i would like to control my sensors remotely.

So the very basic communication is working, I can send messages (with parameters) back and forth, but I'm struggling at one point.
I need to pass the received message to another object in my app.

Could you please give me a hint how can I reach my object from the `on_SetDeviceParameters` method, or how should i use the socket.io package for this prupose? 

[Code is edited, see next post...]

_Sorry for the dumb question, I'm just learning python, this is my first bigger application._

**Comment by miguelgrinberg** [comment]
Where are your other objects? Can you describe the basic organization of your project?

**Comment by bakmario** [comment]
The project is organized as the followings:
 - The "main" (located in the DeviceManager.py) creates the dispatcher than it starts the Socket.IO server
 - The dispatcher is the soul of the system, it creates and connects the subsystems together
 - The client manager handles the remote clients, forwards the message to/from the dispatcher (i wanted to integrate other servers, but since the socket.io server is "blocking" I will solve it in another way)
 - The Server_SocketIO represents the integration of your code.

I'm wondering how could I reach the my objects from the socketio's "on_..." methods which are called asynchronously.
`
**DeviceManager.py**	

	if __name__ == "__main__":
		# Create Dispatcher
		dispatcher = Dispatcher()
		
		# Start the Socket.IO server
	        dispatcher.clientManager.startServerSocketIO("192.168.10.1", 8080)

	
**Dispatcher.py**

	class Dispatcher:
		"""This class creates the subsystems (devices, server, etc.) and connects them together (forwards messages, etc)"""
		
		clientManager = None
		dmDataBase = None
		deviceServiceProviders = []
		
		def __init__(self):
			# Initialize DataBase ...
			# Initialize DeviceServiceProviders ...       
			self.clientManager = ClientManager(self)

		def dispatchCommand(self, message):
			"""This method forwards the commands coming from the clients to the devices"""
			...

		def dispatchAnswer(self, message):
			"""This method forwards the answers coming from the devices to the clients"""
			...
			
			
**ClientManager.py**	
		
	class ClientManager():
    """Manages the clients"""

		dispatcher = None
		server_SocketIO = None

		def __init__(self, dispatcher):
			self.dispatcher = dispatcher
			self.server_SocketIO = Server_SocketIO(self)

		def startServerSocketIO(self, host, port):
			self.server_SocketIO.startServer(host, port)

		def forwardCommand(self, message):
			self.dispatcher.dispatchCommand(message)

		def forwardAnswer(self, message):
			print("forwardAnswer: ", message)

			
**Server_SocketIO.py**

	from aiohttp import web
	import socketio
	import app as app

	sio = socketio.AsyncServer()
	app = web.Application()
	sio.attach(app)

	class Server_SocketIO:

		clientManager = None

		def __init__(self, clientManager):
			self.clientManager = clientManager

		def startServer(self, host, port):
			web.run_app(app, host=host, port=port)

		@sio.on('connect')
		def connect(sid, environ):
			print('Connection request from ', environ['REMOTE_ADDR'])

		@sio.on('SetDeviceParameters')
		async def on_SetDeviceParameters(sid, *args):
			receivedData = args[0]
			
			#Here I would like to reach the ClientManager / Dispatcher somehow...
			# clientManager.forwardCommand(ClientManager.ClientManager, message=receivedData)
			# self.dispatcher.dispatchCommand(receivedData)
			# await sio.emit('DeviceState', "state")

`

**Comment by miguelgrinberg** [comment]
Okay, great. Based on this code, in the Socket.IO server you can access the dispatcher as `self.clientManager.dispatcher`, so the following should work:

```python
class Server_SocketIO:
        # ...

	@sio.on('SetDeviceParameters')
	async def on_SetDeviceParameters(sid, *args):
		receivedData = args[0]
		
		self.clientManager.forwardCommand(ClientManager.ClientManager, message=receivedData)
		self.clientManager.dispatcher.dispatchCommand(receivedData)
		await sio.emit('DeviceState', "state")
```

**Comment by bakmario** [comment]
I don't understand your suggestion. :(
I can't use the `self` keyword inside the `on_SetDeviceParameters(sid, *args)`, because I'm receiving the following error: `NameError: name 'self' is not defined`

**Comment by miguelgrinberg** [comment]
Ah, right, sorry. The structure that you are using is unusual, the Socket.IO handlers appear to be methods of your `Server_SocketIO` class but they are really not.

I recommend you move those out of the class so that they don't look like methods. In any case, to be able to access all your other objects you can save the server instance at the module level, and then you would use it instead of the `self` that I used in my previous example.

```python
my_server = None

class Server_SocketIO:
	def __init__(self, clientManager):
                global my_server
                my_server = self
		self.clientManager = clientManager

@sio.on('SetDeviceParameters')
async def on_SetDeviceParameters(sid, *args):
        receivedData = args[0]
		
        my_server.clientManager.forwardCommand(ClientManager.ClientManager, message=receivedData)
        my_server.clientManager.dispatcher.dispatchCommand(receivedData)
        await sio.emit('DeviceState', "state")
```

**Comment by bakmario** [comment]
Great! Thank you very much, it is working in this way!
