### ISSUE TITLE
RuntimeError: Expected ASGI message 'http.response.start', but got 'websocket.accept'.

### ISSUE THREAD

**Issue by advo-kat** [miguelgrinberg/python-socketio#1131]
When using `python-socketio` and attaching it to FastAPI sometimes you may receive the error on the server-side when the client attempts to connect:

`RuntimeError: Expected ASGI message 'http.response.start', but got 'websocket.accept'.`

This has been previously raised in [#210](https://github.com/miguelgrinberg/python-engineio/issues/210). The minimal setup there applies here.

The other instance where you might still see this error (as I've learnt) is when you didn't install the `websockets` package in your environment. Websockets aren't a dependency for `python-socketio` so this error message can be cryptic. 

This isn't really a bug, but I'm posting this issue here in case anyone else runs into the problem. Installing websockets (or not uninstalling them) should be the first thing you check.

**Comment by serge-eric-kalaga** [comment]
Tell me what solution did you find for the problem?

**Comment by miguelgrinberg** [comment]
@serge-eric-kalaga this error suggests your application isn't configured correctly. See https://github.com/miguelgrinberg/python-socketio/blob/main/examples/server/asgi for some fully working examples.

**Comment by serge-eric-kalaga** [comment]
@miguelgrinberg  thank you !
