### ISSUE TITLE
i use AsyncPubSubManager of aioredis.but i can't set redis password

### ISSUE THREAD

**Issue by larry-dev** [miguelgrinberg/python-socketio#114]
i can't set password of aioredis.
i use AsyncPubSubManager of aioredis

**Comment by miguelgrinberg** [comment]
True, looks like I am not passing the password given in the URL. I will fix it.

**Comment by miguelgrinberg** [comment]
Fixed in af811326103abf90338987a326190df210c421af. Closing.
