### ISSUE TITLE
Support Redis clusters

### ISSUE THREAD

**Issue by miguelgrinberg** [miguelgrinberg/python-socketio#1172]

**Comment by miguelgrinberg** [comment]
Proposed solution here: https://github.com/miguelgrinberg/Flask-SocketIO/issues/1452

**Comment by miguelgrinberg** [comment]
Redis Sentinel can be used via the Kombu manager.

**Comment by fidoriel** [comment]
`AsyncRedisManager` seems not to support Cluster Mode.

**Comment by zachary-jordan16** [comment]
@miguelgrinberg - Although `redis-py` does not seem to have support for cluster mode, it's possible that [coredis](https://github.com/alisaifee/coredis) could be used for the async pub-sub implementation in cluster mode. Is this something that could be considered? Would love to utilize the AsyncRedisManager, but we require cluster mode.

**Comment by miguelgrinberg** [comment]
My suggestion is that you build your own integration by creating a custom client manager class based on the Redis one. If you get it to work, then we can look at integrating it. I just recently added support for Redis Sentinel based on a custom implementation from a user. This would work in the same way
