### ISSUE TITLE
"Unable to connect" on Windows

### ISSUE THREAD

**Issue by loelkes** [miguelgrinberg/python-socketio#1178]
### Description

My Flask application runs without issues on Linux and macOS hosts, either with ```FLASK_DEBUG=True flask run``` (for development) or inside a Docker container with uWSGI (for production). On my Windows 10 (19045.2913) the client (Browser) receives an "Unable to connect" error. The code is the same for all platforms, Python 3.11.3.

I don't know where to look any further. Is this an issue or am I using it wrong?

### Log

```
[2023-04-28 14:54:04 +0200] INFO in app.EngineIO: Ez4TBQPJ_sOIjotRAAAA: Sending packet OPEN data {'sid': 'Ez4TBQPJ_sOIjotRAAAA', 'upgrades': [], 'pingTimeout': 1000, 'pingInterval': 5000}
[2023-04-28 14:54:04 +0200] INFO in app.SocketIO: kombu backend initialized.
[2023-04-28 14:54:04 +0200] INFO in app.EngineIO: Ez4TBQPJ_sOIjotRAAAA: Received request to upgrade to websocket
[2023-04-28 14:54:04 +0200] INFO in app.EngineIO: Ez4TBQPJ_sOIjotRAAAA: Upgrade to websocket successful      
[2023-04-28 14:54:04 +0200] INFO in app.EngineIO: Ez4TBQPJ_sOIjotRAAAA: Received packet MESSAGE data 0/client,
[2023-04-28 14:54:04 +0200] INFO in app.EngineIO: Ez4TBQPJ_sOIjotRAAAA: Sending packet MESSAGE data 4/client,"Unable to connect"
```

This seems to come from here:

https://github.com/miguelgrinberg/python-socketio/blob/270eb372cc83778a897d32e95453eb385328d9de/src/socketio/server.py#L658-L669

### Flask application
```
...
socketio = SocketIO(
    app=app,
    logger=app.logger.getChild('SocketIO'),
    engineio_logger=app.logger.getChild('EngineIO'),
    json=json,
    cors_allowed_origins='*',
    ping_interval=5,
    ping_timeout=1,
    message_queue=f"amqp://{app.config['RABBITMQ_HOST']}")
...
```

### uWSGI command
```bash
uwsgi -b 32768 --http :5000 --gevent 1000 --master --wsgi-file wsgi.py --callable app
```

### wsgi.py
```python
from gevent import monkey
monkey.patch_all()

from app import create_app
app = create_app()
```

### Versions

```
...
Flask-SocketIO==5.3.3
Flask==2.3.1
python-socketio==5.8.0
python-engineio==4.4.1
uWSGI==2.0.21
gevent==22.10.2
...
```

**Comment by miguelgrinberg** [comment]
The connection goes to a namespace called `/client`. Is this correct? The most likely cause for the connection failure is that the server doesn't have this namespace.

**Comment by loelkes** [comment]
That is correct. It's all there. The applications runs in production without issue. This error only appears on Windows. Other than the platform I an't spot any differences.

**Comment by miguelgrinberg** [comment]
@loelkes What was the misconfiguration? What do you think the error message should say? Without these details I have no way to decide if I can provide a more appropriate error message.

**Comment by loelkes** [comment]
The namespace I accessed did not exist. In my application namespaces are created on demand or depending on the configuration of the system so I'm not aware of how they're called and I missed this.

Maybe the message could be something like "Unable to connect, Namespace does not exist"? Do you want me to open a PR for this?
