### ISSUE TITLE
can  write only    redis manager call  enter_room/leave_room?

### ISSUE THREAD

**Issue by notedit** [miguelgrinberg/python-socketio#118]
i want to control the enter room/ leave room from another process.  

can we do that ?

**Comment by miguelgrinberg** [comment]
Unfortunately not at this time.

**Comment by notedit** [comment]
any plan support this?

**Comment by miguelgrinberg** [comment]
It was not on my radar to implement this, no. I don't see it as being that useful. Typically a user joins a room as a result of the client sending an event, and since client events are handled on the main server, that is where I expect room changes will happen most often. What's your use case?

**Comment by notedit** [comment]
i do not want to put too much logic in  socketio  server( db query ),  so i want to move the logic to my application server and  manage the rooms in my application server.

**Comment by miguelgrinberg** [comment]
Sure, but that does not answer my claim, that your clients will join or leave rooms as a response to an event coming from the client. Those events have to be handled in the main server, so how do you plan to make things work?

**Comment by notedit** [comment]
so  i am thinking  move the event from client to http request to my application  server  and  let the socketio  server explode some room manger api.  

socketio server just be used for event emit and  room manager.

**Comment by notedit** [comment]
maybe  celery can  help me

**Comment by dwaltrip** [comment]
Hi Miguel. Thanks for this outstanding library, it is really well done.

I was also wondering about this issue. It seems to me that giving `RedisManager` the ability to manage rooms would allow for decreased decoupling between the main web server and a separate websocket server.

A possible architecture is one that limits the amount of business logic on the websocket server, but this is harder to do if only the websocket server is able to manage rooms. I think this architecture would work especially well if the websocket server is mainly used to publish events to clients (which were emitted by the main web server using a RedisManager with `write_only=True`), and it doesn't directly receive much data from clients. My current use case looks like it will fit this model.

Thoughts?

**Comment by dwaltrip** [comment]
@miguelgrinberg Hey Miguel, thanks for the quick response. I've been mulling this over, but haven't managed to reach anything conclusive yet... 

> Can't you just do all the websocket stuff in the websocket server and the HTTP stuff in the HTTP server?

Websockets and HTTP are just ways of transferring data to and from the client. Business logic will be needed in both cases to determine how that data is used, who can access it, modify it, etc. If I keep the two servers separate, then I eventually will need to find good ways of sharing logic between them and ideally reducing the amount of code duplication. I was thinking that if `RedisManager(write_only=True)` could manage rooms, then I could minimize the amount of business logic that the websocket server would need. For example, clients could join rooms by making an AJAX call, and the HTTP server could verify that client has permission to join the room before using the redis queue to add the client to the room on the websocket server. The idea of the websocket server having little to no business logic and mostly acting as a dumb relay seemed quite elegant to me. But perhaps it is not realistic.

Of course, the issue would be eliminated entirely if a single server handles both HTTP and websockets... maybe that is most straightforward solution.

I don't have that much business logic affecting rooms at this point, so the issue isn't that pressing. However, I wanted to take a broad look at the situation as I am implementing the initial realtime capabilities for the project.
