### ISSUE TITLE
Ec2 hosting flask

### ISSUE THREAD

**Issue by siva1002** [miguelgrinberg/python-socketio#1189]
HI;
    I am new for socketio some socket request went for pending state in chrome(application running in aws ec2 instance),for development we used digital ocean it wasn't make the request in pending, the socket requests makes other api requests too pending because of server response dont know how to resolve this kindly guide me to fix the issue.
Thanks

below code is we used intiate flaskapp and flasksocketio
i can provide further more details if needed
#----------------
app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
sockio = SocketIO(app,cors_allowed_origins="*",message_queue="redis://default:lICb5DP6GTUsmDzjkpo8LdpRmpUtotWB@redis-19361.c305.ap-south-1-1.ec2.cloud.redislabs.com:19361")
CORS(app,supports_credentials=True)
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config['SECURITY_PASSWORD_SALT']=os.getenv('SECURITY_PASSWORD_SALT')
if os.getenv('ENV')=='TEST':
    app.config['SQLALCHEMY_DATABASE_URI'] =os.getenv('DB_URI_TEST')
else:
    app.config['SQLALCHEMY_DATABASE_URI'] =os.getenv('DB_URI_PROD')

**Comment by miguelgrinberg** [comment]
Please do not write questions in the bug tracker of this project. You may want to consult the troubleshooting documentation to learn how to debug issues with Socket.IO. If you need help with your application, then once you have supporting information to provide, please open a discussion topic. Thanks.
