### ISSUE TITLE
asyncio_server  [base_events.py:1765] Task was destroyed but it is pending!

### ISSUE THREAD

**Issue by kaluluosi** [miguelgrinberg/python-socketio#1191]
**IMPORTANT**: If you have a question, or you are not sure if you have found a bug in this package, then you are in the wrong place. Hit back in your web browser, and then open a GitHub Discussion instead. Likewise, if you are unable to provide the information requested below, open a discussion to troubleshoot your issue.

**Describe the bug**
When I make large concurrent request， the asyncio_server’s event_handler is gone.
I can't  provide all code, but I show you what I done.

```shell
ERROR:      [base_events.py:1765] Task was destroyed but it is pending!
task: <Task pending name='Task-2742' coro=<AsyncServer._handle_event_internal() done, defined at C:\Users\john\AppData\Local\pypoetry\Cache\virtualenvs\perfcat-h6WRwzdT-py3.11\Lib\site-packages\socketio\asyncio_server.py:522> wait_for=<Future pending cb=[Task.task_wakeup()]>>
```
**To Reproduce**

app.py
```python
import random
import socketio
import logging
from fastapi import FastAPI

logger = logging.getLogger(__name__)

fast_app = FastAPI()
sio = socketio.AsyncServer(logger=logger, async_mode="asgi", cors_allowed_origins="*")
app = socketio.ASGIApp(socketio_server=sio, other_asgi_app=fast_app)

@sio.event
async def fetch(sid):
         await do_some_async_io_job() # It cost a bit time.

        info ="data"
        return info

```

client.js
```javascript

// make a interval timer to loop emit
setInterval(()=>{
     sio.emit("fetch", (info)=>{
     console.log(info)
   },  10) // <- small interval
```

**Expected behavior**

**Logs**
```shell
ERROR:      [base_events.py:1765] Task was destroyed but it is pending!
task: <Task pending name='Task-2742' coro=<AsyncServer._handle_event_internal() done, defined at C:\Users\john\AppData\Local\pypoetry\Cache\virtualenvs\perfcat-h6WRwzdT-py3.11\Lib\site-packages\socketio\asyncio_server.py:522> wait_for=<Future pending cb=[Task.task_wakeup()]>>
```
**Additional context**

**Comment by kaluluosi** [comment]
All right， this is asyncio bug.
https://stackoverflow.com/questions/70636621/why-is-an-asyncio-task-garbage-collected-when-opening-a-connection-inside-it

task will be GC if it not being hard reference.

asyncio_server.py
```python

    async def _handle_event(self, eio_sid, namespace, id, data):
        """Handle an incoming client event."""
        namespace = namespace or "/"
        sid = self.manager.sid_from_eio_sid(eio_sid, namespace)
        self.logger.info('received event "%s" from %s [%s]', data[0], sid, namespace)
        if not self.manager.is_connected(sid, namespace):
            self.logger.warning("%s is not connected to namespace %s", sid, namespace)
            return
        if self.async_handlers:
            # This is the bug, this task may be GC.
            self.start_background_task(
                self._handle_event_internal, self, sid, eio_sid, data, namespace, id
            )
        else:
            await self._handle_event_internal(self, sid, eio_sid, data, namespace, id)

```

**Comment by miguelgrinberg** [comment]
Okay, yes, this peculiarity of asyncio was already brought up in relation to a similar issue: https://github.com/miguelgrinberg/python-socketio/issues/647.

I will think about how to handle this better. Appears harder than the other issue, as this is an internal background task and I currently have no place to store the task reference.

**Comment by sandro-qiang** [comment]
> Okay, yes, this peculiarity of asyncio was already brought up in relation to a similar issue: #647.
> 
> I will think about how to handle this better. Appears harder than the other issue, as this is an internal background task and I currently have no place to store the task reference. I wonder if there is already a pattern for a task that holds a reference to itself, or something of that style... will have to dig.

https://docs.python.org/3/library/asyncio-task.html#asyncio.create_task

The Python document has an example.
