### ISSUE TITLE
Invalid namespace

### ISSUE THREAD

**Issue by luoxiaofeng1029** [miguelgrinberg/python-socketio#1197]
**Describe the bug**
I am using socket.io for communication. The client is using python-socketio with version 5.8.0, and the server is using netty-socketio with version 2.0.2. Now, when I start the client connection, the console prints an error message saying "Invalid namespace". This message is sent back by the server. Of course, the printed error does not affect the normal connection. The server can still trigger the connect event, and the client can receive messages sent by the server. Ping pong is also normal. The main issue is that I don't know why there is an error. Below are some screenshots of my breakpoints. When packet.nsp = "{}", the error occurs; when nsp = "", there is no error. The main problem is that I don't know why the server receives packet.subType = "CONNECT" with nsg = "{}" instead of nsg = "". I did not specify a namespace for both the client and server, and I am using the default one. I don't know how to solve this issue.

**Expected behavior**
I hope it should connect normally without printing any errors.

**Logs**
![27ee93ad371c37f48f76db5d5ce5cf7](https://github.com/miguelgrinberg/python-socketio/assets/50006313/04920db4-ebaa-437c-954f-9ebc734083bb)
![image](https://github.com/miguelgrinberg/python-socketio/assets/50006313/320b3020-c939-479e-b771-6263ba316787)
![image](https://github.com/miguelgrinberg/python-socketio/assets/50006313/8ca4c344-2062-4aac-ab63-487ec54b5b99)

```
import socketio
import requests
sio = socketio.Client(logger=True, engineio_logger=True)


@sio.event
def connect():
    print('connected to server')


@sio.event
def disconnect():
    print('disconnected from server')


if __name__ == '__main__':
    server_ip= '192.168.10.2'
    server_port = '8098'
    res = requests.post(f"http://{server_ip}:8088/benchLogin",json={
    "password": "admin123",
    "username": "test"
})
    token = res.json()["data"]["token"]
    sio.connect(f"ws://{server_ip}:{server_port}?token={token}", transports=['websocket'])

    sio.wait()

```

**Comment by miguelgrinberg** [comment]
I believe this is an issue on the side of your server, which misinterprets the `0{}` packet. The `0` indicates that this is a `CONNECT` packet. The `{}` is the authentication information, which is empty, because you are sending your token in the query string, not in the `CONNECT` packet payload. Your server does not understand the `{}` as authentication, and instead mistakenly thinks it is a namespace, which makes no sense because namespaces start with a `/`.

**Comment by luoxiaofeng1029** [comment]
> I believe this is an issue on the side of your server, which misinterprets the `0{}` packet. The `0` indicates that this is a `CONNECT` packet. The `{}` is the authentication information, which is empty, because you are sending your token in the query string, not in the `CONNECT` packet payload. Your server does not understand the `{}` as authentication, and instead mistakenly thinks it is a namespace, which makes no sense because namespaces start with a `/`.
Thank you for your reply, but even when we remove the token, the error still occurs. At the same time, ping pong works normally, indicating a successful connection.

![6ec994614b346ca97fb94de040e6413](https://github.com/miguelgrinberg/python-socketio/assets/50006313/f83a9af7-29b5-4d74-9078-e5e33d9a9a63)
![b31fc220868f11ae9ce08908acbb53a](https://github.com/miguelgrinberg/python-socketio/assets/50006313/3af3c005-902a-427e-90ab-8e12c18da212)

**Comment by luoxiaofeng1029** [comment]
> 我相信这是您服务器端的问题，它会误解`0{}`数据包。指示`0`这是一个`CONNECT`数据包。这`{}`是身份验证信息，它是空的，因为您是在查询字符串中发送令牌，而不是在数据包`CONNECT`有效负载中。您的服务器不理解`{}`as 身份验证，而是错误地认为它是一个命名空间，这是没有意义的，因为命名空间以`/`.

please reopen issues thanks

**Comment by miguelgrinberg** [comment]
The token has nothing to with this issue. The Socket.IO protocol passes authentication information in the `CONNECT` package. You may choose to use this feature of the protocol or not. The server should not confusing authentication information with a namespace, that is a bug in the server project that you are using.
