### ISSUE TITLE
Missing Event when there is no sleep between event emission and socket disconnection

### ISSUE THREAD

**Issue by ronak-goti-cognoai** [miguelgrinberg/python-socketio#1202]
Hi, 

Missing Event when there is no sleep between event emission and socket disconnection

**Description:**
I have encountered an packet missing issue where there no delay between emitting an event and disconnecting the socket connection. 

**To reproduce the issue:**

- Set up a connection to the WebSocket server.
- Emit one or more events using the sio.emit() method.
- Immediately disconnect the socket connection using sio.disconnect() without any delay.

**Expected behavior:**
There is no packet loss and all the packet should recevice successfully at server side.

**Actual behavior:**
There are some packet loss at server side.

**Code:**

    async def connect():
            logger.info("Connection established to server")

    async def connect_error(data):
            logger.info(f"Connect error handler - connection failed due to - {str(data)}")

    async def disconnect():
            logger.info("Disconnect handler - disconnected from server")

    async def send_data_to_socket_io_server(event_name, data_to_send, endpoint, namespace):
        try:
            sio = socketio.AsyncClient()
            
            sio.on('connect', connect)
            sio.on('connect_error', connect_error)
            sio.on('disconnect', disconnect)
            
            await sio.connect(url=endpoint, socketio_path="/websocket/", transports=["websocket"], namespaces=namespace)

            custom_encrypt_obj = CustomEncrypt()

            for data in data_to_send:
                data = custom_encrypt_obj.encrypt(data)
                sio.call(event_name, data, namespace=namespace)
            
            await asyncio.sleep(0.1)
            await sio.disconnect()
        except Exception as e:
            exc_type, exc_obj, exc_tb = sys.exc_info()

**Comment by miguelgrinberg** [comment]
This is not a bug. Emitting an event is an asynchronous operation, the `emit()` call starts the process, but there is no guarantees made that the event was sent when this call returns to you. If you want to wait for the event to be delivered, you should add a callback to your event, and disconnect only when the callback is received.
