### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Unprocessed packet", packet)?

### ISSUE THREAD

**Issue by luqy** [miguelgrinberg/python-socketio#1203]
import socketio 
No client object
By from socketio import client
sio=client.Client()
Yes, it can run
But it will prompt：SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Unprocessed packet", packet)?
This seems to be a print that does not support Python 3

i saw my veriosn of python-socketio

![image](https://github.com/miguelgrinberg/python-socketio/assets/42463694/ae661b41-96d9-41d2-aa5e-723c03dfadd7)
No problem, may I ask what version is incorrect?

**Comment by miguelgrinberg** [comment]
This had nothing to do with this package. The print statement requires parenthesis in python 3.
