### ISSUE TITLE
Trouble understanding what I can remove for a stripped down machine to machine conversation.

### ISSUE THREAD

**Issue by bmccoy88** [miguelgrinberg/python-socketio#122]
First of all, thank you for putting all this together, your examples are fantastic and I can see where you can get a LOT of functionality from this package. Now, for my particular needs.

I am new to the whole socketIO world and I am trying to write and interface that can talk between a java-based code on one machine implementing socket.IO and a python based machine on the other end (setting him up as the server and the java guy as client). What I really need is just a reliable way to pass some image/json objects back and forth between these two guys and I don't really have a need to serve them up on a webpage or anything.

Ideally I would use something like websockets directly but the java guy has all his client stuff based in socket.IO so there I am. Now, you mentioned I can just get rid of all the Flask stuff and just use any generic WGSI like eventlet to complete the request. Looking at the code, and different implementations I think I can just get rid of the route stuff but I wasn't sure if that is something the WSGI guy is looking for or just useful to actually serve up a webpage.

Sans Flask I am going to be trying to use python-socketIO with python3.5 on my side (hence the eventlet choice). Any advice on what I can safely ignore or possible a more efficient way to handle this would be great, thanks!

**Comment by miguelgrinberg** [comment]
if you don't need to serve web pages to your clients, then things are greatly simplified. The latency example app can be coded for eventlet as simply as follows:

```python
import eventlet
import eventlet.wsgi
import socketio

sio = socketio.Server(async_mode=async_mode)
app = socketio.Middleware(sio)

@sio.on('ping_from_client')
def ping(sid):
    sio.emit('pong_from_server', room=sid)

if __name__ == '__main__':
    eventlet.wsgi.server(eventlet.listen(('', 5000)), app)
```

The Java app should be able to connect to this service.

**Comment by bmccoy88** [comment]
Works like a charm! Thank you very much this was a huge help!
