### ISSUE TITLE
`engineio==4.7.1` makes `sio.wait()` a required function call

### ISSUE THREAD

**Issue by utkarsh867** [miguelgrinberg/python-socketio#1242]
Bumping up from `python-socketio==5.8.0` to `python-socketio==5.9.0` updates `engineio==4.7.1`. It seemed like a harmless update to me until my application started misbehaving.

Take a simple script:
```py
import socketio

sio = socketio.Client()

@sio.event
def connect():
    print("Connected")
    sio.emit("some_topic", {"key": "value"})


def main():
    sio.connect("https://somedomain.com", wait_timeout=10)
    print("Done")

main()
```

This snippet works with `engineio==4.7.0` and `python-socketio==5.9.0`. The code waits until terminated.

When `engineio==4.7.1` is installed, this same snippet fails to wait, exiting right after connection is made, requiring one change to get the same behaviour:

```diff
import socketio

sio = socketio.Client()

@sio.event
def connect():
    print("Connected")
    sio.emit("some_topic", {"key": "value"})


def main():
    sio.connect("https://somedomain.com", wait_timeout=10)
    print("Done")

main()
+ sio.wait()
```

I needed to revert exactly [this change](https://github.com/miguelgrinberg/python-engineio/commit/53578088046ca9f29b6119c182c7bed67d7a4ffb) out of all the updates in the `engineio==4.7.1`.

I am not sure if the `sio.wait()` is intended to be required, but snippets like mine worked without it until now.

Hope this helps someone.

**Comment by miguelgrinberg** [comment]
The `wait()` call has always been required. From the [documentation](https://python-socketio.readthedocs.io/en/latest/client.html#managing-background-tasks):

> If the application does not have anything to do in the main thread and just wants to wait until the connection with the server ends, it can call the wait() method

So as you see this call was never considered optional.

**Comment by utkarsh867** [comment]
> The `wait()` call has always been required. From the [documentation](https://python-socketio.readthedocs.io/en/latest/client.html#managing-background-tasks):
> 
> > If the application does not have anything to do in the main thread and just wants to wait until the connection with the server ends, it can call the wait() method
> 
> So as you see this call was never considered optional. The fact that your own application worked without calling `wait()` does not mean that this is a supported behavior.

Thanks a lot @miguelgrinberg
