### ISSUE TITLE
SimpleClient does not exist (anymore?)

### ISSUE THREAD

**Issue by tomlynchRNA** [miguelgrinberg/python-socketio#1254]
**Describe the bug**
SimpleClient does not exist (`AttributeError: module 'socketio' has no attribute 'SimpleClient'`)

**To Reproduce**
1. Go to the docs for using the simple client: https://python-socketio.readthedocs.io/en/latest/client.html#using-the-simple-client 
2. Install python-socketio `pip install "python-socketio[client]"`
3. Run example.py (based on the docs example for how to use the simpleclient):
```
import socketio

def main():
    with socketio.SimpleClient() as sio:
        sio.connect('http://localhost:3000/')
        print(sio.receive())

if __name__ == '__main__':
    main()
```

**Expected behavior**
SimpleClient exists.

**Logs**
```
Traceback (most recent call last):
  File "/path/to/example.py", line 9, in <module>
    main()
  File "/path/to/example.py", line 4, in main
    with socketio.SimpleClient() as sio:
         ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'socketio' has no attribute 'SimpleClient'
```

**Additional context**
I don't see anything in the changelog about SimpleClient being removed.
SimpleClient seems to exist in older version (4.x) but I'm not interested in those.

**Comment by ragyabraham** [comment]
@miguelgrinberg i can see `simple_client.py` in the main branch 
![image](https://github.com/miguelgrinberg/python-socketio/assets/52903382/e102ca76-cfc3-4cf3-93db-664d32b4b781)

**Comment by miguelgrinberg** [comment]
The main branch has changes that have not been released yet. If you want to see released code, go to the "Releases" page and choose to browse the code for the release you are using.

For the documentation, the "latest" version is for the main branch (inclulding unreleased code). If you want to see the current official release, select the "stable" version.
