### ISSUE TITLE
AsyncServer.enter_room() is not awaitable

### ISSUE THREAD

**Issue by tt2468** [miguelgrinberg/python-socketio#1256]
**Describe the bug**
When attempting to call `AsyncServer.enter_room()` with await, a TypeError exception is thrown:

`TypeError: object NoneType can't be used in 'await' expression`

**To Reproduce**
1. Implement a basic AsyncServer class
2. On `connect`, attempt to enter SID into a room with `await sio.enter_room(sid, 'testroom')`
3. TypeError will be thrown

Calling the function without an await statement enters the client into the room as expected.

**Expected behavior**
The docs, along with code, label this function as a coroutine, when in fact it does not return any awaitable, making it functionally not a coroutine.

**Additional context**
The `enter_room()` method calls the AsyncServer's manager instance:

https://github.com/miguelgrinberg/python-socketio/blob/d40b3a33fff5c6b896559fc534ccd611ab9cf1f4/src/socketio/async_manager.py#L72

Which calls the synchronous inherited function, `basic_enter_room()`. As such, `None` is returned instead of an awaitable.

**Comment by miguelgrinberg** [comment]
The `enter_room` and `leave_room` methods were not awaitable, and they should have been. I noticed this recently and have fixed it. These fixes have not been released yet.

My guess is that you are reading the "latest" version of the docs, which maps to the main branch. The "stable" docs should show these methods as regular functions. This is obviously going to be a breaking change.

**Comment by tt2468** [comment]
Ah, cool. By chance do you mind pinging or closing this issue when a release is made with these changes?

**Comment by miguelgrinberg** [comment]
The release with the async enter/leave room is out now. This is in version 5.10.0.
