### ISSUE TITLE
`max_http_buffer_size` value seem ignored by the server

### ISSUE THREAD

**Issue by ezio-melotti** [miguelgrinberg/python-socketio#1272]
**Description**
If I set `max_http_buffer_size` on a server (e.g. `socketio.AsyncServer`), the value is seemingly ignored, since I'm still able to send packets that are larger than the max.

**To Reproduce**
`sioserver.py`
```py
import time

import socketio

from aiohttp import web


SMALL_SIZE = 1_500
LARGE_SIZE = 10_000_000
MAX_SIZE   = 1_000_001  # 1 byte more than the default

sio = socketio.AsyncServer(async_mode='aiohttp', max_http_buffer_size=MAX_SIZE,
                           logger=True, engineio_logger=True)
print(f'{sio.eio.max_http_buffer_size=}')
app = web.Application()
sio.attach(app)

@sio.event
def connect(sid, environ):
    print(f'{sid} connected')

@sio.on('send_data')
async def send_data(sid):
    small_msg = {'type': 'small', 'content': 'x'*SMALL_SIZE}
    large_msg = {'type': 'large', 'content': 'x'*LARGE_SIZE}
    print('Sending messages...')
    for n, msg in enumerate([small_msg, large_msg, small_msg]):
        msg['n'] = n
        print(f'Sending test_msg {n} ({msg["type"]})...', end=' ')
        await sio.emit("test_msg", msg)
        print("done")
        time.sleep(2)

    print('Disconnecting client...')
    await sio.disconnect(sid)

@sio.event
def disconnect(sid):
    print(f'{sid} disconnected\n')

if __name__ == '__main__':
    web.run_app(app, host='localhost', port=5000)
```
`sioclient.py`:
```py
import asyncio
import socketio

sio = socketio.AsyncClient(logger=True, engineio_logger=True)

@sio.event
async def connect():
    print('connection established')
    await sio.emit('send_data')

@sio.on('test_msg')
async def test_msg(data):
    print(f'Received test_msg {data["n"]} '
          f'({data["type"]} - len={len(data["content"])})')

@sio.event
async def disconnect():
    print('disconnected from server')

async def main():
    await sio.connect('http://localhost:5000')
    await sio.wait()

if __name__ == '__main__':
    asyncio.run(main())
```
`requirements.txt`
```
python-socketio==5.10.0
python-engineio==4.8.0
aiohttp
```

Commands to run the reproducer:
```
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
python3 sioserver.py
python3 sioclient.py  # in a different shell
```
The `sioclient.py` will request data from the server on connect (by emitting a `send_data` message) and the server will send a small message, a large message, and another small message.  The first small message always reaches the client, the large message reaches the client but it's then rejected, causing a client disconnection.

**Expected behavior**
When running this code, the server is still able to send the `large_message`, even if its size is over the `MAX_SIZE` limit.
If the `max_http_buffer_size` is also supposed to apply to outgoing packets, the server should raise an error when attempting to send a packet that is bigger than the limit, if not, [the docs](https://python-socketio.readthedocs.io/en/latest/api.html#socketio.AsyncServer) should mention this explicitly.

Also note that:
* with `LARGE_SIZE = 1_500_000` the server can send and the client can receive -- probably because the compressed size is still `< MAX_SIZE`
* with `LARGE_SIZE = 10_000_000` the server can send but the client gets disconnected -- probably because the size is bigger than the default 1M, even when compressed

**Logs**
<details>
<summary>Server logs...</summary>

Note: I generated these logs by running `python3 sioserver.py &> sioserver.log` and then manually replacing all the `x`s to generate a shorter log.  It looks like the stderr messages got written before the stdout ones, but the output should still be straightforward enough to understand.

```
Server initialized for aiohttp.
RXB2Ww-fPejL7pC4AAAA: Sending packet OPEN data {'sid': 'RXB2Ww-fPejL7pC4AAAA', 'upgrades': ['websocket'], 'pingTimeout': 20000, 'pingInterval': 25000}
RXB2Ww-fPejL7pC4AAAA: Received request to upgrade to websocket
RXB2Ww-fPejL7pC4AAAA: Upgrade to websocket successful
RXB2Ww-fPejL7pC4AAAA: Received packet MESSAGE data 0{}
RXB2Ww-fPejL7pC4AAAA: Sending packet MESSAGE data 0{"sid":"Muur24c3k0_qO462AAAB"}
RXB2Ww-fPejL7pC4AAAA: Received packet MESSAGE data 2["send_data"]
received event "send_data" from Muur24c3k0_qO462AAAB [/]
emitting event "test_msg" to all [/]
RXB2Ww-fPejL7pC4AAAA: Sending packet MESSAGE data 2["test_msg",{"type":"small","content":"<1500 x manually omitted>","n":0}]
emitting event "test_msg" to all [/]
RXB2Ww-fPejL7pC4AAAA: Sending packet MESSAGE data 2["test_msg",{"type":"large","content":<10000000 x manually omitted>","n":1}]
emitting event "test_msg" to all [/]
RXB2Ww-fPejL7pC4AAAA: Sending packet MESSAGE data 2["test_msg",{"type":"small","content":"<1500 x manually omitted>","n":2}]
Disconnecting Muur24c3k0_qO462AAAB [/]
RXB2Ww-fPejL7pC4AAAA: Sending packet MESSAGE data 1
_BHdZhOE8A300O3lAAAC: Sending packet OPEN data {'sid': '_BHdZhOE8A300O3lAAAC', 'upgrades': ['websocket'], 'pingTimeout': 20000, 'pingInterval': 25000}
_BHdZhOE8A300O3lAAAC: Received request to upgrade to websocket
_BHdZhOE8A300O3lAAAC: Upgrade to websocket successful
_BHdZhOE8A300O3lAAAC: Received packet MESSAGE data 0{}
_BHdZhOE8A300O3lAAAC: Sending packet MESSAGE data 0{"sid":"V0WhC4FLzSUAzuxkAAAD"}
_BHdZhOE8A300O3lAAAC: Received packet MESSAGE data 2["send_data"]
received event "send_data" from V0WhC4FLzSUAzuxkAAAD [/]
emitting event "test_msg" to all [/]
_BHdZhOE8A300O3lAAAC: Sending packet MESSAGE data 2["test_msg",{"type":"small","content":"<1500 x manually omitted>","n":0}]
emitting event "test_msg" to all [/]
_BHdZhOE8A300O3lAAAC: Sending packet MESSAGE data 2["test_msg",{"type":"large","content":"<10000000 x manually omitted>","n":1}]
emitting event "test_msg" to all [/]
_BHdZhOE8A300O3lAAAC: Sending packet MESSAGE data 2["test_msg",{"type":"small","content":"<1500 x manually omitted>","n":2}]
service task canceled
sio.eio.max_http_buffer_size=1000001
======== Running on http://localhost:5000 ========
(Press CTRL+C to quit)
Muur24c3k0_qO462AAAB connected
Sending messages...
Sending test_msg 0 (small)... done
Sending test_msg 1 (large)... done
Sending test_msg 2 (small)... done
Disconnecting client...
Muur24c3k0_qO462AAAB disconnected

V0WhC4FLzSUAzuxkAAAD connected
Sending messages...
Sending test_msg 0 (small)... done
Sending test_msg 1 (large)... done
Sending test_msg 2 (small)... V0WhC4FLzSUAzuxkAAAD disconnected

done
Disconnecting client...
```
</details>

<details>
<summary>Client logs...</summary>

Note: when the large message is received, the client disconnects and tries to reconnect again in a loop (sometimes failing with an error).  Here I stopped it with a ctrl+c.

```
Attempting polling connection to http://localhost:5000/socket.io/?transport=polling&EIO=4
Polling connection accepted with {'sid': 'RXB2Ww-fPejL7pC4AAAA', 'upgrades': ['websocket'], 'pingTimeout': 20000, 'pingInterval': 25000}
Engine.IO connection established
Sending packet MESSAGE data 0{}
Attempting WebSocket upgrade to ws://localhost:5000/socket.io/?transport=websocket&EIO=4
WebSocket upgrade was successful
Received packet NOOP data 
Received packet MESSAGE data 0{"sid":"Muur24c3k0_qO462AAAB"}
Namespace / is connected
connection established
Emitting event "send_data" [/]
Sending packet MESSAGE data 2["send_data"]
Received packet MESSAGE data 2["test_msg",{"type":"small","content":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","n":0}]
Received event "test_msg" [/]
Received test_msg 0 (small - len=1500)
Server sent unexpected packet 258 data Message size 10000050 exceeds limit 4194304, aborting
Waiting for write loop task to end
Exiting write loop task
Engine.IO connection dropped
disconnected from server
Connection failed, new attempt in 1.02 seconds
Exiting read loop task
Attempting polling connection to http://localhost:5000/socket.io/?transport=polling&EIO=4
Polling connection accepted with {'sid': '_BHdZhOE8A300O3lAAAC', 'upgrades': ['websocket'], 'pingTimeout': 20000, 'pingInterval': 25000}
Engine.IO connection established
Sending packet MESSAGE data 0{}
Attempting WebSocket upgrade to ws://localhost:5000/socket.io/?transport=websocket&EIO=4
WebSocket upgrade was successful
Received packet NOOP data 
Received packet MESSAGE data 0{"sid":"V0WhC4FLzSUAzuxkAAAD"}
Namespace / is connected
connection established
Emitting event "send_data" [/]
Sending packet MESSAGE data 2["send_data"]
Reconnection successful
^CSending packet CLOSE data None
Engine.IO connection dropped
disconnected from server
Write loop: WebSocket connection was closed, aborting
Exiting write loop task
Server sent unexpected packet 256 data None, aborting
Waiting for write loop task to end
Exiting read loop task
Traceback (most recent call last):
  File "/home/wolf/dev/my/siobug2/sioclient.py", line 25, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/wolf/dev/my/siobug2/sioclient.py", line 22, in main
    await sio.wait()
  File "/home/wolf/dev/my/siobug2/venv/lib/python3.11/site-packages/socketio/async_client.py", line 179, in wait
    await self.sleep(1)  # give the reconnect task time to start up
    ^^^^^^^^^^^^^^^^^^^
  File "/home/wolf/dev/my/siobug2/venv/lib/python3.11/site-packages/socketio/async_client.py", line 340, in sleep
    return await self.eio.sleep(seconds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wolf/dev/my/siobug2/venv/lib/python3.11/site-packages/engineio/async_client.py", line 190, in sleep
    return await asyncio.sleep(seconds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 639, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError

```
</details>

**Additional context**

<details>
<summary>More context that is not directly relevant with this issue...</summary>

I have a Flask app that is sending large packets to a JS frontend.  After updating to `python-engineio==4.7.1` (indirectly, after an update to `flask_socketio`), the client stopped receiving these large packets, with no errors from the server or the client.

Downgrading to `python-engineio==4.7.0` solves the issue and -- since the frontend is the same -- it would appear that `4.7.1` silently drops these big packets, however I haven't been able to recreate a minimal reproducer for this yet.  I have a different version of the reproducer included above that uses Flask + `flask_socketio`, but the behavior between `4.7.0` and `4.7.1` seems to be the same (i.e. the server sends without errors, the client receives and rejects the large packet).

With this issue I want to make sure if the current behavior is intended or a bug, since setting different limits might help me debug and identify the actual size of the packets I'm sending.  Since both client and server should have the same 1M default limit, seeing an error from the server when I'm trying to send a packet >1M  would confirm that I'm indeed sending packets that are too big for the client to receive.

This issue is a follow-up of:
* https://github.com/miguelgrinberg/python-socketio/issues/1006#issuecomment-1793857499
* https://github.com/overthesun/simoc/pull/443#issuecomment-1793856752

My server-side code (that is failing silently on `>=4.7.1`) is at https://github.com/miguelgrinberg/python-socketio/issues/1006#issuecomment-1793857499

I'll keep working on a reproducer for the `4.7.1` failures and possibly create a separate issue if I succeed.

</details>

**Comment by miguelgrinberg** [comment]
You are sending bit packets from server to client, which isn't a security risk, so it isn't limited.

The intention of the `max_http_buffer_size` argument is to protect the server against attackers trying to make it fail or crash. If the server wants to send a large packet it is assumed that it knows what it is doing.

**Comment by ezio-melotti** [comment]
> You are sending big packets from server to client, which isn't a security risk, so it isn't limited.

Makes sense.  If sending isn't limited, then I'm not sure why I can send big packets successfully with 4.7.0 but not 4.7.1.  This is anyway unrelated to this issue, so I'll dig some more and possibly open a separate issue.

> I think the documentation needs to clarify this, the current wording isn't clear enough.

Do you want me to make a PR?

**Comment by miguelgrinberg** [comment]
Do you have either `gevent-websocket` or `simple-websocket` installed? Which and what version(s)?

**Comment by ezio-melotti** [comment]
> Do you have either `gevent-websocket` or `simple-websocket` installed? Which and what version(s)?

I don't appear to have `gevent-websocket`, but I do have `simple-websocket` (`python-socketio` requires `python-engineio` that requires `simple-websocket`):
```console
# pip list | grep socket
python-socketio        5.9.0
simple-websocket       1.0.0
```
If it matters, I also have `gevent==22.10.2` and `gunicorn==20.1.0`, and I'm using `werkzeug.middleware.proxy_fix.ProxyFix` with Nginx.

**Comment by miguelgrinberg** [comment]
Your analysis is incorrect.

As far as I can see, your WebSocket connection is fine. From your logs:

```
RXB2Ww-fPejL7pC4AAAA: Received request to upgrade to websocket
RXB2Ww-fPejL7pC4AAAA: Upgrade to websocket successful
```

The difference is that python-engineio 4.7.0 required gevent-websocket to enable WebSocket connections, and you don't have this package installed. In 4.7.1 python-engineio can use gevent-websocket or simple-websocket, so WebSocket is enabled through simple-websocket.

I believe the WebSocket connection is ended as a result of your server sending that large message. But I'm not sure where is the disconnection triggered from. The simple-websocket package uses the `wsproto` for the low-level WebSocket protocol logic. There is no maximum configured for simple-websocket, but I'm wondering if maybe there is in wsproto. I'll have to investigate that.

**Comment by ezio-melotti** [comment]
> As far as I can see, your WebSocket connection is fine. From your logs:

Just to clarify, the logs in the first message are from the minimal reproducer included in the same message (with both client and server written in Python, and using `AsyncServer` and `AsyncClient`).  With those two scripts, the behavior between `python-engineio` `4.7.0` and `4.7.1` seems to be the same: the connection is upgraded to websockets, the server is able to send big messages, and the client receives them and rejects them if they are too big.  In their venv, only `simple-websocket==1.0.0` is installed -- `gevent-websocket` isn't.

The actual issue I've been trying to figure out for a few weeks now is on a more complex application, that uses the dependencies described in https://github.com/miguelgrinberg/python-socketio/issues/1272#issuecomment-1800280649.  I haven't been able to create a minimal reproducer for that yet, but I confirmed with my application that the issue has been introduced in `614f564` as described in my previous message.

I also ran into a number of issues while trying to debug the problem:
* downgrading `flask_socketio` version didn't initially fix the issue, since the issue is actually in `python-engineio`, so I had to figure that out and pin its version to `4.7.0` to fix my application
* the `max_http_buffer_size` is set from `python-socketio` and seems to be ignored for outgoing messages, so my attempts at tweaking its value didn't help, leading to this issue (which can now be considered a documentation issue, since the behavior seems intentional)
* the big messages just disappear, with no errors (at least on the server side, I'm still trying to get more logs out of the JS client -- `socket.io-client`)
* the behavior changes depending on the transport used (`polling` or `websocket`), and the transport changes depending on several factors (e.g. the configurations of the Nginx server, Docker containers, frontend/backend, etc.)

I understand that the problems with my application are not strictly related to this issue, and apologize for the confusion.  Given that those problems are related to a number of different packages, I didn't want to open even more issues and making the conversation more difficult to follow, but I'm happy to move the discussion elsewhere if you think it would be better.

**Comment by miguelgrinberg** [comment]
Unfortunately I do not see how I can help any more than I have.

As I explained, the constraining of messages by size in python-engineio is done for security purposes, and it is only enforced on incoming messages (to the server). Outgoing messages are considered trusted, so they are not checked for size. But python-engineio and python-socketio rely on a choice of libraries, some of which may have their own limits.

I also explained that the difference between python-engineio 4.7.0 and 4.7.1 is that in 4.7.1 the gevent driver enables websocket if one of gevent-websocket or simple-websocket is installed, while in 4.7.0 it only enabled it for gevent-websocket, which you indicated that you do not use.

**Comment by ezio-melotti** [comment]
Thanks for you help in debugging this issue.

Since I couldn't get `simple-websocket` to work properly, I [added `gevent-websocket` as a dependency](https://github.com/overthesun/simoc/pull/446) (and updated the `gunicorn` command) and that fixed the issue.

To summarize what I tried:
* with `python-engineio` 4.7.0 (and no other websocket modules installed):
  * no websocket upgrade availables, polling used instead
  * data transferred successfully (through polling)
* with `python-engineio` 4.7.1 (has `simple-websocket` as a dependency):
  * websocket now available through `simple-websocket` and used instead of polling
  * data sent from the server but never received from the client (with no error messages)
* with `python-engineio` 4.7.1 and `gevent-websocket`:
  * websocket also available through  `gevent-websocket`
  * data transferred successfully (through websockets)

----

Before giving up and switching to `gevent-websocket`, I dug a bit deeper and noticed that we are using `sio.start_background_task`.  This might (or might not) be related to the issue, but I haven't investigated further.  If an error is raised in a separate task, it might also get lost, explaining why I didn't see any error in the logs.

So there are still 3 (potential) issues:
* document that `max_http_buffer_size` only works on incoming data (I can update this issue and create a PR for that if you want);
* figure out why `simple-websocket` didn't work for me (if you want me to try/test something else I can help you with that too, but otherwise I consider my issue solved and I'm not planning to dig any deeper myself)
* figure out why there are no errors reported when `simple-websocket` fails (this sounds like a separate issue exposed by the issues I was having, but I might be wrong)

Let me know if you want me to report these separately / turn this in a doc issue / create a PR / help you investigate the remaining issues.

**Comment by miguelgrinberg** [comment]
@ezio-melotti do you have a small example that reproduces the "data sent from the server but never received from the client (with no error messages)" issue?

**Comment by ezio-melotti** [comment]
I can reproduce the problem consistently with my application using `simple-websocket` (works fine with polling and `gevent-websocket`), but I haven't been able to narrow down the issue enough to create a minimal reproducer.

**Comment by miguelgrinberg** [comment]
@ezio-melotti I have updated the documentation based on your suggestions. if you come up with a reproduction example that I can use to reproduce the simple-websocket issue, please open a separate issue with it.

**Comment by ezio-melotti** [comment]
> @ezio-melotti I have updated the documentation based on your suggestions. 

Thanks for updating the docs!

> if you come up with a reproduction example that I can use to reproduce the simple-websocket issue, please open a separate issue with it.

Adding `gevent-websocket` as a dependency solved the problems I encountered with `simple-websocket`, and I haven't looked further into the issue.  This covers the second of the three issues I mentioned above (and below), and I guess that without a reproducer the third also can't be investigated further (except maybe looking at the code for `try/except`s that might be swallowing exceptions).

The first of the three issue should still be addressed though, since the docs don't mention that the limit only applies to incoming data.  Note that `max_http_buffer_size` is also documented in the `socketio-engine` package, so those docs should be updated too (and I'm still willing to create a PR if you want).

For reference, these are the three issues I'm talking about:

>    *  document that `max_http_buffer_size` only works on incoming data (I can update this issue and create a PR for that if you want);
>    *  figure out why `simple-websocket` didn't work for me (if you want me to try/test something else I can help you with that too, but otherwise I consider my issue solved and I'm not planning to dig any deeper myself)
>    * figure out why there are no errors reported when `simple-websocket` fails (this sounds like a separate issue exposed by the issues I was having, but I might be wrong)

**Comment by miguelgrinberg** [comment]
> The first of the three issue should still be addressed though, since the docs don't mention that the limit only applies to incoming data.

Yes, they do now. 

> `max_http_buffer_size` – The maximum size that is accepted for incoming messages. The default is 1,000,000 bytes. In spite of its name, the value set in this argument is enforced for HTTP long-polling and WebSocket connections.

Updated for Socket.IO [here](https://python-socketio.readthedocs.io/en/latest/api.html#socketio.Server) and Engine.IO [here](https://python-engineio.readthedocs.io/en/latest/api.html#engineio.Server) (plus their async counterparts). You have to look at the "latest" version of the docs, which will become "stable" when a release is made.

**Comment by ezio-melotti** [comment]
> Yes, they do now.

Sorry, I saw the part that mentioned that `max_http_buffer_size` also applies to WebSockets connections and missed that you also added the "incoming" in the first sentence :upside_down_face:

If I'll ever manage to create a reproducer for other two issues I'll let you know.  Thanks again!
