### ISSUE TITLE
Implementing `__enter__`/`__exit__` on `Client` like `SimpleClient`

### ISSUE THREAD

**Issue by jamesbraza** [miguelgrinberg/python-socketio#1274]
**Is your feature request related to a problem? Please describe.**

It looks like as of 5.10.0, `SimpleClient` supports `__enter__`/`__exit__` for calling `disconnect`.  This is nice for Pythonic code and ensuring `disconnect` gets called even upon `Exception`.

**Describe the solution you'd like**

Can we port this same capability to `Client`?

**Describe alternatives you've considered**

One can use a DIY `contextlib.contextmanager` for this:

```python
from contextlib import contextmanager

import socketio


@contextmanager
def connection(
    client: socketio.Client, *connect_args, **connect_kwargs
) -> Iterator[socketio.Client]:
    client.connect(*connect_args, **connect_kwargs)
    try:
        yield client
    finally:
        client.disconnect()
```

It would be nice if the source code for `Client` directly supported `__enter__`/`__exit__` though to avoid this extra code.

**Logs**

N/a

**Additional context**

**Comment by miguelgrinberg** [comment]
I don't believe this is very useful on the event-based client, because it is event based, so the decision to disconnect is unlikely to be made in the main function. Normally the disconnection will be triggered inside an event handler, or remotely by the server.

**Comment by jamesbraza** [comment]
Okay, I didn't realize `Client` was supposed to be event based.  I follow what you're saying, thanks for the detailed explanation.  I guess not having `__enter__` and `__exit__` implemented help enforce that usage pattern.

Feel free to close this out
