### ISSUE TITLE
sio.disconnect() will connect after a connection drop

### ISSUE THREAD

**Issue by ghost** [miguelgrinberg/python-socketio#1277]
**Describe the bug**
sio.disconnect() will connect after a connection drop

**To Reproduce**
1. Connect to your backend
2. do the functions you want
3. once done, use sio.disconnect() and it will reconnect if you dropped connections

**Expected behavior**
should fully disconnect, not connect again

**Logs**
```
Emitting event "send_position_1" [/]
Received event "get_position_1" [/]
Engine.IO connection dropped
Connection failed, new attempt in 1.43 seconds
Engine.IO connection established
Namespace / is connected
Reconnection successful
```

**Additional context**
once connection dropped, and then using sio.disconnect(), it will reconnect after

**Comment by miguelgrinberg** [comment]
This is likely a problem in your application. Could you please share a simple client and server that reproduce this problem?

**Comment by Xytriza** [comment]
I dont have a simple example of it, as its a pygame app

but here is some of the code


```
def multiplayer():
    global paddle_a, paddle_b, ball, ball_dx, ball_dy, score
    initialize_game()
    sio.connect('https://ultimatepingpongsocket.xytriza.com')
    while True:
        if ball.left <= 0:
            if sio.connected:
                sio.disconnect()
            initialize_game()
            death_screen(score, 2)
        if ball.right >= 800:
            if sio.connected:
                sio.disconnect()
            initialize_game()
            death_screen(score, 2)

        keys = pygame.key.get_pressed()
        if keys[pygame.K_w] and paddle_a.top > 0:
            paddle_a.y -= 5
            if sio.connected:
                sio.emit('send_position_2', paddle_a.y)
        if keys[pygame.K_s] and paddle_a.bottom < 600:
            paddle_a.y += 5
            if sio.connected:
                sio.emit('send_position_2', paddle_a.y)

        pygame.display.flip()
        pygame.time.Clock().tick(60)
```

for some reason if i send too many updates to the server itll cause a freeze

**Comment by miguelgrinberg** [comment]
The logs do not show that you have initiated a disconnection, they show that the client lost the connection to the server, and for that reason it is attempting to reconnect. If you do not want reconnections to happen, you can disable it when you create the client object.

**Comment by Xytriza** [comment]
well i lost connection a bit before i died, and then disconnect didnt do anything

**Comment by Xytriza** [comment]
i do want reconnects tho, just not after sio.disconnect()

**Comment by miguelgrinberg** [comment]
Let me see if I understand. You got disconnected from the server, and while the client was in the process of reconnecting you called `disconnect()`? And your expectation is that this will stop the reconnection?

**Comment by vipcxj** [comment]
@miguelgrinberg Hi, How can I recognize whether the disconnect event is triggered by invoking disconnect method or a network issue in on callback? I think we should use another event (maybe called close) to represent disconnect triggered bt user manually disconnect.

**Comment by miguelgrinberg** [comment]
@vipcxj correct, the disconnect reason is not being exposed to the disconnect handler. I have never got around to expose that. Will think about how to best do this.

**Comment by Xytriza** [comment]
> Let me see if I understand. You got disconnected from the server, and while the client was in the process of reconnecting you called `disconnect()`? And your expectation is that this will stop the reconnection?

yes this is correct, when dropping connection to the server, and then disconnect() it should cancel the reconnect, not continue it as its meant to be disconnected

**Comment by Xytriza** [comment]
it should ancel the reconnect.

**Comment by Xytriza** [comment]
ok👍

**Comment by blazing-gig** [comment]
I managed to achieve this by manually setting the `_reconnect_abort` event explicitly like so:

```
if self._sio_client.connected:
    await self._sio_client.disconnect()
    if self._sio_client._reconnect_abort:
        self._sio_client._reconnect_abort.set()
```

This seems to have worked.
@miguelgrinberg Could you pls comment on if this can serve as a potential workaround or even a fix ?

**Comment by Xytriza** [comment]
Sorry I haven’t checked GitHub, but when I lost connection and the player
exits the menu (disconnects) it doesn’t disconnect is what I am trying to
explain

**Comment by Xytriza** [comment]
Also I’m not using classes so this isn’t helpful to me

**Comment by blazing-gig** [comment]
@Xytriza You can get rid of the `self` if you aren't using classes. `sio_client` is just an instance of `socketio.AsyncClient`.

**Comment by Xytriza** [comment]
ok

**Comment by miguelgrinberg** [comment]
> I managed to achieve this by manually setting the `_reconnect_abort` event explicitly like so:
> 
> ```
> if self._sio_client.connected:
>     await self._sio_client.disconnect()
>     if self._sio_client._reconnect_abort:
>         self._sio_client._reconnect_abort.set()
> ```
> 
> This seems to have worked. @miguelgrinberg Could you pls comment on if this can serve as a potential workaround or even a fix ?

This is not something that I would recommend, because you are using private attributes that are not guaranteed to be preserved in future releases, but as a temporary workaround it may be okay. You should probably wait for the reconnect task to end after signaling it to exit.

**Comment by blazing-gig** [comment]
@miguelgrinberg Right. So I believe just adding this line should do:

```python
if self._sio_client.connected:
    await self._sio_client.disconnect()
    if self._sio_client._reconnect_abort:
        self._sio_client._reconnect_abort.set()
        await self._sio_client._reconnect_task # Per your suggestion
```

**Comment by miguelgrinberg** [comment]
Sure. As I said above though, I cannot guarantee that this will continue to work in future versions, since you are accessing privates/internals of the library.

**Comment by miguelgrinberg** [comment]
The `shutdown()` method in the client can be now used to stop a client that is connected or in the reconnect loop.
