### ISSUE TITLE
Running a socket server in backgroud?

### ISSUE THREAD

**Issue by piyushdivyankar1994** [miguelgrinberg/python-socketio#128]
So I have a socket server that is constantly receiving data from a source. This data comes in bursts and is processed in threads using threading.Thread class. 
```
def fetch(sock):
    while True:
        """
        Runs the process that will continuously fetch data and keep 
        creating new threads to process it.

        sock : A socket.socket object from standard socket library in python
        """
        c_data, address = sock.recvfrom(8129)
        
        # creates a myThread object that is a derived class from threading.Thread
        newthread = myThread(c_data)
        # Runs the thread
        newthread.start()
```
`newthread.start()` runs a function that processes `c_data`  and emits events to connected clients. 

I have to run a eventlet server and have it be capable of handling all the request that a socketIO-client may make and simultaneously keep running this fetch function so that it can keep emitting data to clients. 

The problem:
If I first start the eventlet server the execution of code stops at that line and nothing else can be executed. However if I first start the `fetch()` then execution never reaches the end. 
I am not able to do this using background threads as well. On using background threads it seems that the server starts but it doesn't handle any events emitted from the client.

**Comment by miguelgrinberg** [comment]
You can't use regular threads with eventlet. You can launch your thread with the `socketio.start_background_task()` function, which is going to start a green thread compatible with eventlet. Alternatively, you can monkey patch the standard library for eventlet, so that all the threading code is converted to green threads.

**Comment by piyushdivyankar1994** [comment]
Thanks for the advice. After changing my code to use only socketIO threads everything works fine.
