### ISSUE TITLE
Update documentation of usage with Gunicorn + gevent/eventlet

### ISSUE THREAD

**Issue by maybephilipp** [miguelgrinberg/python-socketio#1280]
**Describe the bug**
Currently the documentation still states that for websocket support with Gevent, I need to use gevent-websocket. Same for Gevent + Gunicorn.

`simple-websocket` support was added in [this commit](https://github.com/miguelgrinberg/python-engineio/commit/614f564275c635dc8b03d33dab44bf80d280cbcc) so now the docs, in my opinion, should mention that nothing is needed for websocket support (batteries included). But maybe it worth mentioning the difference between two packages (I haven't found comparison, but in my opinion `simple-websocket` is just simpler to configure - almost nothing todo).

https://python-socketio.readthedocs.io/en/stable/server.html#gevent

**Another question is:** why doc says that gunicorn has some limitation of workers number if it's not really true? If I don't miss something, I could be true only if the app uses long-polling with sticky sessions, but otherwise I don't see any reason not to use >1 workers in gunicorn. Am I wrong?

**To Reproduce**
1. Go to 'https://python-socketio.readthedocs.io/en/stable/server.html#gevent'

**Expected behavior**
The doc shouldn't mention `gevent-websocket` unless it has some advantages as an alternative.

**Logs**
_no logs_

Thank you for your work! 🤗

**Comment by miguelgrinberg** [comment]
The doc update is being discused in #1272. I'm taking care of that.

Disabling long-polling allows you to use multiple workers in Gunicorn correct, but it has some disadvantages. And even without the sticky sessions, you still need to use a message queue for the workers to coordinate. I have been thinking about how to explain this in the documentation without making it even more convoluted than it is and at some point I'm going to reorganize the docs to better convey these options in addition to the more traditional ones.

**Comment by miguelgrinberg** [comment]
References to gevent-websocket have been removed.

**Comment by miguelgrinberg** [comment]
@lsapan I think this is less interesting than it sounds because in reality multiple works have always been supported.

- If you want to use long-polling and websocket both: Run multiple single-worker Gunicorns (each on a different port), and put a load balancer such as nginx in front of them.
- If you want only websocket: You can run a single Gunicorn process with multiple workers, but clients attempting to connect with long-polling will get errors.

In both cases each instance of Socket.IO must connect to a message queue.

**Comment by lsapan** [comment]
@miguelgrinberg got it, thanks for clarifying! I just wanted to make sure I wasn't missing some unforeseen issue.

Thanks again for such an awesome library! ✨
