### ISSUE TITLE
emitting to a room simultaneously

### ISSUE THREAD

**Issue by piyushdivyankar1994** [miguelgrinberg/python-socketio#130]
Is it possible to emit data to all the sids in a room simultaneously. Currently it is implemented using a for loop.

**Comment by miguelgrinberg** [comment]
No, because each client has its own connection with the server.

**Comment by piyushdivyankar1994** [comment]
Would a pub-sub reddis sever be able to do this.

**Comment by miguelgrinberg** [comment]
Redis has to do the same thing to notify all subscribers.

**Comment by piyushdivyankar1994** [comment]
Is there an alternative to send messages in parallel.

**Comment by miguelgrinberg** [comment]
The messages are sent in parallel, in spite of the loop. The writes are all asynchronous.

**Comment by piyushdivyankar1994** [comment]
So I understand that if 100 users are connected to a room and I broadcast information to that room all 100 users will receive the message simultaneously. 
And final question: How many users can I connect to a room so that there is no latency or equal latency in receiving the message on the user side?

**Comment by miguelgrinberg** [comment]
Clients will unlikely receive their messages at the same time, it'll just be close, but not exact. The latency will vary for each connection to the server, there is no way to guarantee identical transfer times.

**Comment by piyushdivyankar1994** [comment]
That answers all my questions. Thanks for all the patience and effort. I am closing this issue now.
