### ISSUE TITLE
Python socket ids for client and server dont match.

### ISSUE THREAD

**Issue by manjeshshenoy** [miguelgrinberg/python-socketio#1310]
Hi Miguel,

I find there is  some bug in client side of  python-socketio,  sids of server and client dont match when I review the logs.

# ############Here is my client code.

import socketio
import asyncio
import time

sio_client = socketio.AsyncClient()

@sio_client.event
async  def connect():
    print('Connected to Server')

@sio_client.event
async  def disconnect():
    print('Disconnected from Server')

@sio_client.on('response')
async  def response(data):
    print(data)

async def main():
    #await sio_client.connect(url='http://127.0.0.1:1112', socketio_path='socket_stream_Server')
    await sio_client.connect(url='http://127.0.0.1:1112')
    print('my sid is', sio_client.sid)
    print('my transport is', sio_client.transport)

    while True :
        await sio_client.emit('msg', 'this is client')
        time.sleep(1)
    await sio_client.disconnect()

asyncio.run(main())

# ################Here is my SERVER code

import socketio
from fastapi import FastAPI
import  uvicorn

sio_server =socketio.AsyncServer(
    async_mode ='asgi',
    cors_allowed_origins='*',
    logger=True,
    engineio_logger=True,
)

sio_app = socketio.ASGIApp(
    socketio_server=sio_server,
  #socketio_path='socket_stream_Server'
)

app =FastAPI()
app.mount('/',app=sio_app)

@sio_server.event
async def connect(sid, environ, auth):
    print('connected client', sid)
    await sio_server.emit('response', sid)

@sio_server.event
async def disconnect(sid):
    print('disconnect client', sid)

@sio_server.on('msg')
async def msg(sid, data):
    print("Msg receive from " +str(sid) +"and msg is : ",str(data))
    #await device.set(data)

@app.get('/')
async def home():
    return {'message' :  'Hello Developers'}

if __name__  =='__main__' :
    uvicorn.run('socket_stream_Server:app', reload=True,port=1112)

# ####################client log....
C:\Users\socket_stream_Client.py 
an5BaVkZ6lqt61DyAAAB
Connected to Server
my sid is yIaytbRE_mO4mjg2AAAA
my transport is <bound method BaseClient.transport of <socketio.async_client.AsyncClient object at 0x000001E3B7BD3FD0>>

# ###################server log......
C:\Users\socket_stream_Server.py 
Server initialized for asgi.
INFO:     Will watch for changes in these directories: ['C:\\Users\']
INFO:     Uvicorn running on http://127.0.0.1:1112 (Press CTRL+C to quit)
INFO:     Started reloader process [21716] using StatReload
Server initialized for asgi.
Server initialized for asgi.
INFO:     Started server process [25536]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
yIaytbRE_mO4mjg2AAAA: Sending packet OPEN data {'sid': 'yIaytbRE_mO4mjg2AAAA', 'upgrades': ['websocket'], 'pingTimeout': 20000, 'pingInterval': 25000}
yIaytbRE_mO4mjg2AAAA: Received request to upgrade to websocket
INFO:     ('127.0.0.1', 65076) - "WebSocket /socket.io/?transport=websocket&EIO=4&sid=yIaytbRE_mO4mjg2AAAA&t=1708276915.8557806" [accepted]
yIaytbRE_mO4mjg2AAAA: Upgrade to websocket successful
yIaytbRE_mO4mjg2AAAA: Received packet MESSAGE data 0{}
emitting event "response" to all [/]
yIaytbRE_mO4mjg2AAAA: Sending packet MESSAGE data 2["response","an5BaVkZ6lqt61DyAAAB"]
yIaytbRE_mO4mjg2AAAA: Sending packet MESSAGE data 0{"sid":"an5BaVkZ6lqt61DyAAAB"}
INFO:     127.0.0.1:65076 - "GET /socket.io/?transport=polling&EIO=4&t=1708276915.849796 HTTP/1.1" 200 OK
connected client an5BaVkZ6lqt61DyAAAB

# observation
Here I can clearly see that  socket id returned by server to client is  an5BaVkZ6lqt61DyAAAB which is different from sid of the client when consoled  yIaytbRE_mO4mjg2AAAA

**Comment by miguelgrinberg** [comment]
To get the `sid` assigned to a client, you should use the [get_sid()](https://python-socketio.readthedocs.io/en/stable/api.html#socketio.Client.get_sid) method.

**Comment by manjeshshenoy** [comment]
Ok, now using   get_sid()  provides same  sid on client side , so sid mismatch may not be the problem, 
 but the problem that i face is that client emits are not being received by the server. and there is a disconnect that happens after a minute, any suggestion on why this is happening.

# server log

NFO:     Uvicorn running on http://127.0.0.1:1112 (Press CTRL+C to quit)
INFO:     Started reloader process [4100] using StatReload
db connected!
Server initialized for asgi.
Server initialized for asgi.
INFO:     Started server process [16152]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
uelWnfNVb960WH7-AAAA: Sending packet OPEN data {'sid': 'uelWnfNVb960WH7-AAAA', 'upgrades': [], 'pingTimeout': 20000, 'pingInterval': 25000}
uelWnfNVb960WH7-AAAA: Received request to upgrade to websocket
INFO:     ('127.0.0.1', 57632) - "WebSocket /socket.io/?transport=websocket&EIO=4&t=1708310093.8300152" [accepted]
uelWnfNVb960WH7-AAAA: Upgrade to websocket successful
uelWnfNVb960WH7-AAAA: Received packet MESSAGE data 0{}
emitting event "response" to all [/]
uelWnfNVb960WH7-AAAA: Sending packet MESSAGE data 2["response","pIbKfi6FC1piUe9gAAAB"]
uelWnfNVb960WH7-AAAA: Sending packet MESSAGE data 0{"sid":"pIbKfi6FC1piUe9gAAAB"}
**connected client pIbKfi6FC1piUe9gAAAB**
service task canceled
uelWnfNVb960WH7-AAAA: Sending packet PING data None
**disconnect client pIbKfi6FC1piUe9gAAAB**

# client code.
```
async def main():
    await sio_client.connect(url='http://127.0.0.1:1112',transports=['websocket'])
    print('my sid is', sio_client.get_sid())

    while True :
        await sio_client.emit('msg', 'client msg stream')

```
# server code.

```
@sio_server.on('msg')
async def msg(sid, data):
    print("client :  ",str(data))


```

**Comment by miguelgrinberg** [comment]
Please provide complete simplified versions of your client and your server. With the snippets that you shared I cannot really tell what's wrong.

**Comment by manjeshshenoy** [comment]
I have provided the server.py and client.py  code,  please save the file with same name and run them in two different console.

**requirements**
pip install python-socketio uvicorn fastapi asyncio

python-socketio==5.11.1  
uvicorn==0.27.1
fastapi==0.92.0
asyncio==3.4.3


# # server Code    -- server.py

```
import socketio
from fastapi import FastAPI
import  uvicorn

sio_server =socketio.AsyncServer(
    async_mode ='asgi',
    cors_allowed_origins='*',
    logger=True,
    engineio_logger=True,
)

sio_app = socketio.ASGIApp(
    socketio_server=sio_server
)

app =FastAPI()
app.mount('/',app=sio_app)

@sio_server.event
async def connect(sid, environ, auth):
    print('connected client', sid)
    await sio_server.emit('response', sid)


@sio_server.event
async def disconnect(sid):
    print('disconnect client', sid)


############  below custom events  - msg1 and msg2  are not working !!  ############
@sio_server.on('msg1')
async def msg1(sid, data):
    print("Msg receive from " +str(sid) +"and msg is : ",str(data))
    await sio_server.emit('response',"you are  smart 1!")


@sio_server.event
async def msg2(sid, data):
    print("Msg receive from " +str(sid) +"and msg is : ",str(data))
    await sio_server.emit('response',"you are  smart 2!")

#####################################################################################

@app.get('/')
async def home():
    return {'message' :  'Hello Developers'}


def main():
    try:
        uvicorn.run('server:app', reload=True,port=1112)
    finally:
        print("db disconnected!")

if __name__  =='__main__' :
    main()
```




# # Client Code   -- client.py
```

import socketio
import asyncio
import time

sio_client = socketio.AsyncClient( )


@sio_client.event
async  def connect():
    print('Connected to Server')


@sio_client.event
async  def disconnect():
    print('Disconnected from Server')



@sio_client.on('response')
async  def response(data):
     print(data)



async def main():

    await sio_client.connect(url='http://127.0.0.1:1112',transports=['websocket'])
    print('my sid is', sio_client.get_sid())

     
    while True :
        await sio_client.emit('msg1', 'How are you ?')
        time.sleep(1)
		await sio_client.emit('msg2', 'How are you ?')
		
    await sio_client.disconnect()

asyncio.run(main())
```



**expectation is**   

1 . below two lines are executed in client side.

await sio_client.emit('msg1', 'How are you ?')
await sio_client.emit('msg2', 'How are you ?')

2 . server receives these emits.
  and server respond with the below emits  from  msg1 and msg2 events.

await sio_server.emit('response',"you are  smart 1!")
await sio_server.emit('response',"you are  smart 2!")

3. response from server  has to be received by client side event  @sio_client.on('response')
and print the server response.

**Comment by miguelgrinberg** [comment]
You can't use `time.sleep` in an asyncio application because it is a blocking call. Use `asyncio.sleep` instead.

**Comment by manjeshshenoy** [comment]
oh ok, it works now, thanks for pointing out the mistake.
