### ISSUE TITLE
Broadcast to all connected clients

### ISSUE THREAD

**Issue by bkinman** [miguelgrinberg/python-socketio#133]
I'm not sure if I'm mistaken or not, but it seems that when I have two clients (let's call them `client1`, and `client2 ` operating in the default namespace), that the server does not broadcast events emitted from `client1` to `client2`, and visa versa.

This seems to be in conflict with the documentation:
```
room – The recipient of the message. This can be set to the session ID of a client
to address that client’s room, or to any custom room created by the application,
If this argument is omitted the event is broadcasted to all connected clients.
```

Am I doing something wrong?

**Comment by miguelgrinberg** [comment]
A client can only emit an event to the server. There is no direct client-to-client communication. The server can emit to a single client, a room of clients, or all clients.

In your situation, you want client1 to emit an event to the server, and the hander for that event in the server should forward that data as a broadcast to the other clients.

**Comment by bkinman** [comment]
Excellent, thanks for the clarification Miguel!
