### ISSUE TITLE
Documention needs to be updated to remove outdated note about Sanic

### ISSUE THREAD

**Issue by catdogmat** [miguelgrinberg/python-socketio#1365]
**Describe the bug**
The message below says that the Sanic integration is broken, but the integration works perfect on the lastest version of Sanic.
> Note: Due to some backward incompatible changes introduced in recent versions of Sanic, it is currently recommended that a Sanic application is deployed with the ASGI integration instead.

**To Reproduce**
1. Go to this modules documention
2. Scroll to the Sanic integration section
3. The outdated note is on the page

**Expected behavior**
The note is not there.

**Logs**
None (as it is a documentation change)

**Additional context**
[Sanic issue (with confirmation that the issue is fixed)](https://github.com/sanic-org/sanic/issues/2572)

**Comment by miguelgrinberg** [comment]
Do you know which version of Sanic fixed this? They haven't closed the issue and the code looks exactly as wrong as I remember it.

**Comment by catdogmat** [comment]
I do not. I've only tested the lastest version but I would be happy to test earlier ones if needed.

**Comment by miguelgrinberg** [comment]
The original problem in Sanic isn't fixed. But it appears a [change](https://github.com/miguelgrinberg/python-engineio/commit/ccc7a86886f507bd7aa6985e5d1b070f9505ac46) I've made a few months ago to clean up WebSocket responses has indirectly caused this error response from Sanic to go away. I guess if it works, it works. :shrug:
