### ISSUE TITLE
receive() not implemented on AsyncClient

### ISSUE THREAD

**Issue by khaerensml6** [miguelgrinberg/python-socketio#1366]
As far as I can see, the receive method that is mentioned in the documentation doesn't exist.

https://python-socketio.readthedocs.io/en/latest/client.html#receiving-events

**Comment by miguelgrinberg** [comment]
It's here: https://github.com/miguelgrinberg/python-socketio/blob/main/src/socketio/simple_client.py#L158

**Comment by khaerensml6** [comment]
ahh it's only in the simple clients, apologies

**Comment by miguelgrinberg** [comment]
Correct. The simple client has a blocking receive. The other client uses event handlers.
