### ISSUE TITLE
Set a cookie from the server?

### ISSUE THREAD

**Issue by drawnwren** [miguelgrinberg/python-socketio#1380]
**Is your feature request related to a problem? Please describe.**
Socketio 4.7.0 introduced the ability for servers to set cookies [socketio docs](https://socket.io/how-to/deal-with-cookies)

Is there any way to get a similar set-cookie behavior from python-socketio?

**Comment by miguelgrinberg** [comment]
The `cookie` option has been available for many years, both in the JS and the Python servers. Scroll down from [here](https://python-socketio.readthedocs.io/en/stable/api.html#socketio.Server) to find it in the docs.
