### ISSUE TITLE
request from aiohttp

### ISSUE THREAD

**Issue by dfee** [miguelgrinberg/python-socketio#139]
Below I have two implementations of passing the aiohttp request to the AsyncNamespace methods. Are these methods fragile? Is there a better place upstream where I should be doing this? (i.e. will this work across all Managers?)

A wrapper that passes the aiohttp request.

```
from collections import OrderedDict
import functools
import inspect

import socketio


def pass_request(func):
    argspec = inspect.getargspec(func).args

    @functools.wraps(func)
    async def wrapper(namespace, *args):
        arg_map = OrderedDict(zip(argspec, (namespace, *args, None)))
        request = namespace.server.environ[arg_map['sid']]['aiohttp.request']
        arg_map['request'] = request
        rv = func(*arg_map.values())
        return await rv if inspect.isawaitable(rv) else rv
    return wrapper


class SocketNamesapce(socketio.AsyncNamespace):
    @pass_request
    def on_connect(self, sid, environ, request):
        # pylint: disable=no-self-use
        # pylint: disable=unused-argument
        print("connect ", sid)

    def on_disconnect(self, sid):
        # pylint: disable=no-self-use
        print('disconnect ', sid)

    @pass_request
    async def on_message(self, sid, data, request):
        print("message ", data)
        await self.emit('message', data, room=sid)
```

A subclass for AsyncNamespace that provide the request object if the method is requesting it.
```
class SocketNamesapce(socketio.AsyncNamespace):
    async def trigger_event(self, event, *args):
        handler_name = 'on_' + event
        callback = getattr(self, handler_name, None)
        if callback:
            argspec = inspect.getargspec(callback).args
            if 'request' in argspec:
                args = (*args, self.server.environ[args[0]]['aiohttp.request'])
        await super().trigger_event(event, *args)

    def on_connect(self, sid, environ, request):
        # pylint: disable=no-self-use
        # pylint: disable=unused-argument
        print('request', request)
        print("connect ", sid)

    def on_disconnect(self, sid):
        # pylint: disable=no-self-use
        print('disconnect ', sid)

    async def on_message(self, sid, data, request):
        print('request', request)
        print("message ", data)
        await self.emit('message', data, room=sid)
```

**Comment by dfee** [comment]
It looks like maybe I could hack [`AsyncServer._trigger_event`](https://github.com/miguelgrinberg/python-socketio/blob/master/socketio/asyncio_server.py#L316) to provide this functionality...

**Comment by miguelgrinberg** [comment]
If you want a much simpler approach, you can save the request on the connect handler so that you have it on any subsequent events. And this technique works on namespaces or function based events alike.

```python
requests = {}

@socketio.on('connect')
def on_connect(sid, environ):
    requests[sid] = environ['aiohttp.request']

@socketio.on('message')
def on_message(sid, data):
    print('request:', requests[sid])

@socketio.on('disconnect')
def on_disconnect(sid):
    del requests[sid]
```

**Comment by vlcinsky** [comment]
I have very similar need to access `aiohttp.Application` instance as it bears couple of properties to use in handling the event in Namespace class.

We have resolved that by adding:


	class MyNamespace(socketio.AsyncNamespace):
	    def __init__(self, namespace):
		super().__init__(namespace=namespace)
		self.app = None

	    async def on_connect(self, sid, environ):
		self.app = environ["aiohttp.request"].app
		# continue handling on_connect as needed

	    def on_disconnect(self, sid):
                # no need to remove app as it stays constant and only one
                pass

	    async def on_my_broadcast_event(self, sid, message):
	        # here using all the stuff attached to .app
		app = self.app
		devs_manager = app["devs_manager"]
		with await app["redis_pool"] as redis:
		    snap = await devs_manager.get_snapshot(redis)
		await self.emit('my response', {'data': snap})

I hope, we do it well.

The reason I note it here is to demonstrate, that accessint either `request` or `app` from code handling SocketIO events is rather common requirement.

**Comment by miguelgrinberg** [comment]
@vlcinsky Your solution looks good to me, but keep mind that it works for `app`, but not for `request`. The value of `app` is going to be constant across all requests, that is why you can add an attribute in the namespace. For `request`, you have to use my technique above, you need each thread to have its own.

**Comment by dfee** [comment]
Sorry, just coming back to this. Do you really mean each thread must have access to it's own request? Or, each socket instance must have it's own request? I thought the async implementation was threading independent?

**Comment by miguelgrinberg** [comment]
@dfee sorry, when I said "thread" I meant "green thread". I was referring to the different asyncio tasks, each handling a different request.
