### ISSUE TITLE
Can not send arrays/lists of objects/dicts as reply to a message

### ISSUE THREAD

**Issue by FichteFoll** [miguelgrinberg/python-socketio#15]
I'm using [Flask-SocketIO](https://github.com/miguelgrinberg/Flask-SocketIO) for this, but I believe the issue lies within python-socketio. Note that according to [this page](https://nodesource.com/blog/understanding-socketio/) sending arrays should be supported.

Basically, I want to reply to an event with a list of dicts (in Python), but in the client code I only ever receive the first object in the list as the value and not the list itself. I analyzed the data sent over network and it appears that the list's elements do get sent, but probably not correctly.

What a normal "object" looks like in network: `1[{"playlist":1001,"songs":[...]}]`
What the list of an object looks like: `ÿ432[{"id":1000,"name":"Playlist001"},{"id":1001,"name":"Playlist002"}]`

I belive that python-socketio does not consider arrays when packing data and the client implementation only parses an object inside the brackets, but not the brackets themselves. Please correct me if I'm wrong.

Unfortunately I am not able to provide sample code at this moment.

**Comment by miguelgrinberg** [comment]
I'm unable to reproduce this. I have changed the example app in this repository (and the one in Flask-SocketIO, which is nearly identical) to send lists and that seems to work.

For example, if I modify the emit in the background thread of the example app in this repository to:

    def background_thread():
        """Example of how to send server generated events to clients."""
        count = 0
        while True:
            time.sleep(10)
            count += 1
            sio.emit('my response', [{'data': 'Server generated event'}, 'foo', 'bar'],  # <-- this is now a list
                     namespace='/test')

Then in the html template, I changed the `my response` event to print the data received as follows:

    $('#log').append('<br>Received: ' + JSON.stringify(msg));

With these changes, the client does get the entire list.

How are you sending these lists? Is there any difference with what I did above?

**Comment by FichteFoll** [comment]
I'm using flask-socketio like so:

```py
@sio.on('get')
def get(data, _=None):
    return do_something_with(data)
```

**Comment by miguelgrinberg** [comment]
@FichteFoll in the original report you said:

> but in the client code I only ever receive the first object in the list as the value and not the list itself

In the snippet of code you just added shows the server being receiver, not the client as you initially stated.

If you want to send a list from the client to the server, instead of this

    socket.emit('a', 'b', 'c');

do this:

    socket.emit(['a', 'b', 'c']);

**Comment by FichteFoll** [comment]
I think I'm not making myself clear.

The important part is that the return value of the `get` function is either a `list` or a `dict`. If it is a `dict`, then the code in the client receives all data. If it is a `list`, the code in the client only receives the first element of the list.

Client JavaScript code can be estimated as follows:

```js
var socket = io();
socket.emit("get", {unimportant: "data"}, function (result) { console.log(result); });
```

**Comment by miguelgrinberg** [comment]
Okay, try this:

    @sio.on('get')
    def get(data, _=None):
        return [do_something_with(data)]

The Socket.IO client expands the list that you are returning into multiple arguments. To force the list to go out as a single argument, just wrap it in another list.

**Comment by FichteFoll** [comment]
Thank you for the quick help, that works. So it is an issue with flask-socketio in the end, errorneously unpacking my list in order to pass multiple arguments to the callback function.

I'll open an issue on that repo instead.

**Comment by miguelgrinberg** [comment]
It's actually not a bug, that's the intended way the Socket.IO protocol works. The idea is that events can have a list of arguments. If you pass a list, then these are expanded as independent arguments. If you pass a list in which the first element is a list, then that inner list is given as the first and only argument to the function on the other side.

**Comment by FichteFoll** [comment]
I meant that the bug is with the interface of flask-socketio. In the docsat http://flask-socketio.readthedocs.org/en/latest/ it says:

> Any values returned from the handler function will be passed to the client as arguments in the callback function

I only return one value, though, which was a list. You should either document it like that, or only unpack tuples because that is what Python actually returns if return is given multiple values.

**Comment by miguelgrinberg** [comment]
Okay, I buy that.

The bug is that you are returning a list, not a tuple. I should treat those differently. A list should be considered a single argument. A tuple, which you get if you say something like `return 'foo', 'bar', 'baz'`, would be treated as multiple arguments.

**Comment by FichteFoll** [comment]
:+1:

**Comment by miguelgrinberg** [comment]
This is now fixed. If you upgrade your `python-socketio` package you should be able to send the list as you originally did, I think.

**Comment by FichteFoll** [comment]
Just reviewed the commit.

I suppose you could have also used `*args` in the `.emit` function signature to tell the socket.io client to invoke the callback with exactly those parameters. You would invoke `self._send_packet(sid, data=[event] + list(args), ...)` then and Flask-socketio would have to take care of checking if the return value was a tuple and provide that via `.emit('123', 'event', *return_value)`.

But this works too.

**Comment by miguelgrinberg** [comment]
@FichteFoll if I understand what you are suggesting correctly, that would be a breaking change to the current model of having a single data value in the `emit` function, which like it or not, has been in place since the early days of Flask-SocketIO. Some people send the data with a named argument, for example `emit('my event', namespace='/foo', data={'bar': 'baz'})`, so I did not want to break existing apps.

**Comment by FichteFoll** [comment]
True, that would be breaking.

You could add a `data` keyword however, which overrides the `*args` catch, pending eventual deprecation, so you'd need to weight the downsides.
Personally, I do still think that the `*args` approach is more intuitive, but you are the maintainer. ;)
