### ISSUE TITLE
remote callbacks not working properly

### ISSUE THREAD

**Issue by rettier** [miguelgrinberg/python-socketio#150]
Today i added callbacks to my application but i came across two major issues.

1) when using the async manager the `_return_callback` function is wrapped in a partial. The asyncio.iscoroutinefunction tests whether the function is a coroutine when the callback is executed, but the partial (wrongly) is not classified as a coroutinefunction. 

2) the callbacks are returned into the message queue not with the original hosts id (which sent the message), but the host_id of the receiving server. Due to this the callback is not executed on the original host.

I have fixed the mentioned issues (https://github.com/rettier/python-socketio/commit/22a5f37f1c573e738e2e09ea369e07e39f17a290) so it works. I don't know if i have considered all cases. A lot of test cases currently fail due to the different message format, but if the fixes are desired i will wrap this up into a decent PR.

**Comment by miguelgrinberg** [comment]
@rettier Thanks for the detailed report and the patch.

I'm honestly surprised (maybe a little ashamed too) that this was never implemented correctly. But in any case, using your patch as a base I have now think this is addressed. Can I ask you to try the master branch and confirm that everything works for you, before I cut a release?

**Comment by rettier** [comment]
I have not tried the master branch yet, but as far as i can see the async pubsub manager does not send the correct host id, as the commit only changes the sync. pubsub manager:
https://github.com/miguelgrinberg/python-socketio/blob/8d7059a1a22e2d5e3092623251ab357046595a33/socketio/asyncio_pubsub_manager.py#L99

**Comment by rettier** [comment]
#152

**Comment by miguelgrinberg** [comment]
Oops, yes, I fixed the non-asyncio pubsub_manager only. Need to add the same fix to the asyncio one. Sorry!

**Comment by miguelgrinberg** [comment]
@rettier Okay, the asyncio version of this fix is now committed. Sorry about that.

**Comment by rettier** [comment]
tested this and can confirm it now works for my usecase -> 2 asyncio servers with callbacks
