### ISSUE TITLE
Segmented callback data gives "Unterminated string at: line 1 column 10 (char 9)"

### ISSUE THREAD

**Issue by marcus-oscarsson** [miguelgrinberg/python-socketio#161]
Hi

I have an application where I'm asking the client to give me some data via emit and providing a callback.
The data is returned by the client as the callback argument, 

    ``` cb(getData()) ```

This all works fine using the flask development server, however using this with uwsgi fails with:
    ```"Unterminated string at: line 1 column 10 (char 9)"```

It seems like _handle_eio_message of server.py does not get the entire message sent from the client, the end of the string is missing and thus the error message when finally loads is called. I have verified that all the data is sent so it seems like the end of the data is lost somewhere. 

I have tried to find a solution to this problem but without success, is there some limitation to the callback message size or buffer setting that could differ between the development server and uwsgi ?

Thanks,
Marcus

**Comment by miguelgrinberg** [comment]
Do you know approximately how much data you are sending on this callback?

**Comment by marcus-oscarsson** [comment]
I'm using canvas.todataurl to get a base64 encoded jpeg of the HTML5 canvas (its for a screen shot feature) so it can get quite large like 1-3 Mb

**Comment by miguelgrinberg** [comment]
Oh, I see. You are probably hitting the maximum size in uwsgi. See http://uwsgi-docs.readthedocs.io/en/latest/Options.html#websocket-max-size, maybe all you need to do is set a larger value.

**Comment by marcus-oscarsson** [comment]
Aha, I tried to increase the websockets-max-size parameter to 10MB i also increased the chuncked-input-limit to 10MB, it did not have any effect.

I looked a bit more exactly on the sizes I'm sending and receiving, the string I'm sending is 425705 characters long with some variation, however I'm only receiving between 60000 and 110000 characters. Actually the most I received was 101028, changing the parameters discussed above does not seem to change these figures.

Is there a better place in the code to compare these size, I'm checking in server.py _handle_eio_message right now.

Thanks,
Marcus

**Comment by miguelgrinberg** [comment]
> Is there a better place in the code to compare these sizes

You can look in the Chrome debugger's network tab. The websocket request there will show you the inbound and outbound packets and their lengths.

**Comment by marcus-oscarsson** [comment]
Hm, yes already did that, that's how I know the actual size of what I'm sending. So I'm positive that what I'm sending is not received correctly :) 

It works running the flask development server, the packages received in _handle_eio_message are complete and everything work's as expected, but fails for some reason with uwsgi. It seems to me like the issue is either in uwsgi or between uwsgi and sockt.io.

I imagine that if it where a buffer problem that I would have the same size of the first segment all the time, since the buffer would be full. So I'm thinking that maybe there is a problem with the assembly of the package. Is the data returned by the callbacks fixed size or can it be an arbitrary size and assembled on the receiving end ?

**Comment by miguelgrinberg** [comment]
The flask development web server does not support websocket, so there you have one big difference. Have you tested eventlet or gevent instead of uwsgi?

The packets are all variable size, the Socket.IO protocol adds a thin wrapper around the stuff that you send, but other than that the data that flows through the connection is what you emit.

**Comment by marcus-oscarsson** [comment]
Actually I'm running flask-socketio with gevent (gevent-websocket) for the development and uwsgi with gevent for production.

**Comment by miguelgrinberg** [comment]
Okay, then you are not using the Flask dev server. When you use gevent w/o uwsgi the websocket implementation comes from gevent-websocket. With using uwsgi, websocket support comes from uwsgi itself. So it all points to a bug in uwsgi.

**Comment by marcus-oscarsson** [comment]
Allright, thanks for the help, really great !. Ill take a closer look at uwsgi,

Thanks,
Marcus

**Comment by miguelgrinberg** [comment]
If I can make a suggestion, find an example websocket app for uwsgi and modify it to send big packets. If that blows up in the same way as this application, then I think it is safe to assume it is their bug.

**Comment by marcus-oscarsson** [comment]
Good idea, ill take a closer look and I might end up doing that if I finally don't find any other solution.

Thanks again !
