### ISSUE TITLE
Does leave_room get called on multiple instances using AsyncRedisManager/AsyncServer? 

### ISSUE THREAD

**Issue by JoseRaffucci** [miguelgrinberg/python-socketio#168]
We have been experiencing a problem with leave_room.  When we run a leave_room event from an emitted client side event, the leave_room method does not seem to run on all the other instances.  This causes emitted events issued to the room to still be received by the client that was to leave the room.  When we run this in a single instance everything continues to run correctly.  Is this the expected behaviour?

**Comment by miguelgrinberg** [comment]
No, the enter and leave room calls are assumed to be made in response to an event from the affected client. Are you trying to make client X leave a room when you respond to an event from client Y?

Maybe these events should be sent to all instances just in case, I didn't consider that to be necessary.

**Comment by JoseRaffucci** [comment]
@miguelgrinberg Yes that is exactly the use case, one client calls a kick event and the server tries to remove him from the room.  Right now the work around is to issue an event that the leaving member will respond to and will call another event to leave the room.  This works but as you can see not as clean as the single instance of just doing leave_room.

I'd be open to help adding this feature if you can give me some pointers on how you would like it, don't want to add something you don't want to use.  

Thank you again for all the hard work putting this lib together.

**Comment by miguelgrinberg** [comment]
If you want to attempt this, look at how the `close_room()` function is implemented, which does go across instances: https://github.com/miguelgrinberg/python-socketio/blob/master/socketio/pubsub_manager.py#L69-L71.

**Comment by JoseRaffucci** [comment]
Sounds good, will do.
