### ISSUE TITLE
/socket.io/?EIO requests fail with 404 error

### ISSUE THREAD

**Issue by MyrionPhoenixmoon** [miguelgrinberg/python-socketio#173]
The javascript Socket.IO-client seems to send some sort of keepalive message or something, automatically.
The URL used is `<server:port>/socket.io/` with `EIO`, `transport`, `t` and `sid` as parameters. Unfortunately, I haven't found any documentation about what this actually is.
When used with the node-based server, this works, but with the Python server it returns 404s. 

I'm using eventlet and Flask, as in the example from the documentation:

```
if __name__ == '__main__':
    # wrap Flask application with socket.io's middleware
    app = socketio.Middleware(sio, app)
    # deploy as an eventlet WSGI server
    eventlet.wsgi.server(eventlet.listen(('', 9091)), app)
```

**Comment by MyrionPhoenixmoon** [comment]
Apparently, the problem was with my nginx config. Here's the working conf, for anyone who runs into a similar issue:
```
location /sync-server/ {
		proxy_pass   http://127.0.0.1:9091/;
		proxy_set_header Host $host;
						
		proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
}
		
location /socket.io {
		proxy_pass   http://127.0.0.1:9091/socket.io;
		proxy_set_header Host $host;
			
		proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
}
```

sync-server is used for io.connect, but socket.io is used in the path option, because otherwise it didn't work, for some reason.

**Comment by miguelgrinberg** [comment]
FYI the documentation includes a recommended nginx configuration which is close but not quite like yours.
