### ISSUE TITLE
Is there any way to get access to session object in request?

### ISSUE THREAD

**Issue by nuevoleonkx** [miguelgrinberg/python-socketio#175]
I'm using pyramid and python socket.io as Middleware, and class based namespaces in order to respond on every particular section of my project. I want to check whether a session object in my request is present.

any way I can deal with?

**Comment by miguelgrinberg** [comment]
This really depends on the framework, and unfortunately I don't know much about Pyramid sessions. You can obtain the WSGI environment dictionary with `sio.environ[sid]`, where `sio` is a `Server` instance, and `sid` is the SocketIO session id assigned to the client in question.

The rest really depends on how easy or hard Pyramid makes it to replicate the HTTP environment from the WSGI environment dictionary. The session cookie is going to be in there.

Keep in mind that the concept of a "request" does not really apply when working with SocketIO, since there is a long-term connection with each client. What you get from `sio.environ[sid]` is going to be the WSGI environment used during the SocketIO connection.

**Comment by nuevoleonkx** [comment]
I'm migrating from gevent-socketio to python-socketio, and many thing are different. 
With `sio.environ[sid]`  I get sessionid from request, but now how can I share this with my class based namespaces? Or can I get it from class based itself?

Thanks!

**Comment by miguelgrinberg** [comment]
I don't understand what you are asking. First of all, gevent-socketio and python-socketio are not related in any way. If you want to know the `sid` assigned to a client, you get that as an argument in every callback, both function or class based. Is that what you need?

**Comment by nuevoleonkx** [comment]
thanks for reply. I was confused between request from WSGI and socketio environment when connection is established, they not related in any way. You're right, my framework (pyramid) is responsible to replicate the request.

Let me show you my code and i'll try to explain

```
import socketio

class ACollectionSocketNamespace(socketio.Namespace):
    def __init__(self, namespace):
    	super(ACollectionSocketNamespace, self).__init__(namespace)
        print "Constructor  ACollectionSocketNamespace was called"
        self._request = None
    
    def set_request(self, request):
        self._request = request
    
    def get_request(self):
        return self._request
    
    request = property(get_request, set_request)


class AAlertsNamespace(ACollectionSocketNamespace):
    
    def on_some_event(self):
        print "do some stuff with alerts"


class ADeviceNamespace(ACollectionSocketNamespace):
    
    def on_some_eventself):
        print "do some stuff with devices"
```

As you can see Alerts, Devices, etc inherits from CollectionSocketNamespace

I have a MasterNamespace with trigger_event method that listen for every event, then according to event redirect to each particular namespace (alerts, devices, etc). and call the event. At this time events can listen and respond properly (namespace:event), however, **I need to save the request in some place because inside events I need to check and update some session variables.** In pyramid I already tried to pass the request in views (where the request is passed in every @view_config defined) but the value of request is not saved even when I added as a property.

I see in ([documentation](http://python-socketio.readthedocs.io/en/latest/#class-based-namespaces) ) the following...

`It is important to note that class-based namespaces are singletons. This means that a single instance of a namespace class is used for all clients, and consequently, a namespace instance cannot be used to store client specific information.
`
Sorry but i'm lost, any suggestion is welcome! thanks

**Comment by miguelgrinberg** [comment]
Not sure I understand what is this request object and where it comes from. If this is a Pyramid request, then that does not exist when a Socket.IO route is invoked, as that does not pass through Pyramid. So how do you obtain a request object during a Socket.IO communication?

**Comment by nuevoleonkx** [comment]
In pyramid, a request arrives and is available in every view defined with ```@view_config```. I need to get access to session (request.session), I tried to pass this request object to my namespaces inside some view with no success(I already add a property), i'm not sure why this value never saved. I see other comments where request is passed ```on_connect``` this way 
```
@sio.on('connect', namespace='/')
    def test_connect(sid, environ):
        requests[sid] = environ['aiohttp.request']
```
but I need to check if this is possible with pyramid

**Comment by nuevoleonkx** [comment]
After several days trying to find a solution, I check your flask-sockio and do the following.

My pyramid application uses ```gevent``` and ```socketio``` as a Middleware, this way a request and a socketio connection occurs at different time, so I need to pass application inside middleware.

```
class MySocketioMiddleware(socketio.Middleware):
    """This WSGI middleware simply exposes the application in the WSGI
    environment before executing the request.
    """
    def __init__(self, socketio_app, app, socketio_path='socket.io'):
        self.app = app
        super(MySocketioMiddleware, self).__init__(socketio_app, app, socketio_path)

    def __call__(self, environ, start_response):
        """Create a copy of environ and make app available inside
        """
        environ = environ.copy()
        environ['myapp'] = self.app
        return super(MySocketioMiddleware, self).__call__(environ, start_response)
```
Now inside socket,  access to my app and get the request from environ this way...
```
      app = self.server.environ[sid]['myapp']
      ctx = app.request_context(self.server.environ[sid])
      self.request = ctx.request
```
After this, I can access to request object and session by simple ```request.session```
Thanks for your suggestions!!!
