### ISSUE TITLE
client_manager hangs

### ISSUE THREAD

**Issue by DanielCollins** [miguelgrinberg/python-socketio#18]
when i have this, from the docs:

    mgr = socketio.KombuManager('redis://')
    sio = socketio.Server(client_manager=mgr)

the second line hangs. it works without the keyword argument. I have made sure that reddis and rabbitmq are running and have tried variations on the URI on the first line without success.

can anyone offer any suggestions on diagnosing the problem?

**Comment by miguelgrinberg** [comment]
Does `socketio.RedisManager('redis://')` work? What about `socketio.KombuManager(''amqp://')`?

**Comment by DanielCollins** [comment]
no, neither. neither specifying locahost, port etc. in either case.

my complete script is currently:

    #!/usr/bin/env python

    import socketio

    print 1
    mgr = socketio.RedisManager('redis://')
    print 2
    sio = socketio.Server(client_manager=mgr)                       
    print 3

where python is the name of python2.7

**Comment by DanielCollins** [comment]
ah, i've just discovered that the missing '3' does get printed if i uninstall eventlet. slightly problematic since i was using it for the server

**Comment by DanielCollins** [comment]
uninstalling eventlet and deploying with gevent looks like a suitable workaround

**Comment by DanielCollins** [comment]
alas no. with gevent it gets as far as `serve_forever()` before blocking, but none of the `@sio.on` callbacks fire unless i remove `client_manager`

**Comment by miguelgrinberg** [comment]
I think I know what the problem is.

When you are using eventlet you have to monkey patch the python library, if not redis will not work. Try this:

    import eventlet
    eventlet.monkey_patch()
    mgr = socketio.KombuManager('redis://')
    sio = socketio.Server(client_manager=mgr)

**Comment by DanielCollins** [comment]
success. thank you. this section could perhaps be expanded a little in that regard http://python-socketio.readthedocs.org/en/latest/#id1

**Comment by miguelgrinberg** [comment]
Yes, I wrote a documentation issue on Flask-SocketIO regarding this problem. :)

**Comment by sandeeppsmys** [comment]
> I think I know what the problem is.
> 
> When you are using eventlet you have to monkey patch the python library, if not redis will not work. Try this:
> 
> ```
> import eventlet
> eventlet.monkey_patch()
> mgr = socketio.KombuManager('redis://')
> sio = socketio.Server(client_manager=mgr)
> ```
> 
> With gevent, it's like this:
> 
> ```
> from gevent import monkey
> monkey.patch_all()
> mgr = socketio.KombuManager('redis://')
> sio = socketio.Server(client_manager=mgr)
> ```

I am having problem when I use like this..
import eventlet
eventlet.monkey_patch()
mgr = socketio.KombuManager('amqp://')
sio = socketio.Server(client_manager=mgr)

socketio handshake fails with status code 400
GET /socket.io/?EIO=3&transport=websocket&sid=9b1d580299f34e53abafb61ec4652b1f HTTP/1.1" 400 122 0.000181

If I remove monkey_patch socketio connects normally and I can emit web socket messages. 

Any Idea why web socket connection fails when I use monkey_patch?
