### ISSUE TITLE
How can I emit message to an individual client

### ISSUE THREAD

**Issue by feikiss** [miguelgrinberg/python-socketio#182]
In the doc of emit() it said :
param room: The recipient of the message. This can be set to the
                     session ID of a client to address that client's room, or
                     to any custom room created by the application, If this
                     argument is omitted the event is broadcasted to all
                     connected clients.
Seems it can only send to room or broad cast. My question is how can I send message to an individual client ?

**Comment by JoseRaffucci** [comment]
Every event passes a SID, which is the id of the client making that event call.  If you want to track a client's ID you can do so by recording it yourself in the connect event, the sid is also a room.  From the documentation:
[Rooms](http://python-socketio.readthedocs.io/en/latest/#rooms)

> When clients first connect, they are assigned to their own rooms, named with the session ID (the sid argument passed to all event handlers). 

You can see an example where it prints the SID here:  [Getting Started](http://python-socketio.readthedocs.io/en/latest/#getting-started)

Hope this helps.

**Comment by feikiss** [comment]
@JoseRaffucci  Thanks so much! you saved me much time!!
