### ISSUE TITLE
'socketio' has no attribute 'AsyncServer'

### ISSUE THREAD

**Issue by TensorTom** [miguelgrinberg/python-socketio#191]
I'm trying to run the example script:

```
from aiohttp import web
import socketio

sio = socketio.AsyncServer()
app = web.Application()
sio.attach(app)

async def index(request):
    """Serve the client-side application."""
    with open('index.html') as f:
        return web.Response(text=f.read(), content_type='text/html')

@sio.on('connect', namespace='/chat')
def connect(sid, environ):
    print("connect ", sid)

@sio.on('chat message', namespace='/chat')
async def message(sid, data):
    print("message ", data)
    await sio.emit('reply', room=sid)

@sio.on('disconnect', namespace='/chat')
def disconnect(sid):
    print('disconnect ', sid)

app.router.add_static('/static', 'static')
app.router.add_get('/', index)

if __name__ == '__main__':
    web.run_app(app)
```

Which gives me the error:

```
Traceback (most recent call last):
  File "websockServer.py", line 4, in <module>
    sio = socketio.AsyncServer()
AttributeError: module 'socketio' has no attribute 'AsyncServer'
```

**Comment by TensorTom** [comment]
Oops. Just saw the reply here: https://github.com/miguelgrinberg/python-socketio/issues/190#issuecomment-405113349

**Comment by fatalerrortan** [comment]
Hi,  I installed really the right one "python-socketio" in my virtual environment. but I still keep getting this error

**Comment by miguelgrinberg** [comment]
@fatalerrortan if you don't provide any details there is no way anybody can tell you what you are doing wrong.

**Comment by georgegoldman** [comment]
hi
am getting the same error too, so here is what i did
I installed socketIO.

`pip install "python-socketio[asyncio_client]"`

then i imported the sockeIO as required like so 
`import socketio`

after that i did 

`sio = socketio.AsyncServer()
sio.attach(app)`

but am getting => `AttributeError: 'SocketIO' object has no attribute 'AsyncServer'`

**Comment by georgegoldman** [comment]
`(.venv) golman@goldman:~/projects/test-flask-socket$ python3 run.py
Traceback (most recent call last):
  File "/home/golman/projects/test-flask-socket/run.py", line 1, in <module>
    from server import app
  File "/home/golman/projects/test-flask-socket/server.py", line 34, in <module>
    sio = socketio.AsyncServer()
AttributeError: 'SocketIO' object has no attribute 'AsyncServer'
(.venv) golman@goldman:~/projects/test-flask-socket$ `

**Comment by georgegoldman** [comment]
thanks
