### ISSUE TITLE
emit always JSON-dumps data

### ISSUE THREAD

**Issue by videda** [miguelgrinberg/python-socketio#194]
Hi. The documentation of `Server.emit` says:

    data – [...]. If a list or dict, the data will be serialized as JSON.

but it seems that `data` is processed with `json.dumps` in any case.

I intended to emit a string which is already a JSON-dump. Unfortunately it gets
JSON-dumped again (e.g. all quotes get escaped). The consequence is that in the
front-end the data is not automatically made in to an object.

**Comment by miguelgrinberg** [comment]
I don't understand why this is wrong. You passed a string, so the client gets a string. If you want the client to get an object, then pass a dict or a list. Are you saying that the client gets a different string than the string that you passed from the server due to escaping?

**Comment by videda** [comment]
I completely agree that this is right. I thought the documentation should say that also strings get serialized as JSON. But now I'm not sure anymore.

So it remains the question: wouldn't it be interesting to be able to configure
emit not to process `data`? Or what is the best way to achieve this?

In my case (which is an exercise and not important) I have a lot of data that
is already serialized. So it makes no sense to load and dump it again.

What I came up with:
  - JSON.load the string in the front-end. But than all back-end emits need to
    take this in to account.
  - hack a json module that recognizes when to not serialize the data and pass
    it to emit. But this is a hack.

**Comment by miguelgrinberg** [comment]
The second option is what I would do. You can pass custom json handlers, that is a valid option. Your custom handler could look at the string, and if it starts with `{` or `[` you could just return that as the jsonified payload.
