### ISSUE TITLE
issue while sending message to a particular user

### ISSUE THREAD

**Issue by sachinwhiteman** [miguelgrinberg/python-socketio#196]
i want my send notification to a particular client , who had sent me message earlier via a socketio connection.
i tried to send it using sid, but if the client gets disconneted.
it gets a new sid when connected again.
how can i identify a particular client? is there any particular attributes to find a client?

websocket.py
------------------------
# Start with a basic flask app webpage.
from flask_socketio import SocketIO, emit, send
from flask import Flask, render_template, session, request

__author__ = 'slynn'

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
app.config['DEBUG'] = True

# turn the flask app into a socketio app
socketio = SocketIO(app)

@app.route('/')
def index():
    # only by sending this page first will the client be connected to the socketio instance
    return render_template('index.html', id=1)

@socketio.on('my event', namespace='/chat')
def handle_message(message):
    print(message['data'])
    emit('new message', {'data': message['data']})

@app.route('/msg')
def message():
    print session['sid']
    socketio.emit('new message', {'data': 'something'}, room=session['sid'])
    return render_template('index.html', id=2)

@socketio.on('connect', namespace='/chat')
def test_connect():
    print('connected by')
    session['sid'] = request.sid
    print session['sid']
    send('connected')

@socketio.on('disconnect', namespace='/chat')
def test_disconnect():
    print('Client disconnected')

if __name__ == '__main__':
    socketio.run(app)

index.html
______________

<!DOCTYPE html>
<html>
<head>
    <script src="//code.jquery.com/jquery-3.3.1.min.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script>
    <script src="static/application.js"></script>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>

<div class="container" id="content">
    <div class="row">
        {{ id }}
        <form>
            <input type="text" id="msg" name="message">
            <input type="submit" value="send">
        </form>
    </div>
    <div class="container" id="log"></div>
</div>
<a href="{{ url_for('message')}}">Home</a>

</body>
</html>

application.js
_____________

$(document).ready(function(){
    //connect to the socket server.
    var socket = io.connect('http://' + document.domain + ':' + location.port + '/chat');

    //receive details from server
    socket.on('new message', function(data){
     alert("something");
     $('#log').html($('#log').html() + `<p> received:` + data.data + `</p>`);
  });
  $('form').submit(function() {
        console.log("hey");
        $('#log').html($('#log').html() + `<p>send:` + $('#msg').val() + `</p>`);
        socket.emit('my event', {data: $('#msg').val()});
        return false;
    });

});

i have attached my files here...

**Comment by miguelgrinberg** [comment]
Your clients need to authenticate so that you the server knows who they are. This is the same as with an HTTP based API. The client can pass token or other auth information through a cookie that was set up in advance, or in the query string of the connection URL.
