### ISSUE TITLE
server needs to be killed twice when using client_manager

### ISSUE THREAD

**Issue by DanielCollins** [miguelgrinberg/python-socketio#20]
my script is like this:

```
#!/usr/bin/env python2

import socketio
import eventlet
eventlet.monkey_patch()

mgr = socketio.KombuManager()
sio = socketio.Server(async_mode='eventlet', client_manager=mgr)   

if __name__ == '__main__':
    app = socketio.Middleware(sio)
    eventlet.wsgi.server(eventlet.listen(('', 8000)), app)
```

on startup it prints

```
(29745) wsgi starting up on http://0.0.0.0:8000
```

after one `^C` I have

```
^Cwsgi exiting
(29745) wsgi exited, is_accepting=True
```

but it hangs. I have to ^C again to get

```
^CException KeyboardInterrupt: KeyboardInterrupt() in <module 'threading' from '/usr/lib64/python2.7/threading.pyc'> ignored
```

and then it returns me to my shell.

this two step process makes it harder to run under a process manager that wants to be able to kill its children cleanly.

the issue does not exist if i remove the `client_manager` argument.

**Comment by gordol** [comment]
Indeed, this is annoying especially when using supervisor, and/or auto-reloading via werkzeug. Anyone know any workarounds? I've been doing pkill -9 gunicorn to work around it, but it's very frustrating.

**Comment by miguelgrinberg** [comment]
I do not believe this to be an issue triggered by this project, these are issues with the web servers. I am aware that eventlet servers often require two Ctrl-C to kill, and also the Werkzeug, when used in threaded mode may hang when you hit Ctrl-C. These are issues that I intend to identify and report to the respective projects, but due to not being direct issues in my projects I always tend to prioritze actual SocketIO issues higher.

**Comment by gordol** [comment]
I think launching with supervisord via "exec" command may make things a bit nicer... I will be trying that shortly.

**Comment by christopher-abastar** [comment]
+1 with this issue, 

kinda becoming a zombie when supervisord stop is issued.
 also affects my celery workers not stopping as expected before.

**Comment by miguelgrinberg** [comment]
This is in general an issue with the web servers on which this package is running, not with this package itself. Closing. If you think there is an issue in this package, please reopen.
