### ISSUE TITLE
Allow skip_sid to be a list

### ISSUE THREAD

**Issue by mattpepin** [miguelgrinberg/python-socketio#202]
It's currently only possible to skip 1 sid when using emit. It would be easy to change the test condition to skip multiple sid. This is useful in the case of multiple tabs open and the current user has multiple sid.

**Comment by miguelgrinberg** [comment]
Even in the cases where a user is connected with multiple clients, you would want to only skip one. Consider a chat application. If the user types a message from the first connected client, the message should still be sent to all the other clients this user is using. If you skip those clients, the message from the user will not appear in them.
