### ISSUE TITLE
Is it possible to implement Socket.IO P2P?

### ISSUE THREAD

**Issue by felocru** [miguelgrinberg/python-socketio#203]
Hi miguel.
I was reading this post (https://socket.io/blog/socket-io-p2p/). And I would like to know if it is possible to implement P2P to this great project.

I am looking forward to your response. Greetings.

**Comment by miguelgrinberg** [comment]
I'm not sure the p2p extension continues to work with current socketio clients and servers, it hasn't been maintained for a while.

**Comment by felocru** [comment]
It's true, since 2015 it has not been maintained. Although it would be incredible to have this feature. Hopefully this technology will be resumed. Thank you.
