### ISSUE TITLE
Disconnect event is not fired when socket app on android goes background

### ISSUE THREAD

**Issue by skumarcm** [miguelgrinberg/python-socketio#204]
I am using socket client on an android app with python-socketio on the server side.
I was expecting a disconnect event on the server side when the android app goes background.

But I never got a disconnect event.
I am using gevent on the server side.

**Comment by miguelgrinberg** [comment]
Is your android app disconnecting explicitly? Not sure the app going to the background will trigger a disconnect.

**Comment by skumarcm** [comment]
No. the app is not disconnecting explicitly. I was expecting a disconnect event to be generated on the server side when the PING-PONG message is not received from the client side.
Is that not true?

**Comment by miguelgrinberg** [comment]
If the client stops sending PING packets, then the server is going to assume that the client went away, and will remove it from the active list. No point in sending a disconnect packet, since obviously the client isn't communicating. This whole process can take about a minute. The disconnect event handler in the server will be called after a client is declared as gone.

**Comment by skumarcm** [comment]
Sorry. I didn't mean sending a disconnect event back to the client.
How would I detect on the server side that the client has gone away and not communicating?
I was thinking that the disconnect event handler on the server side will be triggered in that case.

**Comment by miguelgrinberg** [comment]
Yes, as I said above, a minute after the client stops sending pings your disconnect handler should be invoked. This is an area where in the past there were issues, so make sure you are using the latest version of this package and its dependencies.

**Comment by skumarcm** [comment]
I have been referring the issue in flask-socketio related to the same.
python-engineio 1.5.0 was exepcted to resolve the issue.
Here are the packages that I am currently using:

Django==1.8.6
gevent==1.3.5
gevent-websocket==0.10.1
greenlet==0.4.14
psycogreen==1.0
psycopg2==2.6.1
python-engineio==2.2.0
python-memcached==1.57
python-openid==2.2.5
python-socketio==2.0.0
six==1.10.0

For some reason this handler is not invoked.

**Comment by miguelgrinberg** [comment]
As I said, you need to install the latest versions.

**Comment by skumarcm** [comment]
Hey Thanks!!!
I just upgraded to python-engineio 2.3.1
And it is working!!!!
Thank you very much for the awesome work that you are doing with socketio!!!
