### ISSUE TITLE
Virtual host based requests

### ISSUE THREAD

**Issue by pobk** [miguelgrinberg/python-socketio#21]
Hey,

Thanks a bunch for building a more up to date SocketIO implementation... Been a massive help!

Anyway, I'm trying to implement a virtual-host based approach to socketIO server. There's a whole bunch of reasons for this, but the main one is that the project I'm working on would benefit from being a kind of SaaS style, where one-codebase handles all.

Ideally I want to avoid spinning up multiple codebase instances per account instance.

e.g. unicorns.hostname.com and magic.example.com both run from the same code instance and server infrastructure on the front-end but the back-end will separate my data domains separately based on the hostname they're connecting to.

So I've picked my way through the socketio.Server() and engineio.Server() guts, I'm struggling to get my head around where's the best place to implement it... I thought I might be able to hijack the namespace and inject the host-name into the namespace a little e.g /unicorns.hostname.com<actual namespace>. Except I won't be able to connect the messages to the clients since the namespace is intrinsically hard-coded...

Is there a simpler solution? if not, would you be able to suggest a route I should look at?

From what I can see namespace is only really a function of socketIO and engineIO doesn't care really... but I was hoping for some pointers.

 ~ Rich

**Comment by miguelgrinberg** [comment]
It seems that I missed this when it was posted. Not sure I understand the point of virtual host requests implemented in this package. Since a socket.io application is just a WSGI or ASGI app, you can implement any routing on the outside.
