### ISSUE TITLE
Connecting client to multiple servers or making a client also a server

### ISSUE THREAD

**Issue by pudg** [miguelgrinberg/python-socketio#211]
I have a client C and two servers A and B. I'm able to connect C to A, but I also need to take the messages C got from A and forward them to B. Is it possible for a client to connect to multiple servers? Or can a client also act like a server?

**Comment by miguelgrinberg** [comment]
Servers and clients can coexist, there are no limitations on that. You can have C connected to A and B and emit to both and necessary. You can also have a server and a client in the same process if that helps.

**Comment by pudg** [comment]
How would the connection between C  and A/B be stablished? Through namespaces?

**Comment by miguelgrinberg** [comment]
The SocketIO client knows how to connect to a SocketIO client. You need to use the connection function offered by the client.

**Comment by asedlack** [comment]
> You can also have a server and a client in the same process if that helps.

How would you start this? The following results in `RuntimeError: Cannot run the event loop while another loop is running`

```
import asyncio
import socketio
from aiohttp import web

server = socketio.AsyncServer()
client = socketio.AsyncClient()
app = web.Application()
server.attach(app)

async def main():
    await client.connect('localhost:3030')
    web.run_app(app, port=3030)

if __name__ == '__main__':
    asyncio.run(main())
```
