### ISSUE TITLE
tornado example cant work

### ISSUE THREAD

**Issue by thisroot** [miguelgrinberg/python-socketio#212]
Hi, i try to run tornado examples, but both can't work for my Windows machine. 
Then i try to run aiohttp examples and its run successfull

**Comment by miguelgrinberg** [comment]
what happens when you run the tornado example on windows?

**Comment by thisroot** [comment]
the connection accross server and client was estabilished, but messages can't trasmitted on between sides in all directions. thanks for aiohttp its better )

**Comment by nlhnt** [comment]
I am having the same issue with the example running on Windows 10.
The client is accepted on the server side, but then client loses connection.
There are time it works and times it doesn't - my bet is that this is Windows specific.
I will try to deploy with Docker and come back with more information.

**Comment by miguelgrinberg** [comment]
This package does not have any issues with Windows, but obviously there could be Windows issues in some of the dependencies.
