### ISSUE TITLE
How to consume rabbitmq message queue ?

### ISSUE THREAD

**Issue by ohadlahav** [miguelgrinberg/python-socketio#214]
My scenario is as follows:
From external process i'm emitting messages to a flask backend via kombu. This works fine.
In addition i'll want another external process (non flask) to listen to the queue for metadata / logging ingesting.
How can i achieve it using the `socketio.KombuManager('amqp://')` ?
Thanks !

**Comment by miguelgrinberg** [comment]
So you want to listen to the internal messages that are used by Flask-SocketIO?

You can look at the code [here](https://github.com/miguelgrinberg/python-socketio/blob/master/socketio/kombu_manager.py#L91-L105), but a bit of a warning, the queue traffic is not part of the public specification, it can change at any time and without notice.
