### ISSUE TITLE
Please add copyright in files.

### ISSUE THREAD

**Issue by phls** [miguelgrinberg/python-socketio#217]
Hi @miguelgrinberg 

I am currently packaging this software project for Debian and to improve the license documentation, I'd like to ask and recommend you to add in each file an header with your copyright.

Similar with you can see here:
https://github.com/kytos/kytos-utils/blob/master/bin/kytos

Best regards,

**Comment by phls** [comment]
Hi, in fact this is more a suggestion than a issue.

Having license headers on each individual file is a good thing to have, because:

- Files can have different authors (copyright holders), different copyright years.
- People tend to pick individual files from projects and then it is good to have each file documented with a license.

Best regards,

**Comment by miguelgrinberg** [comment]
Unfortunately I don't have the bandwidth to do this and keep it updated. Sorry.
