### ISSUE TITLE
Client cannot connect to server when transports is websocket

### ISSUE THREAD

**Issue by sdvcrx** [miguelgrinberg/python-socketio#225]
Server demo:

```python
from aiohttp import web

import socketio

sio = socketio.AsyncServer(async_mode='aiohttp')
app = web.Application()
sio.attach(app)

async def index(request):
    pass

@sio.on('connection')
async def on_connect():
    print('client connected')

@sio.on('schedule')
async def ping(sid):
    await sio.emit('schedule', {
        'data': 'ok'
    })

app.router.add_get('/', index)

if __name__ == '__main__':
    web.run_app(app)
```

Client code (default transports):

```python
import socketio

sio = socketio.Client()


@sio.on('connect')
def on_connect():
    print('connected to server')
    sio.emit('schedule')


@sio.on('schedule')
def on_pong(data):
    print(data)

if __name__ == '__main__':
    sio.connect('http://localhost:8080')
    sio.wait()
```

When `transports` is default (`['polling', 'websocket']`), everything is fine, output is expected:

```
connected to server
{'data': 'ok'}
```

But when `transports` set to `websocket`, client exited without msg and server did not receive any msg.

```python
sio.connect('http://localhost:8080', transports='websocket')
```

**Comment by miguelgrinberg** [comment]
Hmm. The transport set to websocket works for me. Are you using the latest versions of both python-socketio and python-engineio?

**Comment by sdvcrx** [comment]
Thanks for the quick response.

My mistake! I didn't install `websocket` lib...

FYI: I found https://github.com/miguelgrinberg/python-engineio/blob/master/engineio/client.py#L306 logging a warning message, but if I initialize Client without `engineio_logger=True`, `self.logger` level is setting to `ERROR`, so the warning message will never show. Maybe it is a good idea that setting log level to `WARNING` or using `self.logger.error(msg)` here?
