### ISSUE TITLE
CPU usage remains constant

### ISSUE THREAD

**Issue by felocru** [miguelgrinberg/python-socketio#226]
Hi, I have a geolocation monitoring system for several vehicles through uwsgi-gevent to 1000 cores.
The number of users to monitor varies depending on the day and time.
However, the use of the CPU remains constant.
One day restart the server and in an hour approximately the CPU usage was growing up to 83%.
This is normal?
I attach an image.
![image](https://user-images.githubusercontent.com/11906313/50451193-278d6400-08f8-11e9-8601-8569cbeadf73.png)

Thank you.

**Comment by miguelgrinberg** [comment]
It's really hard to tell, I have no way to know how much of that ~80% CPU comes from your own application versus the server. How many users are you handling? Do you have any background tasks that are running at the same load regardless of how many users are connected?

**Comment by felocru** [comment]
Hi, thanks for your help. On average there are 74 users. 
I do not have any tasks in the background. 
They are pure queries to databases that I make in on_connect events and others. 
I will try to use a profiler (pyflame) to detect where it consumes more CPU. Although I think it will not work with gevent. I will also use the stacksampler that may be the best option. I'll keep you informed. Thank you.

**Comment by felocru** [comment]
I have this dynamic graph in [SVG](https://drive.google.com/open?id=17jSZRo-ZHP61tETK5zU21JmRREBU1mvi) format of pyflame.
I need to do it with stacksampler, but since it is in production mode I have to wait for the least use of the system to try it.

**Comment by felocru** [comment]
As additional information this is my configuration of uwsgi:
```
gevent=1000
http-websockets=true
gevent-monkey-patch=true
master=true
#processes=5
socket= %(base)/%(project)/%(project).sock
chmod-socket=666
vacuum=true
```

**Comment by Serkan-devel** [comment]
Have you tried an asynchronous web framework, like [starlette](https://www.starlette.io/)?
It doesn't use gevent and is probably easier to debug

**Comment by miguelgrinberg** [comment]
@felocru is the SVG supposed to reveal anything? I don't really understand what it means. Why don't you use a profiler that supports gevent? There are a few.

**Comment by felocru** [comment]
Hello @miguelgrinberg I have more information in this URL:
https://github.com/unbit/uwsgi/issues/1954

I'm not sure if this is related to high CPU usage

**Comment by miguelgrinberg** [comment]
Is the CPU usage for the Python process or for the entire system? If the latter, have you verified that it is the Python process to increases its CPU usage? I can't really help much with this, as I said before, if this is indeed high usage on the Python process, then a profile should tell us where the CPU is going, without that it is a guessing game.
