### ISSUE TITLE
About renaming the python-socketio library

### ISSUE THREAD

**Issue by frediz** [miguelgrinberg/python-socketio#23]
Hi,
I'm currently packaging python-socketio for debian and I'm facing the following problem : 
there's already a package named python-socketio in Debian : 

Debian package : https://packages.debian.org/unstable/python-socketio
Upstream project : https://github.com/abourget/gevent-socketio

I could renamed you package's name in debian, but your python library would still want to install in 
/usr/lib/python2.7/dist-packages/socketio which is already used by package python-socketio from gevent-socketio.
So the python library name "socketio" is the problem.
From the few that I read, your library does not provide the same interface as gevent-socketio, so I can't
make both an alternative to each other in debian with a "Conflicts" keyword, meaning that users can install one package at a time in the filesystem and use them indifferently as they provide the same interface.
According to Github metric, gevent-socketio as 999stars and python-socketio has 89, which could mean that less projects are impacted by your python-socketio at the moment (I don't have other metric :) so I could actually be wrong here of course)
My question is, what would you think of renaming "socketio" and maybe "python-socketio" so that both
projects don't collide anymore in the python libraries namespace ?
Thanks for your thoughts on this,

Fred

**Comment by miguelgrinberg** [comment]
Fred,

My impression is that gevent-socketio hasn't been maintained in a long time. For example, it was never updated to run on Python 3, and it requires version 0.9 of the Socket.IO Javascript client (this library is now at 1.4.x releases). The README file shows a message from the creator saying that he is not maintaining it anymore and is looking for a new maintainer. The current release of this package on PyPI is dated 2014-02-03. 

On the other side, this library runs on Python 2 and 3, supports the latest 1.4.x Socket.IO Javascript client, as well other official clients for Java, Swift and C++. I'm also actively maintaining it. The current release is dated 2016-03-21. Does that change your opinion in any way?

**Comment by frediz** [comment]
Hi Miguel,
I noticed the points you mention and they make sense in some way.
I opened a similar issue for gevent-socketio .
F.

**Comment by lukeyeager** [comment]
See relevant discussion here:
https://lists.debian.org/debian-python/2016/03/msg00074.html

@frediz what did you decide to do?

**Comment by frediz** [comment]
Hi Luke,
I didn't decide anything atm.
I still had no answer to my request on the software holding that python module
naming at the moment : https://github.com/abourget/gevent-socketio/issues/239
My packaging is ready, and at some point, I guess I'll have to do some renaming as nothing
changes and gevent-socketio as precedence in Debian.

F.

**Comment by lukeyeager** [comment]
If you're curious to compare notes, here are my packaging scripts:
https://github.com/lukeyeager/python-socketio/tree/debian/1.4.3/debian

I'm not interested in getting this accepted to Debian/Ubuntu repos so I just renamed it "python-socketio2" and made it conflict with "python-socketio". Good luck on finding a solution that works for them.

**Comment by frediz** [comment]
Hi Luke,
I checked that issue again and nothing changed yet :-/
Many people I know would like to have Debian/Ubuntu package for miguel's
python-socketio to use Digit.
So for  now, the only solution  I see as discussed  in the debian-python
mailing list, would be to patch the module name on the packaging side of
the packages willing to import miguelgrinberg/python-socketio.
What would you think if I use your Digit packaging, review you it, maybe
modify it (keeping your copyright of course) and submit it to Debian (it
will follow in Ubuntu then) for inclusion  ? I'd take care of the python
module renaming in the Debian packaging.
Depending on if you are interested in maintaining this in Debian/Ubuntu,
I can help you  on that, or you could offload all  the packaging work to
me and I will maintain that upstream Debian/Ubuntu. I already do that
for some packages :
https://qa.debian.org/developer.php?login=frediz@linux.vnet.ibm.com
Let me know what you think,

Fred

**Comment by lukeyeager** [comment]
@frediz feel free to use whatever you like from my packaging scripts - there are only about 20 lines of relevant code and it's all under @miguelgrinberg's license anyway. I don't have the bandwidth or inclination to get this accepted into official Debian/Ubuntu repos, so I'll leave that to you.

**Comment by frediz** [comment]
Thanks Luke, I'll take some time on this and will keep you updated!
