### ISSUE TITLE
Return data if connection is refused

### ISSUE THREAD

**Issue by andreyrusanov** [miguelgrinberg/python-socketio#234]
With JS socket.io server it is possible to do the following:
```python
// server
io.use(function(socket, next) {
  next(new Error('Authentication error'));
});

// client
socket.on('error', function(err) {
  console.log(err);
});
```
How does this logic could be replicated? When disconnect, I have to return to a client string error code to explain the root cause of declined connection.

**Comment by andreyrusanov** [comment]
Update:
As I discovered in the server source code, it is not possible to do some. However, data could be sent in case of refused connection and it could be handled by the client. Solution for this one would be allow to raise special type of exception where data could be passed. For instance:

```python
    # for AsyncServer
    def _handle_connect(self, sid, namespace):
        """Handle a client connection request."""
        namespace = namespace or '/'
        self.manager.connect(sid, namespace)
        fail_reason  = None
        try:
            success = self._trigger_event('connect', namespace, sid, self.environ[sid])
        except ConnectionRefused as exc:
            fail_reason = exc.message
            success = False

        if not success:
            self.manager.disconnect(sid, namespace)
            self._send_packet(sid, packet.Packet(packet.ERROR, data=fail_reason,
                                                 namespace=namespace))
            if sid in self.environ:  # pragma: no cover
                del self.environ[sid]
            return False
        else:
            self._send_packet(sid, packet.Packet(packet.CONNECT,
                                                 namespace=namespace))
```
@miguelgrinberg if this one looks good to be build into the app I can make a pull requests and add some tests to it.

**Comment by miguelgrinberg** [comment]
So returning `False` is not enough for you? You want to also include an error message?

**Comment by andreyrusanov** [comment]
@miguelgrinberg imagine scenario where during connect authentication data is passed, and it could be different reason why it is not valid. Correct me if I am wrong, I saw it possible in another socket.io implementations. Even more, JS client assumes you may error data as I posted in issue description. What do you think about it?
