### ISSUE TITLE
Importing six in setup.py (commit b0a8b1f) fails in clean Python2 environments

### ISSUE THREAD

**Issue by denebolar** [miguelgrinberg/python-socketio#235]
In clean environments, e.g. a freshly created virtualenv, six is not available as a dependency even though it is included in install_requirements (no pre-depend, ready only after setup finishes).

Environment tested: Python 2.7.15

**Comment by miguelgrinberg** [comment]
I'm not sure I understand what your issue is about. The `six` package is declared as a main dependency, so what is the problem? What do you mean by "six is not available as a dependency"?

**Comment by denebolar** [comment]
Six as a dependency is not be available at installation time (for use in setup.py), only afterwards at runtime, after setup.py finished.

**Comment by denebolar** [comment]
To clarify things, here is what's happening:
```
millner@IPC:~$ virtualenv test
New python executable in /home/millner/test/bin/python
Installing setuptools, pip, wheel...
done.
millner@IPC:~$ test/bin/pip install python-socketio --no-binary :all:
Collecting python-socketio
  Downloading https://files.pythonhosted.org/packages/78/fd/4d54fdcdcbd35abc621f47aa25e30e6bb9ac68b1d94be9ce5b6c46d16135/python-socketio-3.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4MHJsM/python-socketio/setup.py", line 9, in <module>
        import six
    ImportError: No module named six

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-4MHJsM/python-socketio/
```

If you remove the references to `six`, setup will not fail and _afterwards_ install the dependency `six`.

**Comment by miguelgrinberg** [comment]
Oh yes, I see what you mean now. Thanks, I'll take care of it.

**Comment by miguelgrinberg** [comment]
Fixed in master for both packages. New releases coming up in a bit.
