### ISSUE TITLE
How to display ConnectionError: Unexpected status code %s in server response?

### ISSUE THREAD

**Issue by StevenJW** [miguelgrinberg/python-socketio#236]
I'm trying to connect with my website but I'm getting the error I placed in the title and I'm not sure how I can display the unexpected status code %s?
This is my code:
```
sio = socketio.Client()

@sio.on('connect')
def on_connect():
    print("connected")

if __name__ == '__main__':
    try:
        sio.connect('https://example.com/ws/socketio')
    except Exception as e:
        print(e)
    sio.wait()
```

**Comment by miguelgrinberg** [comment]
This is a bug, I'll fix the error message so that it has the number instead of %s.
