### ISSUE TITLE
Aiohttp gets a huge delay after adding background tasks

### ISSUE THREAD

**Issue by brney** [miguelgrinberg/python-socketio#237]
Hello, 

First and foremost thank you for this amazing library. Recently I implemented socketio on my website, which is using the aiohttp framework. However, whenever I want to create server generated events using the emit method and in the form of background tasks, and I start them, the website faces a very huge delay and I do not really know why. Is there any fix to this?

Thank you very much!

`

**Comment by miguelgrinberg** [comment]
Can you show some code? This repository has an example with a background task that emits. Do you see delays with that example as well, or is it only with your application?

**Comment by brney** [comment]
Here is a small snippet of the code:

`
import socketio

from routes import setup_routes

socket = socketio.AsyncServer(async_mode='aiohttp', async_handlers=True)
app = web.Application()
socket.attach(app)
aiohttp_jinja2.setup(
    app, loader=jinja2.FileSystemLoader('./templates'))
main = Main()

async def temperature():
    while True:
        await socket.sleep(0.2)
        await socket.emit('temperature', "{:.1f}".format(main._temperature.convert()))


if __name__ == '__main__':

    socket.start_background_task(compass)
    socket.start_background_task(distance)
    socket.start_background_task(temperature)
    socket.start_background_task(light)
    web.run_app(app, host='10.3.141.1', port=sys.argv[1:][0])

`

I haven't tried your example out yet - I will do that once I get some free time today. As for the context: The application tends to show sensor data on a website

**Comment by miguelgrinberg** [comment]
Are you sure the way you interact with your sensor is friendly to asyncio? If you are doing anything blocking there you have a big problem.

**Comment by brney** [comment]
Right.. Seems like I rushed too quickly haha. Forgot to remove a time.sleep somewhere. Thanks that did the trick!
