### ISSUE TITLE
AttributeError: module 'socketio.exceptions' has no attribute 'TimeoutError'

### ISSUE THREAD

**Issue by imcom** [miguelgrinberg/python-socketio#244]
File "/usr/local/lib/python3.7/site-packages/socketio/client.py", line 289, in emit
raise exceptions.TimeoutError()
AttributeError: module 'socketio.exceptions' has no attribute 'TimeoutError'

I believe it well explains itself .. already...

**Comment by miguelgrinberg** [comment]
@imcom sorry about that, looks like the 3.1.1 build had some code I then decided to not include. I have release 3.1.2 now with the fix.
