### ISSUE TITLE
Can't establish async connection

### ISSUE THREAD

**Issue by xjpf** [miguelgrinberg/python-socketio#246]
Installed:
pip3 install "python-socketio[asyncio_client]"
```
import asyncio
import socketio
sio = socketio.AsyncClient()
await sio.connect('ws://socket.donationalerts.ru:80')
await sio.wait()
```
Shows "invalid syntax" for "await sio.connect.."
What i'm doing wrong?

**Comment by miguelgrinberg** [comment]
Please review the documentation on asyncio at python.org. You can't simply invoke an asynchronous function, there is some boilerplate that you need to write to get an async program going.

**Comment by xjpf** [comment]
Well i'm just reading your documentation:

> Connecting to a Server:
>
> The connection to a server is established by calling the connect() method:
> sio.connect('http://localhost:5000')
>
> In the case of the asyncio client, the method is a coroutine:
> await sio.connect('http://localhost:5000')

Just copied all the things from examples, and all they worked except this one.
Can you then add working examples to documentation? :)

**Comment by miguelgrinberg** [comment]
That is not an example, it is a snippet. It is assumed that you know how to work with asyncio if you want to use that version of the server. It is a non-trivial subsystem of Python, if you are not familiar with it then I strongly suggest you use the non async server.

And if you still want to do this, then complement what you learn from the documentation with the "working" examples that I provide in this repository.
