### ISSUE TITLE
No binary mode in AsyncServer

### ISSUE THREAD

**Issue by maksutovaynur** [miguelgrinberg/python-socketio#248]
Cannot create AsyncServer with binary mode:

> server = AsyncServer(async_mode='aiohttp', client_manager=manager, binary=True)
TypeError: __init__() got multiple values for keyword argument 'binary'

**Comment by miguelgrinberg** [comment]
The `binary` option makes sense only for Python 2 to specify one of two modes for handling binary values. In Python 3 binary and text values are always handled correctly so there is no need for this setting.

**Comment by maksutovaynur** [comment]
Thank you for reply!

The problem, actually, is that when I try to send binary types (Python 3 version), Exception is thrown.

**Comment by miguelgrinberg** [comment]
@maksutovaynur I can't see what you are linking to, the link is to an email only you have access to.

**Comment by maksutovaynur** [comment]
I've created another issue for that.
https://github.com/miguelgrinberg/python-socketio/issues/251
