### ISSUE TITLE
graceful shutdown

### ISSUE THREAD

**Issue by DeoLeung** [miguelgrinberg/python-socketio#253]
Hi I'm testing my project using `tornado`, one problem is the `AsyncServer` and `AsyncClient` are not properly shutdown, which generating quite a lot of noisy logs at the end. is there and document about how to do a graceful shutdown?

**Comment by miguelgrinberg** [comment]
I'm aware of this. A fix is coming up soon.

**Comment by miguelgrinberg** [comment]
Fixed in release 3.4.3 of package python-engineio.
