### ISSUE TITLE
python-socketio handlers working asynchronously, even after specifying 'async_handlers = False'

### ISSUE THREAD

**Issue by pia-nyk** [miguelgrinberg/python-socketio#257]
server.py
![screen shot 2019-02-23 at 1 25 26 pm](https://user-images.githubusercontent.com/24822362/53283565-7deb1780-376e-11e9-9531-27d7670ce0d7.png)

client.py
![screen shot 2019-02-23 at 1 33 40 pm](https://user-images.githubusercontent.com/24822362/53283668-ade6ea80-376f-11e9-98e2-89973daa03bd.png)

**Comment by miguelgrinberg** [comment]
What is the problem with the code you posted?

**Comment by pia-nyk** [comment]
The message from the second emit is printed to the console before the message from the first emit. If the code was working synchronously, why is it not waiting for the first handler to complete execution. I am under the impression that 'async_handlers = False' should make the code synchronous.

**Comment by miguelgrinberg** [comment]
Sure, but the `async_handlers` option is a server option. The client has nothing to do with that. If you revert your logic and have the client send two consecutive messages to the server then they'll be handled one after the other. The client does not have the option to run handlers asynchronously at this time.

**Comment by pia-nyk** [comment]
Got it! Thanks a lot!
