### ISSUE TITLE
ClientNamespace calls Client.disconnect incorrectly

### ISSUE THREAD

**Issue by sambrightman** [miguelgrinberg/python-socketio#259]
`ClientNamespace` does this:

https://github.com/miguelgrinberg/python-socketio/blob/1fb1f6d6e5a25159e9c1f35b005098e05a4a18e4/socketio/namespace.py#L184-L191

but `Client` doesn't take a `namespace` keyword argument:

https://github.com/miguelgrinberg/python-socketio/blob/1fb1f6d6e5a25159e9c1f35b005098e05a4a18e4/socketio/client.py#L329-L337

It's hard to tell whether `Client` is intended to take a `namespace` argument or not, since it appears to always disconnect all namespaces. I get the impression that `ClientNamespace.disconnect()` should probably not refer to namespaces at all.

**Comment by miguelgrinberg** [comment]
Yes, this is a recent mistake, the disconnect method should not take a namespace. I'll fix it.
