### ISSUE TITLE
can't return nothing from an event handler

### ISSUE THREAD

**Issue by dude8604** [miguelgrinberg/python-socketio#26]
With the javascript socket.io, if fn is the server's callback question to the client, calling fn() will send a blank response to the client.  Is there a way to do that with this library?  I've tried all I can think of, but it always sends at least true, false, or null, but never just blank like the original socket.io.  Is this a limitation of this library or am I doing something wrong?

**Comment by miguelgrinberg** [comment]
It's a bug, you are right. If you don't return anything, the library will call the callback function with `(null)`. One way to trick it into doing the right thing is, I think, to return an empty tuple:

    return tuple()

Have you tried that?

In any case, I will fix this.

**Comment by dude8604** [comment]
Thanks, that worked.
