### ISSUE TITLE
connect() returns too soon - "packet already sent in initial handshake"

### ISSUE THREAD

**Issue by adam-nielsen** [miguelgrinberg/python-socketio#260]
I am trying to briefly connect to a Node SocketIO server, send a message, then disconnect and continue with the Python code.

Unfortunately while this works occasionally, most of the time the Node code gives me an error:
```
  socket.io:server incoming connection with id Np_DSC3cJZVrp67LAAAU +2m
  socket.io:client connecting to namespace / +2m
  socket.io:namespace adding socket to nsp / +2m
  socket.io:socket socket connected - writing packet +2m
  socket.io:socket joining room Np_DSC3cJZVrp67LAAAU +0ms
  socket.io:socket packet already sent in initial handshake +0ms
```
My Python code is very short:
```
data = {"some": "data"}  # data is from a long running task, so doing it before connect()
sio = socketio.Client()
sio.connect("ip")
sio.emit('setData', data)
sio.disconnect()
```
The problem seems to be that `connect()` returns before the connection has been established, even though I am not running anything in async mode, so when `emit()` is called the connection hasn't been fully established yet.

I have looked through the docs but there doesn't seem to be any way to reliably achieve this?  I can put an `sio.sleep(1)` after `connect()` and this does fix the problem, but it's not a very robust approach.

Is there a way to do everything synchronously?

**Comment by miguelgrinberg** [comment]
The server has background tasks that support many of the operations, such as emits. The connect call is in fact synchronous, but the emit is not.

The "robust" way to handle this is by having the server invoke a callback after it received and processed the `setData` event. On the Python side you will get the callback, and at that point you can disconnect. The next release of this package will have a new mode in which an emit and its callback are handled as a bundle:

    sio.call('setData', data)

This will block until the server invokes the callback. If you want to do this, you need to install the master branch.

**Comment by adam-nielsen** [comment]
Interesting, thanks for the info!  If the `connect` call is synchronous, how is the `emit()` message able to arrive at the destination before the connection has been fully established?  The remote end is complaining that I am sending data with `emit()` before the connection is ready.  If `connect()` were synchronous, this shouldn't be possible?

**Comment by miguelgrinberg** [comment]
@adam-nielsen I may be missing something here. You say that the emit arrives before the connection has been established. How did you determine that? I don't see anything in the logs that you copied that indicates that the emit was received. There is no reference to `setData`, which is the event name.

My interpretation of the problem is that you are disconnecting before giving time for the emit to complete, so adding a sleep after the emit should also avoid this problem, I think.
