### ISSUE TITLE
Issue each SocketIO connection for each client independently?

### ISSUE THREAD

**Issue by ragymorkos** [miguelgrinberg/python-socketio#262]
Hi Miguel,

I am currently trying to do some experimentation with python-socketio. The flow of events I am aiming for looks like the following:

1) Client sends a GET request to a Flask server
2) Flask server responds with the needed HTML/JS/CSS/img, etc.
3) In a separate thread, a SocketIO connection is made to this client. This thread will live for as long as the client is connected.

This is just for experimentation, and although it seems simple, I cannot find how to implement it. Would you have any ideas on how I could proceed? 

Thanks for all of your amazing open-source projects, Miguel!

**Comment by miguelgrinberg** [comment]
The connections are always initiated by the client, there is no mechanism for the server to set up a Socket.IO connection from a background thread.

I would modify your flow of events as follows:

1. Client sends a GET request to a Flask server
2. Flask server responds with the needed HTML/JS/CSS/img, etc.
3. The JS provided by the server includes code that imports the Socket.IO client and connects to the server with it.
4. The Socket.IO connection will remain active for as long as the browser stays on that page. Either the client or the server can freely send data to the other side at any time while the connection is active.

Would that work? The example server applications in this repository all do this.

**Comment by ragymorkos** [comment]
Thanks for the quick response! You are correct; the client is always the one that initiates the Socket.IO connection. My main goal, however, is to deal with each client in a separate thread. That is, on connection to a client, I would like all of the messaging between the server and client from that point afterwards to occur in its own thread only. The main HTML/JS/CSS/img, etc. can be sent to the client in the main thread. Is there a way to accomplish this using the `@socketio.on('connect')` syntax? It's just the Socket.IO functionality that I am looking to see if it could be completely encapsulated in a separate thread when each client connects. One supposed benefit of this would be to have the variables and activity associated with each client completely inaccessible/unattainable to those of other clients (which would be in their own separate threads as well).

**Comment by miguelgrinberg** [comment]
@ragymorkos the threading is managed internally by the Socket.IO server. There are a couple of threads allocated to each client, you do not get access to them directly. I suspect this package is not what you want, to be honest. You probably want something that is low-level. This package is very high-level.

**Comment by ragymorkos** [comment]
Ok, thanks a lot, this is helpful. What package(s) would you recommend for me that would be low-level enough to try and achieve this?

**Comment by miguelgrinberg** [comment]
@ragymorkos I'm not sure, I really don't understand why you are interested in managing threads yourself. Maybe a plain websocket server, there are a few out there.

You may also want to look at the user session support in this package, which also allows you to store separate settings per-client, but without you having to manage it. See https://python-socketio.readthedocs.io/en/latest/server.html#user-sessions for details.
