### ISSUE TITLE
AsyncClient in tests hangs after completing tests

### ISSUE THREAD

**Issue by abondar** [miguelgrinberg/python-socketio#263]
Hi

I have an issue with my test setup. After completing all tests runner hangs indefinitely.
As far as I investigated it has something to do with not closing connections properly on server side

Here are my test setup:

```
@pytest.fixture
async def app(aiohttp_client, request, loop):
    app = web.Application()
    sio = AsyncServer()
    sio.attach(app)

    setup_routes(app, sio)
    return app


@pytest.fixture
async def client(app, aiohttp_client):
    return await aiohttp_client(app)

@pytest.fixture
async def sio_client(client, request, loop):
    sio_client = AsyncClient()
    await sio_client.connect(f'ws://{client.server.host}:{client.server.port}')

    def fin():
        loop.run_until_complete(sio_client.disconnect())  # breakpoint somewhere here next string

    request.addfinalizer(fin)
    return sio_client

async def test_basic(client, sio_client):
    print(1)
```

After completing `test_basic` runner hangs. If I remove `sio_client` fixture from test it closes normally.

If I put breakpoint on marked line, and try getting `asyncio.Task.all_tasks()` I get following pending tasks
```
< Task pending coro = < AsyncServer._service_task() running at / Users / andreybondar / PyCharmProjects / webinar - client - backend / venv / lib / python3 .6 / site - packages / engineio / asyncio_server.py: 417 > wait_for = < Future pending cb = [ < TaskWakeupMethWrapper object at 0x113424df8 > ()] >> , 
< Task pending coro = < RequestHandler.start() running at / Users / andreybondar / PyCharmProjects / webinar - client - backend / venv / lib / python3 .6 / site - packages / aiohttp / web_protocol.py: 398 > wait_for = < Future pending cb = [ < TaskWakeupMethWrapper object at 0x113424d98 > ()] >> , 
< Task pending coro = < RequestHandler.start() running at / Users / andreybondar / PyCharmProjects / webinar - client - backend / venv / lib / python3 .6 / site - packages / aiohttp / web_protocol.py: 398 > wait_for = < Future pending cb = [ < TaskWakeupMethWrapper object at 0x1134e90a8 > ()] >>
```

Also, sometimes, if I leave runner hanging for long time it warns about unclosed client session and tcpconnector, though tcpconnector pops not every time.

```Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x111cb29e8>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x111ce7588>, 391343.655161257)]']
connector: <aiohttp.connector.TCPConnector object at 0x111f8d630>
```

As workaround right now I am using this in my finalizer
```        
tasks = asyncio.Task.all_tasks()
for task in tasks:
    task.cancel()
```

**Comment by miguelgrinberg** [comment]
Can we provide a complete unit test to help me reproduce the issue here?

**Comment by abondar** [comment]
Here are testing files:

`conftest.py` - https://gist.github.com/abondar/eb7b62353c443adf08a0796b437f8ac8
`test_basic.py` - https://gist.github.com/abondar/4ac8cdb272439d08c9cc0bb532f1ff28

Requirements to setup env:
https://gist.github.com/abondar/852c0addda2a6b5a82e488fb0dd4a4b7

So if you put testing files in directory `test`

And call from the root of the project `pytest test/` issue should be reproduced for you

**Comment by miguelgrinberg** [comment]
Thanks.

There are a couple of problems. The first is with the dependencies. The `pip install python-socketio[asyncio_client]` does not pull one required dependency, the `websockets` package. This has been corrected in master a few days ago, but haven't completed the work that goes in the next release yet.

Still investigating the remaining problem...

**Comment by miguelgrinberg** [comment]
The other problem is, I think, a misunderstanding on your part. The `disconnect()` call is asynchronous, it just initiates a disconnect. The hang occurs because the server disappears before the disconnect process is completed, I think. I was able to avoid the hang adding a `wait()` call, which does block until the client is completely disconnected:

```python
    def fin():
        loop.run_until_complete(sio_client.disconnect())
        loop.run_until_complete(sio_client.wait())
```

**Comment by Nocturem** [comment]
I would mention that engineIO appears to be importing websockets https://pypi.org/project/websockets/ in async_client but importing websocket https://pypi.org/project/websocket/ in the sync code
this is version 0.2.1 Last released: Dec 3, 2010

is this intentional? 
websocket looks like abandoned code..

**Comment by miguelgrinberg** [comment]
@Nocturem the websocket client for the sync code is called [websocket-client](https://pypi.org/project/websocket_client) and it is not abandoned.

**Comment by abondar** [comment]
Yeah, `wait()` really did solve the issue. 
But for some reason it really takes some time to wait for connection to close (approximately second per connection)

However, thanks for your help, it was blazingly fast!

**Comment by Nocturem** [comment]
ahh installed and now getting a response. 
getting the same ssl verify errors for both transports now which progress :)
