### ISSUE TITLE
Close client_session

### ISSUE THREAD

**Issue by voidloop** [miguelgrinberg/python-socketio#267]
I would want to manage ConnectionError exception but what is the right manner?
This is my client code:

```
from socketio.exceptions import ConnectionError
import asyncio
import socketio
import logging

sio = socketio.AsyncClient()
logger = logging.getLogger('pumpd_simple_client')
logger.setLevel(logging.INFO)


@sio.on('connect')
async def on_connect():
    logger.info('connected to server')
    await sio.emit('pump stop')


@sio.on('no water')
async def no_water(_):
    logger.info('no water')


@sio.on('pump stopped')
async def pump_stopped(_):
    logger.info('pump stopped')


async def main():
    try:
        await sio.connect('http://rpi.lan:5000')
    except ConnectionError as err:
        logger.error(err)
    await sio.wait()

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```
I have this output message: 
```
Connection refused by the server
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fdd201e3ba8>
```
How can I gracefully close the client session?
python-socketio version 4.0.0.

Thank you.

**Comment by miguelgrinberg** [comment]
It's a bug, I inadvertently introduced. It's related to using `emit()` in the connect handler. If you remove that you'll be fine. Since this isn't a real connection error you can't really catch anything to prevent it. I'll take care of it.

**Comment by miguelgrinberg** [comment]
@voidloop you've only shared the client. Can you share the server as well? Your server is likely erroring in an unexpected place, and that is I think the reason why a connection error isn't properly raised by the client. On second thought I believe this is probably a mistake in your server application, but in any case, whatever it is it is being handled really badly and that needs to be improved.

**Comment by voidloop** [comment]
I think the server is not important because when I ran the client I also intentionally shut down the server. So http://rpi.lan:5000 was intentionally unreachable. 
If you think the server is important, I can surely share it.

**Comment by miguelgrinberg** [comment]
@voidloop maybe we are not on the same page on this then. This is what I think should be your results:

- If you connect to an unreachable server, a `ConnectionError` is raised in the client.
- If you connect to a reachable server that has this still unknown problem I'm trying to discover, your client ends without raising any exception, but shows a few error messages on the console.

Am I wrong? If I'm right, then I do think what the server does is important.

**Comment by voidloop** [comment]
You are right, but I would want to know in the first case (an unreachable server) why the client prints out "Unclosed client session" when the server is unreacheable and if it exists a way, how to I could finalize/manage the exception.

**Comment by miguelgrinberg** [comment]
Okay, now I think I understand. Unclosed client session is a message from aiohttp, the HTTP client that I'm using for the long-polling transport. It appears I'm not doing proper clean up when the client fails. Was the unclosed message all you cared about?

**Comment by voidloop** [comment]
Yes. I'm sorry Miguel, I didn't explain in the right way the problem.
I tried python-engineio with the new fix and now my client seems to work great: the message is gone.
Thank you.
