### ISSUE TITLE
confused about the port param

### ISSUE THREAD

**Issue by chendongxtu** [miguelgrinberg/python-socketio#270]
Hi, miguelgrinberg, thanks for your great work!
      i'm confused at how to used the port in flask project.  for example:

in the __init__.py, some part of the code:
from flask import Flask
from flask_socketio import SocketIO
socket_io = SocketIO()

def create_app(config=None):
    app = Flask(__name__)
    app.wsgi_app = ProxyFix(app.wsgi_app)
    socket_io.init(app)

in the views.py, some part of the code:
@app.route('/')
def index():
    return render_template('index.html', async_mode=socketio.async_mode)

@app.route('/test')
def test():
    return 'hello world'

@socketio.on('my_event', namespace='/test')
def test_message(message):
    print('message:{} '%message)
    session['receive_count'] = session.get('receive_count', 0) + 1
    emit('my_response',
         {'data': message['data'], 'count': session['receive_count']})

in the manage.py, some part of the code:
from flask_script import Manager
from auction import create_app
from auction import socket_io
app = create_app()
manager = Manager(app)
manager.add_command('run', socketio.run(app=app, host='127.0.0.1', port=5000)) 
if __name__ == '__main__':
    manager.run()

my question is the port 5000 is used  both for websocket connection and other flask routers ,
that is to say when a request is not websocket, it will comminucate by the port 5000(for example: 127.0.0.1:5000/test ), and
a webscoket requset comminucate by the port 5000 too(for example,  call emit function).

can i seprate the port from flask router and websocket router? 
for example, when request is a flask web route,  set the port 5002
when request is a websocket, such as we call emit, set the port 5000

**Comment by miguelgrinberg** [comment]
The application combines the http and websocket routes into a single server, so it is not possible to them on separate ports. You can write two separate applications and then use different ports.

**Comment by chendongxtu** [comment]
umm， thanks！
but how can i run this two different applications int the same project?
createt a sub thread to run the websoket application?

and i have another problem, the default socket_io is use ws protocal,
how can i upgrade it to wss? 
in the source code, i see only use eventlet , then it can use ssl,
if i wanna use gevent, how can i upgrade ws to wss?
thanks and hope for ur guid and reply, thanks, thanks!

**Comment by miguelgrinberg** [comment]
> createt a sub thread to run the websoket application?

I guess you can do that, but why? Run them as separate application, you'll avoid the complications of hosting two applications in the same process space.

> how can i upgrade it to wss?

This package has not say on how you run your server. You have to check the documentation for the server that you are using (eventlet, gevent, uwsgi, asgi, aiohttp, sanic, tornado) and configure it to use https and wss.

**Comment by chendongxtu** [comment]
thanks for ur reply, i have read the document and will try to use nginx as a proxy_server to support wss.

in my flask project, all of the requests are used https method now,
but in some special situation, it is not a good idea. 
for example:
      if client wanna know the auction newest bid price,  it will frequently calls the server using short polling to get results, which will influence performance. so i wanna use socket replace short polling,
when the sever know the order status changed, it will send the result to client actively.

but in my flask porject, the method of start project is like this:
```python
app = Flask(__name__)
if __name__ ==  '__main__':
    app.run()
# when use websocket:
socket_io = SocketIo()
if __name__ ==  '__main__':
    socket_io.run(app)
```
so if use like that, the websocket and flask app application use the same port.
i do not know to run them as separate application, because the websocket event 
will triggered by some case in the flask application.
for example, when thirdparty callback the server, the server change order status, and the notify
the client result through websocket.

so how can i run them as separate application(becase the socketio event need triggered by the flask application )?

**Comment by miguelgrinberg** [comment]
You just need to write two separate apps and run one of them in a background thread, while the other is in the main thread. This is a strange configuration, I never needed to do this so I don't have any examples to show. Sorry.
