### ISSUE TITLE
Emit delayed from thread

### ISSUE THREAD

**Issue by Majiick** [miguelgrinberg/python-socketio#271]
```
import eventlet
eventlet.monkey_patch()
import socketio
import zmq
import threading
from aiohttp import web
from mlogging import logger

logger.info("Started socketio server")

app = web.Application()
sio = socketio.Server(async_mode='eventlet')


@sio.on('connect', namespace='/update')
def connect(sid, environ):
    logger.info("connected ", sid)
    sio.emit('update', {'data': 'Connection established.'}, namespace='/update')


def listen_to_alert_pub():
    context = zmq.Context()
    sub_socket = context.socket(zmq.SUB)  # Subs to alert_generation pub socket
    sub_socket.connect('tcp://alert_generation:28000')
    sub_socket.setsockopt_string(zmq.SUBSCRIBE, '')

    while True:
        eventlet.sleep(0.0)

        try:
            json = sub_socket.recv_json(flags=zmq.NOBLOCK)
            logger.debug('json')
            sio.emit('update', {'data': json})
        except zmq.Again:
            pass  # No message


app = socketio.Middleware(sio, app)
sio.start_background_task(target=listen_to_alert_pub)
eventlet.wsgi.server(eventlet.listen(('', 443)), app)
```

The `logger.info("connected ", sid)` runs instantly when the client connects, and `logger.debug('json')` runs instantly as well when a message from zmq is received. 

However, there is usually a big delay 1-20sec from when sio.emit is called to when the client receives it. Sometimes the client receives the update instantly, but most of the time there's a delay and the client will receive the updates in bulk at the same time.

There is only like 10 messages per minute, so eventlet.sleep(0.0) is getting called a lot.

**Comment by miguelgrinberg** [comment]
I haven't done much with zmq, but from what I recall eventlet comes with its own wrapper for it, you can't just use pyzmq on its own. Try using `from eventlet.green import zmq` instead of `import zmq`.

**Comment by Majiick** [comment]
Works perfectly now, thank you. Since I was using noblock didnt think it'd cause any problems.

**Comment by Majiick** [comment]
I'm not sure if this is socketio related or ZMQ related however, feel free to close this issue.

**Comment by miguelgrinberg** [comment]
Not sure if this is causing your problem, but you definitely do not want an application that is spinning doing nothing. Either increase the sleep, or better, use a non-blocking read from your socket. You may also want ensure the delay is not on the client side by adding logging that shows when each Socket.IO packet was received.

**Comment by Majiick** [comment]
I checked using TCP dump and some prints in socketio lib, it seems that internal_emit is getting called but the packets do not get sent until later sometimes according to TCPDump.

I also tried a blocking read without the sleep and the behavior is exactly the same.

I noticed something strange in the logs socketio generates.

When the client connects, this gets instantly logged:

```
socketio_server_1         | (1) accepted ('46.7.13.167', 62789)
socketio_server_1         | 46.7.13.167 - - [16/Mar/2019 14:13:34] "GET /socket.io/?EIO=3&transport=polling&t=Mc6skI6 HTTP/1.1" 200 399 0.001060
socketio_server_1         | (1) accepted ('46.7.13.167', 62792)
socketio_server_1         | 46.7.13.167 - - [16/Mar/2019 14:13:34] "GET /socket.io/?EIO=3&transport=polling&t=Mc6skK4&sid=efdb41594ba7475d90fdd5676626fab3 HTTP/1.1" 200 233 0.09750
```

After this for about 20 seconds or so, the server is emitting packets to the client but the client doesn't receive anything. Then, the socketio logs this and the client instantly receives every update that wasn't received and there is no lag from this point on.

```
socketio_server_1         | 46.7.13.167 - - [16/Mar/2019 14:14:10] "GET /socket.io/?EIO=3&transport=polling&t=Mc6skMB&sid=efdb41594ba7475d90fdd5676626fab3 HTTP/1.1" 200 229 35.861316
socketio_server_1         | 46.7.13.167 - - [16/Mar/2019 14:14:10] "GET /socket.io/?EIO=3&transport=websocket&sid=efdb41594ba7475d90fdd5676626fab3 HTTP/1.1" 200 0 35.965211
socketio_server_1         | 46.7.13.167 - - [16/Mar/2019 14:14:10] "GET /socket.io/?EIO=3&transport=polling&t=Mc6stGx HTTP/1.1" 200 399 0.000655
socketio_server_1         | (1) accepted ('46.7.13.167', 62822)
socketio_server_1         | 46.7.13.167 - - [16/Mar/2019 14:14:11] "GET /socket.io/?EIO=3&transport=polling&t=Mc6stHY&sid=d24dadc5cf294f139425ab2fbd508b01 HTTP/1.1" 200 233 0.059273
```

Although sometimes it works instantly.

**Comment by miguelgrinberg** [comment]
You have to enable the logs from Socket.IO to see what's happening. Add `logger=True, engineio_logger=True` to your `Server()` instance.

The problem that you describe is really very common, and happens when something that the application does is blocking. I don't know what it is, but it clearly seems like you do have a blocking problem. By blocking I mean blocking that is incompatible with eventlet. The blocking functions from eventlet are obviously okay.
