### ISSUE TITLE
How to pass datas on connection

### ISSUE THREAD

**Issue by Dr-Chaos** [miguelgrinberg/python-socketio#272]
Hi, I would like to send data when connecting (from the client to the server), from Python to JavaScript, and inversely.

For exemple:

Client.py -> Server.py Work
client.py:
```
sio.connect('http://localhost:1337', {'username':'root, 'password':'root'})
```

server.py
```
@sio.on('connect')
async def connect(sid, environ):
    print('username ' + environ['HTTP_USERNAME'])
    print('username ' + environ['HTTP_PASSWORD'])
```

Client.py -> Server.js : Work
client.py:
```
sio.connect('http://localhost:1337', {'username':'root, 'password':'root'})
```

server.js
```
io.on('connection', function(socket){
  console.log('username: ' + socket.handshake.headers.username);
  console.log('password: ' + socket.handshake.headers.password);
});
```

Client.js -> Server.py Don't work
client.js
```
const socket = io.connect("http://localhost:1337", {query: 'username=root&password=root'});
```

server.py
```
@sio.on('connect')
async def connect(sid, environ):
    print(str(environ)
```
and I get 
```
'QUERY_STRING': 'username=root&password=root&EIO=3&transport=polling&t=Mc7Isz7'
```

I do not know how to manage this, for having only username and password. Or if there is a more elegant way of doing that

Ty for your work and your help !

**Comment by miguelgrinberg** [comment]
The query string is a standard component of a URL. You can parse it by splitting the string at each `&`, and then for each part splitting again at the `=`, which will give you the variable name and the value.

**Comment by Dr-Chaos** [comment]
Yes, I thought about it, but I was hoping for a more elegant and common method to Socketio Python and Socketio JS
Because my server receives requests in both Python and JavaScript, so If I can treat all queries in the same way, whether they come from Python or JS, I'll be better :)

**Comment by miguelgrinberg** [comment]
The query string is the most common method for this. Sending custom headers like you are doing in Python is really the unusual solution here, and it is actually not possibly to do from the browser. You can send a query string from my Python client as follows:

    sio.connect('http://localhost:1337?username=root&password=root')

**Comment by Dr-Chaos** [comment]
It was perfectly what I was looking for, thank you very much !
