### ISSUE TITLE
Starvation

### ISSUE THREAD

**Issue by voidloop** [miguelgrinberg/python-socketio#273]
Hi, I would like to send data from server to client on connection event. Is it possible? Why does it seem the server is blocked if it emits an event on own connection event?

**latency_client.py**:
```python
import asyncio
import time
import socketio

loop = asyncio.get_event_loop()
sio = socketio.AsyncClient()
start_timer = None


async def send_ping():
    global start_timer
    start_timer = time.time()
    await sio.emit('ping_from_client')


@sio.on('connect')
async def on_connect():
    print('connected to server')
    # await send_ping()


@sio.on('my_test')
async def on_my_test(data):
    print('my_test')
    await send_ping()


@sio.on('pong_from_server')
async def on_pong(data):
    global start_timer
    latency = time.time() - start_timer
    print('latency is {0:.2f} ms'.format(latency * 1000))
    await sio.sleep(1)
    await send_ping()


async def start_server():
    await sio.connect('http://localhost:5000')
    await sio.wait()


if __name__ == '__main__':
    loop.run_until_complete(start_server())
```

**latency_server.py**:
```python
from aiohttp import web
import socketio

sio = socketio.AsyncServer(async_mode='aiohttp')
app = web.Application()
sio.attach(app)


@sio.on('connect')
async def on_connect(sid, environ):
    await sio.emit('my_test', room=sid)


@sio.on('ping_from_client')
async def ping(sid):
    await sio.emit('pong_from_server', room=sid)

if __name__ == '__main__':
    web.run_app(app, port=5000)
```

The server never calls ping function. What's wrong in my code?
Thank you.

**Comment by miguelgrinberg** [comment]
Well, it seems nothing is wrong with your code. I need to investigate, but it would appear as if these early packets that are being exchanged right after the connection is established affect the upgrade to websocket process.

I was able to workaround the problem by having the client connect via websocket directly:

    await sio.connect('http://localhost:5000', transports=['websocket'])

I'll investigate and report back, but based on what I see this is something I need to address from my side, your app is fine.

**Comment by miguelgrinberg** [comment]
@voidloop please upgrade your python-engineio package to 3.5.0 or later to resolve this issue.
