### ISSUE TITLE
which version of JS socket.io client?

### ISSUE THREAD

**Issue by fenicento** [miguelgrinberg/python-socketio#275]
Hi, I'm experiencing frequent disconnections from the client with error transport close", while on the server I have:

0aacf7de620d4211a4c4217c3b3fd859: Received packet PING data None
Receive error -- socket is closed

this is how I initialize the server:

```
sio = socketio.AsyncServer(async_mode='aiohttp',ping_timeout=10, ping_interval=3, allow_upgrades=False, engineio_logger=True)
app = web.Application()
sio.attach(app)
```

the client sends a JSON object at 30 fps to the server, which should be fine performance wise.

I read around that a possible cause could be a mismatch of versions between server and client, so I was curious if there's any official supported version for the Js client.

**Comment by miguelgrinberg** [comment]
All the 1.x and 2.x JS clients should work.

Do you see any difference if you revert the ping interval and timeout to the defaults? Your settings will add a lot of overhead in the connection, you are forcing ping/pong packets every three seconds. No need for that.

There are lots of possible causes for this problem. I would investigate if that high rate of data packets isn't unintentionally causing the server to block for too long. That paired with the short timeout could trigger disconnections. Try reducing the packet rate to see if that has an effect on the problem.
