### ISSUE TITLE
Do we need to create socketio.Server instances for each django socket apps?

### ISSUE THREAD

**Issue by Avinash-Raj** [miguelgrinberg/python-socketio#276]
I have created one django project with two socket apps having socketio.Server instances created on each app .  Both socket app initiates a background task at the start for achieving separate functionalities. 

My question is, can we create a single socketio Server instance on the project root folder and make both the apps to share the created server instance and achieving the functionality by emitting to separate namespaces? Does it cause any issue in terms of performance?

**Comment by miguelgrinberg** [comment]
Do you intend to share the Python module where the server is created, as in importing the same module into both your applications? Or do you really mean creating a single server used by both applications? The former should be no problem. The latter can also work, but you need to decide how do you intend each of the Django apps to talk to this unified Socket.IO server. Your options are to use the "external process" approach, or to make your Django apps Socket.IO clients using the new client support in this package.
