### ISSUE TITLE
I got this printing all over the terminal:"GET /socket.io/?EIO=4&transport=websocket HTTP/1.1" 200 0 95.515740 and can't run my code

### ISSUE THREAD

**Issue by AbdulrahmanMossad** [miguelgrinberg/python-socketio#277]

**Comment by miguelgrinberg** [comment]
It's not possible for me to diagnose this issue with the little information that you provided. Can you provide more details, and maybe some code?

**Comment by AbdulrahmanMossad** [comment]
I used Reinforcement Learning in my project and  build my Unity3D environment  in headless mode , when I do training and for a short time connection is fine  then I found that the conecttion is interrupted where I see this message like this :
127.0.0.1 - [25 / Mar / 2019 05:02:25] "GET /socket.io/?EIO=4&transport=websocket HTTP / 1.1" 200 0 60.221815
 
The training process stops i found some people say that i should update my python-socketio  but i'm using the latest version .

**Comment by AbdulrahmanMossad** [comment]
![Screenshot from 2019-03-25 05-32-05](https://user-images.githubusercontent.com/46299447/54890100-6fe4ff80-4eb0-11e9-9e71-9bb59ed380ae.png)

**Comment by miguelgrinberg** [comment]
WebSocket connections can be interrupted for a lot of different reasons, the message that you are seeing in your console just indicates that a WebSocket request ended, it is not indicative of an error, and it does not indicate what caused the request to end, unfortunately. Your application should be able to adapt to these disconnections. Your client, for example, should be attempting to reconnect right after this happens, correct?

**Comment by AbdulrahmanMossad** [comment]
i train my code without gui (headless mode) , when WebSocket request ended i run gui and found problem solved (connection starts again).
but i want to complete training  without Gui .

**Comment by miguelgrinberg** [comment]
I don't understand why the GUI is part of this discussion. A Socket.IO client must always reconnect if the connection is dropped, that is how the protocol works. Even if you are using a headless client, a disconnection should be followed by an immediate attempt to reconnect.

**Comment by AbdulrahmanMossad** [comment]
sorry i want to ask a question please ,  127.0.0.1 - [25 / Mar / 2019 05:02:25] "GET /socket.io/?EIO=4&transport=websocket HTTP / 1.1" 200 0 60.221815   this line means attempt to reconnect ?
if yes should i see it always replicates until connection established again ? because this line  replicates for 4 or 5 times and stopped like image that i sent .

**Comment by miguelgrinberg** [comment]
That line is printed when a request ends. As I said above, there is little information there, I can't really tell you what's going on from that alone.

**Comment by zhl001** [comment]
> sorry i want to ask a question please , 127.0.0.1 - [25 / Mar / 2019 05:02:25] "GET /socket.io/?EIO=4&transport=websocket HTTP / 1.1" 200 0 60.221815 this line means attempt to reconnect ?
> if yes should i see it always replicates until connection established again ? because this line replicates for 4 or 5 times and stopped like image that i sent .

Hello！Have you solved this problem? I get the same like you! Thank you!
