### ISSUE TITLE
Custom JSON encoder

### ISSUE THREAD

**Issue by cxong** [miguelgrinberg/python-socketio#278]
python-socketio uses plain `json.dumps` to encode data. This means if the data is not serializable, it cannot be emitted.

Usually you get around this by defining a custom `JSONEncoder` and passing this to the `json.dumps` method like (https://stackoverflow.com/a/3768975/2038264):

```python
json.dumps(cls=MyEncoder)
```

But this method isn't exposed by the `Packet` class. I'd like to be able to pass maybe a `json_encoder` argument so that I can do:

```python
sio.emit('my event', data, json_encoder=MyEncoder)

...

# https://github.com/miguelgrinberg/python-socketio/blob/master/socketio/packet.py#L71
encoded_packet += self.json.dumps(data, separators=(',', ':'), cls=self.json_encoder)
```

For now a workaround could be to do `sio.emit('my event', json.loads(json.dumps(data, cls=MyEncoder)))` but this is a bit hacky

**Comment by miguelgrinberg** [comment]
You can pass your own json encode/decode functions in the `Server()` constructor. See the `json` option: https://python-socketio.readthedocs.io/en/latest/api.html#socketio.Server
