### ISSUE TITLE
What is  difference between flask-socketio and python-socketio?

### ISSUE THREAD

**Issue by WaleedMeselhy** [miguelgrinberg/python-socketio#279]

**Comment by miguelgrinberg** [comment]
- python-socketio is a dependency of flask-socketio.
- python-socketio works with pretty much any Python web framework, while flask-socketio is obviously a Flask extension.

**Comment by WaleedMeselhy** [comment]
Which is best for production messaing app?
1 - Flask_socketio + gunicorn + eventlet
2 - python-socketio + gunicorn + aiohttp

**Comment by miguelgrinberg** [comment]
There is no better or worse, really. Use the stack that you like best.
