### ISSUE TITLE
missing git release tag for 1.2

### ISSUE THREAD

**Issue by anthraxx** [miguelgrinberg/python-socketio#28]
Hey, as a package maintainer I'm having an upstream watch onto this git repository, this is incredibly convenient. Unfortunately the 1.2 version tag was missing, therefor I missed the 1.2 release and updated from 1.1 to 1.3.
Could you please push the missing 1.2 tag and maybe try to make sure they will not be missing? :smile_cat:

**Comment by miguelgrinberg** [comment]
Sorry about that. I pushed the v1.2 now.

**Comment by anthraxx** [comment]
@miguelgrinberg awesome, thank you very much
