### ISSUE TITLE
RedisManager listen hang

### ISSUE THREAD

**Issue by wangyang02** [miguelgrinberg/python-socketio#281]
I'm using Flask-Socketio building a websocket server.I have read doc about flask socketio 【Emitting from an External Process】and chose to use this feature.But after hours the websocket server could not receive message from this external process(flask-socketio server will listen this event and do something).I have spend some time to dig into it ,describe as below:

- When emitting from an external process,I chose redis as message queue.

- redis server indeed receive emit from the external process. this is Sub/Pub support by redis,I could subscribe the same channel to prove it, it's not the external process problem.

- SocketIO server will user RedisManager as client manager,which will launch a thread subscribe redis channel, [redis_manager](https://github.com/miguelgrinberg/python-socketio/blob/master/socketio/redis_manager.py#L104)

- Listen will get connection from a redis connection pool [here](https://github.com/miguelgrinberg/python-socketio/blob/master/socketio/redis_manager.py#L66)

In my case , my redis server will close connection after a client is idl for 600 seconds(common config for redis server).I found some CLOSE_WAIT status connections which is suspicious.It seems reids pubsub listen method will not raise timeout exception in such case and do not realize this socket has been closed from redis server.I add socket_timeout=60,retry_on_timeout=True to "from_url" method,it works.This will force the socket timeout 60s and raise a timeout error,which retry_on_timeout=True will tell redis client to retry connect [here](https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L3016)

env:
uwsgi+gevent
python-engineio==3.1.2
python-socketio==3.0.0
redis==2.10.6
gevent==1.4.0
uwsgi==2.0.17.1

Another question, why after 5~8 hours redis manager hangs(due to 600 seconds timeout in redis server), something about gevent ?

**Comment by miguelgrinberg** [comment]
> It seems reids pubsub listen method will not raise timeout exception in such case

My understanding is that timeouts do not apply to pub/sub, only to regular client connections. Pub/sub is supposed to be idle until an event occurs, so it does not make sense to have timeouts there.

> why after 5~8 hours redis manager hangs(due to 600 seconds timeout in redis server), something about gevent ?

I don't really know. All this package is doing is opening a pub/sub connection. I guess there could be bugs in gevent that could cause this. You may want to test the same application under gunicorn+eventlet instead of uwsgi+gevent to see if there is any difference.

**Comment by wangyang02** [comment]
> My understanding is that timeouts do not apply to pub/sub, only to regular client connections. Pub/sub is supposed to be idle until an event occurs, so it does not make sense to have timeouts there.
> 
> >
Yeah  that's correct, timeout do not apply to Pub/Sub , but if redis server config timeout option for some  purpose , that would be a problem.Could  you consider provide a timeout option for RedisManager ?

**Comment by miguelgrinberg** [comment]
I don't understand why a timeout is necessary. I suggest you upgrade your redis and socketio packages, you may be missing on changes. I do not see any problems when using recent versions.

**Comment by wangyang02** [comment]
all right, I will try. Thank you ~
