### ISSUE TITLE
Example ASGI server does not work with newer Uvicorn

### ISSUE THREAD

**Issue by grjzwaan** [miguelgrinberg/python-socketio#282]
Niet that I do not neccesarily expect that the example would keep working as dependencies change. However, perhaps there’s an easy fix or insightful remark that’ll help me :)

**Issue**
The example ASGI server does not work with Uvicorn 0.6, but it does work with Uvicorn 0.3.

`if __name__ == '__main__':
    loop = auto_loop_setup()
    sio.start_background_task(background_task)
    uvicorn.run(app, '127.0.0.1', 5000, loop=loop)`

**Error**
`[...]site-packages/uvicorn/protocols/http/httptools_impl.py:20: RuntimeWarning: coroutine 'render' was never awaited
  status_code: _get_status_line(status_code) for status_code in range(100, 600)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2019-03-28 16:21:14,464 ERROR    Task was destroyed but it is pending!`

**What I think**
It seems you no longer pass the loop to uvicorn. If you check for the current loop after 'auto_loop_setup()' then there is a loop, but it hasn't started yet. 

**Why I'm interested**
I have a hardware project where a single thread can change some GPIO pins. Preferably I keep everything in asyncio: in that way I get parallelism, socket connections with a global state (GPIO pins) without locking/.

**Comment by miguelgrinberg** [comment]
It's unfortunately that uvicorn changed in a way that broke these examples, but I'll see if I can fix everything to work again. Thanks.

**Comment by grjzwaan** [comment]
I got `python-socketio` working together with background tasks on `uvicorn`. Additionally I made it work together with Starlette. I didn't see an example here, so perhaps it's a nice example to add.

```python
import logging
import asyncio
import uvicorn
from uvicorn.loops.uvloop import uvloop_setup
from starlette.applications import Starlette
from starlette.responses import JSONResponse
import socketio

# Set some basic logging
logging.basicConfig(
    level=2,
    format="%(asctime)-15s %(levelname)-8s %(message)s"
)

# Create a basic app
sio = socketio.AsyncServer(async_mode='asgi')
star_app = Starlette(debug=True)
app = socketio.ASGIApp(sio, star_app)


@star_app.route('/')
async def homepage(request):
    return JSONResponse({'hello': 'world'})


@sio.on('connect')
async def connect(sid, environ):
    logging.info(f"connect {sid}")


@sio.on('message')
async def message(sid, data):
    logging.info(f"message {data}")
    # await device.set(data)


@sio.on('disconnect')
async def disconnect(sid):
    logging.info(f'disconnect {sid}')


# Set up the event loop
async def start_background_tasks():
    while True:
        logging.info(f"Background tasks that ticks every 10s.")
        await sio.sleep(10.0)


async def start_uvicorn():
    uvicorn.run(app, host='0.0.0.0', port=8000)


async def main(loop):
    bg_task = loop.create_task(start_background_tasks())
    uv_task = loop.create_task(start_uvicorn())
    await asyncio.wait([bg_task, uv_task])

if __name__ == '__main__':
    uvloop_setup()
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main(loop))
    loop.close()
```

Probably you can also add background tasks from the event handlers. That also worked in the original example, so that should still work.

If you want I can make a pull request with a sample (similar to the other samples). However, the background_task would have a slightly different API (as in: I use the asyncio way to schedule functions and not the function in python-socketio-library.

**Comment by miguelgrinberg** [comment]
I have addressed the problems with uvicorn now.

**Comment by adamlwgriffiths** [comment]
I just wanted to provide a correct version of the example above, since it's indexed on some search engines but doesn't work out-of-the-box.
Ironically the output from the background task obscures the error generated by the uvicorn task, removing the background task makes this apparently.

The issues are mainly in `start_uvicorn`:
* cannot call "run" in this context (inside an asyncio event). Solution seems to be to use `Server.serve`.
* needs to "await" something for the `asyncio.wait` call to use.

`uvloop` import depends on the uvloop module, which wasn't obvious to me, but the rest of the code seems to be using vanilla asyncio so I removed this.
For simplicity I also removed starlette.

It should also be noted that the background task has no control method in this example, ctrl+c will _not_ stop it.
As is it only stops to kill -9. Ie, this example is incomplete.

Anyway, "working" version is below.
If I get time I'll try and resolve the background task / ctrl+c issue.

```
import logging
import asyncio
import uvicorn
from uvicorn.loops.asyncio import asyncio_setup
import socketio

logging.basicConfig(
    level=2,
    format="%(asctime)-15s %(levelname)-8s %(message)s"
)

sio = socketio.AsyncServer(async_mode='asgi')
app = socketio.ASGIApp(sio, sio)

@sio.on('connect')
async def connect(sid, environ):
    logging.info(f"connect {sid}")

@sio.on('message')
async def message(sid, data):
    logging.info(f"message {data}")

@sio.on('disconnect')
async def disconnect(sid):
    logging.info(f'disconnect {sid}')

async def start_background_tasks():
    while True:
        logging.info(f"Background tasks that ticks every 10s.")
        await sio.sleep(10.0)

async def start_uvicorn():
    config = uvicorn.config.Config(app, host='0.0.0.0', port=8000)
    server = uvicorn.server.Server(config)
    await server.serve()

async def main(loop):
    bg_task = loop.create_task(start_background_tasks())
    uv_task = loop.create_task(start_uvicorn())
    await asyncio.wait([bg_task, uv_task])

if __name__ == '__main__':
    asyncio_setup()
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main(loop))
    loop.close()
```

**Comment by grjzwaan** [comment]
Great that you're correcting the example. Perhaps this helps: in june 2019 I made a note about `ctrl+c`:
(apparently I put the awaitables in the app)

Note sure it it works with current versions.


```
import logging
import uvicorn
from app import app
import asyncio
from uvicorn.loops.uvloop import uvloop_setup


logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)-15s %(levelname)-8s %(message)s"
)


def uvicorn_task():
    """ Returns running the app in uvicorn as an awaitable to join the main
        asyncio loop. """
    config = uvicorn.Config(app, host='0.0.0.0', port=8000)
    server = uvicorn.Server(config)

    return server.serve()


async def main(app):
    """ Joins unicorn together with background tasks defined in the app. """
    # Make the list with awaitables
    aws = [uvicorn_task(),
           *app.background_tasks()]
    # Run and return when the first completes or is cancelled
    await asyncio.wait(aws, return_when=asyncio.FIRST_COMPLETED)


if __name__ == '__main__':
    # Set up the loop
    uvloop_setup()
    loop = asyncio.get_event_loop()

    # Run the main loop
    asyncio.run(main(app))

```

**Comment by adamlwgriffiths** [comment]
I spent some time with asyncio trying to get it to honor the ctrl+c signals and gave up.
The only solution I could find was using your code with `asyncio.FIRST_COMPLETED`.
I've seen examples that setup signal handlers and catch asyncio Stop exceptions in the tasks, but none of these worked.
I'll hold my tongue on my opinions of asyncio.
