### ISSUE TITLE
More definitive HTTPS connection documentation

### ISSUE THREAD

**Issue by xsduan** [miguelgrinberg/python-socketio#283]
Possibly related: #69, #222 

I really like this library, but it is not entirely clear how to set it up to use https/wss connections using the client (and the server, I suppose). I have tried to simply connect to an https url, but it does not work, so there’s something extra to it. I can’t find anything on the documentation about how to set something like that up, even just a relevant link would be helpful. 

It would also be nice to be able to have some confirmation that the socket io server is indeed only accepting secure connections. So far the only feedback is that the aiohttp server url is https, but I am not sure that that means the websocket connection is secure (I feel like it is? But I’d like to know more definitively). Even a simple mention in the docs that https implies wss would be good.

**Comment by miguelgrinberg** [comment]
> I have tried to simply connect to an https url, but it does not work

What have you tried? Please indicate how you create the secure server and how you connected to it from the client. Also show any errors you've got on either side.

**Comment by xsduan** [comment]
```
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)
```

I'm using a self signed certificate for testing purposes, so it's to be expected, but there's no documentation on where to insert a "trusted" cert (e.g. [requests](http://docs.python-requests.org/en/master/user/advanced/#client-side-certificates). I guess can hold off on testing ssl until I get an actual domain name, but it would have been nice to do some local testing beforehand.

In any case, at least some mention of ssl functionality (or explicit lack thereof) would be nice.

**Comment by miguelgrinberg** [comment]
If I explain how to use self-signed certificates, then people will start using them, and that is a bad idea. If you are running tests, then you do not need SSL, but if you really need to do this, then you can configure requests to accept your self-signed certificate through environment variables.

**Comment by xsduan** [comment]
I suppose. As I said I can probably wait until I get an actual domain to do this so the main issue is that there is literally no mention of HTTPS/WSS in the docs or that it automatically works based on URL which can be a bit confusing, but it's a minor issue anyways.
