### ISSUE TITLE
SocketIO uWSGI server + RabbitMQ example

### ISSUE THREAD

**Issue by melikyan-a** [miguelgrinberg/python-socketio#287]
Hello!
I have some chat application and using message queue (RabbitMQ), uWSGI +gevent websocket with NGINX.

here my code:

    import pika
    import uwsgi

    def application(env, start_response):
    connection = pika.BlockingConnection(
    pika.ConnectionParameters(host='localhost')
    )
    channel = connection.channel()

    exchange = env['PATH_INFO']

    channel.exchange_declare(
        exchange=exchange, exchange_type='fanout'
    )
    result = channel.queue_declare(exclusive=True)
    queue_name = result.method.queue  # random queue name generated by RabbitMQ

    channel.queue_bind(exchange=exchange, queue=queue_name)

    uwsgi.websocket_handshake()

    def keepalive():
        print('PING/PONG...')
        try:
            msg = uwsgi.websocket_recv_nb()
            connection.add_timeout(30, keepalive)
        except OSError as error:
            return['']
    keepalive()

    while True:
        for method_frame, _, body in channel.consume(queue_name):
            try:
                uwsgi.websocket_send(body)
            except OSError as error:
                break
            else:
                channel.basic_ack(method_frame.delivery_tag)

I have some problem, because when client disconnect from websocket I can't kill his session and after some time I get **[DANGER] async queue is full !!!**

Is SocketIO server can resolve this issue?
Can you give me example, how can I do my app with SocketIO?

Thanks!

**Comment by miguelgrinberg** [comment]
I do not know the cause of your problem, so I can't really tell you if Socket.IO will experience the same issue or not. There is documentation for Socket.IO if you are interested in porting your application to test it. https://flask-socketio.readthedocs.io/en/latest/

**Comment by melikyan-a** [comment]
I use django with celery.

**Comment by miguelgrinberg** [comment]
@melikyan-a then use these docs: https://python-socketio.readthedocs.io/en/latest/
