### ISSUE TITLE
Question: is it possible to use uvloop?

### ISSUE THREAD

**Issue by Dmitry-N-Medvedev** [miguelgrinberg/python-socketio#29]

**Comment by miguelgrinberg** [comment]
Not at this time, only gevent and eventlet are supported.

**Comment by dfee** [comment]
It should be supported now with [`socketio.AsyncServer`](http://python-socketio.readthedocs.io/en/latest/#socketio.AsyncServer) right?

**Comment by miguelgrinberg** [comment]
Ah, yes. This is now supported. You can use this package with sanic or aiohttp now.

**Comment by RajshekarReddy** [comment]
Hello miguelgrinberg,

Currently I have this line of code 
`# creates a new Async Socket IO Server
sio = socketio.AsyncServer(async_mode='aiohttp', async_handlers=True)
# Creates a new Aiohttp Web Application
app = web.Application()
# Binds our Socket.IO server to our Web App
# instance
sio.attach(app)`

is there anything else I need to setup to make the server user uvloop?

**Comment by miguelgrinberg** [comment]
@RajshekarReddy Not from this side. Your aiohttp application controls the loop, so you need to ensure aiohttp is configured to use it.

**Comment by RajshekarReddy** [comment]
@miguelgrinberg  Thank you that helps. By the way you are doing a fantastic job :) thank you so much.
