### ISSUE TITLE
ImportError: cannot import name 'Namespace' from 'socketio' (/usr/lib/python3.7/site-packages/socketio/__init__.py)

### ISSUE THREAD

**Issue by leond08** [miguelgrinberg/python-socketio#290]

**Comment by leond08** [comment]
Error : In python3.7

flask_socketio = 3.3.2
python-socketio = 4.0.0

from flask_socketio import SocketIO
File "/usr/lib/python3.7/site-packages/flask_socketio/__init__.py", line 24, in <module>
from .namespace import Namespace
File "/usr/lib/python3.7/site-packages/flask_socketio/namespace.py", line 1 <module>
from socketio import Namespace as _Namespace
ImportError: cannot import name 'Namespace' from 'socketio' (/usr/lib/python3.7/site-packages/socketio/__init__.py)

**Comment by miguelgrinberg** [comment]
You probably have a conflicting dependency. I recommend that you do this in a virtualenv, where you can install just the Socket.IO packages.
