### ISSUE TITLE
TypeError: emit() got an unexpected keyword argument 'wait' when send is called

### ISSUE THREAD

**Issue by greggzj** [miguelgrinberg/python-socketio#292]
Hello miguel, I am fresh on this and I really like your flask extension package:)
I use the latest version of the socket-io package and use the send method on client side , when calling send , python just raise : `TypeError: emit() got an unexpected keyword argument 'wait'.`
I check the code , seems the emit method can be replaced by call method in function send ?
Hoping for your feed back thanks in advance
https://github.com/miguelgrinberg/python-socketio/blob/cacb621ad75b64b7bd740e695446cef5e4f335a2/socketio/client.py#L295

Could you please confirm if it is an ISSUE ?

**Comment by miguelgrinberg** [comment]
@greggzj oh yes, looks like I left the `send()` method in a broken state. The `wait` argument that I added for a short time in between releases but later decided to remove, should not have made it to an official release. I'll take it out and make another release. Sorry about that!

**Comment by miguelgrinberg** [comment]
Fixed in version 4.0.1.
