### ISSUE TITLE
Client shall not be able to emit events to namespace which it is not belong

### ISSUE THREAD

**Issue by bestchanges** [miguelgrinberg/python-socketio#295]
I expected that only successfully connected to given namespace client is able to emit events to this namespace.
Instead I found that any client can emit event to any namespace.
Also I didn't find opportunity to check if sid belongs to namespace. 

What is the use of namespace then?

**Comment by miguelgrinberg** [comment]
The namespace determines which events you can receive. Emitting is not limited by being connected to a namespace.

**Comment by bestchanges** [comment]
I got it. 

And it also can be check if the client is_connected inside event handler.
```
    async def on_command(self, sid, data):
        if sio.manager.is_connected(sid, self.namespace):
            await sio.emit('reboot', namespace=None)
        else:
            sio.logger.warning(f"client {sid} cannot execute method {__name__}")
```
