### ISSUE TITLE
Invalid Frame Header with Skipper reverse proxy and async_mode=aiohttp

### ISSUE THREAD

**Issue by nebularazer** [miguelgrinberg/python-socketio#300]
When using the aiohttp example from the [examples folder](https://github.com/miguelgrinberg/python-socketio/tree/master/examples/server/aiohttp) and use [Skipper](https://github.com/zalando/skipper) as reverse proxy Chrome logs `WebSocket connection to 'ws://localhost:8000/socket.io/?EIO=3&transport=websocket' failed: Invalid frame header' failed: Invalid frame header` to the console.

The aiohttp example works with nginx and without any proxy.
The asgi example works with skipper, nginx and without any proxy.
A nodejs test server also works with skipper, nginx and without any proxy.
**I am using `transports: ['websocket']` to force the client to use websockets only**

Versions used:
- pytohn 3.7.3 (also tested with paython 3.6.8)
- aiohttp 3.5.4
- python-engineio 3.5.2
- python-socketio 4.0.2
- skipper v0.10.216

How to reproduce:
- edit app.html to force websockets only. change line 10: 
```
var socket = io.connect('http://' + document.domain + ':' + location.port + namespace, {
    transports: ['websocket']
});
```
- run skipper with docker:
```
docker run --rm -it --network host registry.opensource.zalan.do/pathfinder/skipper:v0.10.216 skipper -experimental-upgrade -experimental-upgrade-audit -application-log-level DEBUG -address :8000 -inline-routes 'r: * -> "http://127.0.0.1:8080/"'
```
- run `python app.py`
- check console output from skipper (has websocket audit enabled) and chrome console for "invalid frame header" -> ws connection is dropped immediately after it has been established.

**Comment by miguelgrinberg** [comment]
I think this is something that needs to be taken to the aiohttp project, the websocket implementation is theirs. I suggest you try one of their WebSocket examples (maybe [this one](https://github.com/aio-libs/aiohttp/blob/master/examples/web_ws.py)) to confirm that you see the same problem without this package.

**Comment by nebularazer** [comment]
Hey Miguel, thanks for your fast response!

I tested with the example from aiohttp and can confirm this still does not work with skipper.
The error message is a different one: `WebSocket connection to 'ws://localhost:8000/' failed: One or more reserved bits are on: reserved1 = 0, reserved2 = 1, reserved3 = 1`

I will take this issue to their project or talk to one of the maintainers of skipper, maybe we can figure something out.
