### ISSUE TITLE
How to query?

### ISSUE THREAD

**Issue by lujo777** [miguelgrinberg/python-socketio#303]
I'd like to connect to socket with specific query (for example, access_token)
How can I do it with pytho socket io client?

**Comment by miguelgrinberg** [comment]
The connection URL can include a query string.

**Comment by lujo777** [comment]
How? Examples please

**Comment by miguelgrinberg** [comment]
I don't understand what you need me to show you. Just pass the token in the query string of your URL. Or pass it as a header if you prefer. Both options are supported by the client. If you want an example client to start from, see the examples directory in this repository.

**Comment by lujo777** [comment]
How to add token into header?

**Comment by miguelgrinberg** [comment]
This is covered in the documentation: https://python-socketio.readthedocs.io/en/latest/api.html#socketio.Client.connect

**Comment by lujo777** [comment]
In node js as works `socket = io('localhost:5000/api/sockets/mynamespace', {query: "anyquery=query"})`

**Comment by victormoyanodiaz** [comment]
You can send your own custom headers in the connect function. For example, you could do the following: 
`
websocket = socketio.Client()
websocket.connect(server_url, headers= {'access_token': 'your token here'})
`
Then in the server you can read this access token and disconnect the client if is not valid.

**Comment by theorivero** [comment]
```
import socketio


websocket = socketio.Client()

websocket.connect('https://exemple.com?access_token=w77w5q57w7qw75q')
```

this work for me

**Comment by miguelgrinberg** [comment]
@theorivero not a good solution. Including secrets in query string is not as secure as other methods such as a header or the request body. This is an old ticket, in current versions of the Socket.IO protocol it is possible to pass authentication information in the connection call, and this information is sent to the connect handler for verification.
