### ISSUE TITLE
restrict upgrade transport

### ISSUE THREAD

**Issue by h0rn3t** [miguelgrinberg/python-socketio#304]
Hello, i have few questions:
1. is possible  restrict upgrade to websocket trasport, stay on polling?
2. if not possible, can I handle upgrade to websocket with some event

**Comment by miguelgrinberg** [comment]
On the server, use `allow_upgrades=False` to prevent an upgrade to WebSocket. On the client, use `transports=['polling']`.

**Comment by h0rn3t** [comment]
@miguelgrinberg thanks
