### ISSUE TITLE
Reconnection thread not triggered in some situations

### ISSUE THREAD

**Issue by victormoyanodiaz** [miguelgrinberg/python-socketio#305]
Hello, 

First of anything, congrats on the super great library. We have a node.js server running socket.io and we use your socket.io client in some raspberries to connect to it and is super useful to us. We are using the following versions with python 3.5.3:

```
python-engineio==3.8.0
python-socketio==4.1.0
websocket-client==0.56.0
```

The thing is sometimes your reconnection thread does not get triggered when the socket io connection has been lost. It is easy to replicate if for example we unplug the ethernet cable or prevent the node.js server from responding the PINGS from the client (simulating communication problems). 

The question I have is regarding the trigger of the reconnection. Check the following lines found in the client.py file. 

![imagen](https://user-images.githubusercontent.com/18706091/59091860-82e46900-8910-11e9-84d4-6d9180d6aac0.png)

Is there any special reason in line 562 to only start the reconnection thread if self.eio.state == 'connected'? Probably there are things happening I am not aware of but the common sense tells me that the reconnection thread should be started if the eio state is disconnected. What am I missing here? I have tried removed this conditional and in my use case seems to work just fine.

Thank you so much in advance and have a great day

**Comment by miguelgrinberg** [comment]
> Is there any special reason in line 562 to only start the reconnection thread if self.eio.state == 'connected'?

Yes. The idea is that if the client or the server issued an explicit disconnect that should not trigger a reconnection. Reconnections only happen when the disconnection is unexpected. That said, I don't discard that my logic incorrectly determines that a reconnection is not needed, open to consider an improvement if it is necessary.

**Comment by victormoyanodiaz** [comment]
Appreciate the quick response. 

I suspect the self.eio.state changes to 'disconnected' in some weird case when the disconnection is unexpected. I have been debugging a bit the engine.io library and found out this error is being printed: 
```
ERROR ::2019-06-07 13:04:33,876 client.py  packet queue is empty, aborting
```

So I have been taking a look at the code, and it seems the error could be in the engine.io library. Before triggering the 'disconnect' event, the write_loop_task thread has to finish, as you can see in line 567:

![imagen](https://user-images.githubusercontent.com/18706091/59100840-83d4c500-8927-11e9-8ee9-b2ef9e0053e0.png)

The write_loop_task is basically running this code. In line 593 you can see the error I am getting being printed:

![imagen](https://user-images.githubusercontent.com/18706091/59100462-65ba9500-8926-11e9-8cfe-732fb5081ff0.png)

And just after this error prints, a reset is done. The reset function sets the state to 'disconnected':

![imagen](https://user-images.githubusercontent.com/18706091/59100548-b500c580-8926-11e9-94eb-a24be7d20236.png)

So, before the 'disconnect' event is triggered the state is being changed to 'disconnected'. Thus, your reconnection background process will not start. This behaviour is present in both websocket and polling transport.

Just to recap, this is happening when the communication with the socket io server is broken. Such as disconnection the ethernet cable or preventing the server from responding to the pings.  I will submit a pull request so you can review it more closely whenever you can.

Thanks a lot!

**Comment by miguelgrinberg** [comment]
@victormoyanodiaz Thank you for the detailed explanation. I think your change is correct, the queue empty condition certainly falls in the "unexpected" category so a retry in that case is warranted.

**Comment by victormoyanodiaz** [comment]
That was quick! We have been testing it in production today and now it works like a charm. I will close this issue then. 

Thanks!
