### ISSUE TITLE
Pass more information into event callback

### ISSUE THREAD

**Issue by thezboe** [miguelgrinberg/python-socketio#309]
I am emitting an event to a room, and receiving callbacks as an "acknowledgement" from all clients which is intended. These callbacks all go to the same function, which I would like to keep track of which clients have acknowledged. But, the callback only receives data that the client returns.

Can the callback be modified to have access to the sid, namespace, room, etc?

**Comment by miguelgrinberg** [comment]
For the namespace and the room you can use a partial (see https://docs.python.org/3.7/library/functools.html#functools.partial). The `sid` is not sent to the callback, so the only way right now would be to have the client include it in the callback arguments it sends back to the server.
