### ISSUE TITLE
Bad request (400) under broadcast and CORS.

### ISSUE THREAD

**Issue by eeerrrwwwuuu** [miguelgrinberg/python-socketio#314]
I'm using standard background task to emit message to all opened guis.

```
async def background_broadcast_statuses():
    """Example of how to send server generated events to clients."""
    global cfg
    global cam_statuses
    while True:
        print("BROADCAST:",cfg['sio_gui_room'])
        await sio.sleep(cfg['sio_broadcast_sleep']) 
        await sio.emit("cam_statuses", {'data': 'Server generated event'},room=cfg['sio_gui_room'])

```
..

```
if __name__ == '__main__':

	try:
		cfg = load_config()
                 ....
		app.run(host=cfg['sio_url'], port=cfg['sio_port'], debug=True)
```

I must admit it was pretty hard to deal with CORS ( this functionality should be supported by default I guess not just by Sanic ), but now I have another problem I can emit message but I'm unable to get broadcast message in proper form. 

```
          var socket = io.connect('http://192.168.1.2:5000',{
         //   transports: ['websocket','polling'],
          });
 
          socket.on('connect', function() {
              send();
          });
          socket.on('cam_statuses', function() { 
              console.log('STATUS'); 
          });
          socket.on('disconnect', function() {
              /* 
              */
          }); 
          function send() { 
              socket.emit('join', { room: 'gui_room' } ); 
          }
```

`firebug-lite.js:18996 POST http://192.168.1.2:5000/socket.io/EIO=3&transport=polling&t=MlbCKI8 400 (Bad Request)
`
I'm using Sonic 18.2 for python3.5 + latest socket.io.js and Chromium under ubuntu.

I  can always create loop on GUI site and emit message every second, but I'm expecting that broadcast is more professional.

**Comment by miguelgrinberg** [comment]
My guess is that this is also related to CORS issues. Enable logs in the Socket.IO server to have more information. Just add `logger=True, engineio_logger=True` to your `Socketio()` constructor.

**Comment by eeerrrwwwuuu** [comment]
```
BROADCAST: gui_room
emitting event "cam_statuses" to gui_room [/]
BROADCAST: gui_room
emitting event "cam_statuses" to gui_room [/]
BROADCAST: gui_room
emitting event "cam_statuses" to gui_room [/]
BROADCAST: gui_room
62758b9ab23347039342d1cf097602fc: Sending packet OPEN data {'pingInterval': 25000, 'upgrades': ['websocket'], 'pingTimeout': 60000, 'sid': '62758b9ab23347039342d1cf097602fc'}
emitting event "my_response" to 62758b9ab23347039342d1cf097602fc [/]
62758b9ab23347039342d1cf097602fc: Sending packet MESSAGE data 2["my_response",{"data":"Connected","count":0}]
62758b9ab23347039342d1cf097602fc: Sending packet MESSAGE data 0
[2019-07-13 00:18:43 +0200] - (sanic.access)[INFO][192.168.1.2:51806]: GET http://192.168.1.2:5000/socket.io/?EIO=3&transport=polling&t=MleH61R  200 166
Invalid session None
[2019-07-13 00:18:43 +0200] - (sanic.access)[INFO][192.168.1.2:51806]: POST http://192.168.1.2:5000/socket.io/?EIO=3&transport=polling&t=MleH63i  400 11
emitting event "cam_statuses" to gui_room [/]
BROADCAST: gui_room
emitting event "cam_statuses" to gui_room [/]
BROADCAST: gui_room
9705cbd1b7794304860ac8cb12997f96: Sending packet OPEN data {'pingInterval': 25000, 'upgrades': ['websocket'], 'pingTimeout': 60000, 'sid': '9705cbd1b7794304860ac8cb12997f96'}
emitting event "my_response" to 9705cbd1b7794304860ac8cb12997f96 [/]
9705cbd1b7794304860ac8cb12997f96: Sending packet MESSAGE data 2["my_response",{"data":"Connected","count":0}]
9705cbd1b7794304860ac8cb12997f96: Sending packet MESSAGE data 0
[2019-07-13 00:18:45 +0200] - (sanic.access)[INFO][192.168.1.2:51806]: GET http://192.168.1.2:5000/socket.io/?EIO=3&transport=polling&t=MleH6Op  200 166
Invalid session None
[2019-07-13 00:18:45 +0200] - (sanic.access)[INFO][192.168.1.2:51806]: POST http://192.168.1.2:5000/socket.io/?EIO=3&transport=polling&t=MleH6P3  400 11
emitting event "cam_statuses" to gui_room [/]
BROADCAST: gui_room
emitting event "cam_statuses" to gui_room [/]
BROADCAST: gui_room
emitting event "cam_statuses" to gui_room [/]

```

**Comment by eeerrrwwwuuu** [comment]
I'm really getting confused with this library, it doesn't work in many scenarios. I managed to bypass problem with CORS by proxy on NodeJS express level, but this example which You're presenting is simply not working. Code is loosing SIDs ,  I get bad request 400 everywhere. Broadcast is multiplying sessions on each call  .. from my perspective it's far away from official implementation. :(

**Comment by miguelgrinberg** [comment]
>  I managed to bypass problem with CORS by proxy on NodeJS express level

I need details. Are you using the Node server now? In the original report you seemed to be using the Python server. Please provide details.

> but this example which You're presenting is simply not working

What example is this? Can you share a link to it?

**Comment by eeerrrwwwuuu** [comment]
I'm using example with Sonic server from Your repo, but customized a bit for my needs:

I have python server under :  192.168.1.2:5000  and I want to connect from nodeJs application but only on frontend level, where host is:  192.168.1.2:8000 , due to problems with CORS I set proxy from 
192.168.1.2:8000/proxy_socket   --> 192.168.1.2:5000  next I set in front-end connection:

```
var socket = io.connect('http://192.168.1.2:8000' ,
 {
    path:'/proxy_socket/socket.io',
    transports: ['polling'],
 }
 );

connect.on('my_response', function() { 
    console.log('GOT RESPONSEEEE AFTER LOGIN'); 
});

```
Socket Backend is just classic from Your [tutorial](https://github.com/miguelgrinberg/python-socketio/blob/master/examples/server/sanic/app.py).

```

app = Sanic()
"""ping_timeout=900000, ping_interval=1000,"""
sio = socketio.AsyncServer(async_mode='sanic',  logger=True, engineio_logger=True)
sio.attach(app)

@sio.event
async def connect(sid, environ):
    await sio.emit('my_response', {'data': 'Connected', 'count': 0}, room=sid)

```

I'm able to connect, but this library behaves quite tricky. From my perspective after setting connection something is happening with session and library is loosing it. If I expand pingTimeout and enable broadcast on each run I get +1 hash on output so after 20 iterations broadast sends 20 messages. 
This is what I get from FireBug.  --> 200 followed by 400 
![Screenshot from 2019-07-14 21-19-15](https://user-images.githubusercontent.com/30157733/61188298-7c6aaf00-a67d-11e9-9266-c57122a2ae47.png)
Logs from Sanic:

7fb32bc06dee405ea00376dfb4bf05a9: Client is gone, closing socket
0a9d8545183f4e1ea4e3193a5011f88a: Client is gone, closing socket
Client disconnected
0a9d8545183f4e1ea4e3193a5011f88a: Client is gone, closing socket
b54e6b96c55b4f908f0dece0df111eb5: Sending packet OPEN data {'upgrades': ['websocket'], 'pingInterval': 25000, 'sid': 'b54e6b96c55b4f908f0dece0df111eb5', 'pingTimeout': 60000}
emitting event "my_response" to b54e6b96c55b4f908f0dece0df111eb5 [/]
b54e6b96c55b4f908f0dece0df111eb5: Sending packet MESSAGE data 2["my_response",{"count":0,"data":"Connected"}]
b54e6b96c55b4f908f0dece0df111eb5: Sending packet MESSAGE data 0
[2019-07-14 21:29:14 +0200] - (sanic.access)[INFO][192.168.1.2:35438]: GET http://192.168.1.2.:5000/socket.io/?EIO=3&transport=polling&t=MlnzUls  200 166
**Invalid session None**
[2019-07-14 21:29:14 +0200] - (sanic.access)[INFO][192.168.1.2:35442]: POST http://192.168.1.2.:5000/socket.io/?EIO=3&transport=polling&t=MlnzUmp  400 11
6a607d28d1104b18a96d715dfd615284: Client is gone, closing socket
Client disconnected
6a607d28d1104b18a96d715dfd615284: Client is gone, closing socket
76490f3a7bd346d89c00d8179147f9d9: Sending packet OPEN data {'upgrades': ['websocket'], 'pingInterval': 25000, 'sid': '76490f3a7bd346d89c00d8179147f9d9', 'pingTimeout': 60000}
emitting event "my_response" to 76490f3a7bd346d89c00d8179147f9d9 [/]
76490f3a7bd346d89c00d8179147f9d9: Sending packet MESSAGE data 2["my_response",{"count":0,"data":"Connected"}]
76490f3a7bd346d89c00d8179147f9d9: Sending packet MESSAGE data 0

**Comment by miguelgrinberg** [comment]
This proxying that you set up is insufficient, as I believe it won't proxy WebSocket connections, just HTTP.

How many Sanic processes are you running, by any chance. If you are running more than one, try just one and let me know if there is an improvement.

**Comment by eeerrrwwwuuu** [comment]
> This proxying that you set up is insufficient, as I believe it won't proxy WebSocket connections, just HTTP.
> 
I can queue socket directly threw 192.168.1.2:5000 same result  * path /socket.io
> How many Sanic processes are you running, by any chance. If you are running more than one, try just one and let me know if there is an improvement.
I have just one server, by design I want to have server with two rooms:
room_cameras: which will grab messages from 4 external programs
room_gui: each instance of gui should connect there, from this level I want to aggregate all messages from room_cameras and emit single message with 4 statuses of cameras.

**Comment by miguelgrinberg** [comment]
If you can provide a small example client and server I can test here I can attempt to reproduce the problem.
