### ISSUE TITLE
i can't connect from my react-native client

### ISSUE THREAD

**Issue by mtalhagaoglu** [miguelgrinberg/python-socketio#317]
hi. i have to connect python socketio server from reactnative app. i was able to connect socketio server in ubuntu server ( http://remoteip:8080 ). so the server is working properly but react native couldn't connect. this is the code: `const socket = SocketIOClient("http://remoteip:8080"); 
        socket.on("connect", () => { console.warn("connected") });`

are there anyone know how can i connect?

**Comment by miguelgrinberg** [comment]
You may have better luck asking in a react native community, but don't you need to call `socket.connect()` to actually establish a connection?
