### ISSUE TITLE
AsyncRedisManager SSL Support

### ISSUE THREAD

**Issue by dbanty** [miguelgrinberg/python-socketio#318]
Is there a way to use SSL with the AsyncRedisManager?  This is possible with RedisManager by passing in a "rediss" scheme instead of a "redis" scheme, but I don't see a way to do it with the Async manager.

I have sort of patched in a way to do this just by adding an "ssl" option to `AsyncRedisManager.__init__()`, then passing it through to `aioredis.create_redis()` in `_publish` and `_listen`.  Happy to do a pull request if that's the right way to do this.

**Comment by miguelgrinberg** [comment]
@dbanty can you expand the function that parses the Redis URL to recognize `redis://` vs. `rediss://`? I think that would be better than adding a `ssl` argument.

**Comment by dbanty** [comment]
@miguelgrinberg I created a pull request that allows recognition of the rediss scheme.  Other than using that instead of an ssl param, it works the same way as my initial comment suggested.

**Comment by dbanty** [comment]
Thanks @miguelgrinberg!  Do you have a timeframe for when this will make into a release?

**Comment by miguelgrinberg** [comment]
@dbanty It's not released.
