### ISSUE TITLE
Emitting to a FeathersJS server?

### ISSUE THREAD

**Issue by jogiji** [miguelgrinberg/python-socketio#321]
Please have a look at this..
https://github.com/feathersjs/feathers/issues/1471

**Comment by miguelgrinberg** [comment]
Try `client.emit('methodname', ('servicename', {}))`.

The event name is the first argument. The remaining data items need to be given in the second argument as a tuple if you have more than one.

**Comment by jogiji** [comment]
Thank you.. will try and revert.

**Comment by jogiji** [comment]
Your suggestion worked. Thank you :)
