### ISSUE TITLE
Can you teach me how to get the return value of the request?

### ISSUE THREAD

**Issue by Hellowlonewolf** [miguelgrinberg/python-socketio#322]

**Comment by miguelgrinberg** [comment]
I don't understand what you are asking. Do you have example code to show me?

**Comment by Hellowlonewolf** [comment]
async def run_client():
    await sio.connect('http://localhost:8802')
    await sio.emit('new_message', {
        "user_id": 123,
        "team_id": 345,
        "content": "我来了4"
    },namespace='/chat')

**Comment by Hellowlonewolf** [comment]
After sending a message, how can I determine in the client whether the request was successful?Is there a return value requested or a functional method like recv() in websocket

**Comment by miguelgrinberg** [comment]
You can use the `callback` argument in the `emit()` call to request a callback function to be invoked with the data provided by the server.

Or if you prefer, you can use `call()` instead of `emit()` to combine the emit and the callback handling into one:

```python
result = sio.call('new_message', {...}, namespace='/chat')
```

**Comment by Hellowlonewolf** [comment]
> 您可以使用调用中的`callback`参数`emit()`来请求使用服务器提供的数据调用回调函数。
> 
> 或者如果您愿意，可以使用`call()`而不是`emit()`将emit和回调处理组合成一个：
> 
> ```python
> result = sio.call（' new_message '，{ ... }，namespace = ' / chat '）
> ```

Sorry I'm too stupid, install your method I print(result), it prints out for node

**Comment by Hellowlonewolf** [comment]
> 您可以使用调用中的`callback`参数`emit()`来请求使用服务器提供的数据调用回调函数。
> 
> 或者如果您愿意，可以使用`call()`而不是`emit()`将emit和回调处理组合成一个：
> 
> ```python
> result = sio.call（' new_message '，{ ... }，namespace = ' / chat '）
> ```

Sorry, I am too stupid, follow your method I print (result), it prints out the node
