### ISSUE TITLE
AsyncServer cors_allowed_origins docs incorrecr

### ISSUE THREAD

**Issue by dbanty** [miguelgrinberg/python-socketio#327]
I believe the docs for the AsyncServer class are incorrect.  They state "cors_allowed_origins – List of origins that are allowed to connect to this server. All origins are allowed by default." All origins means to me that the default is '*', but that doesn't seem to be the case.  Only the same origin was allowed to make requests by default, I had to explicitly set cors_allowed_origins='*' in the AsyncServer constructor to allow all.

I think this is probably the right choice for a default (more secure) but the docs should properly indicate the behavior.

**Comment by miguelgrinberg** [comment]
This changed recently, I think there must be a problem with my documentation builds, the docs should reflect the current state.

**Comment by miguelgrinberg** [comment]
Actually no, you are correct, I forgot to update the docs on this particular change.
