### ISSUE TITLE
socketio.exceptions.ConnectionError: Unexpected status code 203 in server response

### ISSUE THREAD

**Issue by JulienBrochier** [miguelgrinberg/python-socketio#331]
Hi,
I have this issue when I try to connect to a server 

> socketio.exceptions.ConnectionError: Unexpected status code 203 in server response

My minimalist code : 

```
import socketio
sio = socketio.Client()
sio.connect('https://app.relay.crisp.chat/')
```
Is there a way to fix it from my side ? How can I authorize data from this source ?

**Comment by miguelgrinberg** [comment]
No, this can only be modified by changes in this package or in your server. Do you know why your Socket.IO server returns a 203 response instead of the standard 200?

**Comment by JulienBrochier** [comment]
I don't, that's not my server :(
