### ISSUE TITLE
Security issue. "Connect to namespace" executes on client side

### ISSUE THREAD

**Issue by vldpro** [miguelgrinberg/python-socketio#333]
Thanks for fix in #325 , but it will not work if client has version less than 4.3.1 and server on 4.3.1.
So, I still can emit events to a namespace without passing "on_connect" handler. I think it should be  handled on server side, instead of client side.

**Comment by miguelgrinberg** [comment]
I have to check how the reference server implementation behaves on this situation. The Socket.IO protocol does not prevent unconnected or even non-existing namespaces to be used in events.
