### ISSUE TITLE
Can I connect a socketio client through a proxy ?

### ISSUE THREAD

**Issue by Panpeter-pou** [miguelgrinberg/python-socketio#335]
Hello,

First of all, thank you for this package.

I have currently created a basic script that runs two socket.io clients in two different threads and I would like to know if there is a way to set a proxy for each client, I found nothing in the documentation.

Thank you in advance

**Comment by miguelgrinberg** [comment]
Not at this time. It would be an interesting option to add.

**Comment by dzervas** [comment]
Note that defining `http_proxy` and `https_proxy` environment variables, work. Maybe you want to do this from inside python though.

**Comment by miguelgrinberg** [comment]
Current releases support passing an initialized HTTP session object.

**Comment by INF800** [comment]
I am using the following code:

```python
import socketio
import requests

username = 'spxk*******'
password = 'SZn********'
proxy = f"http://{username}:{password}@us.smartproxy.com:***00"
session = requests.session()
session.proxies = {'https': proxy}

sio = socketio.Client(http_session=session)
 
@sio.on('connect', namespace='/all-filings')
def on_connect():
    print("Connected to https://api.sec-api.io:3334/all-filings")
 
@sio.on('filing', namespace='/all-filings')
def on_filings(filing):
    print(filing)
 
sio.connect('https://api.sec-api.io:3334/?apiKey=********************************', namespaces=['/all-filings'], transports=["websocket"])
sio.wait()
```

But it results in error:
```
ParseResult(scheme='http', netloc='spxk********:SZn9Y*********@us.smartproxy.com](mailto:SZn9Y************@us.smartproxy.com):***00', path='', params='', query='', fragment='')
---------------------------------------------------------------------------
ConnectionError                           Traceback (most recent call last)
[<ipython-input-20-74e4373d0b20>](https://localhost:8080/#) in <cell line: 20>()
     18     print(filing)
     19 
---> 20 sio.connect('https://api.sec-api.io:3334/?apiKey=*********************************************', namespaces=['/all-filings'], transports=["websocket"])
     21 sio.wait()

1 frames
[/usr/local/lib/python3.10/dist-packages/socketio/client.py](https://localhost:8080/#) in connect(self, url, headers, transports, namespaces, socketio_path)
    280                 'connect_error', '/',
    281                 exc.args[1] if len(exc.args) > 1 else exc.args[0])
--> 282             six.raise_from(exceptions.ConnectionError(exc.args[0]), None)
    283         self.connected = True
    284 

/usr/local/lib/python3.10/dist-packages/six.py in raise_from(value, from_value)

ConnectionError: Connection error
```

**Comment by INF800** [comment]
> I am using the following code:
> 
> ```python
> import socketio
> import requests
> 
> username = 'spxk*******'
> password = 'SZn********'
> proxy = f"http://{username}:{password}@us.smartproxy.com:***00"
> session = requests.session()
> session.proxies = {
>     'http': proxy,
>     'https': proxy
> }
> 
> sio = socketio.Client(http_session=session)
>  
> @sio.on('connect', namespace='/all-filings')
> def on_connect():
>     print("Connected to https://api.sec-api.io:3334/all-filings")
>  
> @sio.on('filing', namespace='/all-filings')
> def on_filings(filing):
>     print(filing)
>  
> sio.connect('https://api.sec-api.io:3334/?apiKey=********************************', namespaces=['/all-filings'], transports=["websocket"])
> sio.wait()
> ```
> 
> But it results in error:
> 
> ```
> ParseResult(scheme='http', netloc='spxk********:SZn9Y*********@us.smartproxy.com](mailto:SZn9Y************@us.smartproxy.com):***00', path='', params='', query='', fragment='')
> ---------------------------------------------------------------------------
> ConnectionError                           Traceback (most recent call last)
> [<ipython-input-20-74e4373d0b20>](https://localhost:8080/#) in <cell line: 20>()
>      18     print(filing)
>      19 
> ---> 20 sio.connect('https://api.sec-api.io:3334/?apiKey=*********************************************', namespaces=['/all-filings'], transports=["websocket"])
>      21 sio.wait()
> 
> 1 frames
> [/usr/local/lib/python3.10/dist-packages/socketio/client.py](https://localhost:8080/#) in connect(self, url, headers, transports, namespaces, socketio_path)
>     280                 'connect_error', '/',
>     281                 exc.args[1] if len(exc.args) > 1 else exc.args[0])
> --> 282             six.raise_from(exceptions.ConnectionError(exc.args[0]), None)
>     283         self.connected = True
>     284 
> 
> /usr/local/lib/python3.10/dist-packages/six.py in raise_from(value, from_value)
> 
> ConnectionError: Connection error
> ```
> 
> The proxy works fine. Tested it using:
> 
> ```python
> import requests
> url = 'https://ip.smartproxy.com/json'
> username = 'sp*****************'
> password = 'SZn9***************'
> proxy = f"http://{username}:{password}@us.smartproxy.com:***00"
> result = requests.get(url, proxies = {
>     'http': proxy,
>     'https': proxy
> })
> 
> from pprint import pprint
> pprint(result.json())
> ```
> 
> resulting in:
> 
> ```
> {'browser': {'name': '', 'version': ''},
>  'city': {'code': 'MD',
>           'name': 'Gambrills',
>           'state': 'Maryland',
>           'time_zone': 'America/New_York',
>           'zip_code': '21054'},
>  'country': {'code': 'US',
>              'continent': 'North America',
>              'name': 'United States'},
>  'engine': {},
>  'isp': {'asn': 11951,
>          'domain': 'lan2wan.net',
>          'isp': 'Cogent Communications',
>          'organization': 'Cogent Communications'},
>  'platform': {'os': 'undefined undefined'},
>  'proxy': {'ip': '207.152.153.249', 'is_anonymous_proxy': False, 'type': 'ISP'}}
> ```

@miguelgrinberg can you please have a look at this.

**Comment by miguelgrinberg** [comment]
@INF800 It is really impossible for me to debug this for you. You are getting a connection error, so you should check the logs of your proxy to find out what happened. Maybe it does not support WebSocket, you may want to try using long-polling to see if that helps.
