### ISSUE TITLE
Execute callback in body of event listener

### ISSUE THREAD

**Issue by gitavi** [miguelgrinberg/python-socketio#336]
The `js` `socket.io` provides access to the `ack` callback function within the event listener's body, allowing the server to say, immediately execute the `ack` callback, instead of executing it at the end of the event listener. Here's what I mean from the `socket.io` docs.

```js
io.on('connection', (socket) => {
  socket.emit('an event', { some: 'data' });

socket.emit('ferret', 'tobi', (data) => {
  console.log(data); // data will be 'woot'
});

  // the client code
  // client.on('ferret', (name, fn) => {
  //   fn('woot');
  // });

});
```

I have a situation where I want to execute the `ack` callback (which starts a server-side timer) after a client-side state change shows the client that it is their turn to play, but before the client attempts to automatically play; something like this:
```python
class ClientBot(AsyncClientNamespace):

    ...

    async def on_set_on_turn(self, payload, callback):
        self._on_turn()
        callback()
        await self._auto_play()
``` 

From the docs `return` is how the callback is executed with arguments but this wouldn't allow doing the above. Is this currently possible? Thanks!

**Comment by miguelgrinberg** [comment]
That's correct, you have to return from the handler to trigger the ack. What you can do is move the remaining logic after the ack to a separate task. Something like this:

```python
class ClientBot(AsyncClientNamespace):

    ...

    async def on_set_on_turn(self, payload, callback):
        self._on_turn()
        asyncio.ensure_future(self._auto_play())
```

**Comment by gitavi** [comment]
I tried this with an `auto_play` that `asyncio.sleep`s for a bit before auto playing but am unable to guarantee that the server-side timer is set for all bots in situations where there are many bots, 1000 say. So this might be an issue with server load now but what happens is 1000 bots receive a `set_on_turn` event at around the same time and some of them start auto playing before the `ack` callback has been executed by the server. I could increase the `asyncio.sleep` time but this is counter to the purpose of autoplaying and whatever time I set won't generalize to any number of bots.

Is there any way to *guarantee* that the `ack` callback has been executed *before* calling `auto_play`? I feel like exposing the callback function to the event listener is the only way?

**Comment by miguelgrinberg** [comment]
There isn't really a way to do what you are asking, sadly. The server only know when it sends the ack, it has no control over when the client receives it, and there are a lot of factors that can affect that. I recommend that you use a separate event that the client sends after it receives the ack to request the start of auto-play.

**Comment by gitavi** [comment]
Ok well, my frontend uses the `js` `socket.io` so it won't be a problem there since the callback function is exposed and I can call it immediately. But out of curiosity, why can't the same be done with the `python` client? Shouldn't I be able to directly call the function that is handling the callback with the return values of the event listener? Thanks again.

**Comment by miguelgrinberg** [comment]
@gitavi the function that handles the callback is on the other side of the wire, it can't obviously be called directly. The client sends the ack packet and has no control over when this packet arrives in the other side. The operation is asynchronous, so in the regard timings are unpredictable even for the JS client.

The decision to use the return values of the handler to trigger the ack packet is just to make it more Pythonic. Even if I implement the ack similar to the JS way you will still have the code that follows the ack run before the callback on the other side, since it's all asynchronous.
