### ISSUE TITLE
simple exampe for client receive continuous

### ISSUE THREAD

**Issue by fajaryoedha** [miguelgrinberg/python-socketio#339]
when i start to receive from server, client just only receive first(when connect).. seems like event not triggered

**Comment by fajaryoedha** [comment]
import socketio
import time
sio = socketio.Client()

@sio.on('raspberry')
def on_message(data) :
    print(data)

sio.connect('http://localhost:14046')

while 1 :
    sio.emit('raspberry', {'lol': 123})
    print('send')
    time.sleep(1)

**Comment by miguelgrinberg** [comment]
What does your server do?

**Comment by fajaryoedha** [comment]
get it
https://stackoverflow.com/questions/15461600/how-to-trigger-messages-using-socket-io

the problem is in server side
