### ISSUE TITLE
get_participants does not list users connected to a different server

### ISSUE THREAD

**Issue by vtjeng** [miguelgrinberg/python-socketio#34]
I successfully implemented a modified version of [Flask-SocketIO-Chat](https://github.com/miguelgrinberg/Flask-SocketIO-Chat) which allows users connected to different ports (in my case, `5001` and `5002`) but in the same namespace and room to communicate using a `kombu_manager`. However, it looks like the`client_manager` for each of the servers maintains a separate list of connected users. (I'm accessing the list of users using `socketio.server.manager.get_participants()`. Is this the expected behavior?[`pubsub_manager.py`](https://github.com/miguelgrinberg/python-socketio/blob/0173306ee98ae7825cfd5840911f9d35439d7e8d/socketio/pubsub_manager.py#L14-L17) suggests that any class that implements it should be able to share the full list of clients. 

I can provide more details and a minimal working example if necessary, but I wanted to check whether the list of users is intended to be shared (via `get_participants()`) first.

---

To give a bit more detail, the code for handling events in [this section](https://github.com/miguelgrinberg/Flask-SocketIO-Chat/blob/master/app/main/events.py#L15-L20) was replaced by the following:

```
@benchling_socketio.on('text', namespace='/chat')
def text(message):
    """Sent by a client when the user entered a new message.
    The message is sent to all people in the room."""
    room = session.get('room')
    emit('message', {'msg': session.get('name') + ':' + message['msg']}, room=room)
    if message['msg'] == 'list-all-users':
        participants = list(benchling_socketio.server.manager.get_participants(namespace='/chat', room=room))
        emit('message', {'msg': u'Total number of participants is {}'.format(len(participants))}, room=room)
        emit('message', {'msg': 'Current user ids of users in room are ...'}, room=room)
        for participant in participants:
            emit('message', {'msg': u'  {}'.format(participant)}, room=room)
```

Examples of the app in use are shown:

<img width="535" alt="screen shot 2016-07-11 at 7 17 28 pm" src="https://cloud.githubusercontent.com/assets/5932817/16753147/2b5ec850-479c-11e6-81b1-61fd1bad15ce.png">

**Comment by miguelgrinberg** [comment]
`get_participants` is not a public method that you can call, it is used internally. As a rule of thumb, anything that is not documented is not intended to be used by applications.

A full list of clients cannot be obtained. This is a distributed server, there is no consolidated list of clients anywhere. My recommendation is that you build your own list on the application side, you can do so by using connect and disconnect handlers.

**Comment by vtjeng** [comment]
Thanks for the reply! I intended to use get_participants to populate an
initial list of connected users when a new client connects (which can then
be maintained on the client side), but it seems that this is not possible.
Several alternative options that I can think of would be to:

1) Have each connected user send an acknowledgement that they are still
connected when they receive information that a new user has connected
2) Have each user send the most updated list of connected users they know
about when they receive information that a new user has conmected.

Is there any preferred way based on your experience, or is there an
alternative I'm missing?

**Comment by miguelgrinberg** [comment]
@vtjeng have you considered using the connect/disconnect handlers as a way to find out what users join or leave the system? That should be enough for you to maintain a list of active users.
