### ISSUE TITLE
"event" method with AsyncSever

### ISSUE THREAD

**Issue by LeehoLim** [miguelgrinberg/python-socketio#340]
The Sanic example shows a call with an event method being used as a decorator function; however, upon inspecting the library, the method doesn't exist... is there something that I am missing?

**Comment by miguelgrinberg** [comment]
Any chance you have an older version of this package? The `event` decorator does exist, it's here: https://github.com/miguelgrinberg/python-socketio/blob/master/socketio/server.py#L195.

**Comment by LeehoLim** [comment]
python-socketio==3.1.2... ok it seems as though this is very outdated

**Comment by LeehoLim** [comment]
my mistake!

**Comment by miguelgrinberg** [comment]
This version restriction has been removed, so this shouldn't be a problem anymore.
