### ISSUE TITLE
Sharing cookies with http(s)

### ISSUE THREAD

**Issue by kohtala** [miguelgrinberg/python-socketio#341]
I have a REST API server that has many options for authentication (OAuth etc.) all ending with a session cookie. It implements also Socket.IO that is authenticated using the same cookie.

The server may update the cookie on use regardless if it is used on REST API, polling or websocket. Just copying the cookie header is not enough, it must also update the common cookie jar. https://tools.ietf.org/html/rfc6455#section-1.3 states also the Websocket opening handshake can also set cookies.

Looking at the engineio websocket stack, a common cookie jar is not used. There is copying of Cookie header from polling session to Websocket, but no update of cookie. It also seems the rules of https://tools.ietf.org/html/rfc6265#section-5.4 are not followed when copying the cookie.

When looking at this, after not finding a documented interface, I tried sharing the sesssion by patching in the session used on the REST API as below. It partially works as the creation of `sio.eio.http` is lazy and `None` at this point. 

```
    self.session = aiohttp.ClientSession(headers={
        "Accept": "application/json"
    })
...
    sio = socketio.AsyncClient()
    sio.eio.http = self.session
    await sio.connect(url)
    result = await self.session.post(...)
```

But it closes the session when the `sio.connect` upgrades to Websocket, so the `session.post` fails with ´RuntimeError('Session is closed')`.

Passing in a session with shared cookie jar works further:

```
    self.session = aiohttp.ClientSession(headers={
        "Accept": "application/json"
    })
...
    sio = socketio.AsyncClient()
    sio.eio.http = aiohttp.ClientSession(cookie_jar=self.session.cookie_jar)
    await sio.connect(url)
    result = await self.session.post(...)
```

I realize this may be a problem to report in engineio and websockets, but as there may be some bigger cookie sharing issue that needs be handled on socketio as well, I report it here first.

There saw some problem also with the synchronous API, but I did not study that much as I target the async API.

Here some of the packages I have in my venv:

aiohttp==3.5.4
python-socketio==4.3.1
websockets==8.0.2
async-timeout==3.0.1
python-engineio==3.9.3
requests==2.20.1
urllib3==1.24.3
websocket-client==0.56.0

**Comment by miguelgrinberg** [comment]
Who is adding a `Set-Cookie` header to the 101 response returned by the websocket connection? I don't understand how your application can do this in the scope of the Socket.IO client, since there is no access to insert custom headers at that stage. Or is this issue about adding support for that?

**Comment by kohtala** [comment]
python-socketio is the client. I have another server it needs to talk to, and this other server can set the cookie.

https://tools.ietf.org/html/rfc6455#section-1.3 states the server may set cookies in the 101 response. 

Here is the relevant line from the RFC6455:

> 1.3.  Opening Handshake
>  ...
>         HTTP/1.1 101 Switching Protocols
>  ...
>    The server can also set cookie-related option fields to _set_
>    cookies, as described in [RFC6265].

It can be needed for example to update cookie expiration or JWT content. If the server updates the cookie, python-socketio currently discards the update, and this lost can impact the session.

Websocket users and documentation seem to often forget authentication and think that once they are authenticated on the HTTP pages, the WebSocket is also secure. But this is not the case. The RFC6455 says on this:

> 10.5.  WebSocket Client Authentication
> 
>    This protocol doesn't prescribe any particular way that servers can
>    authenticate clients during the WebSocket handshake.  The WebSocket
>    server can use any client authentication mechanism available to a
>    generic HTTP server, such as cookies, HTTP authentication, or TLS
>    authentication.

This issue is about supporting the case where the server uses the cookies authentication.

Related to this is that python-socketio client has no documented supported interface to share the cookie. Patching it in the `sio.eio.http` with a session is poking the internals. I am starting a discussion on what would be a good interface to for the python-socketio to pass cookies to python-socketio and receive updated cookies. Maybe the `socketio.AsyncClient()` should have a `cookie_jar` parameter for the cookie jar that would be used and updated also during polling and websocket.

Also this incomplete cookie handling can weaken security in some cases by not following  https://tools.ietf.org/html/rfc6265#section-5.4 . It should get fixed at the same time.

**Comment by miguelgrinberg** [comment]
Authentication with cookies is already supported. If you pass credentials in the connection and the server returns a token cookie or similar, this cookie is sent in follow up HTTP requests and also in the WebSocket upgrade request, as you have seen.

I don't oppose offering high-level access to cookies in the client, but it wouldn't be high on my priority list. To be able to implement this, the underlying websocket clients used by this package would have to offer access to the cookies. I checked the asyncio client [websockets](https://github.com/aaugustin/websockets/tree/master/src/websockets) and it currently does not parse `Set-Cookie` headers in the WebSocket handshake.

**Comment by kohtala** [comment]
Thanks for looking in to this.

Do you mean by "Authentication with cookies is already supported" that it supports cookie that was received on the Socket.IO polling transport? My only credential is a cookie that I have received over the REST API. I have no login or other credentials to send over Socket.IO to get a new cookie, nor does the Socket.IO server implement any login. I can not get a new cookie over Socket.IO. I only get updates to existing cookie.

The aiohttp seems to have WebSockets support. See https://aiohttp.readthedocs.io/en/stable/client_quickstart.html#aiohttp-client-websockets. That would share the session with polling and update cookie jar from the 101 response as well. Is there some reason why the separate websockets has to be used instead?

**Comment by miguelgrinberg** [comment]
You can pass any cookies that you have from previous interactions with the server to the Socket.IO connection:

    sio.connect('http://example.com', headers={'Cookie': 'token=1234'})

I think this way of passing cookies is fairly basic and could be made into a more robust solution. I think it would be nice to have a `cookies` dictionary here that is then rendered internally as a header. But in any case, have you tried this? I'd be interested to know if this works for your server.

The reason why I decided to use the websockets package instead of aiohttp's own ws client is that the former has a public low-level API that I was already familiar with, so it seemed like a better choice at the time. I haven't really looked at the ws client in aiohttp in detail, so I don't know how much effort it would be to use it instead of the current one. And in any case, for me that would be half the battle, because even if the cookie handling is simplified by using aiohttp's ws client, I still have the non-async client which will have to support the same functionality.

**Comment by kohtala** [comment]
Passing the Cookie header like that does not receive cookie updates.
As in the initial comment, I have patched in a session that shares the cookie jar with the REST API, so polling is covered for cookie updates. It works better, but only misses any set-cookie updates on the Websocket response.
I know PR are better than this kind of discussion. There are two changes needed, a) the real API for passing in the cookie jar things, b) change from websockets to aiohttp. I'd gladly make them if ever I find time, but can not work on it right now. Anyway, thanks for the info on websockets selection. It helps to know if a PR could have any success if/when I find the time to make PR.

**Comment by miguelgrinberg** [comment]
Sorry, I dropped the ball here. Yes, I would accept a PR for passing a cookie jar, as long as it is implemented in a generic way that works for all supported platforms.

**Comment by Nithanaroy** [comment]
I disabled the cookie which also removed the warning, but I'm not sure of the side effects.
```python
app = Flask(__name__)
socketio = SocketIO(app, cookie=None)
```
