### ISSUE TITLE
socketio js client utf-8 compatibility problems

### ISSUE THREAD

**Issue by JoonatanPartanen** [miguelgrinberg/python-socketio#345]
I can't get utf-8 support working. I tried downgrading the client to socketio-1.7.4, but that doesn't seem to help. Apparently there is a breaking change in sio 2.0.0 (https://github.com/socketio/engine.io-parser/pull/81). The problem is I don't know what version of the js client this implementation supports/is based on. 

My client is socketio 2.0.4. My server is python-socketio 4.2.0.

**Comment by miguelgrinberg** [comment]
Please describe the problem in detail.

**Comment by JoonatanPartanen** [comment]
The problem was in reading YAML files in the wrong encoding. My bad.
