### ISSUE TITLE
Size limit for emit messages 

### ISSUE THREAD

**Issue by silent-vim** [miguelgrinberg/python-socketio#350]
Hi, I wanted to get an idea if there is any message size limit when emitting the json messages and if it can be configured. I noticed that when we emit a batch of json messages reducing the size we do not get a broken pipe error but with larger sizes we do. 

In the websockets asyncio [documentation](https://websockets.readthedocs.io/en/stable/api.html) I read this "The max_size parameter enforces the maximum size for incoming messages in bytes. The default value is 1 MiB" 

Thanks.

**Comment by miguelgrinberg** [comment]
This package does not impose any limitations to size, but as you have found there might be limitations imposed by the websocket dependency that you are using. At this time there is no way to pass configuration options to the underlying websocket layer, so depending on the async mode that you are using you'll have to check on the corresponding websocket implementation what these limits are if they exist at all.
