### ISSUE TITLE
Difference between call and emit method

### ISSUE THREAD

**Issue by dingluo** [miguelgrinberg/python-socketio#355]
From the documentation it seems that the only difference is that "call" would block the program until some message is received. Is it correct? And how to understand their difference under an async scenario?

**Comment by miguelgrinberg** [comment]
Emit sends an event. Optionally you can request that a callback function is invoked when the other side acknowledges the event and sends a response.

Call send the event and inserts its own callback function. It then waits for the callback to be invoked and returns the arguments passed to the callback.

**Comment by dingluo** [comment]
I got it now. So "call" is like "emit" equipped with a simple callback while "emit" can be issued with any callback.
