### ISSUE TITLE
Get IP address on message

### ISSUE THREAD

**Issue by zaanposni** [miguelgrinberg/python-socketio#357]
I know this is kinda a duplicate of #57 but I cannot figure out how your approach works in my setup.

So you said the remote IP would be receivable by using `server.environ[sid]` 
However we are not using a instance of the Server class nor I have access to a sid as far as I know.

My setup (using a normal flask app):
```
socketio = SocketIO(app, logger=True)

@socketio.on('chat_message')
def handle_message(message):
    ip = x  #TODO
```

**Comment by miguelgrinberg** [comment]
This is because you are using Flask-SocketIO, while my comment was for python-socketio, the generic server.

In your case, you want to do `socketio.server.environ[sid]`.

**Comment by zaanposni** [comment]
Thanks for your quick response. Works.
Keep up the great work!
