### ISSUE TITLE
main thread is stuck

### ISSUE THREAD

**Issue by zur250** [miguelgrinberg/python-socketio#358]
Hi miguel,
First, thanks for this awesome library!
i am trying to implement a simple example of socketio usage.
this is my server code:

```
import socketio
import eventlet


# create a Socket.IO server
sio = socketio.Server()

# wrap with a WSGI application
app = socketio.WSGIApp(sio)

@sio.event
def disconnect(sid):
    print('disconnect ', sid)
    return

@sio.on('my custom event')
def another_event(sid, data):
    return
    
@sio.event
def connect(sid, environ):
    #username = authenticate_user(environ)
    sio.save_session(sid, {'username': "zur"})
    print('connect ', sid)
    
    return

@sio.on('scan results')
def sendScan(db_name,another):
    print('This is the results')
    return



if __name__ == '__main__':
    eventlet.monkey_patch()
    eventlet.wsgi.server(eventlet.listen(('', 8000)), app)
    print("1")
    sio.emit('find vulnerabilities', {'data': 'foobar'})
    print("2")
    sio.emit('send vulnerabilities', {'data': 'vulnerabilities pls'})
    print("3")
    sio.emit('update payloads', {'data': 'this is a payload'})
```

After the client connects the server does not emit anything. Any idea how to fix it?

In addition, i am trying to wrap the library and have some issues in the client.
this is the client wrapped class:

```
import socketio

class SocketIOClient():
    global sio
    sio = socketio.Client()

    def connectToServer(self,serverURL):
        self.severURL = serverURL
        sio.connect(serverURL)

    def disconnectFromServer(self):
        sio.disconnect()

    @sio.event
    def connect(self):  # auto event - invoked when the connection is completed
        print("I'm connected!")
        print('my sid is', sio.sid)
        return

    @sio.event
    def disconnect(self):  # auto event - invoked when the client disconnected from the server
        print("I'm disconnected!")
        return

    @sio.on('find vulnerabilities')
    def startScan(url_list):  # start scan method, the server needs to provide urls to scan
        print('I need to start scan')
        print(url_list)
        return

    @sio.on('send vulnerabilities')
    def sendScan(db_name):  # we need to get DB name ( which is scan name)
        print('I need to send results')
        print(db_name)
        sio.emit('scan results', {'data': 'results'})
        return

    @sio.on('update payloads')
    def updatePayloads(payloadObject):  # should be payload type and payload data
        print('I need to update vulneabilities payloads')
        print(payloadObject)
        return
```

once i am using the following main :

```
if __name__ == '__main__':
    c = SocketIOClient()
    c.connectToServer("http://127.0.0.1:8000")
```

i am getting the following error:
TypeError: connect() takes exactly 1 argument (0 given)

will appreciate your help.

**Comment by miguelgrinberg** [comment]
The emits that you've added in the server code are all after the server is started so they never run. The `eventlet.wsgi.server()` starts the server and never returns, you cannot put code after it.

If you want to emit to a client when it connects, you can do so in a connect handler.

Regarding the client error, can you include the full stack trace?

**Comment by zur250** [comment]
yes ofcourse:
"C:\Users\zur\XSS Scanner\Seccurate\vulnerabilities\Scanner\venv\Scripts\python.exe" "C:/Users/zur/XSS Scanner/Seccurate/vulnerabilities/Scanner/layout/AnotherMain.py"
Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\Python27\Lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\Lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\zur\XSS Scanner\Seccurate\vulnerabilities\Scanner\venv\lib\site-packages\socketio\client.py", line 577, in _handle_eio_message
    self._handle_connect(pkt.namespace)
  File "C:\Users\zur\XSS Scanner\Seccurate\vulnerabilities\Scanner\venv\lib\site-packages\socketio\client.py", line 446, in _handle_connect
    self._trigger_event('connect', namespace=namespace)
  File "C:\Users\zur\XSS Scanner\Seccurate\vulnerabilities\Scanner\venv\lib\site-packages\socketio\client.py", line 515, in _trigger_event
    return self.handlers[namespace][event](*args)
TypeError: connect() takes exactly 1 argument (0 given)

**Comment by miguelgrinberg** [comment]
Oh I see. You are applying the event decorator to a method of a class, so the framework does not know which instance of your class to invoke it on. You need to use a static method, or else you need to set up the handlers specifically on an instance of the class.
