### ISSUE TITLE
load balancing

### ISSUE THREAD

**Issue by deounix** [miguelgrinberg/python-socketio#359]
In BaseManager all data are saved as objects (stored in memory).

So what if I've structure like this :

1. server (1.1.1.1) public --> install python-socketio
2. server (2.2.2.2) public --> install python-socketio
3. nginx server enabled proxy redirect to server 1 && server 2

So if I create one room in server 1 the room will not exist on server 2!
Cuz all data that handled by server 1 going to be in memory in server 1! not shared between server 1 & 2. how to do such thing ?

**Comment by miguelgrinberg** [comment]
You can't use multiple servers unless you also install a message queue that the servers use to coordinate. The documentation explains this setup.

**Comment by deounix** [comment]
thnx.
