### ISSUE TITLE
Event name with dash causes crash in Python 3.5

### ISSUE THREAD

**Issue by jeremyfromearth** [miguelgrinberg/python-socketio#36]
Running `flask-socket-io` using Python 3.5 I ran into the following issue when trying to send a message with an event name containing a dash. 

From .js client:
```
socket.on('connect', function() {
    socket.emit('connect-event', {data :  'Client connected'});
});
```

Error in Python 3.5
`ValueError: invalid literal for int() with base 10:`

Points to: 
`packet.py` line 84

**Comment by jeremyfromearth** [comment]
Issue appears to be a bug in `python-socket.io`

**Comment by miguelgrinberg** [comment]
Yes. The Socket.IO protocol uses a dash as a separator in the encoded packages, so a dash in an event name confuses things. I'll look at how the official Socket.IO server handles dashes and do the same here.
