### ISSUE TITLE
handle requests with token

### ISSUE THREAD

**Issue by skillfaker0090** [miguelgrinberg/python-socketio#360]
Hello!
It's my first time writing something in GitHub ...
I used the socketIO-client 0.7.2 and found your python-socketio today.
i have to send requests (with module requests) with http and a token (should be a header right?). is this possible with yours?

thank you,
best regards
m

**Comment by miguelgrinberg** [comment]
Not sure why you mention the requests package. If you need to send HTTP requests outside of the SocketIO communication that is not a problem, there is no interference. This client also uses requests for the long-polling part of the protocol.

Sending headers is supported. See the documentation for the details.
