### ISSUE TITLE
NGINX proxying python socketio server to the outside

### ISSUE THREAD

**Issue by rubiomiguel06** [miguelgrinberg/python-socketio#361]
Hello,
From what I've seen [here](https://github.com/miguelgrinberg/Flask-SocketIO/issues/22), it is possible to do what the title says with Flask-SocketIO. I was wondering if this could also be done with the python socketio server (sio = socketio.Server() ), running a WSGI App.
I've tried with MiguelGrinberg solution:

server {
    listen 80;
    server_name localhost;
    access_log /var/log/nginx/example.log;

    location /socket.io {
        proxy_pass http://127.0.0.1:5000/socket.io;
        proxy_redirect off;
        proxy_buffering off;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }

    location / {
        proxy_pass http://127.0.0.1:5000;
        proxy_redirect off;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

having no good results for now.
Thanks in advance for any help you can bring me.

**Comment by miguelgrinberg** [comment]
Can you be more specific about what happens? The nginx config file from the documentation has been tested and found to work by many people, so I doubt there is a problem in it.

**Comment by rubiomiguel06** [comment]
Sure. 
Right now, I'm getting my index.html, passing through nginx, with my browser, but my python server doesn't seem to connect to the socket I'm trying to set via Javascript within the .html. Should I change the socket = io('http://(my_ip):5000') to connect to port 80? If I do it, connection establishes, but weird things start to happen, for example, connection duplicates (I have a counter were I can see how many connections are established). Also, I get some http 400 errors, when trying to "GET /socket.io/?EIO=3&transport=polling&t=MsxQbCi HTTP/1.1". Both things don't happen if I point my URL directly to the port 5000.

**Comment by miguelgrinberg** [comment]
Oh, yes, definitely. I assume you connect to your site through nginx as `http://localhost`, correct? Then you have to use the same URL for Socket.IO. In fact, the Socket.IO client can do this for you, you can connect by doing `socket = io()` and the client will figure out what to do.

**Comment by rubiomiguel06** [comment]
Okey. I'm doing socket=io(). The thing is, connections to the server seem to duplicate, or even appear from nowhere. Most of the accept look like this: (870) accepted ('127.0.0.1', 35056). Always randomly appearing 127.0.0.1 requests. Also, GET or POST method are logged with two IP's, 127.0.0.1 and my IP: M.Y.I.P,127.0.0.1 - - [12/Oct/2019 01:37:11] "GET /socket.io/?EIO=3&transport=polling&t=Msyz__V HTTP/1.1" 200 404 0.001371
I really don't know what's happening. Can the nginx be generating this random connections? I really depend on knowing who is connected, because my application depends on only one person being able to use it at a time.

**Comment by miguelgrinberg** [comment]
Socket.IO starts with a long-polling connection. This is going to generate a few GET and POST requests. But shortly after the connection is initiated, a WebSocket connection is made and at that point there shouldn't be any more HTTP activity unless the connection is dropped, in which case the whole thing is repeated for the reconnection.

I'm not clear if when you say multiple connections you are really talking about different clients connecting, or just that you see many requests from the same client, which would be normal until the connection goes to WebSocket.

Your client has options to request a direct connection with WebSocket, by the way. See the "With WebSocket transport only" section at https://socket.io/docs/client-api/. This will avoid the HTTP dance at the start of a connection.

**Comment by rubiomiguel06** [comment]
When I say connection I mean real connections, when the output prints: ('connect ', 'fd98f789801c4f35b675697fc89f0d6a'). Randomly creates new connections and disconnections, when there only should be one connection, persistent. This only happens when I try to redirect requests through Nginx. If I directly point my browser to port 5000 everything works perfect. Maybe it's because I'm newbie with Nginx but, could it be that exists another script besides the configuration one that is making this weird things happen?

**Comment by miguelgrinberg** [comment]
@rubiomiguel06 can you show me a log session both from nginx and from the Socket.IO server? For the server, please enable verbose logging by adding `engineio_logger=True, logger=True` to your `Server()` object.

**Comment by rubiomiguel06** [comment]
Miguel, before showing you the logs, I believe I've found the problem. In the python code, I've put `cors_allowed_origins='*'` inside `Server()`. This stopped the constant connections. I believe the webBrowser was trying to connect with the server, and the server accepted it's connections, but the webBrowser didn't acknowledge it in some way, so it tried again to establish a connection, and that's what created multiple connections on the server side (or something like that). What do you think?

**Comment by miguelgrinberg** [comment]
@rubiomiguel06 the log would have showed the problem too. Sounds like you are doing a cross-origin connection, which is by default not allowed. What you did with `cors_allowed_origins='*'` is okay for a test, but not a good idea for a production site. It's best to only allow a short list of origins that you know about.

**Comment by rubiomiguel06** [comment]
I connect doing `socket = io()`. I don't know why I need it, but clearly when I put it, it works. Is there any workaround to this problem without allowing cross-origin connections? Why is there a cross-origin connection if what I'm doing is `io()`?

**Comment by miguelgrinberg** [comment]
Can you get me those logs? I may have an answer for you after I see that.

**Comment by miguelgrinberg** [comment]
The cross-origin validation fails in this case because the browser is reporting the `http://34.73.177.121:5000`. The server knows nothing of nginx, so it thinks the server is running at `http://34.73.177.121:1234`.

You can add `cors_allowed_origins='http://34.73.177.121:5000'` to change the accepted origin to the correct one.

**Comment by rubiomiguel06** [comment]
That solved it. Thank you so much! Great work by the way, I enjoy using it.
