### ISSUE TITLE
server logger setup behaviour

### ISSUE THREAD

**Issue by DmitriyValetov** [miguelgrinberg/python-socketio#365]
Hello!

Found strangeness of logger setup in server.py.
Server's docstring says that if you put logger=False, it will disable logging of the server.
But on rows 124, 125 there is: ``not logging.root.handlers and self.logger.level == logging.NOTSET`` and that would be ok, if logging.root.handlers  was empty while server initialization. But if I use something like ``logging.basicConfig(level=logging.CRITICAL)`` before server initialization -> ``logging.root.handlers`` will now be ``[<StreamHandler <stderr> (NOTSET)>]`` and condition on row 124, 125 will be False, that cause default logger to live with 0 level of logging -> logging everything. 

Is this a normal behaviour? Should I free the ``logging.root.handlers`` before initialization of socketio server and than repopulate ``logging.root.handlers`` from temporary buffer or put a silent logger to logger kwarg as workaround?

thank you,
best regards

**Comment by miguelgrinberg** [comment]
> and condition on row 124, 125 will be False, that cause default logger to live with 0 level of logging -> logging everything.

Why would then everything be logged? If you call basicConfig then this library makes no changes to the logging set up, so the level that you set in basicConfig should be the level of your logging. At least that was the intent.
