### ISSUE TITLE
Client examples, debugging and auth

### ISSUE THREAD

**Issue by Serkan-devel** [miguelgrinberg/python-socketio#370]
I'm trying to make sense of how to use the client properly, but it doesn't give me any option to debug a connection or explicitly join a room.

What I managed to do was to recreate a client which can contact an example socketio_server grom the repo.

```
import socketio 

sio = socketio.Client() 

@sio.on('disconnect') 
def disconnected():
    print("Disconnected") @sio.on('connect')
def connected():
    sio.emit("my_event", {"data": "I'm connected"}) @sio.on('my_response')
def reciever(data):
    print("Recieved: ",data)

def broadcast(data):
    sio.emit("my_broadcast_event",{"data": data})

def echo(data):
    sio.emit("my_event", {"data": data})

def join(room):
    sio.emit("join", {"room" : room }) 

def leave(room):
    sio.emit("leave", { "leave": room }) 

def send_room(room,data):
    sio.emit("my_room_event", { "room": room, "data": data})

def close_room(room):
    sio.emit("close_room", {"room" : room})

def disconnect():
    sio.emit("disconnect_request")
```

I'd like to see something like that also being documented, but what I couldn't find even on the server-side is a way to authenticate a connection. Does this client even have support to authenticate with a socketio server?

**Comment by miguelgrinberg** [comment]
> doesn't give me any option to debug a connection

You can use the `engineio_logger=True` and `logger=True` options to enable detailed logging.

> or explicitly join a room

Rooms are managed by the server, not the client. The server decides when to put a client in a room.

> but what I couldn't find even on the server-side is a way to authenticate a connection.

You can use your preferred mechanism for authenticating clients. The server gives you access to cookies, headers and query string sent by the client in the connect handler. If you want to refuse access based on the credentials provided you can just return `False` from this handler and the connection will be terminated.
