### ISSUE TITLE
[Question] Multiple workers with Sanic

### ISSUE THREAD

**Issue by snguyenthanh** [miguelgrinberg/python-socketio#371]
I have a Sanic app using `python-socketio`.
The Websocket connection only works with `app.run(workers=1)`; otherwise, `Invalid session ...` is raised.

Although I uses the `AsyncRedisManager` for the `AsyncServer`, the app still doesn't seem to use `redis` to store the sessions:

```
app = Sanic(__name__)

mgr = socketio.AsyncRedisManager("redis://127.0.0.1:6379/0")
sio = socketio.AsyncServer(async_mode="sanic", cors_allowed_origins=[], client_manager=mgr)
sio.attach(app)
```

Is there a way for `python-socketio` to support multiple workers on `Sanic` ?

**Comment by miguelgrinberg** [comment]
Your load balancer needs to be configured for sticky sessions for this to work.

**Comment by snguyenthanh** [comment]
To my understanding, cookies doesn’t work with websocket, so the sticky sessions on the load balancer would need to use *Authorization* header.

Right now, I’m having 1 Sanic app with multiple workers running on a VM machine. Do you think it would be good to set up a load balancer, with sticky sessions, redirecting the requests to a few Sanic apps (each with 1 worker) running in the same machine ?

**Comment by miguelgrinberg** [comment]
@snguyenthanh Sanic does not do sticky session type load balancing when it runs multiple workers, so yes, you have to run multiple one worker Sanic apps, and put a proper load balancer that you can configure for sticky sessions.

**Comment by snguyenthanh** [comment]
I see. Thank you very much for the quick response and advice.

**Comment by snguyenthanh** [comment]
Another question: Why don't storage of SID sessions supports client manager ?

Isn't this way easier for applications to use `redis` (for example) to store all the SID sessions and information, so they could be shared among multiple workers ?

**Comment by miguelgrinberg** [comment]
The workers do not need to share sessions. If you are implying that storing the sessions in Redis would eliminate the need to use sticky sessions, then sure, but the implementation would be very inefficient and also complex, because locking would have to be implemented in access to sessions to prevent two workers from making changes at the same time.

**Comment by snguyenthanh** [comment]
I see. Thank you for the explanation.

I think I will just go with the multiple-1-worker-app approach.
