### ISSUE TITLE
Sanic worker with python-socketio crashes when the client does a hot-reload

### ISSUE THREAD

**Issue by snguyenthanh** [miguelgrinberg/python-socketio#373]
Hi,

I’m using python-socketio with Sanic, and having a client (front-end) running ReactJS (using [react-boilerplate](https://github.com/react-boilerplate/react-boilerplate)).

The Sanic app sometimes crashes when the client performs a hot-reload (when the ReactJS process auto-restarts in `dev` environment to update the newest changes). Here is the error logs retrieved from journalctl, the service’s name is Ora socketio:

```
Oct 31 16:04:39 ora-backend systemd[1]: Stopping Running Ora socketio...
Oct 31 16:04:39 ora-backend python3.7[15005]: [2019-10-31 16:04:39 +0000] [15005] [INFO] Stopping worker [15005]
Oct 31 16:04:39 ora-backend python3.7[15005]: [2019-10-31 16:04:39 +0000] [15005] [ERROR] Experienced exception while trying to serve
Oct 31 16:04:39 ora-backend python3.7[15005]: Traceback (most recent call last):
Oct 31 16:04:39 ora-backend python3.7[15005]:   File "/root/venv/lib/python3.7/site-packages/sanic/app.py", line 1135, in run
Oct 31 16:04:39 ora-backend python3.7[15005]:     serve(**server_settings)
Oct 31 16:04:39 ora-backend python3.7[15005]:   File "/root/venv/lib/python3.7/site-packages/sanic/server.py", line 825, in serve
Oct 31 16:04:39 ora-backend python3.7[15005]:     loop.run_until_complete(asyncio.sleep(0.1))
Oct 31 16:04:39 ora-backend python3.7[15005]:   File "uvloop/loop.pyx", line 1415, in uvloop.loop.Loop.run_until_complete
Oct 31 16:04:39 ora-backend python3.7[15005]: RuntimeError: Event loop stopped before Future completed.
Oct 31 16:04:39 ora-backend python3.7[15005]: Traceback (most recent call last):
Oct 31 16:04:39 ora-backend python3.7[15005]:   File "app_socketio.py", line 6, in <module>
Oct 31 16:04:39 ora-backend python3.7[15005]:     app.run(**SOCKETIO_RUN_CONFIG)
Oct 31 16:04:39 ora-backend python3.7[15005]:   File "/root/venv/lib/python3.7/site-packages/sanic/app.py", line 1135, in run
Oct 31 16:04:39 ora-backend python3.7[15005]:     serve(**server_settings)
Oct 31 16:04:39 ora-backend python3.7[15005]:   File "/root/venv/lib/python3.7/site-packages/sanic/server.py", line 825, in serve
Oct 31 16:04:39 ora-backend python3.7[15005]:     loop.run_until_complete(asyncio.sleep(0.1))
Oct 31 16:04:39 ora-backend python3.7[15005]:   File "uvloop/loop.pyx", line 1415, in uvloop.loop.Loop.run_until_complete
Oct 31 16:04:39 ora-backend python3.7[15005]: RuntimeError: Event loop stopped before Future completed.
Oct 31 16:04:39 ora-backend systemd[1]: ora_socketio.service: Main process exited, code=exited, status=1/FAILURE
Oct 31 16:04:39 ora-backend systemd[1]: ora_socketio.service: Failed with result 'exit-code'.
```

Do you know what the causes are and how to fix this ?

I asked this same question on the forum of `Sanic` and they think this seems to be an issue with `python-socketio`: https://community.sanicframework.org/t/sanic-worker-with-python-socketio-crashes-when-the-client-does-a-hot-reload/436

**Comment by miguelgrinberg** [comment]
The error isn't very explicit unfortunately, it says some task did  not finish, but it does not say which one.

You said you are hot reloading the React app, but really you meant you are reloading the Sanic server, correct? So basically this is triggered when you make a change on the Python side? Unfortunately I don't believe that there is a mechanism by which Sanic informs all running tasks that they need to exit gracefully. This would be the ideal, if Sanic decides to restart it can then give time to all the running tasks to exit.

**Comment by snguyenthanh** [comment]
After debugging and running the worker in `debug` mode, it seems when the worker *crashes*, it only rejects new connections but the current clients still can exchange events with the worker.

However, this issue has been resolved after I put the `Sanic` app behind `Nginx` :)
