### ISSUE TITLE
[Question] Handler sometimes not work with multiple processes of clients 

### ISSUE THREAD

**Issue by klize** [miguelgrinberg/python-socketio#377]
Here is my situation,

Server.py
```python
import eventlet
eventlet.monky_patch(thread=True)

from flask import Flask, request
from flask_socketio import SocketIO

def connect()
    id = request.sid
    l.append(id) 

    sio.emit('test', {'test': len(l) }, room=id)
    sio.sleep(0.1) # Adding or Deleting this line yields the same situation.

... # in some function, emit 'check' message to clients

if __name__ == '__main__':
    global l
    l=[]

    app = Flask(__name__)
    sio = SocketIO(app, logger=True, engineio_logger=True, ping_timeout=60,ping_interval=25, monitor_clients=True)
    sio.on_event('connect', connect)
    sio.run(app, host=args.host, port=args.port, debug=True, use_reloader=False)

```

Client.py
```python
import socketio

def connect()
    print('Connected to the server')

def handle_test(msg):
    print(msg)
    sio.start_background_task(proc_test, msg) # Can be a huge job like ML

def proc_test(msg):
   a['test'] = msg['test']

def handle_check(msg):
    sio.start_background_task(check_test)

def check_test()
   print(a['test'])

...

if __name__ == '__main__':
    global a
    a={}    

    sio = socketio.Client(logger=True, engineio_logger=True)

    sio.on('connect', connect)

    sio.on('test', handle_test)
    sio.on('check, handle_check)

    sio.connect(args.addr, transports=['websocket']) # I use websocket transportation.
    sio.wait()
```

 One more important thing is that server is started on my local and i run 20 different client processes on another machine. 

I expected:
each process has its own number as an id
-------------------- my terminal displays
[client 1] : 0
[client 2] : 1
...
[client 20] : 19
----------------------

the actual is:
when server emits 'check' to clients, some of clients yields KeyError: 'test', but the rest get and set their own number successfully.
----------------- my terminal displays
[client 1] : 0
[client 2] : 1
...
[client 10] -> KeyError: 'test'
..
[client 20] : 19
--------------------

So I turned on the logger on the both side of server and clients.
I figured out the fact that when clients start to connect server, it sends packets of emitting 'test' event to each client successfully, and engineio also receives them. 
But some of clients process fails to execute handle_test, so they have nothing in the dictionary 'a'.
Finally found that the 'handle_test' never starts up by printing 'msg' at the beginning of handler.

The log looks like:
[client 10]
...
Received packet MESSAGE data 2["test",{"test":"9"}]
Received event "test" [/]
Received packet MESSAGE data 0
Namespace / is connected
...

[client 9]
...
Received packet MESSAGE data 2["test",{"test":"8"}]
Received event "test" [/]
Received packet MESSAGE data 0
Namespace / is connected
...

I guess this is not the fault of emit on server machine.
In python-engineio/client.py,  _receive_packet function calls the handler through a background task or calls directly and here comes something wrong: the thread exits immediately or never starts

Could you please give me any advice to try to solve this ?

**Comment by miguelgrinberg** [comment]
It's odd, but I suppose it can happen that the handlers for test and check run at the same time, and the check handler manages to get ahead of the test handler in some of the clients. You aren't really doing anything to ensure these two handlers are synchronized.

You have two options:

1. add `async_handlers=False` to your `SocketIO()` constructor. This ensures that all handlers for a given client are serialized, so basically the second handler will not start until the first returns.

2. implement proper thread synchronization mechanisms to prevent the check handler from getting ahead of the test handler.

**Comment by klize** [comment]
Thank you, I am not sure but it looks the problem is gone almost with the support of sio.sleep().
Moreover, not only the argument you suggested, but I also did ```always_connect=True``` to ensure unexpected issues so that server's ```emit``` executed after clients are connected completely.

This is what the flask-socketio documentation says

**```always_connect ```**– When set to False, new connections are provisory until the connect handler returns something other than False, at which point they are accepted. When set to True, connections are immediately accepted, and then if the connect handler returns False a disconnect is issued. Set to True if you need to emit events from the connect handler and your client is confused when it receives events before the connection acceptance. In any other case use the default of False.

I am not sure above since I need to run 100 or more clients totally( 20 clients per desktop * 5).
As you said option #2, I has a doubt that something like process race condition or thread synchronization may remain to solve but anyway as a result of applying option #1, It looks good. 
i appreciate immediate insight , thank you.

**Comment by miguelgrinberg** [comment]
Yes, the two options that I gave you are two separate ways to address this problem. Adding `async_handlers=False` should take care of the problem, but of course you get less parallelism, since now each client will be limited to handling one event at a time.
