### ISSUE TITLE
Can't exit cleanly with Sanic integration

### ISSUE THREAD

**Issue by joseph-long** [miguelgrinberg/python-socketio#378]
I'm adding socketio support to a Sanic app with

```python
sio = socketio.AsyncServer(
    async_mode='sanic',
    cors_allowed_origins="*", # TODO only CORS in dev
    ping_interval=PING_INTERVAL,
)
sio.attach(app)
```

The app is started by a console script that calls `app.run(host=bind_host, port=bind_port)`.

When I use `Ctrl-C` or `systemctl restart appname`, with websocket connections open, the app never exits and has to be repeatedly `Ctrl-C`ed or killed.
### Buggy output
```
[2019-11-14 14:57:22 -0300] - (sanic.access)[INFO][127.0.0.1:64039]: GET http://127.0.0.1:8000/socket.io/?EIO=3&transport=polling&t=Mvh40Iv&sid=0c54f70a83fc45c6b3776b38b8601f31  200 4
INFO:sanic.access:
^C[2019-11-14 15:03:03 -0300] [9624] [INFO] Stopping worker [9624]
INFO:sanic.root:Stopping worker [9624]
[2019-11-14 15:03:08 -0300] [9624] [INFO] Server Stopped
INFO:sanic.root:Server Stopped
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<AsyncServer._service_task() running at /Users/jlong/miniconda3/lib/python3.7/site-packages/engineio/asyncio_server.py:452> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1040808e8>()]>>
```

### Output where no sockets were open
```
[2019-11-14 15:27:59 -0300] [9732] [INFO] Starting worker [9732]
INFO:sanic.root:Starting worker [9732]
INFO:purepyindi.eventful:Connected to ('::1', 7624, 0, 0)
^C[2019-11-14 15:28:02 -0300] [9732] [INFO] Stopping worker [9732]
INFO:sanic.root:Stopping worker [9732]
[2019-11-14 15:28:02 -0300] [9732] [INFO] Server Stopped
INFO:sanic.root:Server Stopped
```

Does python-socketio register its websocket tasks in the `Sanic.websocket_tasks` list? (https://github.com/miguelgrinberg/sanic/commit/fd823c63aba8b7a74da4660a7e1dfbf4c2a05ea3)

I'm having trouble following exactly how `sio.attach` operates, but since that Sanic commit is by the same author it seems likely it does—meaning there's something else I'm missing. (Incidentally, thanks for your work! Impressive library.)

**Comment by joseph-long** [comment]
Hmm. It just occurred to me that this could be due to the polling transport in use. I haven't dug in to why I'm (apparently?) not getting real WebSocket connections, yet.

**Comment by joseph-long** [comment]
Alas... I'm not the first https://github.com/miguelgrinberg/python-socketio/issues/189

**Comment by miguelgrinberg** [comment]
The websocket_tasks support happens at the Sanic level, this package does not need to do anything to be part of that. The problem seems to be with the service_task. I don't know if there is a mechanism for Sanic to inform background tasks that they need to exit, that's what is needed here.

**Comment by joseph-long** [comment]
Can you suggest where I should look to see how the service_task gets set up? If I can hack it so that I retain a reference to it, I can cancel it with my other background tasks `before_server_stop`

**Comment by miguelgrinberg** [comment]
The service task is started here: https://github.com/miguelgrinberg/python-engineio/blob/master/engineio/server.py#L490-L493.

Unfortunately I'm not storing a reference to this task at this time.

**Comment by miguelgrinberg** [comment]
Feel free to submit a PR if you have an improvement to propose.

**Comment by joseph-long** [comment]
Update: I solved this, but my solution isn't really a solution for Sanic. I migrated to Starlette, which seems to follow the consensus ASGI API, and by composing with `socketio.ASGIApp` I got the clean shutdown behavior I wanted.
