### ISSUE TITLE
Emit-ing data from Python server takes upwards of 30 seconds to be sent to client

### ISSUE THREAD

**Issue by tmello01** [miguelgrinberg/python-socketio#379]
I have a python-socketio client running locally (with aiohttp as a webserver). After loading, I do some operations, then try and emit some data to the client, but it can take from 30 seconds to a few minutes to actually be received by the client (javascript socketio). 

Here is the python server setup:
```python
sio = socketio.AsyncServer(cors_allowed_origins='*')
app = web.Application() #aiohttp web server
loop = asyncio.get_event_loop()
sio.attach(app)

async def index(request):
    with open('./index.html') as f:
        return web.Response(text=f.read(), content_type='text/html')

app.router.add_get('/', index)
app.router.add_get('/index.html', index)

if __name__ == '__main__':
    web.run_app(app)
```

and the event is being fired like so (from a synchronous function, so I had to use event loops):
```python
print('Starting event')
loop = asyncio.new_event_loop()
asyncio.set_event_loop(loop)
loop.run_until_complete(sio.emit('ChangeProgressState'))
loop.close()
print('Event has been fired.')
```
I am consuming this event on the client side like so:
```javascript
const socket = io.connect("http://localhost:8080", {
      transports: ['websocket']
})

socket.on("ChangeProgressState", function (data) {
    console.log("got event.")
    //some code here...
});
```

I believe this issue to be on the serverside. I can send messages from the client to server with sub-1second response time, but not the other way around. Any help would be much appreciated.

**Comment by miguelgrinberg** [comment]
Are you using a different loop to do the emit? That's not going to work, you have to emit from within the same loop where the server is running.

**Comment by tmello01** [comment]
Would that be what is causing the stark delay? 

From my experience, since the server is running on the main thread, it doesn't like trying to use asyncio loops there. Should I have my whole server outside the main thread?

**Comment by tmello01** [comment]
Alright, I'll leave this here for future generations. 

@miguelgrinberg was correct, the methods have to be run in the same event loop as the server. However, this causes an issue, as the default asyncio libraries do not allow for run_until_complete on an already running event loop, it gives the error: `RuntimeError: This event loop is already running.`

However, this problem is prevalent enough that there is a seperate library that essentially monkey patches the asyncio library to allow this to work. I found it in the issues of a different python github page:

https://github.com/spyder-ide/spyder/issues/7096#issuecomment-449655308

This now works as expected, but perhaps we can get a change that allows for server communication outside of the server event loop?

**Comment by miguelgrinberg** [comment]
Instead of monkey patching asyncio, why don't you use `sio.start_background_task()`?

**Comment by tmello01** [comment]
@miguelgrinberg using that method still causes the `RuntimeError: this event loop is already running!` error.

**Comment by miguelgrinberg** [comment]
@tmello01 I need to see your code and the full stack trace of the error please.

**Comment by tmello01** [comment]
@miguelgrinberg 

Relevant code:
```python
sio = socketio.AsyncServer(async_mode='aiohttp', async_handlers=False, cors_allowed_origins='*')
main_event_loop = asyncio.get_event_loop()

def DoSendBatteryUpdate(arg1):
    main_event_loop.run_until_complete(sio.emit('BatteryUpdate', arg1))

def DoHandleBatteryUpdate(arg1):
    sio.start_background_task(DoSendBatteryUpdate(arg1)) 
```


Stack Trace:
```python
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/DeIcerMain/hardware.py", line 147, in OnHandleCharging
    HandleBatteryCharging()
  File "/home/pi/DeIcerMain/hardware.py", line 197, in HandleBatteryCharging
    pub.sendMessage('BatteryUpdate', arg1=batteryPercentage)
  File "/usr/local/lib/python3.5/dist-packages/pubsub/core/publisher.py", line 216, in sendMessage
    topicObj.publish(**msgData)
  File "/usr/local/lib/python3.5/dist-packages/pubsub/core/topicobj.py", line 452, in publish
    self.__sendMessage(msgData, topicObj, msgDataSubset)
  File "/usr/local/lib/python3.5/dist-packages/pubsub/core/topicobj.py", line 482, in __sendMessage
    listener(data, self, allData)
  File "/usr/local/lib/python3.5/dist-packages/pubsub/core/listener.py", line 237, in __call__
    cb(**kwargs)
  File "socket_server.py", line 45, in DoHandleBatteryUpdate
    sio.start_background_task(DoSendBatteryUpdate(arg1))
  File "socket_server.py", line 42, in DoSendBatteryUpdate
    main_event_loop.run_until_complete(sio.emit('BatteryUpdate', arg1))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 454, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 408, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
```

**Comment by miguelgrinberg** [comment]
Your `DoSendBatteryUpdate` function is trying to run the asyncio loop, but the loop is already running.

**Comment by tmello01** [comment]
Hi Miguel,

I've come back around to this recently. sio.start_background_task works great when running from the main thread, but when running from other threads (in order to avoid blocking the websever thread), there are issues with there being no event loop on that thread. Starting an event loop and setting it as an event loop creates issues with events not sending correctly. 

Here is a sample method to send an event to the client:

```python
def HandleBatteryUpdate(arg1):
    global current_battery_percentage
    current_battery_percentage = arg1
    event_loop = asyncio.new_event_loop()
    asyncio.set_event_loop(event_loop)
    sio.start_background_task(DoBatteryUpdate, arg1)

async def DoBatteryUpdate(arg1):
    await sio.emit('BatteryUpdate', arg1)
```

However, when this runs, this error appears:

```python
Task was destroyed but it is pending!
task: <Task pending coro=<DoBatteryUpdate() running at /home/pi/t/webserver.py:270>>
```

Is there a way around this? Or must I run every event on the main thread/loop?

**Comment by miguelgrinberg** [comment]
When you use the asyncio Socket.IO server all your Socket.IO related activities need to be done within the same event loop and thread. Asyncio does not support multithreading, so if you allocate more threads those cannot do anything related to the Socket.IO server.

**Comment by tmello01** [comment]
Gotcha. I'll have to start some king of queuing system on the main thread to that will handle the event sending for me. Thanks for the help, this issue can be considered closed.

**Comment by tmello01** [comment]
Or would you suggest using one of the messaging queue services as opposed to trying to force python-socketio to work to my desires?

**Comment by miguelgrinberg** [comment]
@tmello01 I really cannot say, since I don't know exactly what you are looking for. What I can tell you is that asyncio packages do not work nicely with threads, in general you use async or threads, not both. The exception can be using a thread executor to put some code in threads in a way that does not affect the asyncio app.

**Comment by gwendalF** [comment]
Hello,

I think I have the same issue. I do not master python async/await and review some code where the issues is the same.
Previously, it was working with the huge delay.
Here is how the server is defined:
`sio = socketio.AsyncServer(
    logger=(not args.quiet), async_handlers=False, cors_allowed_origins="*"
)

app = web.Application()
sio.attach(app)`

I have a workspace where I need to put my event emit function:
`@sio.event
def connect(sid: str, _environ, _auth):
    print("connect", sid)
    if sid not in workspaces:
        workspaces[sid] = Workspace(partial(send_event, sid), logger)`
And the send_event function:

`def send_event(sid: str, event: str, data: tuple):
    if event in ["connect", "disconnect", "message"]:
        print("Invalid event name")
        return
    asyncio.run(sio.emit(event=event, data=data, to=sid))`

I have tried to use the sio.start_background_task method as follow:
`async def event_handler(sid: str, event: str, data: tuple):
    if event in ["connect", "disconnect", "message"]:
        print("Invalid event name")
        return
    await sio.emit(event=event, data=data, to=sid)


def send_event_bis(sid: str, event: str, data: tuple):
    sio.start_background_task(event_handler, sid, event, data)`
and change my workspace:

`workspaces[sid] = Workspace(partial(send_event_bis, sid), logger)`

However I received an error saying my event_handler was never awaiter:
`[2] RuntimeError: There is no current event loop in thread 'Thread-1'.
[2] C:\Users\Gwendal\AppData\Local\Programs\Python\Python38\lib\threading.py:934: RuntimeWarning: coroutine 'event_handler' was never awaited
[2]   self._invoke_excepthook(self)
[2] RuntimeWarning: Enable tracemalloc to get the object allocation traceback`

How can I handle this?
Thanks in advance

**Comment by miguelgrinberg** [comment]
@gwendalF My suggestion is that if you do not have experience with asyncio then you do not use it. You are doing things that really make no sense, such as calling `asyncio.run()` to run an asynchronous function.

**Comment by gwendalF** [comment]
@miguelgrinberg Yes thanks, looking deeper in the code I found it's using thread which are incompatible with asyncio so it might be the issue here. I will look deeper with the person who acutally wrotes the code to solve this issue. Thanks for your help
