### ISSUE TITLE
SocketIO: Order of messages

### ISSUE THREAD

**Issue by vldpro** [miguelgrinberg/python-socketio#382]
Hello, I have a problem with delivering messages using SocketIO in correct order.

For example, I have a stream of data which should be delivered from one client to another in correct order. I've seen the source code of `socketio.Client` class, and understood that for each message on socket new thread starts. So, if each message in its own thread, there is a possibility that event handler for `N + 1` message can be executed before `N` message.

Is there a way to send messages in correct order?

**Comment by miguelgrinberg** [comment]
Messages are sent in the correct order. If your handlers run for too long there is always the possibility that the handler for message N and N+1 run concurrently, and then depending on what each handler does the N+1 handler may get ahead. You can use standard synchronization primitives to prevent this.
