### ISSUE TITLE
C# client and handshake problems

### ISSUE THREAD

**Issue by kpoman** [miguelgrinberg/python-socketio#383]
Hello Miguel,
I run a Flask SocketIO server and am able to connect with browser's javascript code. However, I am trying to build a C# .Net app and am getting Handshake errors. I can't use gevent or eventlet in my case as the app is pretty multithreaded (lot of ctypes c modules), so I need to fallback to socket.io and not websockets. There are not many C# libs for direct socket.io connections. Do you know of some compatible ones or examples somewhere ?
Thank you !

**Comment by kpoman** [comment]
BTW I am using this one: SocketIO4Net.Client from https://archive.codeplex.com/?p=socketio4net
The client code is: 

         ```
   CaptureData response = instance.SensorUuidCaptureGet(selectedSensorUUID);
            socket = new Client(selectedSensorSocketURL);
            socket.On("connect", (fn) =>
            {
                Console.WriteLine("connected event");
            });
            socket.Connect();
```
The error from the client side is:

Error Event: Error initializing handshake with http://localhost:12321/
	System.Exception: Exception of type 'System.Exception' was thrown.
The thread 0x652c has exited with code 0 (0x0).

And on Flask I do see the connection being established: 

sio connection established from 127.0.0.1:64077 to 0.0.0.0:12321 with sid a09ec39bb7ce40a79d52f6767bc3de3c
disconnect  a09ec39bb7ce40a79d52f6767bc3de3c

**Comment by kpoman** [comment]
And last but not least, here is the TCP trace:

GET /socket.io/1/ HTTP/1.1
Host: localhost:12321
Connection: Keep-Alive

> HTTP/1.0 200 OK
> Set-Cookie: io=41473b05027949779f03236685b779d2
> Content-Type: application/octet-stream
> Access-Control-Allow-Credentials: true
> Connection: close
> Server: Werkzeug/0.16.0 Python/3.7.5
> Date: Wed, 20 Nov 2019 08:55:41 GMT
> 
> .	..0{"sid":"41473b05027949779f03236685b779d2","upgrades":[],"pingTimeout":60000,"pingInterval":25000}...40
> 

Seems like python's socketio is responding correctly, thus my question: do you know of a compatible C# lib ?

**Comment by miguelgrinberg** [comment]
Looks like the client library that you are using only supports the WebSocket transport. The Python server only supports WebSocket when you use it together with an asynchronous framework, so without eventlet or gevent your server can only do HTTP long-polling, which your client does not appear to support.

I'd recommend that you confirm this by creating a small eventlet or gevent example, just to confirm that your C# client can connect that way.

**Comment by kpoman** [comment]
Miguel, it is indeed trying upgrade to WebSocket support, at least reading at their source code. The simple lib I tried to use comes from this guy on medium explaining what a pain it is to run socket.io client on dotnet nowadays: https://medium.com/@it9gamelog/socket-io-a-c-client-library-be9bdc1eb6ab

For what I am trying to do, which failed using at least eventlet (weird bugs and non-launching sockets), is that I have an API that creates capture devices (say, webcams), and once created, gives the viewer a websocket where to see the live stream. I launch that socket.io stream on a new thread. And this is why I need something compatible with common python threads.

The code that is triggered when I create a device is here below:


```
   def build_socketio_target(self, options):
        import logging
        log = logging.getLogger('werkzeug')
        log.setLevel(logging.ERROR)
        sio = socketio.Server(logger=False, async_mode='threading', cors_allowed_origins='*')
        app = Flask(__name__) #socketio.WSGIApp(sio)
        app.wsgi_app = socketio.WSGIApp(sio, app.wsgi_app) #app.sio = sio
        app.sio = sio
        CORS(app)

        @sio.on('connect')
        def connect(sid, environ):
            print('socket.io connection established from %s:%s to %s:%s with sid %s'%(\
                    environ['REMOTE_ADDR'], environ['REMOTE_PORT'],\
                    environ['SERVER_NAME'], environ['SERVER_PORT'],\
                    sid))

        @sio.event
        def my_message(sid, data):
            print('message ', data)

        @sio.event
        def disconnect(sid):
            print('disconnect ', sid)

        return app

    def append_target(self, target_name, target_type='socketio', target_options={}):
        if target_name not in self.attached_targets:
            if target_type == 'socketio':
                target = self.build_socketio_target(target_options)
                if 'port' in target_options:
                    # @TODO: check if the port is free otherwise chose a random one
                    port = target_options['port']
                else:
                    port = 5000
                host = '0.0.0.0' # or specify if restricted
                #t = threading.Thread(target=eventlet.wsgi.server, args=(eventlet.listen(('', port)), target))
                t = threading.Thread(target=target.run, args=(), kwargs={'threaded':True, 'host':host, 'port':port})
                t.start()
            self.attached_targets[target_name]  = target

```

**Comment by miguelgrinberg** [comment]
Websocket is actually not particularly better than HTTP to deliver video streams. I suggest you look at a standard HTTP streaming endpoint, which you can implement with Flask/Python or most other HTTP frameworks.
