### ISSUE TITLE
SocketIO signal issue

### ISSUE THREAD

**Issue by w8eight** [miguelgrinberg/python-socketio#387]
Hi,

I am trying to run some application using python-socketio as Windows Service and while executing this line into cmd: 'python myapplication.py start' I am getting following error. 

`  File "C:\Users\w23209\Documents\Subversion\Webservice\Digital Factory Web Service\src\frontend\server.py", line 14, in <module>
    from socketio.server import Server
  File "C:\Users\w23209\Documents\Subversion\Webservice\venv\Lib\site-packages\socketio\__init__.py", line 3, in <module>
    from .client import Client
  File "C:\Users\w23209\Documents\Subversion\Webservice\venv\Lib\site-packages\socketio\client.py", line 6, in <module>
    import engineio
  File "C:\Users\w23209\Documents\Subversion\Webservice\venv\Lib\site-packages\engineio\__init__.py", line 3, in <module>
    from .client import Client
  File "C:\Users\w23209\Documents\Subversion\Webservice\venv\Lib\site-packages\engineio\client.py", line 49, in <module>
    original_signal_handler = signal.signal(signal.SIGINT, signal_handler)
  File "C:\Program Files\Python37\Lib\signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread 
%2: %3`

Any idea what can cause such error?

Python 3.7.4, running from virtualenv

**Comment by miguelgrinberg** [comment]
What webserver are you using? Can you show me the code that runs as a response of the `start` argument passed into your script?

**Comment by w8eight** [comment]
> What webserver are you using? Can you show me the code that runs as a response of the `start` argument passed into your script?

I am using pywin32 hadnle 'start':
`win32serviceutil.HandleCommandLine(MyService)`
MyService is class inheriting from 'win32serviceutil.ServiceFramework'

Inside Myservice class SvcDoRun function starts actual server. 

`
import bottle
from socketio.server import Server

class GeventSocketIOServer(bottle.ServerAdapter):
    def run(self, handler):
        address = (self.host, self.port)
        self.srv = Server(address, handler, **self.options)
        try:
            log.debug('serve forever')
            self.srv.serve_forever()
            log.debug('stopped serve forever')
        except KeyboardInterrupt:
            self.srv.close()
            raise
`

**Comment by miguelgrinberg** [comment]
Thanks. I've written https://github.com/miguelgrinberg/python-engineio/issues/147 to keep track of this issue, so I'll close this one here.
