### ISSUE TITLE
WebSocket transport issue when eventlet.monkey_patch() is used

### ISSUE THREAD

**Issue by funoverip** [miguelgrinberg/python-socketio#388]
Hi,

I've created a client code to connect to my Web server app (the server side use flask_socketio / nginx).

My client can connect and upgrade from polling to websocket without problem. But as soon as I use the monkey_patch, the WebSocket transport fails.

My client code:

```
$ cat test.py 
#!/usr/bin/env python3
#import eventlet
#eventlet.monkey_patch()
import sys
import os
import json
import socketio

sio = socketio.Client(logger=True, engineio_logger=True)
sio.connect('https://<snip>', namespaces=['/signal'])
```

Output without monkey_patch:

```
$ ./test.py 
Attempting polling connection to https://<snip>/socket.io/?transport=polling&EIO=3
Polling connection accepted with {'pingTimeout': 60000, 'pingInterval': 25000, 'upgrades': ['websocket'], 'sid': 'f33d3d0a35534a0c92671f91c6b9c7c9'}
Engine.IO connection established
Received packet MESSAGE data 0
Namespace / is connected
Sending packet MESSAGE data 0/signal
Attempting WebSocket upgrade to wss://<snip>/socket.io/?transport=websocket&EIO=3
WebSocket upgrade was successful
Sending packet PING data None
Received packet NOOP data None
Received packet MESSAGE data 0/signal
Namespace /signal is connected
Received packet PONG data None
Sending packet PING data None
Received packet PONG data None
Sending packet PING data None
...

```

And now with Monkey_patch:

```
$ ./test.py 
Attempting polling connection to https://<snip>/socket.io/?transport=polling&EIO=3
Polling connection accepted with {'sid': '5ca970fd518e4e1ab7ae4584ce95f64f', 'pingInterval': 25000, 'upgrades': ['websocket'], 'pingTimeout': 60000}
Engine.IO connection established
Received packet MESSAGE data 0
Namespace / is connected
Sending packet MESSAGE data 0/signal
Attempting WebSocket upgrade to wss://<snip>/socket.io/?transport=websocket&EIO=3
Traceback (most recent call last):
  File "./test.py", line 12, in <module>
    sio.connect('https://<snip>', namespaces=['/signal'])
  File "/tmp/myenv/lib/python3.5/site-packages/socketio/client.py", line 268, in connect
    engineio_path=socketio_path)
  File "/tmp/myenv/lib/python3.5/site-packages/engineio/client.py", line 184, in connect
    url, headers, engineio_path)
  File "/tmp/myenv/lib/python3.5/site-packages/engineio/client.py", line 322, in _connect_polling
    if self._connect_websocket(url, headers, engineio_path):
  File "/tmp/myenv/lib/python3.5/site-packages/engineio/client.py", line 366, in _connect_websocket
    cookie=cookies)
  File "/tmp/myenv/lib/python3.5/site-packages/websocket/_core.py", line 514, in create_connection
    websock.connect(url, **options)
  File "/tmp/myenv/lib/python3.5/site-packages/websocket/_core.py", line 223, in connect
    options.pop('socket', None))
  File "/tmp/myenv/lib/python3.5/site-packages/websocket/_http.py", line 120, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "/tmp/myenv/lib/python3.5/site-packages/websocket/_http.py", line 189, in _open_socket
    raise error
  File "/tmp/myenv/lib/python3.5/site-packages/websocket/_http.py", line 172, in _open_socket
    sock.connect(address)
  File "/tmp/myenv/lib/python3.5/site-packages/eventlet/greenio/base.py", line 248, in connect
    while not socket_connect(fd, address):
  File "/tmp/myenv/lib/python3.5/site-packages/eventlet/greenio/base.py", line 44, in socket_connect
    raise socket.error(err, errno.errorcode[err])
OSError: [Errno 101] ENETUNREACH
```

```
$ pip3 freeze
certifi==2019.11.28
chardet==3.0.4
dnspython==1.16.0
eventlet==0.25.1
greenlet==0.4.15
idna==2.8
monotonic==1.5
netifaces==0.10.6
pkg-resources==0.0.0
python-engineio==3.10.0
python-socketio==4.4.0
requests==2.22.0
six==1.13.0
urllib3==1.25.7
websocket-client==0.56.0
```
Any advice ?

Thank you very much !

**Comment by funoverip** [comment]
Wait, I have disabled CloudFlare and now that I use a direct connection with my server, the problem seems gone.
Could it be a simple sticky session issue ?

**Comment by miguelgrinberg** [comment]
Monkey patching should not affect the client, but do you really need eventlet in your client at all? I suggest you remove it if you don't have it there for a specific reason.

**Comment by funoverip** [comment]
Hi,

Thanks for your answer.
I need the monkey patching because this code also use flask-socketio .

Anyway, my issue was a mix of CloudFlare and CORS configuration. 
Apologies for the wasted time.

**Comment by funoverip** [comment]
Hi, 
I know this issue is probably not related to the implementation of `python-socketio` but I still can' make my test socketio client to work with monkey_patch + cloudflare.  As soon as I disable cloudflare (by altering the DNS I mean), it works like a charms. I have absolutely no idea why.

**Comment by miguelgrinberg** [comment]
@funoverip can you be more specific about how you are using cloudflare? Is this something you are doing in the Python process, or just some external configuration on your server box?

**Comment by funoverip** [comment]
Hi,

Here is the setup:
- I run a main website under `flask` + `flask_socketio` + `nginx`. Only one worker for now. With or without Cloudflare , everything works great (I mainly tested under Chrome so far)

- On top of browser usage, I want to give CLI interaction with the website and therefore, created this little Python client code based on `python-socketio` client. As soon as I use eventlet monkey patch, this client fails to connect to my webserver , only when Cloudflare is used. 

PS: I don't have any lines of code related to Cloudflare in my python code. Cloudflare is only working as reverse proxy between my client and nginx.
 
Right now I try to re-verify everything because no one on Internet has reported similar issue. And since it work great with chrome, I guess Cloudflare isn't really the problem. I keep searching..

**Comment by miguelgrinberg** [comment]
I still don't understand why you enable eventlet when you run your client. You just mentioned it is a CLI process, so clearly it is not running in the same process as the server. My recommendation is that you use eventlet in the server, but not in the client.

**Comment by funoverip** [comment]
Sorry for the lack of information,

Actually, this CLI also run a local webapp on the client workstation, accessed via https://localhost:xxxx. 

This "client" code use both` python-socketio `to get data from the main web site, and `flask_socketio` to serve data to the user browser. I know it sounds strange but this client app holds some secret keys of 3rd party app, that we don't want to store on the main server for security reasons. So we provide to the client, a kind of extension of the main website, which run locally on his workstation.

So this "client" is both a websocket client AND server. And for that, I need eventlet .

**Comment by miguelgrinberg** [comment]
The error that you are getting isn't very telling, but one possible issue might be with SSL, which is known to be a bit unstable under eventlet. Delegating the client portion to a subprocess could help, since the subprocess would not be bound to eventlet.
