### ISSUE TITLE
How use socketio decorator within another class

### ISSUE THREAD

**Issue by sraboncmc** [miguelgrinberg/python-socketio#390]
Hi Miguel
I tried to use socketio.Client within a class where i can call socketio and its related event frequently.But dnt understand how figure out it.
It works fine on normal python file.

i m a part time coder,so plz dnt laugh on my coding.
Thanks in advance.
```python
import socketio

class warSock:

    global mwar
    global name
    global ps
    mwar = socketio.Client()

    def __init__(self, name, ps):
        self.name = name
        self.ps = ps

    @mwar.event
    def connect(self):
        print('connected to server')

    @mwar.on('login')
    def on_login(data):
        print data

    def connectme(self):
        mwar.connect('http://localhost')

    def dc(self):
        mwar.disconnect()
```

**Comment by miguelgrinberg** [comment]
What part of this does not work? The only thing I noticed is that the on_login method is missing `self`.

As a side note, you may want to look at class-based namespaces in the documentation, as they already provide a way to implement events as methods in a class.

**Comment by sraboncmc** [comment]
Thanks for your reply.
Problem was from here

> @mwar.event
    def connect(self):
        print('connected to server')

sio wants connect(), but here class wants connect(self)
thats why sio call argument typeError (something like this)

**Comment by sraboncmc** [comment]
And i think i sort out this by putting all sio related events inner function(def) of class def. And it works still.
And So much thanks for your great creation.I tried it 9 month earlier,bt i failed to connect single one.
may be i failed to understand the concept of decorator.

I have a request for connection establishment. It got hang on ide as like httplib connection.
I used socketio js and java client.Those are faster.

**Comment by Zartris** [comment]
This might be old and you have solved it.
If you don't need the self functionality in connect just make it static like this:
    
@staticmethod
@mwar.event
def connect():
     print('connection established')

**Comment by Robokishan** [comment]
i know this is old but i wanted to have this kind of functionality and i have done this

# # socketIO.wait(seconds=1)
```
import socketio
import json

class Wrapper_class():
        sio = socketio.Client()

        def __init__(self):
            pass
        def setup(self):
            self.call_backs()
            self.sio.connect('http://localhost.local:8081')

        def loop(self): 
            self.sio.wait()

        def call_backs(self):
            @self.sio.event
            def connect():
                self.sio.emit('subscribe','room')
                print('connection established')
                
            @self.sio.on("docs")
            def raw_data(data):
                print(f"Data Received {data}")


            @self.sio.event
            def auth(data):
                print(f"Data Received {data}")


            @self.sio.event
            def disconnect():
                print('disconnected from server')
        def run(self):
            self.setup()
            self.loop()

wrapper = Wrapper_class()
wrapper.run()
```

**Comment by paulbuer** [comment]
@Robokishan 
wrapper = Wrapper_class()
wrapper.run()

Sorry for this noob questions, I'm a python beginner. 
1) How to send events declared inside call_backs function to the socketio server using the wrapper instance? How to invoke? 
2) Will self.loop() blocks until disconnect event happens? If there is code after wrapper.run(), will it also be blocked until the socket connection ended? 
3) What if I want to have multiple namespaces, can I connect them all first like this (see below)? And afterwards, I can emit to any namespace since they're all connected with the same sid? 
4) Then if there is code after wrapper.run(), let's say I want to emit to a specific namespace, can I use: 
`wrapper.<function_to_call_with_the_emit_command_to_server>`? And then return a response message status?
5) How to detect if self.loop() was ended (socket disconnected) in the wrapper instance? What to do with the wrapper.run() ?

```
class Wrapper_class():
    sio = socketio.Client(logger=True, engineio_logger=True)
    latest_status = None
    namespaces = ['/', '/info']

    def __init__(self, url, headers=None, auth=None):
        self.url = url
        self.headers = dict() if not headers else headers
        self.auth = auth

    def setup(self):
        self.call_backs()
        self.sio.connect(self.url, headers=self.headers, auth=self.auth, namespaces=self.namespaces)

    def loop(self):
        self.sio.wait()

     def call_backs(self):
         ....
```

**Comment by miguelgrinberg** [comment]
@paulbuer My suggestion is that you first make your client work in the standard way. Once you have it working, many of your questions will be more clear to you. Also, let me mention one more time that this package has class-based namespaces for implementing the client in a class. Maybe that is enough for your needs and you don't need to invent a new wheel for this.

**Comment by paulbuer** [comment]
@miguelgrinberg 
Thank you so much for your response. I will do what you said and more power to you sir. 
I also saw `flask-sock`, your recent project. I would definitely try in the next release.
