### ISSUE TITLE
socketio - sync client on diffrent threads

### ISSUE THREAD

**Issue by zur250** [miguelgrinberg/python-socketio#392]
Hi Miguel,
i came into a serious issue on my project.
After debugging the problem i found that the main issue is that each socketio sync client event is on diffrent thread( no clue why).
example:
```python
 @sio.on('scan_page')
    def startScan(scanParams):  # start scan method, the server needs to provide urls to scan
        configScanBoundary = ScanBoundary.deserialize(scanParams)
        print("thread: "+str(threading._get_ident()))
        clientLogicService.startScan(pageEntity=configScanBoundary.getPageEntity(),
                                     sessionEntity=configScanBoundary.getSessionEntity())
        sio.emit('scan_page_done')
        return
```
The code above make the call to `startScan` function ( inside `clientLogicService object`) on diffrent thread.
this cause my app to lose some syncing which I did not expect.
Any idea how can i force all the socketio module to run on the same thread?

Thanks for the help!

**Comment by miguelgrinberg** [comment]
Each event handler is invoked on a new thread, this has always been this way. It is exactly like it is done in Flask, where also each view function is invoked within a new thread. Why is that a problem?

**Comment by zur250** [comment]
The problem is i am using a singletone object that once created cant be removed ( PYQT4 QApplication object).
At the first time `startScan` event calls `startScan` everything works good.
But at the second time, since the QApplication object allready intialized and cant be destroyed, the program crashed with the error that : QApplication object `exec` function cannot be called on another thread.
Is there any way to make the event come from the same thread?

**Comment by miguelgrinberg** [comment]
You can create your own long-lived thread for this if that is required by your application. The server is constantly creating and destroying threads.

**Comment by zur250** [comment]
by create my own long-lived thread you mean that i will manage a thread that his run method runs forever and pool from a queue the `startScan` event params?

**Comment by miguelgrinberg** [comment]
@zur250 Yes, that would be a good solution for your problem.

**Comment by zur250** [comment]
I am tring to implement it. Any idea how can i make sure that the current sockio Event( the incoming thread) is finished before leaving the CPU?

**Comment by miguelgrinberg** [comment]
@zur250 What do you mean exactly by "before leaving the CPU"? If the last thing you do in this thread is add an entry to a queue, then the function will exit once the queue is updated. Isn't this sufficient for your needs?

**Comment by zur250** [comment]
it is, i will try first
