### ISSUE TITLE
How can I enter room by client?

### ISSUE THREAD

**Issue by neosarchizo** [miguelgrinberg/python-socketio#396]
I read [the docs](https://python-socketio.readthedocs.io/en/latest/intro.html#client-examples). But I couldn't find how to enter room by client. I think client doesn't have a function to enter room.
Right?

**Comment by miguelgrinberg** [comment]
The client doesn't have access to rooms, only the server does. The client can request to the server to be added to a room, and then the server can decided if the client is allowed into the room and actually add the client if approved.

**Comment by neosarchizo** [comment]
I understand!!
