### ISSUE TITLE
Access cookies on the http upgrade request

### ISSUE THREAD

**Issue by johnyburd** [miguelgrinberg/python-socketio#398]
I'd like to access some cookies on the original http upgrade request in order to do some authentication.  Is there any mechanism for accessing these or do I need to modify the driver?  I'm using aiohttp.

**Comment by miguelgrinberg** [comment]
Are you doing this in the `connect` handler? This handler gets the `environ` dictionary. You can access the aiohttp request object as `environ['aiohttp.request']`.

If you are doing this in another event, use `sio.environ[sid]['aiohttp.request']` to get the request.

**Comment by johnyburd** [comment]
yeah I'm using the `connect` handler.  `environ['aiohttp.request']` is what I needed.

thanks!
