### ISSUE TITLE
What's the equivalent version of socketio.js 0.9.17?

### ISSUE THREAD

**Issue by yvdjee** [miguelgrinberg/python-socketio#399]
The server uses 0.9.17 (JS) and there's no way to connect using the latest version.

**Comment by miguelgrinberg** [comment]
Sorry, this package implements the protocol starting at Socket.IO 1.0. For 0.9.x I suggest you look at old releases of [socketio-client](https://github.com/invisibleroads/socketIO-client), maybe you can find one that works.

**Comment by yvdjee** [comment]
Thank you man, will look into it
