### ISSUE TITLE
rooms() doesn't return previous rooms after client disconnection

### ISSUE THREAD

**Issue by EpicEric** [miguelgrinberg/python-socketio#400]
Hi! I'm currently using [Flask-SocketIO](https://github.com/miguelgrinberg/Flask-SocketIO) and it's pretty great so far!

There was one error in my logic when a client joins/leaves rooms, where I tried to call `flask_socketio.rooms()` on a disconnect event, and it wasn't returning all rooms the client had joined up to the disconnection. When inspecting it, it only showed the default sid room -- which makes sense if the client is considered to have been removed from these rooms before the event handler is called.

Still, I had to add custom logic in my application to update/persist the rooms prior to the client disconnecting, and get the list of rooms from a custom map instead of calling `rooms()` to solve my problem. It'd be better if we could get the rooms that the client had joined up to this point, or if this behavior (`rooms() will only return the client's sid if it has already disconnected`) was documented for python-socketio and Flask-SocketIO.

**Comment by miguelgrinberg** [comment]
This problem was addressed long ago, closing.
