### ISSUE TITLE
Flushing multiple messages once

### ISSUE THREAD

**Issue by ericman93** [miguelgrinberg/python-socketio#406]
I have a problem that I'm sending too many messages to the client, that the client can't handle that amount.

I was wondering if there is a flushing mechanism that I can you to send multiple messages in one WebSocket event, or should I implement it

**Comment by miguelgrinberg** [comment]
Unfortunately the Socket.IO protocol does not provide any grouping mechanism for multiple events in the WebSocket transport. Interestingly it does when using long-polling over HTTP.

So yes, this should be implemented at the application layer.
