### ISSUE TITLE
Unexpected status code 400 in server response, client not reconnect 

### ISSUE THREAD

**Issue by pykiwi** [miguelgrinberg/python-socketio#407]
I used python-socketio for Raspberry pi.When server response 400, client not reconnect.
How to client auto reconnect ?
Code:
`sio_client = socketio.Client(ssl_verify = False, engineio_logger = True, logger = True)`
`sio_client.connect("https://abcxyz.com:3445", namespaces = name_space)`

Log:
`Thg 1 13 12:50:40 raspberrypi main[560]: HTTP GET request to https:/abcxyz.com:3445/socket.io/?transport=polling&EIO=3&sid=x0vH0OBvwmcKlzLmAAA3&t=1578894610.6793702 failed with error HTTPSConnectionPool(host='abcxyz.com', port=3445): Read timed out. (read timeout=30.0).`
`Thg 1 13 12:50:40 raspberrypi main[560]: Connection refused by the server, aborting`
`Thg 1 13 12:50:40 raspberrypi main[560]: Waiting for write loop task to end`
`Thg 1 13 12:50:43 raspberrypi main[560]: Unexpected status code 400 in server response, aborting`
`Thg 1 13 12:50:43 raspberrypi main[560]: Exiting write loop task`
`Thg 1 13 12:50:43 raspberrypi main[560]: Waiting for ping loop task to end`
`Thg 1 13 12:50:43 raspberrypi main[560]: Exiting ping task`
`Thg 1 13 12:50:43 raspberrypi main[560]: Exiting read loop task`

Dependencies:
`Python : 3.7.3`
`python-socketio : 4.4.0`
`engineio : 3.11.2`

**Comment by miguelgrinberg** [comment]
The 400 code implies the user sent a bad request. There is no point in retrying that without addressing what caused the error. Do you know what caused this 400?

**Comment by pykiwi** [comment]
I think my internet connection is down. However, after running the program in a limited time, I still have problems.

**Comment by miguelgrinberg** [comment]
A 400 error means that the server received a request and found it to be incorrect. You would never get a 400 when the internet is down, because in that case there would be no server that could respond.

**Comment by pykiwi** [comment]
Ok. I will check my code. And I have more logs.Can you explain this to me? 
Thanks!
Log:
`Thg 1 13 23:52:59 raspberrypi main[3274]: HTTP POST request to https://meshthings.io:3445/socket.io/?transport=polling&EIO=3&sid=CNztmwXqToRAhhVnAAAP failed with error HTTPSConnectionPool(host='meshthings.io', port=3445): Max retries exceeded with url: /socket.io/?transport=polling&EIO=3&sid=CNztmwXqToRAhhVnAAAP (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x75197390>: Failed to establish a new connection: [Errno -2] Name or service not known')).`
`Thg 1 13 23:52:59 raspberrypi main[3274]: Connection refused by the server, aborting`
`Thg 1 13 23:52:59 raspberrypi main[3274]: Exiting write loop task`
`Thg 1 13 23:53:04 raspberrypi main[3274]: Received packet CLOSE data None`
`Thg 1 13 23:53:04 raspberrypi main[3274]: Sending packet CLOSE data None`
`Thg 1 13 23:53:04 raspberrypi main[3274]: Engine.IO connection dropped`
`Thg 1 13 23:53:04 raspberrypi main[3274]: Waiting for write loop task to end`
`Thg 1 13 23:53:04 raspberrypi main[3274]: Waiting for ping loop task to end`
`Thg 1 13 23:53:04 raspberrypi main[3274]: Exiting ping task`
`Thg 1 13 23:53:04 raspberrypi main[3274]: Exiting read loop task`

**Comment by miguelgrinberg** [comment]
This log indicates that the server is offline actually, there are no 400 errors here.

**Comment by pykiwi** [comment]
Thank you very much !! It seems that after I updated from 'polling' to 'websocket', there was no such situation.
