### ISSUE TITLE
Django 3 and Daphne deploy

### ISSUE THREAD

**Issue by nunesvictor** [miguelgrinberg/python-socketio#408]
Hi,

I'm trying to implement a simple socket emit with Django 3 and Daphne, but for some reason the event emited isn't never captured by the client. Here is my code

asgi.py
```python
import os
import socketio

from django.core.asgi import get_asgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'eleicoes.settings')

sio = socketio.AsyncServer(async_mode='asgi', cors_allowed_origins='*')
application = socketio.ASGIApp(sio, get_asgi_application())

```

views.py

```python
from eleicoes.asgi import sio

# other code

print('emit vote event', sio)
sio.emit('user', UserSerializer(instance=request.user).data)

# other code
```

It simples doesn't work. I think I followed the documentation in this matter but I can't find anything with this specific setup (django 3 and daphne)

**Comment by miguelgrinberg** [comment]
@nunesvictor it would be useful if you enable Socket.IO logs in the server and the client and we can look at those to see where is this emit getting lost. For the server, add `logger=True` and `engineio_logger=True` arguments when you create your `AsyncServer` object. For the JS client see https://socket.io/docs/logging-and-debugging/.

**Comment by nunesvictor** [comment]
Thank you for your quick response. I think we found the problem, but I'm still struggling with the solution. I had to change the verbosity of daphne logs too, but it told me that:

```
web_1      | 2020-01-16 11:33:00,002 WARNING  Executing <Task pending name='Task-12' coro=<ASGI3Middleware.asgi() running at /usr/local/lib/python3.8/site-packages/daphne/cli.py:30> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.8/asyncio/futures.py:357, <TaskWakeupMethWrapper object at 0x7f566d57c880>()] created at /usr/local/lib/python3.8/asyncio/base_events.py:418> created at /usr/local/lib/python3.8/site-packages/daphne/server.py:205> took 0.106 seconds
web_1      | 2020-01-16 11:33:00,314 WARNING  ./api/views.py:206: builtins.RuntimeWarning: coroutine 'AsyncServer.emit' was never awaited
```

I think emit has to be called with await, but I can't get into it because my api call (simple Django REST Framework view call) is a synchronous one. How can I encapsulate that async call inside a sync one?

Sorry for the throubles and thank you!

**Comment by miguelgrinberg** [comment]
@nunesvictor oh, you are mixing asyncio and standard apps, I think that's a recipe for trouble. Do you have a good reason to do that? Why not use the `Server` class instead of `AsyncServer`, which is fully compatible with WSGI and thus Django?

**Comment by nunesvictor** [comment]
Actually I don't think I have a good reason. I just couldn't make uWSGI work for that. It always fails on firsts attempts to connect, something like `Error: xhr poll error` and then connects after a few attempts.

Also, the event emited on my view doesn't reach the client I and can't put my finger on why.

**Comment by nunesvictor** [comment]
My alternative setting to run with runserver and/or uWSGI is this one:

wsgi.py
```python
import os
import socketio

from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'eleicoes.settings')

sio = socketio.Server(
    cors_allowed_origins='*',
    engineio_logger=True,
    async_mode='gevent',
    logger=True,
)

application = socketio.WSGIApp(sio, get_wsgi_application())
```

and in my views.py I try to emit the signal with

```python
sio.emit('vote', UserSerializer(instance=request.user).data)
```

and I run uWSGI with this ini file

```ini
[uwsgi]
base = /app
app = wsgi

processes = 10
max-requests = 4000
limit-as = 1024
buffer-size= 32768

pythonpath = %(base)/src
http-socket = 0.0.0.0:8000
chmod-socket = 666
vaccum = true
module = eleicoes.%(app):application

static-map = /static=/app/src/staticfiles
static-expires = /* 7776000
offload-threads = %k

gevent = 10

```

Note than it's not working with runserver and uWSGI ether

**Comment by miguelgrinberg** [comment]
Socket.IO is an asynchronous server. If you are going to use uWSGI you have to use it along with gevent. There are a few options that are based on WSGI besides that, see the [documentation on deployment](https://python-socketio.readthedocs.io/en/latest/server.html#deployment-strategies) to find what works best for you.

**Comment by nunesvictor** [comment]
I honestly don't know how to thank you. Apparently the problem was I had added the wrong `async_mode` on `socketio.Server`. I'll put the correct configuration down here to whoever this may help in the future.

myapp.wsgi
```python
import os
import socketio

from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'myapp.settings')

sio = socketio.Server(
    async_mode='gevent_uwsgi',
    cors_allowed_origins='*',
    engineio_logger=True,
    logger=True,
)

application = socketio.WSGIApp(sio, get_wsgi_application())
```
uWSGI command line
`uwsgi --http :8000 --gevent 1000 --http-websockets --master --module myapp.wsgi:application`

**Comment by miguelgrinberg** [comment]
I suggest you remove `cors_allowed_origins='*'`. This is basically allowing anybody to connect to your server, and can open the door to CSRF attacks. My recommendation is that you explicitly name the allowed origins instead.

**Comment by nunesvictor** [comment]
Will do
