### ISSUE TITLE
Initial reconnect

### ISSUE THREAD

**Issue by adrianlubitz** [miguelgrinberg/python-socketio#409]
The socketio is not automatically trying to reconnect when there is no Internet connection on the initial connect. I have the following code snippet:
```python
import socketio
sio = socketio.Client()

@sio.event
def connect():
    print("I'm connected!")

@sio.event
def connect_error():
    print("The connection failed!")

@sio.event
def disconnect():
    print("I'm disconnected!")
    
sio.connect(MYSERVER)
```
It works perfectly if the Internet connection is established by the time of the connect. If it breaks down later it will reconnect, just as intended.

But if there is no Internet connection on the initial connect the following Exception is raised:

```
Traceback (most recent call last):
  File "pyTest.py", line 18, in <module>
    sio.connect(MYSERVER)
  File "/home/al/anaconda3/envs/socketioTest/lib/python3.6/site-packages/socketio/client.py", line 270, in connect
    six.raise_from(exceptions.ConnectionError(exc.args[0]), None)
  File "<string>", line 2, in raise_from
socketio.exceptions.ConnectionError: Connection refused by the server
```

The behavior should be that it tries to reconnect until there it can reach the server.

I worked my way around it by having the connect in a loop with try/except but I feel like this should be shipped with this great library.
Thanks ;)

**Comment by miguelgrinberg** [comment]
Your description is accurate, the initial connection is not retried. This behavior was intentional, to me it does not make sense to enter a reconnect loop when there has never been a connection established before. Open to add an option to enable this if you have a use case that justifies it, but I don't see it as working that way by default.

**Comment by adrianlubitz** [comment]
The problem I see here is if you have an unstable connection you never know when you have a connection and when you don't. Therefore it makes sense, that a connection is established whenever it is possible.
As far as I remember the js implementation does it like that and I just tested the java implementation and here it is just like that.
Just wanted to let you know, that when I was starting to use your implementation I was expecting this behavior and was confused by the way it is.
Besides that I was super happy how clean everything is structured :+1:

**Comment by snorfalorpagus** [comment]
If the connection error was always the result of a configuration problem (e.g. the wrong URL has been given) I would agree that throwing the exception and not retrying makes sense. But it could be that the socketio server simply isn't available when the client starts up.

I'm running a socketio client inside a Docker container on ECS. Sometimes the containers will be killed (for reasons outside the control of the application). This means there is a chance the application restarts at a point when the websocket (and external service) is not available. ECS will restart the container each time it crashes, but it doesn't have the nice exponential backoff logic that the reconnect does, and it adds noise to the logs (the application has crashed vs a disconnect/reconnect message).

I'll have a go at implementing this as a non-default option to the existing connect method.

**Comment by luizcz** [comment]
Was this feature implemented?

**Comment by miguelgrinberg** [comment]
@luizcz No.
