### ISSUE TITLE
Invalid async_mode specified while running docker image

### ISSUE THREAD

**Issue by nmanthena18** [miguelgrinberg/python-socketio#411]
Hi,
while running docker image I am facing the below issue, I have added the --hidden-import=gevent-websocket, but no luck.

anyone can help me on this.
**my requirements.txt**
Click==7.0
dnspython==1.16.0
eventlet==0.25.1
Flask==1.1.1
Flask-SocketIO==4.2.1
greenlet==0.4.15
itsdangerous==1.1.0
Jinja2==2.10.3
MarkupSafe==1.1.1
monotonic==1.5
pymongo==3.10.1
python-engineio==3.11.2
python-socketio==4.4.0
gevent-websocket==0.10.1
six==1.13.0
Werkzeug==0.16.0

[6] Failed to execute script app
Traceback (most recent call last):
  File "app/app.py", line 12, in <module>
  File "flask_socketio/__init__.py", line 185, in __init__
  File "flask_socketio/__init__.py", line 245, in init_app
  File "socketio/server.py", line 108, in __init__
  File "engineio/server.py", line 139, in __init__
ValueError: Invalid async_mode specified

**Comment by miguelgrinberg** [comment]
Are you using eventlet or gevent? For eventlet you don't need any other packages. If you are using gevent, then you need to add gevent-websocket.

What do you mean by hidden import in this context?

**Comment by nmanthena18** [comment]
**this is my docker file for build **
FROM ubuntu:18.10 as base
RUN apt-get update
RUN apt-get install -y software-properties-common
RUN apt-get install -y build-essential python3.6 python3.6-dev python3-pip libcups2-dev libcairo2-dev  libjpeg-dev libgif-dev && \
    python3 -m pip install --upgrade pip wheel setuptools pyinstaller 

COPY ./app /app
COPY ./requirements.txt /app/requirements.txt
WORKDIR /app
RUN python3 -m pip install -r requirements.txt
RUN pyinstaller /app/app.py --hidden-import=gevent
ENV NODE_ENV=dev
EXPOSE 8080
FROM ubuntu:18.10
COPY --from=base /app/dist /dist
RUN mkdir -p /data/adminapp
WORKDIR /dist
ENTRYPOINT ["app/app"]

**Comment by nmanthena18** [comment]
Which repository?

**Comment by miguelgrinberg** [comment]
https://github.com/miguelgrinberg/python-socketio/issues/35
https://github.com/miguelgrinberg/python-socketio/issues/178
https://github.com/miguelgrinberg/Flask-SocketIO/issues/259
https://github.com/miguelgrinberg/Flask-SocketIO/issues/233
