### ISSUE TITLE
Selecting the socket.io version to be used

### ISSUE THREAD

**Issue by BenSpex** [miguelgrinberg/python-socketio#412]
Hi, 
is there a way to use socket.io version 1.4 instead of the current 2.x  and still use the current python-socket-io framework? 

Thanks
Ben

**Comment by miguelgrinberg** [comment]
version 1.4 of which socket.io client? The JS one? Sure, just load the JS client that you like, as long as it is a 1.x or 2.x you should be fine.

**Comment by BenSpex** [comment]
thanks for the quick reply. 

the situation is following: 
I have the latest version of python-socketio and cannot seem to get a golang client with socketio v1.4 to connect probably and receive / send messages.

So I was hoping to be able to get the server to use 1.4 as well

**Comment by miguelgrinberg** [comment]
What does 1.4 mean in this context? The versions apply to each implementation, there isn't an absolute version number that applies to all implementations as a whole.

**Comment by BenSpex** [comment]
socket.io js version 1.4 
All I do get a bad handshake response

**Comment by miguelgrinberg** [comment]
This is confusing. You first said you are using a golang client 1.4. Now it is JS version 1.4? Please reopen if you can provide code that I can use to test this issue here.
