### ISSUE TITLE
make SIGINT handling optional

### ISSUE THREAD

**Issue by prodipta** [miguelgrinberg/python-socketio#414]
Currently adding SIGINT handling makes it impossible to run the Client in a thread. Suggest move signal handling to optional (also in engineIO). This use case is running a different program that does many things in its main thread - and also uses socketIO client to handle some communications with a counterparty in a background thread.

**Comment by miguelgrinberg** [comment]
I like this idea. Would you like to have a go at this? The code [here](https://github.com/miguelgrinberg/python-engineio/blob/master/engineio/client.py#L79-L82) needs to be controlled with an option passed into the `Client` class.

**Comment by prodipta** [comment]
Fine, thx, I will give it a try
