### ISSUE TITLE
send a event when server is running

### ISSUE THREAD

**Issue by hamidb80** [miguelgrinberg/python-socketio#416]
Hi.
I am trying to create a console for server that I can send events whenever.

but I can't emit a event when app is running.

```
def code_executor():
    while True:
        code = input('> ')

        try:
            exec(code)
        except:
            print('err')


Thread(target=code_executor).start()
```
when I type in console "socket.emit('ev_name')", it doesn't work.

what should I do?

**Comment by miguelgrinberg** [comment]
Do you get an error? Also note that since you are using the `threading` module, if you are running with eventlet or gevent you have to monkey patch the standard library.

**Comment by hamidb80** [comment]
> Do you get an error? Also note that since you are using the `threading` module, if you are running with eventlet or gevent you have to monkey patch the standard library.

Can you give me an example using monky patch?
