### ISSUE TITLE
Checking data is None in {AsyncServer,Server}._emit_internal()

### ISSUE THREAD

**Issue by tsangwpx** [miguelgrinberg/python-socketio#419]
In AsyncClient, the case `data is not None` is checked so the server will receive an empty list as data.

https://github.com/miguelgrinberg/python-socketio/blob/aa2882cb3e2f3cda3a9d8c94b1c5db1bd0dbbf99/socketio/asyncio_client.py#L167

However, in `AsyncServer`, the case `data is not None` is not checked so `[None]` is passed to client instead of an empty list `[]`.
https://github.com/miguelgrinberg/python-socketio/blob/aa2882cb3e2f3cda3a9d8c94b1c5db1bd0dbbf99/socketio/asyncio_server.py#L357

So the behavior is not symmetric between server and client.

There is a similar situation in the `Server` class as well.

I think this is a bug.

**Comment by miguelgrinberg** [comment]
Do you want to create a PR for this fix? Thanks!
