### ISSUE TITLE
Highlight `cors_allowed_origins` in tutorial

### ISSUE THREAD

**Issue by QuantumGhost** [miguelgrinberg/python-socketio#421]
I have wasted about 10 hours because of `cors_allowed_origins` defaults to `Host` in http request headers.

I guess it's better to remind users that they need to set `cors_allowed_origins` to avoid getting unexpected `Bad Request` in tutorial. (especially for those who are using socket.io in native applications)

**Comment by miguelgrinberg** [comment]
`cors_allowed_origins` does not need to be set when using native applications. You only need to set it when the client is a web browser that is connecting from a different origin. Why did you need to set it for a native app? Which client are you using?

**Comment by QuantumGhost** [comment]
If I recall it correctly, it is because the client making request does not set a correct `Origin` header. (It is not empty and in the default origin list.)

I believe this should be considered a bug of the http client
