### ISSUE TITLE
long running task in async handler is blocking other handlers

### ISSUE THREAD

**Issue by RamVellanki** [miguelgrinberg/python-socketio#422]
I am trying to implement a logic where I have a long-running task inside one of my async handlers, but when this handler is being executed other handlers aren't getting called. Following code simulates my requirement:

```
import socketio
from aiohttp import web
import time

sio = socketio.AsyncServer(async_mode='aiohttp', async_handlers=True)
app = web.Application()
sio.attach(app)

@sio.on('record')
async def record(sid):
    print("Got message 'record'")
    time.sleep(60) #simulating long running task

@sio.on('stop')
async def stoprecord(sid):
    print("Got message 'stop'")

if __name__ == '__main__':
    web.run_app(app, host='0.0.0.0', port=5000)
```

The line `time.sleep(60)` simulates long-running task. And from a client (in this case I have used nodejs), once the `record` method is called, the `stop` call gets completely ignored. Am I missing anything?

**Comment by RamVellanki** [comment]
I think I figured out the problem to some extent. If I call the `stop` handler from another client it gets called, but as long as I am calling from the same client it is not being called.

**Comment by miguelgrinberg** [comment]
You can't call blocking functions in an asynchronous program. The `time.sleep()` function is cannot be used at all, it blocks the asyncio loop.

**Comment by RamVellanki** [comment]
Thank you. I added sleep to represent a long running callback. I realise that it’s a wrong representation. Basically, the place where I have mentioned sleep, I register a callback and then start a process that calls the callback continuously.

**Comment by miguelgrinberg** [comment]
What I said still applies. You can't block an async application. If you are going to run for a long time, then you need to call `await asyncio.sleep(0)` often to allow other tasks to run.
