### ISSUE TITLE
"ValueError: signal only works in main thread" when using the server

### ISSUE THREAD

**Issue by pcmoritz** [miguelgrinberg/python-socketio#424]
When using the server together with aiohttp, I'm getting the error
```
ValueError: signal only works in main thread
```

from https://github.com/miguelgrinberg/python-socketio/blob/master/socketio/client.py#L28. Can we have the same fix as in https://github.com/miguelgrinberg/python-engineio/commit/6534d324f3dce2e1e4927932660d5e5e8bcab202 also for socketio? That would help a lot! At the moment I'm doing this ugly workaround:
```
        import signal
        origsignal = signal.signal
        signal.signal = lambda x, y: None
        from socketio.asyncio_server import AsyncServer
        signal.signal = origsignal
```

**Comment by miguelgrinberg** [comment]
Ah yes, sorry, I missed it, this one needs to be fixed as well.
