### ISSUE TITLE
socket over flask and https

### ISSUE THREAD

**Issue by mmayor** [miguelgrinberg/python-socketio#426]
Hi, I'm trying to implement socket over flask and https. What would be the best variant?

**Comment by miguelgrinberg** [comment]
I'm sorry but I don't understand what you are asking. Best variant of what?

**Comment by mmayor** [comment]
Well, thanks for answering. I am in a project, I have react in the frontEnd
and flask in the backEnd. Everything works on HTTPS. Of necessity I have to
use socket to implement some functionalities in real time. But I have not
managed to get flask-Socketio work over https

tkanks

**Comment by miguelgrinberg** [comment]
This package does not really care about https, the encryption/decryption is all handled by your web server. That's where you should be looking for the problem, I think.

**Comment by mmayor** [comment]
perfect thank you sir

**Comment by luizvaz** [comment]
You must use nginx ou traefic as reverse proxy to handle SSL and load balance before your frontend and backend.
By the way you inform to uvicorn where SSL keyfile and certifile are.
Example:

uvicorn chat:app --reload --host 0.0.0.0 --port 8000 --ssl-keyfile /etc/letsencrypt/<yourdomain.com>/<yourdomain.com>.key --ssl-certfile /etc/letsencrypt/<yourdomain.com>/<yourdomain.com>.cer --ssl-ca-certs /etc/letsencrypt/<yourdomain.com>/fullchain.cer
