### ISSUE TITLE
'int' object has no attribute 'encode'

### ISSUE THREAD

**Issue by higrw123** [miguelgrinberg/python-socketio#429]
when i use client connected , then i close socket server , 
     await sio.wait() -> await self.eio.wait() -> async def _read_loop_websocket(self): ->   pkt = packet.Packet(encoded_packet=p)
will raise Exception
     'int' object has no attribute 'encode'
will break the logic of reconnect

**Comment by miguelgrinberg** [comment]
This is a duplicate of https://github.com/miguelgrinberg/python-socketio/issues/417. Do you have a client and server I can use to reproduce this problem?

**Comment by higrw123** [comment]
don't find your email,  can you give me one

**Comment by miguelgrinberg** [comment]
first name dot last name at gmail

**Comment by miguelgrinberg** [comment]
closing since this is a duplicate.
