### ISSUE TITLE
Geting answer from JS server on Python client

### ISSUE THREAD

**Issue by OscarSoto6** [miguelgrinberg/python-socketio#431]
i get problems trying to get the answer from a JS server using socket io , i already get conected and send my data from python client, but i don't know how to get a confirmation answer from the server, here it's my client code:
```

sio = socketio.Client() 
sio.connect('http://159.89.129.132:3000')

@sio.event
def connect_error():
    print("error")

@sio.event
def disconnect():
    print("id disconected: ", sio.sid)
    sio.disconnect()

print('Id : ', sio.sid)
sio.emit("message", data)
print("Send")
```
the server part on JS:
```

const onMessage = (socket) => {
  return new SocketEvent('message', (message) => {
    socket.emit('message', 'alive');
    socket.emit('soto', 'message recibed');
    console.log(`${message}`);
  });
};
```
The console log of the server its this:

```
2|sandras  | 13-02 20:26:30.353: fpqRMsw5U-fEHVO6AACz connected new
2|sandras  | 13-02 20:26:30.590: 5:00,9:00,286:15,28354,121,5,2,158,0,76,0,0,0,0,0,0
```
The data have been sent properly, but i dont know the way to listen to an answer from the side of the client, any help will be helpful.

**Comment by hamidb80** [comment]
You have to define a new event on client. Like connect_error or...

**Comment by miguelgrinberg** [comment]
To wait for events call `sio.wait()`. Also move the `sio.connect()` call to the bottom, after you define your handlers.

**Comment by OscarSoto6** [comment]
Wow, thanks i didn't think that the problem be the location of the sio.connect(), this solve everything, i get the answer from the server, thank you very much
