### ISSUE TITLE
Using ASGI servers with workers

### ISSUE THREAD

**Issue by acnebs** [miguelgrinberg/python-socketio#437]
Can you provide any guidance as to whether it is possible to use workers when using an ASGI server like `uvicorn`, `hypercorn`, or `daphne`? The issues with load-balancing and `socketio` being stateful are well detailed with respect to running things in WSGI-land under something like `gunicorn`, but details are a bit sparse when it comes to ASGI and workers.

I understand that it depends on the load-balancing algorithm used (whether it is / can be sticky or not), but I'm not really sure how to apply this knowledge to ASGI workers.

**Comment by miguelgrinberg** [comment]
There is actually no difference. All those rules that you say apply to WSGI are not really WSGI specific. So sticky sessions are required. The easiest way to deploy WSGI or ASGI is to run several single-instance servers, each on a different port, putting nginx with the ip_hash option as load balancer.
