### ISSUE TITLE
emitting from an external process, not able to receive it on client

### ISSUE THREAD

**Issue by LovikaJain** [miguelgrinberg/python-socketio#440]
I am trying to emit events from external process using redis but not able to receive it on client end.
I used the sample file from examples for aiohttp for client.

`Code:`
```
async def background_task():
    count = 0
    global streaming_status
    streaming_status = True
    while streaming_status:
        await sio.sleep(10)
        count += 1
        print("Keep alive message")
        await external_sio.emit('event response', {'data': 'getting external event'}, namespace=namspace_live_meeting)
        await sio.emit('event response', {'data': 'Keep alive event'}, namespace=namspace_live_meeting)

```

**Comment by miguelgrinberg** [comment]
How did you create `sio` and `external_sio`? Why do you have two?

**Comment by LovikaJain** [comment]
I want to use aiohttp with redis. I have created sio using socketio.asyncserver(async_mode=“aiohttp”)
And external_sio with RedisManager.
And with redis not able to use .on

**Comment by miguelgrinberg** [comment]
Please review the documentation on emitting from external processes. You haven't configured the client_manager in the server, and you seem to also be using the RedisManager object in the main process, not in the external process.

**Comment by LovikaJain** [comment]
I am using RedisManager object in external process not in main process and for external process also I need to configure client manager? and can I use client manager and async_mode together?

This is what I have tried till now I am completely new to socketio and redis so bit confused.

```
sio = socketio.AsyncServer(async_mode='aiohttp')
external_sio = socketio.AsyncRedisManager('redis://127.0.0.1:6379/0', write_only=True)
@sio.on('broadcast message', namespace=namspace_live_meeting)
async def test_broadcast_message(sid, message):
    print("Session with session Id:", sid)
    print("Broadcast message:", message['data'])
    await sio.event('event response', {'data': message['data']}, namespace=namspace_live_meeting)

@sio.on('external process', namespace=namspace_live_meeting)
async def external_emit(sid, message):
    print("Getting external process event")
    await external_sio.emit('event response', {'data': message['data']}, namespace=namspace_live_meeting)

app.router.add_static('/static', 'static')
app.router.add_get('/', client)


if __name__ == '__main__':
    sio.start_background_task(background_task)
    web.run_app(app)

```

I have followed the documentation for external process though couldn't get much details on it and no samples are available for it.
https://python-socketio.readthedocs.io/en/latest/server.html#id1

I had tried to use async_mode and client_manager together but it didn't work.
```

mgr = socketio.RedisManager('redis://127.0.0.1:6379/0')
sio = socketio.AsyncServer(async_mode='aiohttp', client_manager=mgr)
```

When I am using both together I get error and the execution gets stuck!

**Comment by miguelgrinberg** [comment]
The external process is write only, as you can see in the creation of the redis manager object. You cannot receive events, that can only be done in a server process.

**Comment by LovikaJain** [comment]
ok, in that case I will have to use server process as I want to send the data back to the client and keep the connection bidirectional. how do I use both async_mode and AsyncRedisManager (client_manager) together? as I tried using simply client_manager and it didn't work for the customized events.

`@sio.on()`

**Comment by LovikaJain** [comment]
what is the purpose of having the external process? what's the use case of external process? where it can be used? Will client manager work for the case where python code is running on different docker container and redis is running on different container?

**Comment by Geo-Joy** [comment]
1. can an external process emit data to others connected to the same room?
2. how is the sio event triggered if i use external_sio.emit?

- I have a kubernetes cluster running 2 websocket pods and 1 redis master with 2 slaves running in different pods.
- here since any of the websocket server can get request from the client - how would i use redis as and external process.

**Comment by databasedav** [comment]
@LovikaJain
You should think of the external process as an abstraction corresponding to a process that can emit events to clients. While the `AsyncServer` is the process that actually communicates with the client, you can have it subscribe to a message queue on which other processes can publish events they want emitted. This way if you have many microservices that all want to emit events to clients connected to many different `AsyncServer`'s and the microservice knows which client it wants to emit to but not the `AsyncServer` they are connected to, they can simpy publish events to the message queue knowing that the event will be consumed and emitted by the `AsyncServer` their desired client is connected to. And yes using a message queue is perfect for multi container applications.


@Geo-Joy
1. yes if your external process knows the room; I'm not sure if there is the map from `sid` to the rooms they are in but you can easily implement this yourself if not
2. what do you mean triggered? `.emit`ing from an external process just publishes the event to the message queue which one or many `AsyncServer`'s can be subscribed to

redis is not the external process; it is the message queue. The `AsyncServer`'s on each websocket pod should declare the redis as its `client_manager`. Then your external processes in other pods (also connected to the same redis) can `.emit` to publish events to be emitted.

**Comment by miguelgrinberg** [comment]
> what is the purpose of having the external process? what's the use case of external process?

Emit to clients from an auxiliary process that is related to a server, but not a server itself. Best example is a Celery worker.

>  Will client manager work for the case where python code is running on different docker container and redis is running on different container?

Sorry, don't understand why it matters which container(s) each piece is running on. The components communicate over the network, as long as the hosts/IP addresses are set correctly it does not really matter.

**Comment by devamin** [comment]
>Emit to clients from an auxiliary process that is related to a server, but not a server itself. Best example is a Celery worker.
Why not the server itself acting as an auxiliary process, let's say we are making a chat application [client]C1 is connected to [server]S1, and C2 is connected to S2. 
C1 -> send message to -> C2 
we can do something like this : 
C1 -> S1 -> broker -> S2 -> C2

**Comment by miguelgrinberg** [comment]
@devamin what you describe is already implemented.

**Comment by devamin** [comment]
@miguelgrinberg thanks a lot for fast reply > would you mind sharing some resources about it, I read all documentation didn't find something and also couldn't find open source examples. 

Another thing and sorry to bother you, but I am unable to handle aux emitted events. 
having this server.py 
``` python
# server.py
from typing import Any
import uvicorn
from fastapi import FastAPI
import socketio
mgr = socketio.AsyncRedisManager('redis://localhost:6379')
sio: Any = socketio.AsyncServer(client_manager=mgr,async_mode="asgi",logger=True, engineio_logger=True)
socket_app = socketio.ASGIApp(sio)
app = FastAPI()
app.mount("/", socket_app)
@sio.on("connect")
async def connect(sid, env):
    print("on connect")
@sio.on("auxevent")
async def auxevent(sid,data):
    print(sio)
    print(f"auxevent {data}")
if __name__ == "__main__":
    kwargs = {"host": "0.0.0.0", "port": 8555}
    kwargs.update({"debug": True})
    uvicorn.run(app, **kwargs)
```

```python
#aux.py
import socketio
import asyncio
mgr = socketio.AsyncRedisManager('redis://localhost:6379',write_only=True)
async def emit_event():
    await mgr.emit("auxevent", data="message from aux")
asyncio.run(emit_event())
```

After debugging, I found out that the Manager doesn't get initialized until there is a connection, so I created a dummy client. 
```python
#client
import socketio
cl = socketio.Client()
cl.connect("http://127.0.0.1:8555/")
```

For hours of debugging, I found out that the :
* client does publish an event
* server does receive it
But the event handler is not triggered. 
I am using python 3.10.9

**Comment by miguelgrinberg** [comment]
@devamin this is the section of the docs that covers scaling the server: https://python-socketio.readthedocs.io/en/latest/server.html#scalability-notes. I have a complete example based on the Flask-SocketIO extension here: https://github.com/miguelgrinberg/flack.

The code that you posted is actually incorrect. Emitting from an auxiliary process is a feature that allows the aux process to emit to a client. You seem to be trying to emit to the server, which is not what this feature does. If you want to emit to the server, then there is no reason to use an auxiliary process, just use the client directly.

**Comment by devamin** [comment]
Thanks a lot
