### ISSUE TITLE
translate a javascript script into python

### ISSUE THREAD

**Issue by thomas-bchz** [miguelgrinberg/python-socketio#442]
Hello, i work on a python project and i have to translate a connection in javascript to a socket.io server, i try with the documentation to write a python script but it doesnt work.
the javascript is :

> http://developers.pioupiou.fr/api/push/
Actually my script is :\

```python
import socketio

sio = socketio.AsyncClient()

@sio.event
async def connect():
    # etabliseement de la connection

def connect():
    # etablisement de la connection
    print('la connection est établie')
    # emission du windbird voulu
    await sio.emit('subscribe', 'all')
    # unique session identifier
    print('mon identifiant de session est :', sio.sid)

@sio.on('error')
def on_message(data):
    print('erreur: ', data)

@sio.on('status')
def on_message(data):
    print('status: ', data)

@sio.on('measurement')
def on_message(data):
    print('measurement: ', data)

@sio.on('location')
def on_message(data):
    print('location: ', data)

@sio.event
def disconnect():
    print('deconnecter du serveur')

if __name__ == "__main__":
    await sio.connect('http://api.pioupiou.fr/v1/push')
    # attend d'un signal
    await sio.wait()
```

the connection is ok but i never see the data send by the server.
thanks for the help.

**Comment by miguelgrinberg** [comment]
Well, you have two connection functions. I think your connect event handler should merge the two, something like this:

```python
@sio.event
async def connect():
    # etablisement de la connection
    print('la connection est établie')
    # emission du windbird voulu
    await sio.emit('subscribe', 'all')
    await sio.emit("subscribe", 1);  # station n° 1
    # unique session identifier
    print('mon identifiant de session est :', sio.sid)
```

**Comment by thomas-bchz** [comment]
hello, thanks for the answer, i know is because i just want a single connection, i modifie my script for create methode juste like in the javascript script :
import socketio

sio = socketio.Client()

# connect method:
def connect_handler():
    # etabliseement de la connection
    print('la connection est établie')
    # emission du windbird voulu
    sio.emit('subscribe', 'all')
    # unique session identifier
    print('mon identifiant de session est :', sio.sid)
sio.on('connect', connect_handler)

# error method:
def error_handler(msg):
    print('Received error: ', msg)
sio.on('error', error_handler)

# status a method:
def status_handler(msg):
    print('Received status: ', msg)
sio.on('status', status_handler)

# measurement a method:
def measurement_handler(msg):
    print('Received measurement: ', msg)
sio.on('measurement', measurement_handler)

# location a method:
def location_handler(msg):
    print('Received location: ', msg)
sio.on('location', location_handler)

@sio.event
def connect_error():
    print('La connection a échouée')

@sio.event
def disconnect():
    print('deconnecter du serveur')

if __name__ == '__main__':
    sio.connect('http://api.pioupiou.fr/v1/push')
    # attend d'un signal
    #sio.wait()



But when i run my script, he connect and give me the sid connection but i never receved a answer or data by the server and when i kill the process i have that :

**Comment by miguelgrinberg** [comment]
Okay, another bug, you are missing the namespace. Try this:

```python
import socketio                                                                                                                                                      [5/5088]

sio = socketio.Client(engineio_logger=True, logger=True)

# connect method:
def connect_handler():
    # etabliseement de la connection
    print('la connection est établie')
    # emission du windbird voulu
    sio.emit('subscribe', 'all', namespace='/v1/push')
    sio.emit('subscribe', 1, namespace='/v1/push')
    # unique session identifier
    print('mon identifiant de session est :', sio.sid)
sio.on('connect', connect_handler, namespace='/v1/push')

# error method:
def error_handler(msg):
    print('Received error: ', msg)
sio.on('error', error_handler, namespace='/v1/push')

# status a method:
def status_handler(msg):
    print('Received status: ', msg)
sio.on('status', status_handler, namespace='/v1/push')

# measurement a method:
def measurement_handler(msg):
    print('Received measurement: ', msg)
sio.on('measurement', measurement_handler, namespace='/v1/push')

# location a method:
def location_handler(msg):
    print('Received location: ', msg)
sio.on('location', location_handler, namespace='/v1/push')

@sio.event
def connect_error():
    print('La connection a échouée')

@sio.event
def disconnect():
    print('deconnecter du serveur')

if __name__ == '__main__':
    sio.connect('http://api.pioupiou.fr', namespaces='/v1/push')
    # attend d'un signal
    sio.wait()```

**Comment by thomas-bchz** [comment]
hello,

thank for the help it works !
