### ISSUE TITLE
python-socketio bridge with ws4py

### ISSUE THREAD

**Issue by Geo-Joy** [miguelgrinberg/python-socketio#443]
what i need.
client-machine (python-socketio-client) -> server-1 (python-socketio-server also ws4py-client) -> server-2(ws4py-server)

currently 2 websocket connections exists

from client to server-1 (socketio)
from server-1 to server-2(ws4py)
what i hold is server-1.
server-2(ws4py) is from a third party service provider.

i want to get data from client -> receive it on my server-1 thru websocket running on socketio -> send this data to server-2 thru websocket running on ws4py.

What i have currently built.
socketio client and server-1 = working fine
ws4py server-1 to server-2 = working fine

what i want
get the event or class object of that connected client from socketio and send that directly to ws4py.

Can someone guide me on this.

**Comment by miguelgrinberg** [comment]
Sorry, I know nothing about ws4py and you are not providing any code, so I'm not sure how I can help.

**Comment by Geo-Joy** [comment]
@miguelgrinberg 

here is a sample code.

`class StreamClient(WebSocketClient):
    def __init__(self, audiofile, url, speech_id, content_type=None,
                 protocols=None, extensions=None, heartbeat_freq=None, byterate=32000):
        print (url)
        super(StreamClient, self).__init__(url, protocols, extensions, heartbeat_freq)
        self.content_type = content_type
        self.audiofile = audiofile
        self.byterate = byterate
        self.speech_id = speech_id

    @rate_limited(4)
    def send_data(self, data):
        self.send(data, binary=True)

    def opened(self):
        print ("Socket opened")

        def send_data_to_ws():
            msg = {
                "content_type": self.content_type,
                "action": "start",
                "speech_id": self.speech_id,
                "offset": 0
            }
            self.send(json.dumps(msg))
            print ("start to send audio data")
            try:
                ####### i need to get the on message event here ##########
                #   self.send_data(block)
            except Exception as e:
                print("entered exeption")
                tb = traceback.format_exc()
                print ("error: {}\n{}".format(e, tb))
            print("outside exeption")
            print ("Audio sent, now sending stop")
            msg = {'action': 'stop'}
            self.send(json.dumps(msg))
        t = threading.Thread(target=send_data_to_ws)
        t.start()

    def close(self, code=1000, reason=''):
        print ("closed code=%s reason=%s" % (code, reason))

    def received_message(self, m):
        print ("received message:", m)

    def closed(self, code, reason=None):
        print ("Websocket closed() called")
        self.close()`

**Comment by miguelgrinberg** [comment]
Your is using plain WebSocket, not Socket.IO.

**Comment by Geo-Joy** [comment]
@miguelgrinberg as per the first post.
Iam using socketio to get data from client - I need to pass this data to another websocket running on ws4py - please do check the fist post

**Comment by miguelgrinberg** [comment]
The Socket.IO server is asynchronous, you cannot get a message in the middle of some other code. What you have to do is in the Socket.IO event handler store the data somewhere (maybe a global variable), then get the data from the stored location in your WebSocket thread.

**Comment by Geo-Joy** [comment]
fixed if by running the second web-socket connection in separate thread!
