### ISSUE TITLE
Support for dynamic namespaces

### ISSUE THREAD

**Issue by brechtm** [miguelgrinberg/python-socketio#444]
Does python-socketio support dynamic namespaces? socket.io supports them by [accepting a regular expression or a function](https://socket.io/docs/server-api/#server-of-nsp). If not, is this feature planned?

**Comment by miguelgrinberg** [comment]
Not planning to add this feature at this time, but happy to accept it as a contribution.

**Comment by brechtm** [comment]
Not being familiar with socket.io, I was under the impression that my application required dynamic namespaces. I learned that rooms are perfectly capable of what I need.

For reference, the following question and answers on StackOverflow were very helpful in understanding the differences between namespaces and rooms: [socket.io rooms or namespacing?](https://stackoverflow.com/questions/10930286/socket-io-rooms-or-namespacing). This [quote](https://stackoverflow.com/a/17276952/438249) in particular was enlightening: "_Although it is theoretically possible to create namespaces dynamically on a running app you use them mainly as predefined separate sections of you application. If, on the other hand you need to create ad hoc compartments, on the fly, to accommodate groups of users/connections, it is best to use rooms._"
