### ISSUE TITLE
Logs getting smashed with "pubsub message: disconnect" messages

### ISSUE THREAD

**Issue by sillyfrog** [miguelgrinberg/python-socketio#446]
I have recently upgraded to v4.5.0 and finding that after a while (it appears to be when a user changes pages, causing the websocket connection to disconnect, which makes sense), it smashes the logs with:
```
pubsub message: disconnect
```
And pegs the CPU at 100%

I'm guessing it's related to https://github.com/miguelgrinberg/python-socketio/commit/b68e859045d25903ce1e0a4b729958cb6174df7b

Downgrading to v4.4.0 sorts out the problem.

I'm running an eventlet flask_socketio server, with a redis pub/sub message queue. There are also other processes sending socketio events (via redis), using the `.emit` method on flask_socketio.

I'll try to get this down to a simple test case (I have not been able to yet, very simple servers don't appear to have this issue as yet), and will send it through when I can, but hoping you maybe able to provide some pointers that may assist in debugging further. Cheers!

**Comment by miguelgrinberg** [comment]
Fix is coming soon. Use the master branch of this repo if you want the fix now.

**Comment by sillyfrog** [comment]
Thanks for the quick response! Sorry I didn't see the existing issue - looked for the wrong thing apparently :/
I'll give master a go shortly. Thanks again!
