### ISSUE TITLE
What's the version of python-socket.io

### ISSUE THREAD

**Issue by oldmtn** [miguelgrinberg/python-socketio#452]
I am using the socket.io-client(2.3.0) to connect a torando, python-socketio server.
It can connect to the server, but will failed with 400 Bad Request when ping/pong.

What's the reason?
What's socket.io-client verion should I use for python-socketio(4.5.1)?

Thanks

**Comment by miguelgrinberg** [comment]
The client and the server are released together, so for best results use the same version or as close as possible.

To find out about the error enable detailed logging on the `Server` or `AsyncServer` object, then check your logs.

**Comment by oldmtn** [comment]
Fixed. It was because the python-socketio don't open the cors.
