### ISSUE TITLE
Is there possible to carry cookies when opening a connection?

### ISSUE THREAD

**Issue by xiezhuojin** [miguelgrinberg/python-socketio#454]
I read the documentation but can not find any to carry cookies when I try to open a connection. I am using flask-socketio and using flask-login to authenticate users.

**Comment by xiezhuojin** [comment]
I found there is a header parameter in Client's connect method, can I use it to send cookies?

**Comment by miguelgrinberg** [comment]
You can pass cookies into the server by adding a `Cookie` header. Example:

    sio.connect('http://localhost:5000', headers={'Cookie': 'foo=bar'})

**Comment by a7711555** [comment]
Can I get headers infomation on server side?

**Comment by a7711555** [comment]
I found them in environ, thx a lot!
