### ISSUE TITLE
restricting access to socketio/client files with flask-socketio?

### ISSUE THREAD

**Issue by raheel4839** [miguelgrinberg/python-socketio#455]
Hi,

i am having a problem where i am able to download certain socketio files from my flask application.

sending a call to https://localhost:port/socket.io/ downloads a file with 'sid' and other information.

Similarly i am able to download different socketio files like : socket.io.tar.gz and socket.io.arj and other socketio compressed files by appending the names in the path. e.g. https://localhost:port/socket.io/socket.io.tar.gz gives me the file.

after searching alot about this issue, one thing i think can be helpful is setting serveClient=false as it is recommended in production environment. but i am unable find any information on how and where to set this parameter in case of python flask socketio.

So my question is how can we restrict access to these files? is there some socketio side configuration or some Content-Security-Policy i am missing.

I ll be grateful if someone can help with this issue.

Thanks

**Comment by miguelgrinberg** [comment]
What Socket.IO server are you using?

**Comment by raheel4839** [comment]
i am using socketio with eventlet gunicorn. 
 is this because my connection to socketio is not gaurded and when i send a request at `https://localhost:5000/socket.io/` which is the default endpoint where socketio is exposed, it opens a connection with socketio and send me the `sid` and other information?

**Comment by miguelgrinberg** [comment]
Yes, you are connecting to the Socket.IO endpoint so you will receive a Socket.IO connection response. Add authentication so that you can reject those connections that are from unexpected clients.

**Comment by raheel4839** [comment]
okay i got it now.... thanks for clarifying things.
