### ISSUE TITLE
Doesn't trigger 'disconnect' event for default namespace if custom namespace set

### ISSUE THREAD

**Issue by gex3do** [miguelgrinberg/python-socketio#456]
Please check, it could be a bug in version **4.51** while triggering 'disconnect' event for custom + default namespaces.

File: socketio/server.py
Method: __handle_disconnect_

Current code snippet:
```
        for n in namespace_list:
            if n != '/' and self.manager.is_connected(sid, n):
                self.manager.pre_disconnect(sid, namespace=namespace)
```

should be:

```
        for n in namespace_list:
            if n != '/' and self.manager.is_connected(sid, n):
                self.manager.pre_disconnect(sid, namespace=n) <---- n instead of namespace
```

Example:

When __handle_disconnect_ with hardcoded default namespace is called in __handle_eio_disconnect_ method (_socketio/server.py):
``` 
    def _handle_eio_disconnect(self, sid):
        """Handle Engine.IO disconnect event."""
        self._handle_disconnect(sid, '/')
```

and if there are more namespaces than just default ('/') one, _self.manager.pre_disconnect(sid, namespace=namespace)_ adds '/' namespace as disconnecting (in pending), so that the code which should trigger 'disconnect' event for default namespace will never be called. The method _is_connected_ will return always False as default namespace is already in pending_disconnect list.

```
        if namespace == '/' and self.manager.is_connected(sid, namespace): 
            # WILL BE SKIPPED AND NEVER CALLED
            self.manager.pre_disconnect(sid, namespace=namespace)
            self._trigger_event('disconnect', '/', sid)
```

Server-Side: two event handlers with 2 different namespaces:
```
# THIS WILL BE CALLED
@sio.event(namespace="/users")
def disconnect(sid):
    print('disconnect custom', sid)`

# THIS WILL BE SKIPPED
@sio.event
def disconnect(sid):
    print('disconnect default', sid)
```

Client-Side
```
import socketio
sio = socketio.Client()

@sio.event(namespace='/users')
def connect():
    print('connection established')

sio.connect('http://localhost:5000')
sio.wait()
```

Please check this issue, and in case if I'm wrong, please explain why the event handler with default namespace should not be called if there are more than only default namespace registered.

Thanks.

**Comment by miguelgrinberg** [comment]
Thanks for the detailed report. You are correct, I need to correct this.

**Comment by gex3do** [comment]
> Thanks for the detailed report. You are correct, I need to fix this.

No problem. Thanks.
