### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Sapphire8888** [miguelgrinberg/python-socketio#457]
I've installed python-socketio but don't have socketio installed.
Error is:
Traceback (most recent call last):
  File "manage.py", line 5, in <module>
    sio = socketio.AsyncServer()
AttributeError: module 'socketio' has no attribute 'AsyncServer'

Why this error is happend?
Please help me.

**Comment by miguelgrinberg** [comment]
it's called `python-socketio`. My guess is that you did `pip install socketio`, so you've installing someone else's package.

**Comment by Sapphire8888** [comment]
I solved this problem.
I downloaded and installed your code.
https://github.com/miguelgrinberg/python-socketio.git

Thanks miguelgrinberg.
