### ISSUE TITLE
Client keeps Disconnecting all the Time

### ISSUE THREAD

**Issue by acegilz** [miguelgrinberg/python-socketio#458]
I have python-socketio v 4.5.1.

This is my config:

```python
import socketio

sio = socketio.Client(engineio_logger=True, logger=True)

@sio.event
def connect():
    print('my sid is', sio.sid)
    print('connection established')
    sio.emit('key', 'trial')

@sio.event
def connect_error():
    print("The connection failed!")

@sio.event
def rates(sid):
    # handle the message
    print(sid)


@sio.event
def disconnect():
    print('disconnected from server')

sio.connect('https://wss.live-rates.com', transports="polling", namespaces=['/'])
sio.wait()
```

I would like to receive the incoming data, that should be flowing for very long times, however after just few seconds it keeps crashing.

```
my sid is wyloWyw5okc0hP_VAABK
connection established
{'info': 'Connected to Live-Rates Socket in EU Datacenter.. Feed Subscribed!'}
disconnected from server
my sid is Ahs3Z-XOj0_tGMl_AABL
connection established
disconnected from server
my sid is yDF5zE2AhfT7u7vsAABM
connection established
{'info': 'Connected to Live-Rates Socket in EU Datacenter.. Feed Subscribed!'}
disconnected from server
my sid is cWjcrifMPR0RX7JnAABN
connection established
```

I have this same code running with the native socke.io, node js code and it never disconnects.
I asked support what was the cause of this disconnects, they said: 

>  server namespace disconnect 

regular disconnects are:

> transport close

Any help will be appreciated..

**Comment by acegilz** [comment]
```

Received event "rates" [/]
{"currency":"XLMUSD","bid":0.0492,"ask":0.0507,"high":0.0499,"low":0.0474,"open":0.0478,"close":0.0492,"timestamp":1586369511638}
Sending polling GET request to https://wss.live-rates.com/socket.io/?transport=polling&EIO=3&sid=_kjjoS3nW4-e8NFgAABS
Unexpected status code 503 in server response, aborting
Waiting for write loop task to end
Exiting write loop task
Waiting for ping loop task to end
Sending packet PING data None
PONG response has not been received, aborting
Exiting ping task
Engine.IO connection dropped
disconnected from server
Connection failed, new attempt in 1.25 seconds
Exiting read loop task
Attempting polling connection to https://wss.live-rates.com/socket.io/?transport=polling&EIO=3
Polling connection accepted with {'sid': 'U4ZmN6TDVfdAdGRIAABT', 'upgrades': ['websocket'], 'pingInterval': 25000, 'pingTimeout': 5000}
Engine.IO connection established
Received packet MESSAGE data 0
Namespace / is connected
my sid is U4ZmN6TDVfdAdGRIAABT
Sending packet PING data None
connection established
Emitting event "key" [/]
Sending packet MESSAGE data 2["key","7a392e80c7"]
Sending polling GET request to https://wss.live-rates.com/socket.io/?transport=polling&EIO=3&sid=U4ZmN6TDVfdAdGRIAABT
Reconnection successful


```

**Comment by tcmal** [comment]
I think I'm getting a related error:

```
WebSocket connection accepted with {'sid': '673q08KfoKfVYyuNAVe9', 'upgrades': [], 'pingInterval': 25000, 'pingTimeout': 60000}
Sending packet PING data None
packet queue is empty, aborting
Exiting write loop task
PONG response has not been received, aborting
Exiting ping task
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f2fd1bc46d0>
```

**Comment by acegilz** [comment]
I think the problem may be this.. for some reason the python version cannot upgrade. As you can see, the node.js version immediately upgrades to websocket.

<img width="969" alt="Screenshot 2020-04-08 22 39 15" src="https://user-images.githubusercontent.com/4284362/78836638-6f030b00-79ea-11ea-9d9d-726afef55f3c.png">
<img width="1010" alt="Screenshot 2020-04-08 22 35 49" src="https://user-images.githubusercontent.com/4284362/78836646-732f2880-79ea-11ea-84d3-a097c58f365c.png">

**Comment by miguelgrinberg** [comment]
Your server is returning a 503 error:

    Unexpected status code 503 in server response, aborting

Have you investigate what this is about?

**Comment by acegilz** [comment]
@miguelgrinberg thanks for the quick reply.

The server is running on latest node version socket.io-2.3.0. Is this compatible with it?
As you can see, the client (nodejs) is working. There is no 503 being returned there.

The working client version (javascript) is this: 
https://github.com/Live-Rates/live-rates.com/blob/master/examples/Websocket-Streaming%20API/Node/streaming_client.js

**Comment by miguelgrinberg** [comment]
The 503 code is for a server error. Errors from the side of the client are coded in the 4xx range. Can you please check your server to find why it is responding to requests with a 503 code?

**Comment by acegilz** [comment]
I see the error is really there.. however it doesn't show on the other version.

**Comment by acegilz** [comment]
Ok, just find the issue:
https://github.com/miguelgrinberg/python-socketio/issues/334#issuecomment-544401919

ssl_verify=False was the key for this.
