### ISSUE TITLE
server emit msg to client more than once in redis-mgr when there is more than one server

### ISSUE THREAD

**Issue by QunxingHu** [miguelgrinberg/python-socketio#460]
I start 3 servers, all servers use redis manger which connect to the same redis.
In every server, i started a background thread to listent to selfdefined redis channel(not socket.io channel), to handle msg change, when msg change send msg to selected room.
```
class RedisListener():
    def __init__(self, sio):
        self.rc = redis.Redis(host=cfg.get('REDIS_CONFIG', 'host'), port=cfg.getint('REDIS_CONFIG', 'port'), db=0, password=cfg.get('REDIS_CONFIG', 'pwd'))
        self.ps = self.rc.pubsub()
        self.ps.subscribe(['socket_message'])
        self.sio = sio

    def msg_handler(self, message):
        print(message)
        try:
            json_data = json.loads(message['data'].decode("utf-8"))
            room_name = json_data['room_name']
            data = json_data['data']
            if json_data['room_name']:
                self.sio.emit("server_response", data, room=room_name)
        except Exception as e:
            print(e)
        
    
    def listen_msg(self):
        for item in self.ps.listen():
            if item['type'] == 'message':
                self.msg_handler(item)
```
**It's curious when my redis channel recived a message,  a client has recived 3 same msg.** 

I searched in the code, **the redis-mgr send msg by publish data to socket.io channel,**  if there are 3 servers, **this msg will be published by 3 times,**  the sever that the cliented connected will  handle this msg for 3 times. which led to the client received 3 same msg.

```
    def emit(self, event, data, namespace=None, room=None, skip_sid=None,
             callback=None, **kwargs):
        """Emit a message to a single client, a room, or all the clients
        connected to the namespace.

        This method takes care or propagating the message to all the servers
        that are connected through the message queue.

        The parameters are the same as in :meth:`.Server.emit`.
        """
        if kwargs.get('ignore_queue'):
            return super(PubSubManager, self).emit(
                event, data, namespace=namespace, room=room, skip_sid=skip_sid,
                callback=callback)
        namespace = namespace or '/'
        if callback is not None:
            if self.server is None:
                raise RuntimeError('Callbacks can only be issued from the '
                                   'context of a server.')
            if room is None:
                raise ValueError('Cannot use callback without a room set.')
            id = self._generate_ack_id(room, namespace, callback)
            callback = (room, namespace, id)
        else:
            callback = None
        self._publish({'method': 'emit', 'event': event, 'data': data,
                       'namespace': namespace, 'room': room,
                       'skip_sid': skip_sid, 'callback': callback,
                       'host_id': self.host_id})
```
this will not shown when i use BaseManger instead of RedisManger.
is this correct ? or i used the redis-mgr in an wrong way?

**Comment by miguelgrinberg** [comment]
What are you trying to do with your `message` channel on Redis?

If all you want is to get Socket.IO to work, then that is not something you need to worry about, all you need to do is configure the redis manager and this package takes care of the rest. No need to define your own pub/sub channel.

**Comment by QunxingHu** [comment]
> What are you trying to do with your `message` channel on Redis?
> 
> If all you want is to get Socket.IO to work, then that is not something you need to worry about, all you need to do is configure the redis manager and this package takes care of the rest. No need to define your own pub/sub channel.

I am tring to subscribe  my message channel on redis in a server  background thread and hanle the msg. there will be other application publish message on  my message channel to notify all client to do something.

1. the socket.io works well. 
2. what i am confused is in my case, these msg will be handled mor than one once in every server?

**Comment by miguelgrinberg** [comment]
Is there anything that isn't working, or are you just asking? There are no duplication of messages if that's what you are asking.
