### ISSUE TITLE
 Cannot rapidly emit events from the server

### ISSUE THREAD

**Issue by RaviGhaghada** [miguelgrinberg/python-socketio#464]
I'm working on an application that sends video (in the form of a screenshot) from a server to a client (let's assume there's just one client for now). The client receives that screenshot and displays it.

Previously I had a working version where the client would send an event to the server to request for each screenshot individually but it was slow (obviously). So I threw the video/screenshot emitting part to another threading so that it would keep sending video forever and ever and ever...

Unfortunately, the sio.emit thing doesn't really emit anything. I've spent all my free time in the past 2 weeks to fix this so I was wondering if someone could give me an idea of how to rapidly emit events from the server?

```
#!/usr/bin/python3.6

import eventlet
import socketio
from serverwindow import Serverwindow
from pynput.keyboard import Key, Controller
import threading
import time
controller = Controller()

sw = Serverwindow()
sio = socketio.Server()
app = socketio.WSGIApp(
    sio
)

class Sender (threading.Thread):
    def __init__(self):
        threading.Thread.__init__(self)
    def run(self):
        while True:
            global sio
            data = sw.get_screenshot()
            sio.emit('video', "boo")
            print("sending video")
            time.sleep(2);
s = Sender()

@sio.event
def connect(sid, environ):
    print("connect ", sid)
    sio.emit("video", "boo")
    global s
    sio.start_background_task(s.start)


@sio.on("keypress")
def keypress(sid, data):
    controller.press(data)

@sio.on("keyrelease")
def keyrelease(sid, data):
    controller.release(data)


@sio.event
def disconnect(sid):
    print("disconnect ", sid)

if __name__ == "__main__":
    print("woohoo")
    eventlet.wsgi.server(eventlet.listen(("", 5000)), app)

```

**Comment by RaviGhaghada** [comment]
I'm going through this thread : https://github.com/miguelgrinberg/python-socketio/issues/16

Not sure if I'll solve it because it's 2:25 AM in my time zone but I hope this issue doesn't get closed.

**Comment by RaviGhaghada** [comment]
Okay so I used:
`
sio = socketio.Server(async_mode='threading')`

but now I get this:

> AttributeError: module 'eventlet' has no attribute 'wsgi'

**Comment by miguelgrinberg** [comment]
For eventlet, try the following:

```
#!/usr/bin/python3.6

import eventlet
eventlet.monkey_patch()

import socketio
from serverwindow import Serverwindow
from pynput.keyboard import Key, Controller
import threading
import time
controller = Controller()

# ... everything else the same here
```

**Comment by RaviGhaghada** [comment]
Thank you so much, Miguel. I've tried both things and now my server (successfully) continuously emits pictures to the client. I've gone from 1 FPS to 5 FPS so that's a huge improvement! 

If you have any other suggestions to speed up my video streaming thing, I would love to hear them! 

Once again, thank you so much :)
