### ISSUE TITLE
Mocking / Patching / Testing

### ISSUE THREAD

**Issue by aktary** [miguelgrinberg/python-socketio#465]
I have a socket.io client that connects to a third-party's server.  I'd like to write some tests using fixtures such that I'm validating that my client handles messages appropriately, but without actually connecting to the third party server.  Note that in my case, I had to write a custom class-based namespace to have a catch-all for messages because of how the third party implemented their server.

My question is: how do I do this patch/mock?  I'm thinking I'd mock the `client.connect()` call, so it doesn't actually connect to the server, but then how do I trigger the `trigger_event()` method?

I'm sure there's a simple answer to this that I'm not seeing, but I'd really appreciate some help.

**Comment by miguelgrinberg** [comment]
If you are going to use a mock for the connection, then you can just call the trigger method directly from the test. Would that work?

The alternative is to build a fake server, put it to run in a background thread, and then have the test use the client to connect to it as if it was the real server. This can allow you create more complex tests, but it is also more complex to orchestrate.

**Comment by aktary** [comment]
No idea if that would work, but that feels like the direction I'd want to go since I don't really want to set up a server. 

How do I call the `trigger_event` method from the test, and do I call it directly on the client object, or do I need to access the custom namespace object somehow?

**Comment by miguelgrinberg** [comment]
> How do I call the trigger_event method from the test

I haven't seen how you write your tests, but if this is a namespace, you can just create a namespace and invoke the method on it. That has the advantage that you are also skipping all the connection/disconnection parts.

**Comment by aktary** [comment]
Makes perfect sense.  Thank you.... closing this issue.
