### ISSUE TITLE
Feature - UWSGI cache backend

### ISSUE THREAD

**Issue by johaven** [miguelgrinberg/python-socketio#469]
As it was done on the lib werkzeug (werkzeug.contrib.cache.UWSGICache), it would be interesting to directly using uwsgi as cache method (like redis).

It is not really the message queue function that interests me but rather session management in Flask-SocketIO.

**Comment by miguelgrinberg** [comment]
Flask-SocketIO can use the Flask session. Any session extensions for Flask will work with Flask-SocketIO once installed. Doesn't that address your problem?

**Comment by johaven** [comment]
It would be interesting to have a native support for uwsgi that works "out of box" with no dependencies to install (like redis).

The purpose would be to be able to configure the cache directly this way: _socketio = SocketIO(app, message_queue='uwsgi://')_

https://uwsgi-docs.readthedocs.io/en/latest/Caching.html

**Comment by miguelgrinberg** [comment]
The `message_queue` option has nothing to do with caching though. That is used for the pub/sub mechanism used with a cluster of processes.

**Comment by johaven** [comment]
Ah ! Thanks for the clarification, I thought it was a shared list of pending messages.
