### ISSUE TITLE
Question: Rest over socket using python-socketio client

### ISSUE THREAD

**Issue by AsadJivani** [miguelgrinberg/python-socketio#470]
I have written my socket server using flask-socketio, now I want to write a rest end using python-socketio client, as my client site need rest api which can communicate to my socket server indirectly, I also wanted to use asyncio to avoid continously polling for the request completion so I have tried aiohttp and quart but it didn't work as expected, so is there any example that I can follow where python-socketio client has been used by restful site ?

Thank you.

**Comment by miguelgrinberg** [comment]
I don't understand what you mean. REST APis work over HTTP, not Socket.IO.

**Comment by AsadJivani** [comment]
Sorry for not being clear, I am aware of it, what I'm trying to say is that on a HTTP request I am connecting my socket server and then trying to pass the response to the request provided by the socket server but as Socket.IO is event based so for the response either I have to continuously poll for the response using a condition or use socket.sleep for constant time which is blocking thread, so I am looking for a solution where I can implement python-socketio client and restful server asynchronously, hence applying rest over socket.

**Comment by miguelgrinberg** [comment]
Still not sure I understand, but the `call()` method in the client emits and event and waits for the response from the server. Maybe that's what you are looking for?

**Comment by AsadJivani** [comment]
I hope the code explains it better, anyways it worked, I should have read the documentation carefully, thanks alot.
```
from flask import Flask, request, jsonify, session
import socketio

app = Flask(__name__)
app.config['SECRET_KEY'] = 'mysecret'
sio = socketio.Client()
response = None


@sio.on('login')
def on_login(data):
    global response
    response = data


@app.route('/login', methods=['POST'])
def login():
    sio.connect('http://127.0.0.1:8080')
    sio.call('login', data=(request.form['username'], request.form['password'], request.form['bank']))
    global response
    return jsonify(response)

if __name__ == '__main__':
    app.run(port=9090)
```
