### ISSUE TITLE
Scoket io session id

### ISSUE THREAD

**Issue by hdkhoa162** [miguelgrinberg/python-socketio#472]
Hi guys,
@miguelgrinberg 
I have a question. How can I keep the session id (sid) unchanged for a user's connection even this guy is disconnected and re-connected.

Thanks

**Comment by miguelgrinberg** [comment]
You can't. The sid is a randomly generated connection identifier. It is different every time. Use the `connect` and `disconnect` handlers to map sids to your user ids.

**Comment by hdkhoa162** [comment]
@miguelgrinberg what do you mean by mapping sids to user ids? You mean we can assign session id to user id and use user id as session id? Sorry could you be more specific about this?

**Comment by miguelgrinberg** [comment]
No, it means that you can find out the sid from the user_id or the user_id from the sid. This is so that in a place where you have one of these two you can get the other if you need it.

**Comment by hdkhoa162** [comment]
@miguelgrinberg Gotcha, I have one more question. How can we get user_id from sid? Do we use save_session and get_session? save_session just allows us to store user info using sid as key.

**Comment by miguelgrinberg** [comment]
This is really left for the application to implement. You can store the user id in the session if you like. You can also build a dictionary with these mappings, or store them on redis.

**Comment by hdkhoa162** [comment]
thanks
