### ISSUE TITLE
Question: Interoperability with flask-socketio?

### ISSUE THREAD

**Issue by jamesharding** [miguelgrinberg/python-socketio#473]
Hello!
I know that flask-socketio uses this package as a dependency, but my question is regarding the communication via redis between instances.

I have a rest API built in Flask, and I have a microservice socketio server that is built using this python-socketio package. On the microservice I have initiated it with the following:
`mgr = socketio.AsyncRedisManager('redis://localhost:6379/0')
sio = socketio.AsyncServer(async_mode='aiohttp', client_manager=mgr, logger=True, cors_allowed_origins='*')`

In the rest flask app, I am trying to emit events that will be sent from the python-socketio server, and I have initalised the Flask-SocketIO instance as follows:
`socketio.init_app(app, message_queue='redis://localhost:6379/0', logger=True)`

Both servers are running the latest version of both packages (4.5.1 of socketio).

I can see on redis logs that there are indeed messages being sent from both processes, but the python-socketio instance does not seem to pick up the messages for transmission. Is it intended that one can emit messages via redis from flask-socketio to a python-socketio instance or are they separate in this regard? It looks like the redis pubsub messages might use a different redis key (flask-socketio vs socketio).

Assuming that they are not interoperable, do you have any reccomendations for the best method to provide access to the python-socketio instance from the rest API that is using the application factory (with init_app for all extensions) pattern?

Thanks for all of the help :)

**Comment by miguelgrinberg** [comment]
Flask-SocketIO uses its own channel, that's correct. Either change your python-socketio server to use `flask-socketio`, or change your Flask process to use `socketio` so that both go to the same place.

**Comment by jamesharding** [comment]
Brilliant, thanks for the quick response!
