### ISSUE TITLE
Random Disconnect if message is too large

### ISSUE THREAD

**Issue by anon767** [miguelgrinberg/python-socketio#475]
Hey guys,
I need some help solving this particular issue.
I am using the latest version of python-socketio as server and client both on the same machine but in separate processes.
However I am receiving following warning:
```
WARNING:engineio.client:Connection refused by the server, aborting
```
Then all clients disconnect.

The problem seems to be caused by a client-side emit:
```
self.socketio.emit('some_event', some_message)
```
some_message appears to be really large, about 750 Megabyte. The same piece of code works if I am just sending 7 Megabyte.

Is there a way I could still send this large amount of data? 

Thanks in Advance

**Comment by miguelgrinberg** [comment]
Maybe the `max_http_buffer_size` is what you need? https://python-socketio.readthedocs.io/en/latest/api.html#server-class.

**Comment by anon767** [comment]
Yay, thanks that solved it :)
