### ISSUE TITLE
Client is gone, closing socket for multiple clients

### ISSUE THREAD

**Issue by LovikaJain** [miguelgrinberg/python-socketio#478]
I have a socketio event running inside websocket `send_data()` method which gets the audio data stream and send the audio data to the websocket. When I am connecting the multiple clients, the connection is getting disconnected automatically after sometime and the server throws an error `"Client is gone, closing socket".` Could you suggest what is missing here?

```
class StreamClient(WebSocketClient):
  def __init__()
  // code
 def send_data(self, data):
  try: 
     self.send(data, binary=True)
  raise Exception as err:
     print(err)

 def send_data_to_ws():
	try:
		self.send(data)
		@self.sio.event(namespace='/test')
        async def speech_to_text(sid, data):
			chunk = data
			if chunk == b'':
			   raise Exception("The client has closed the socket")
			elif not chunk:
			   print("chunk hasn't been received yet!")
			else:
				self.send_data(chunk)
				await self.sio.emit('event response', {'data': 'some data'}, namespace='/test')	
	raise Exception as err:
		print(err)

 th = threading.Thread(target=send_data_to_ws)
 th.start()
```

**Comment by miguelgrinberg** [comment]
Are you combining threads with asyncio? That is very hard to do and likely causes blocking for extended periods of time in the asyncio loop. If the loop blocks, then the background tasks of the Socket.IO server cannot maintain connections, and this causes clients to be dropped with the "client is gone" message.

**Comment by LovikaJain** [comment]
Yes, I am using threads. The class I have mentioned in the question is running on a thread from another method and then I am sending send_data_to_ws() in the background. If I don't call the event inside send_data_to_ws() I won't be able to send the data chunks to websocket method send_data(). Is there any way I can run asyncio with threads?

**Comment by miguelgrinberg** [comment]
> Is there any way I can run asyncio with threads?

You can run a thread alongside an asyncio app as long as each runs on its own and does not interact with the other. If you need them to communicate then it gets very complicated. I suggest you look at the [ThreadPoolExecutor](https://docs.python.org/3/library/concurrent.futures.html#threadpoolexecutor) class, which does implement a safe communication mechanism to run jobs in background threads issued from the asyncio loop.

**Comment by LovikaJain** [comment]
will thread work If I implement it with synchronous server? Method inside which event is being called is  running on thread 

```
opened() [default function of websocket]
 send_data_to_ws()
  sync event()
th = threading.Thread(target=send_data_to_ws)
th.start()
```

**Comment by miguelgrinberg** [comment]
Only if you use the `threading` async mode, but you'll have to give up websocket, as this mode only supports long polling.

**Comment by LovikaJain** [comment]
I tried using threadpoolexecutor to run the threads still I am getting error 

> "Client is gone, closing socket"

```
class StreamClient(WebSocketClient):
  def __init__()
  // code
 def send_data(self, data):
  try: 
     self.send(data, binary=True)
  raise Exception as err:
     print(err)
 def opened():
	def send_data_to_ws():
		try:
			self.send(data)
			@self.sio.event(namespace='/test')
			async def speech_to_text(sid, data):
				chunk = data
				if chunk == b'':
					raise Exception("The client has closed the socket")
				elif not chunk:
					print("chunk hasn't been received yet!")
				else:
					self.send_data(chunk)
					await self.sio.emit('event response', {'data': 'some data'}, namespace='/test')	
		raise Exception as err:
			print(err)

 executor = ThreadPoolExecutor(max_workers=1)
 executor.submit(send_data_to_ws)
```

**Comment by miguelgrinberg** [comment]
Sure, but you have a Socket.IO handler in your background thread. Remember what I said, you can have threads happily running alongisde your asyncio server, but they cannot communicate or mix with each other.

I don't really understand what you are trying to do, but I would look into solving the problem all within the context of the asyncio application, without using additional threads.
