### ISSUE TITLE
Cannot connect to server from javascript

### ISSUE THREAD

**Issue by garthtee** [miguelgrinberg/python-socketio#48]
When connecting to my server from a html/javascipt file I get the following error: 

**GET https://127.0.0.1:8000/socket.io/socket.io.js net::ERR_CONNECTION_REFUSED**
**Uncaught ReferenceError: io is not defined**

This is how I connect in the HTML file:

<script src="https://1270.0.0.1:8000/socket.io/socket.io.js"></script>

And this is how I connect in the JS file:

var socket = io('https://127.0.0.1:8000/', {secure: true});

I am emitting values from the server. This works when I do it with NodeJS but I wanted it to be a python server, any help appreciated!

**Comment by miguelgrinberg** [comment]
Have you investigated why you get a connection refused error when downloading the socket.io javascript client? That is the problem, there is no connection related issue.

**Comment by garthtee** [comment]
I downloaded the socket.io javascript client from [here](https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js) instead! Thanks for the reply!
