### ISSUE TITLE
setup flask-socket.io on rpi with nginx

### ISSUE THREAD

**Issue by elad101** [miguelgrinberg/python-socketio#481]
I'm running it fine on my local machine. 
node server runs React JS with proxy 
python flask-socketio

however, when running this on raspberry I'm using nginx to run react.
I'm running nginx 1.14.2, I can't proxy the websocket and I'm getting blocked from the browser.

Flow:
run python flask-socket.io on rpi 
run nginx on rpi
go from my laptop to raspberrypi.local 
when the web app is trying to call the ws polling I'm getting cors error

**Comment by miguelgrinberg** [comment]
And did you configure CORS properly on the Socket.IO server? The default CORS configuration is conservative, you have to adapt it to your needs.

**Comment by elad101** [comment]
I assume you meant `socketio = SocketIO(app, cors_allowed_origins='*')`
yes.

**Comment by miguelgrinberg** [comment]
Well, then you need to find more information about the problem. Is there anything in the browser's console or network tabs? Anything in the server log? Did you enable verbose Socket.IO logs in the server?

Also, configuring CORS in general does not mean disabling it like you did. That's an insecure approach, better to configure your origin(s).
