### ISSUE TITLE
Disable client reconnection logic on the fly

### ISSUE THREAD

**Issue by bhakta0007** [miguelgrinberg/python-socketio#482]
I have created a systemd service out of a python program that used async client. When the service is started - the client connects to a server - and keeps the connection alive.

I have let the defaults of the reconnection parameters as-is - so the client can reconnect to the server on disconnect event.

On "service <> stop", I call sio.disconnect() method the client but I see that (not all the time but say 1 out of 3 times) the client immediately attempts to reconnect - causing the thread not to exit.

Is this an expected behavior? The side effect of this is the service does not exit voluntarily when asked to do so.

How can I disable the reconnection logic on the existing client object?

**Comment by miguelgrinberg** [comment]
The reconnection should not trigger when you disconnect explicitly, regardless of your settings. This is only for a connection that is lost due to external factors.

Do you think you can create a simplified version of your service that I can use to test this?

**Comment by bhakta0007** [comment]
Here you go.

Server:   
 python-socketio/examples/server/wsgi
Running on port 5000

Client (Note: I had to take my existing app, and create a test version. Its not pretty)

testSIO.py

```
import asyncio
import click
import os
import time
import signal
import socketio
from threading import Lock, get_ident
import sys

PIDFILE = "webSocketAgent.pid"
HOST = "bhakta-test.3022"
WSURL = "http://127.0.0.1:5000"
TENANT = "tenant1"

loop = asyncio.get_event_loop()
sio = socketio.AsyncClient()


BG_THREAD = None
BG_THREAD_LOCK = Lock()
RUN_AGENT = True
BG_HANDLERS = []



async def background_thread():
    count = 0
    while True:
        count += 1
        if count % 100 == 0:
            print("BG thread {} has {} handlers".format(
                get_ident(), len(BG_HANDLERS)))
        await sio.sleep(5)


@sio.event
async def connect():
    global BG_THREAD
    print('connected to server')
    with BG_THREAD_LOCK:
        if BG_THREAD is None:
            #BG_THREAD = sio.start_background_task(background_thread)
            print("Started BG thread")


@sio.event
async def disconnect():
    global BG_THREAD
    # from celery.contrib import rdb; rdb.set_trace()
    print('Disconnected from server')
    if BG_THREAD:
        BG_THREAD.cancel()
        BG_THREAD = None
        print("Stopped BG thread")


def int_handler():
    global RUN_AGENT
    RUN_AGENT = False
    print("Stop Agent")

    for task in asyncio.Task.all_tasks():
        print("Cancel task {}".format(task))
        task.cancel()

    if BG_THREAD:
        BG_THREAD.cancel()
        print("stop Agent - stop BG Task")

    # Ideally I must be doing await sio.disconenct but
    # co-routines cannot be setup as hanlder functions
    # I am not sure how to handle this..
    if sio:
        print("stop Agent: disconnect sio")
        sio.disconnect()

    print("stop Agent: Gracefully exiting")


async def main_loop():
    print("main_loop - enter")
    while RUN_AGENT:
        try:
            print("Try to connect to {}".format(WSURL))
            await sio.connect(WSURL, headers={"client_id": HOST, "tenant": TENANT, "isAgent": "True"}, namespaces=['/agents'])
            await sio.wait()
        except Exception as ec:
            print(
                "Agent exited with error: {}, re-try in 2 seconds".format(ec))
            await sio.sleep(2)
    print("main_loop - exit")


@click.command()
@click.option('--version', help='Show version')
def main(version):
    if version:
        print("Version: {}".format(env.get("version", "")))
        sys.exit(0)

    print("Agent: start..")
    loop.add_signal_handler(signal.SIGINT, int_handler)
    loop.add_signal_handler(signal.SIGTERM, int_handler)

    try:
        loop.run_until_complete(main_loop())
    finally:
        pass

    print("hostAgent: ended..")


if __name__ == '__main__':
    main()

```


Repro:

1. Start server
2. pyton testSIO.py
3. Wait few seconds, press Ctrl-C. 
4. If program exits - then repeat (2, 3) again.

When I try this 10 times, I get the situation where the program doesn't exit 3-4 times.

**Comment by miguelgrinberg** [comment]
The problem is in your signal handler. If I comment out the SIGINT handler then Ctrl-C exits immediately and cleanly.

Haven't looked in detail at the problem, but for sure you are doing too much in this handler. You can't just cancel all asyncio tasks. The Socket.IO server also has a SIGINT handler and it uses it to end the server cleanly. It cannot do that if you cancel all tasks.

You shouldn't be calling disconnect either, since the package's own handler takes care of that.

Setting a handler via the loop like you are doing appears to not provide a pointer to the next function in the signal chain. This is necessary so that you can cleanup your own stuff, and then invoke the next callback to give the socketio server a chance to end.

**Comment by bhakta0007** [comment]
Thanks Miguel. Let me give these suggestions a try and update back.

**Comment by bhakta0007** [comment]
@miguelgrinberg  removing the int_handler does the trick. I cannot recollect why i put it in the first place. Things work just fine without it.. Thanks for checking this out.
