### ISSUE TITLE
How to create secure server client application using python-socketio?

### ISSUE THREAD

**Issue by secretlyvogon** [miguelgrinberg/python-socketio#484]
I need to create secure connections over https/wss. I was going through this [python-grpc-ssl library](https://github.com/joekottke/python-grpc-ssl) and I need something similar. [WebSockets' secure example](https://websockets.readthedocs.io/en/stable/intro.html#secure-example) offers similar functionality, but I can't use it as I need event-based communication that this library offer. 

For my simple tests, I have generated my own certificate and key. I am using aiohttp server where I am passing the above to `ssl_context` argument like so:

```
ssl_context = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
ssl_context.load_cert_chain('myRootCA.pem','myRootCA.key')
web.run_app(self.app, port=8080, ssl_context=ssl_context)
```

This creates an https server on port 8443 which I intend to connect to. I am unable to figure out how to go about this with the python socket-io client. For my use case, I need the server and client to verify each other and hence passing `ssl_verify=False` is not an option for me. Please help me understand how I can go about this.

Thanks.

**Comment by miguelgrinberg** [comment]
This is currently not implemented. Both the option of passing a CA or a client certificate have yet to be implemented. Leaving this issue open as a reminder.

**Comment by witling** [comment]
So currently there is no way of creating an `AsyncServer` for self signed certificates?

**Comment by miguelgrinberg** [comment]
I personally prefer to handle the encryption outside of the Python server. Nginx works really well for this. So there are ways to support TLS and certificates, just not in the same server.

**Comment by secretlyvogon** [comment]
@miguelgrinberg if use Nginx as a reverse proxy for TLS, how can I use the python-socketio client library to securely connect to it?

**Comment by miguelgrinberg** [comment]
The Socket.IO client accepts an initialized HTTP session object (either requests or aiohttp depending on which client you use).

**Comment by Ivaylo-Korakov** [comment]
Hi,
I understand that usually, things run behind something else that provides the HTTPS like nginx, traefik etc.
But for example, when you run things in dev we like to have all of our things with HTTPS. When developing we don't have access to our ingress controllers that provide the HTTPS and it would be pretty annoying and slow to build images each time we need to make a change and test it.
We have our Flask server run with HTTPS in development and that has been working perfectly for us.
Just wanted to voice my support for this issue.

**Comment by miguelgrinberg** [comment]
@Ivaylo-Korakov Are you interested in server-side SSL support? This issue is for client-side, and as I said above, it can be implemented by passing an initialized requests or aiohttp session. For server-side SSL you can enable SSL in your web server, this package does not have its own web server.
