### ISSUE TITLE
ConnectionRefusedError not working

### ISSUE THREAD

**Issue by databasedav** [miguelgrinberg/python-socketio#487]
This is on Python 3.8.2 with
```
python-engineio==3.12.1
python-socketio==4.5.1
uvicorn==0.11.5
```
and you can reproduce with
```python
# server.py
import socketio
from socketio.exceptions import ConnectionRefusedError

sock = socketio.ASGIApp(
    socketio.AsyncServer(async_mode="asgi"),
)

@sock.engineio_server.event
async def connect(sid, environ):
    # raise Exception()
    raise ConnectionRefusedError()
```
```python
# client.py
import asyncio
import socketio

async def test():
    c = socketio.AsyncClient()
    await c.connect('ws://localhost:8002')
    await asyncio.sleep(1)
    await c.disconnect()
    await asyncio.sleep(1)

asyncio.run(test())
```
and running `uvicorn --host 0.0.0.0 --port 8002 server:sock` and `python client.py`

raising an `Exception` produces the expected behavior.

**Comment by miguelgrinberg** [comment]
Sorry, but I can't reproduce. I get the expected `ConnectionError` in the client using exact copies of your server and client:

```
socketio.exceptions.ConnectionError: Connection refused by the server
```

**Comment by databasedav** [comment]
Hmm not sure why reproduction isn't working. On my end, downgrading to 4.3.1 solves the issue so it seems to be something introduced in 4.4.0. I'm on Ubuntu 20.04 but not sure if that is relevant. I'll investigate further.

**Comment by miguelgrinberg** [comment]
Sorry, I gave your code another run today and I do see the problem. I must have put your server on the standard 8000 port yesterday, instead of the custom 8002 that you are using.

**Comment by ysde** [comment]
Hi @miguelgrinberg 

I raise ConnectionRefusedError('authentication failed') in `on_connect` event.

But the client only got `ConnectionError('Connection error')` when I print the exception.

The goal is to get the `authentication failed` message to tell the client. Just like the instruction in the documentation.

```
Sometimes it is useful to pass data back to the client being rejected. In that case instead of returning False socketio.exceptions.ConnectionRefusedError can be raised, and all of its arguments will be sent to the client with the rejection message:

@sio.event
def connect(sid, environ):
    raise ConnectionRefusedError('authentication failed')
```
======================================================================
Here is the code

```
try:
    sio.connect('http://xxxxxxxxxxxxx')
except ConnectionError as ex:
    print(repr(ex))
```

**Comment by miguelgrinberg** [comment]
@ysde can you please run your application with `engineio_logger=True` set in the server object? That should give me more idea of what's going on. Thanks.

**Comment by databasedav** [comment]
@miguelgrinberg I think this issue might have resurfaced? here's a repro:

`Pipfile`
```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
python-socketio = "*"
uvicorn = {extras = ["standard"],version = "*"}
aiohttp = "*"

[requires]
python_version = "3.8"

```

`server.py`
```python
import socketio
from socketio.exceptions import ConnectionRefusedError

sock = socketio.ASGIApp(
    socketio.AsyncServer(
        async_mode="asgi",
        monitor_clients=False,
        engineio_logger=True
    ),
)

@sock.engineio_server.event
async def connect(sid, environ):
    # raise Exception('custom')
    raise ConnectionRefusedError('custom')

```

`client.py`
```python
# client.py
import asyncio
import socketio
import traceback

async def test():
    c = socketio.AsyncClient()
    try:
        await c.connect('ws://localhost:8002')
        await asyncio.sleep(1)
        await c.disconnect()
        await asyncio.sleep(1)
    except:
        traceback.print_exc()

asyncio.run(test())

```

here's what i see from the server after running `uvicorn --host 0.0.0.0 --port 8002 server:sock` and then `python client.py`
```
Server initialized for asgi.
INFO:     Started server process [54517]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8002 (Press CTRL+C to quit)
iygUxmw6v1ROJCEVAAAA: Sending packet OPEN data {'sid': 'iygUxmw6v1ROJCEVAAAA', 'upgrades': ['websocket'], 'pingTimeout': 5000, 'pingInterval': 25000}
INFO:     127.0.0.1:56026 - "GET /socket.io/?transport=polling&EIO=4&t=1609627767.9831548 HTTP/1.1" 200 OK
iygUxmw6v1ROJCEVAAAA: Received request to upgrade to websocket
INFO:     ('127.0.0.1', 56026) - "WebSocket /socket.io/" [accepted]
iygUxmw6v1ROJCEVAAAA: Upgrade to websocket successful
iygUxmw6v1ROJCEVAAAA: Received packet MESSAGE data 0
iygUxmw6v1ROJCEVAAAA: Sending packet MESSAGE data 4{"message":"custom"}
```
the client never raises an exception ...

based on the logs, it looks like the server sends out the connection refused message but doesn't actually refuse the connection? 

thanks!

**Comment by miguelgrinberg** [comment]
@databasedav the Socket.IO protocol changed and the way this works had to change to accommodate the new version of the protocol. A connection rejected exception triggers a `connect_error` event in the client, but it does not raise an exception anymore, since the connection did not actually fail, the server just refused it.

**Comment by databasedav** [comment]
@miguelgrinberg ok got it, so it's up to the client to disconnect after getting a `connect_error`?

**Comment by miguelgrinberg** [comment]
@databasedav the disconnect handler should not be invoked for a rejected connection. Are you saying that it is being invoked in your application? The client should be disconnecting on its own after receiving the rejection and invoking the `connect_error` event handler.

**Comment by kouohhashi** [comment]
Hi, is this issue solved?

I use Python for server and Javascript for client and I can not get ConnectionRefusedError exception at client.

server-side (Python):
```
python-socketio: 5.5.1  
python-engineio: 4.3.1
```

client-side (Javascript):
```
socket.io-client: 4.4.1
```

ConnectionRefusedError do not even emit disconnect, or connect_error event at all.
Is there any way to get errors like below?

```
try {
  socketio.connect()
} catch (err) {
 console.log("err: ", err) // <-- here we get message from ConnectionRefusedError
}

```
Thanks in advance.

**Comment by miguelgrinberg** [comment]
@kouohhashi this package has no control over how the JavaScript client reports connection errors. See the `connect_error` event in their docs: https://socket.io/docs/v4/client-socket-instance/#events
