### ISSUE TITLE
Async Client doesn't reconnect?

### ISSUE THREAD

**Issue by QuirijnLangedijk** [miguelgrinberg/python-socketio#495]
When I close my (NestJS) server, the Python client disconnects, but whereas my website reconnects, Python never reconnects again when I start the server again, even though reconnect is on. Any idea whats causing this?

![image](https://user-images.githubusercontent.com/31623496/83163832-c7fa4000-a10b-11ea-8b63-cb48a87cab6a.png)

![image](https://user-images.githubusercontent.com/31623496/83163848-ccbef400-a10b-11ea-93c2-d0c3222d14f8.png)

Am I missing an event?

**Comment by miguelgrinberg** [comment]
Are you using latest versions of all packages? I just retested using the `latency.py` for the server and `latency_client.py` for client and reconnection works fine.
