### ISSUE TITLE
I need to emulate this JS Code with python but is not working for me

### ISSUE THREAD

**Issue by pestrac** [miguelgrinberg/python-socketio#496]
I need to emulate this JS Code with python but is not working for me

JS Code
-------------------------
const io = require('socket.io-client');

const ioOptions = {
    autoConnect: true,
    rejectUnauthorized: false // needed when using a self signed cert
};

const apiAddress = 'https://localhost:8443/mt/api/rt/v1';
const socket = io(apiAddress, ioOptions)
    .on('connect', () => console.log('connected'))
    .on('connect_error', error => console.log('connect_error):', error))
    .on('error', error => console.log('error:', error));

console.log('open connection');
socket.open();

socket.emit(
    'read-event-subtopics',
    {},
    response => console.log('read-event-subtopics:\n', JSON.stringify(response, undefined, '  '))
);

Python Code
--------------------------
import asyncio
import time
import socketio

loop = asyncio.get_event_loop()
sio = socketio.AsyncClient(engineio_logger=True,ssl_verify=False)
start_timer = None

async def send_ping():
    global start_timer
    start_timer = time.time()
    await sio.emit('read-event-subtopics',{},callback=notification)

@sio.event
async def connect():
    print('connected to server')
    await send_ping()

@sio.event
async def notification(data):
    global start_timer
    latency = time.time() - start_timer
    print('latency is {0:.2f} ms'.format(latency * 1000))
    print(data)
    await sio.sleep(1)
    await send_ping()

async def start_server():
    await sio.connect('https://127.0.0.1:8443/mt/api/rt/v1')
    await sio.wait()

if __name__ == '__main__':
    loop.run_until_complete(start_server())

JS Response
---------------------------------
open connection
connected
read-event-subtopics:
 {
  "status": "success",
  "result": [
    "ALL",

Python Response
---------------------------------
Attempting polling connection to https://127.0.0.1:8443/socket.io/?transport=polling&EIO=3
Polling connection accepted with {'sid': 'IFY6mxSuso62zyciAAAd', 'upgrades': ['websocket'], 'pingInterval': 10000, 'pingTimeout': 5000}
Received packet MESSAGE data 0
Attempting WebSocket upgrade to wss://127.0.0.1:8443/socket.io/?transport=websocket&EIO=3
connected to server
Sending packet MESSAGE data 21["read-event-subtopics",{}]
WebSocket upgrade was successful
Sending packet PING data None
Received packet PONG data None

**Comment by miguelgrinberg** [comment]
Use this to connect:

    await sio.connect('https://127.0.0.1:8443', namespaces=['/mt/api/rt/v1'])

**Comment by pestrac** [comment]
Thanks for your response, but unfortunately not works for me.

I also tried this:
await sio.emit('read-event-subtopics',{},callback=notification,namespace='/mt/api/rt/v1')

**Comment by miguelgrinberg** [comment]
Well, there might be more errors that you need to debug, but the line that I gave you is the correct way to connect.

**Comment by pestrac** [comment]
Adding namespace at @sio.event(namespace='/mt/api/rt/v1') works!

Thank you very much for your help and for your work.
