### ISSUE TITLE
On Multiple worker processes

### ISSUE THREAD

**Issue by charyorde** [miguelgrinberg/python-socketio#50]
Should messages be published to the default `socketio` exchange or any custom exchange can be used?

**Comment by miguelgrinberg** [comment]
You do not need to post directly to the exchange, this package creates the exchange and posts to it. All of this is done inside the `KombuManager` class. The name of the exchange is controlled by the `channel` argument passed on the class constructor: https://github.com/miguelgrinberg/python-socketio/blob/master/socketio/kombu_manager.py#L32.
