### ISSUE TITLE
Right way put database connection  in case with socketio.ASGIApp

### ISSUE THREAD

**Issue by h0rn3t** [miguelgrinberg/python-socketio#500]
Hello, in aiohttp we have aiohttp.web.Application object that supports dict interface, and we have place to store database connections or any other resources that we can share between handlers.

What "right way" do same in socketio.ASGIApp ? because we can't do some thing like that

```
    app['mongo_conn'] = motor.motor_asyncio.AsyncIOMotorClient(config['DEFAULT']['MONGODB_HOST'], 27017)
    app['redis_conn'] = await aioredis.create_redis((config['DEFAULT']['REDIS_HOST'], 6379))
```

**Comment by miguelgrinberg** [comment]
ASGI is not a web framework, it's just a protocol. If you are using a web framework on top of ASGI like maybe Quart, then use the framework facilities. If you are not using any web framework, then just create your own application class, populate it with the things that you need, and then create an instance of it in the global scope.

```python
class App:
    def __init__(self):
        self.mongo_conn = ...
        self.redis_conn = ...

app = App()
```

**Comment by h0rn3t** [comment]
thanks
