### ISSUE TITLE
Sanic server freezes after connect

### ISSUE THREAD

**Issue by autogestion** [miguelgrinberg/python-socketio#501]
Have tried this example 
https://github.com/miguelgrinberg/python-socketio/tree/master/examples/server/sanic
with sanic v. 19.12.2 and 20.3.0  + python-socketio v. 4.6.0
Server allows client to connect, after this any interaction is impossible

Have tried to run  app with  app.run(protocol=HttpProtocol)
It throws AttributeError: 'HttpProtocol' object has no attribute 'websocket_handshake'
but after this it works fine

**Comment by miguelgrinberg** [comment]
Quite possible that the sanic project made backwards incompatible changes without letting me know. I don't use sanic myself. I'll investigate when I have a moment, but if you are able to debug this and report or post a solution please do.

**Comment by miguelgrinberg** [comment]
Not planning to invest time fixing Sanic bugs anymore. Use the ASGI support instead.
