### ISSUE TITLE
How to pass parameters in sio.connect

### ISSUE THREAD

**Issue by Renjila** [miguelgrinberg/python-socketio#507]
My C# code to connect a server is 
var options = new IO.Options();
options.Path = "/xxxx/websocket/socket.io";
options.AutoConnect = false;
options.Cookies.Add("jwt", jwtToken); 
var socket = IO.Socket(url, options);

In python 
-------------
import socketio
sio=socketio.Client()
Please let me know how to provide the options in sio.connect().

**Comment by miguelgrinberg** [comment]
To disable reconnect:

    sio = socketio.Client(reconnection=False)

To pass a cookie:

    sio.connect(url, headers={'Cookie': f'jwt={jwtToken}'})

**Comment by Renjila** [comment]
Thank you for your reply.
I have given the followin command

sio.connect(erServer,headers={'Cookie': f'jwt={jwtToken}'},socketio_path='/aaa/bb/websocket/socket.io')

It is throwing the error as follows

simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Please let me know what could be the problem.
Thanks

**Comment by miguelgrinberg** [comment]
Can I see the complete stack trace of the error please?

**Comment by RenjilaRajan** [comment]
when I try the actual socket io path , I get the following error
![image](https://user-images.githubusercontent.com/65487501/85015017-daf7b180-b199-11ea-9158-3c89c163dbc5.png)

when I try with a dummy socket io path, I get the following error.
![image](https://user-images.githubusercontent.com/65487501/85015125-09758c80-b19a-11ea-8e95-b0465e8007ae.png)

Could it be a error from the server side?

**Comment by miguelgrinberg** [comment]
Your server isn't responding with a valid response. Do you know what version of Socket.IO your server uses? It might be an old version. The Python client works with Socket.IO 1.0 and up, it is not compatible with any of the older 0.x releases.

**Comment by Renjila** [comment]
Currently I am not sure about the version of this remote server. Can this response be expected , if server is down /not running?

**Comment by miguelgrinberg** [comment]
The server is up, since it is sending a response. But the response is invalid.

**Comment by Renjila** [comment]
Thank you.
