### ISSUE TITLE
connect_error reason

### ISSUE THREAD

**Issue by mcg88** [miguelgrinberg/python-socketio#508]
```
@sio.event
def connect_error():
    print("The connection failed!")
```

Is there a way to see what caused the connection to fail? I was looking at this issue which accepts the message parameter, but on the latest version this does not seem to work.

https://github.com/miguelgrinberg/python-socketio/issues/344#issuecomment-557880894

**Comment by miguelgrinberg** [comment]
How is it not working? The `connect_error()` handler takes one argument, at least it should. I would think not defining an argument like you have in your example above would not work.

**Comment by mcg88** [comment]
The example I posted is straight from the [docs](https://python-socketio.readthedocs.io/en/latest/client.html#creating-a-client-instance. ).

If I put in a positional argument (from the issue answer I posted) such as:
`@sio.event
def connect_error(message):
    print("The connection failed! ", message )`

The code errors out saying expected 0 positional arguments, received one.

**Comment by miguelgrinberg** [comment]
Okay, I think I now understand what's going on.

There are two situations in which the connect_error handler is invoked. The most common is when the client is unable to connect. In this situation there is one argument.

The other situation is when the server sends an `ERROR` packet. So in this case, the physical connection was made, but the server rejected the client. In this situation, the arguments that are sent are whatever the server sent in this packet. In your case it appears your server isn't passing any arguments.

Do you have access to the server? Why is it rejecting the connection and how?

**Comment by mcg88** [comment]
No, its a third party server so no access there. The situation I noticed it was where it was connected for a period of time. When my app errored out in the stack trace I saw a connection refused error

**Comment by miguelgrinberg** [comment]
Best way to handle the two error cases is to set a default value for your message argument.

```python
@sio.event
def connect_error(message=None):
    print("The connection failed! ", message )
```
