### ISSUE TITLE
ValueError: event names cannot contain hypens

### ISSUE THREAD

**Issue by davidskuza** [miguelgrinberg/python-socketio#51]
With Socket.io Node stack we can use names-with#hypens.

**Comment by MFlyer** [comment]
Hi @davidskuza & @miguelgrinberg , this should be updated:
hypens ( minus symbol ) can't be used on namespaces too

Mirko

**Comment by PierrePaul** [comment]
Just linking #36 here, in case someone ask why **hyphens** support has been removed.
