### ISSUE TITLE
Has the Event server can exit?

### ISSUE THREAD

**Issue by ghost** [miguelgrinberg/python-socketio#510]
Has the Event server can exit?

like this:
@sio.on("close_server")
def close_server(sid):
    sio.close()

app = socketio.WSGIApp(sio, socketio_path="/simulate")
eventlet.wsgi.server(eventlet.listen(("127.0.0.1", 8889)), app)

**Comment by miguelgrinberg** [comment]
This is something that depends on the web server that you use. This package does not provide a server.

I believe in eventlet you can trigger an exit by raising a `SystemExit` exception, but not completely sure this is reliable as it does not appear to be documented.
