### ISSUE TITLE
Client hangs on exit

### ISSUE THREAD

**Issue by emannguitar** [miguelgrinberg/python-socketio#513]
Using v4.6.0/python 3.8

I have a program that uses a socketio Client to receive notifications that information on the backend has changed, and that the program needs to refresh its local data. Attempting to exit the program hangs until I KeyboardInterrupt, giving the following output:

```
Exception ignored in: <module 'threading' from '/usr/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
  File "/home/ethan/.local/lib/python3.8/site-packages/engineio/client.py", line 43, in signal_handler
    return original_signal_handler(sig, frame)
  File "/home/ethan/.local/lib/python3.8/site-packages/socketio/client.py", line 28, in signal_handler
    return original_signal_handler(sig, frame)
KeyboardInterrupt:``
```

I've found that if I manually ```disconnect()``` the Client object, it solves this issue _most of the time._

**Comment by miguelgrinberg** [comment]
How do you exit when you don't disconnect? The client uses a bunch of threads, you can't just really exit, the disconnect is actually doing all the clean up.

**Comment by emannguitar** [comment]
I am trying to disconnect all clients manually, and far as I can tell all of my socketio clients are disconnected before exit. This is specifically happening at the end of a pytest run, so there's a chance some fixture kept something alive when it shouldn't have, but I'm pretty sure I'm disconnecting all active clients (I have however added logging to confirm that all clients `.connected == False`.)

Is there any way to see which client is staying alive? Perhaps something is slipping under my radar

**Comment by emannguitar** [comment]
I've now found the sneaky client that was still connected, and that seems to have solved my issue. Just to be clear - the client must be manually disconnected before exit the parent program?

**Comment by miguelgrinberg** [comment]
For a clean exit yes, you have to disconnect the client(s).
