### ISSUE TITLE
Can I create default event handler in python-socketio server?

### ISSUE THREAD

**Issue by ahmed-tracxpoint** [miguelgrinberg/python-socketio#515]

**Comment by miguelgrinberg** [comment]
What do you mean by "default"? Do you want a "catch-all" handler? There is no direct support for this, but if you implement a class-based namespace you can override the [`trigger_event`](https://github.com/miguelgrinberg/python-socketio/blob/master/socketio/namespace.py#L8) method and add your logic there.

**Comment by ahmed-tracxpoint** [comment]
Yes I mean , in case this event not exist in this namespace handler just call default function.
Thank you I understand your point

**Comment by miguelgrinberg** [comment]
@ahmed-tracxpoint No. This is the method that dispatches events to the `on_whatever` methods. It is called for all events, whether they are defined or not.

**Comment by ahmed-tracxpoint** [comment]
Yeah so I should add the "else" part in case this handler_name doesn't exist just call a static handler I already define in my Namespace Object
