### ISSUE TITLE
In scan mode, screen reader focus is moving out of "Sample Panel" in backward navigation

### ISSUE THREAD

**Issue by SyedRehmanRazvi** [miguelgrinberg/python-socketio#516]
User Experience: 
Users who rely on Screen reader for navigating between elements are getting affected as screen reader focus is moving out of "Sample Panel" in backward navigation. User will be confused if the screen reader focus moves to background elements and announcing inappropriate information.

Test Environment:
OS: Win 10 
OS Version: 1909 (OS Build 18363.778) 
Browser: Edge - Dev (Version 84.0.488.1)
URL: https://fabricweb.z5.web.core.windows.net/oufr/7.78.2/#/examples/panel

Screen reader : Narrator
Repro Steps:
Step 1: Turn on Narrator and open above URL using Edge Browser.
Step 2: Open above URL
Step 3: Verify screen reader focus is moving out of "Sample Panel" in backward navigation

Actual:
screen reader focus is moving out of "Sample Panel" in backward navigation

Expected:
screen reader focus should not move out of "Sample Panel" in backward navigation
![Dialog Focus](https://user-images.githubusercontent.com/53210862/86763011-aa9e8700-c064-11ea-942a-33d9e0978a41.png)

**Comment by miguelgrinberg** [comment]
You submitted a bug for the wrong project. This is a server project, nothing to do with browser apps.
