### ISSUE TITLE
Client throws "TypeError 'Handlers' object not callable" if no original SIGINT handler

### ISSUE THREAD

**Issue by dbrnz** [miguelgrinberg/python-socketio#517]
I get this exception when interrupting a simple socketio client application that is sleeping. It appears to be identical to miguelgrinberg/python-engineio/issues/139 and indeed applying changing [line 26](https://github.com/miguelgrinberg/python-socketio/blob/master/socketio/client.py#L26) of `client.py` to read:
```
    if callable(original_signal_handler):
        return original_signal_handler(sig, frame)
    else:  # pragma: no cover
        # Handle case where no original SIGINT handler was present.
        return signal.default_int_handler(sig, frame)
```
fixes things.

**Comment by miguelgrinberg** [comment]
Yes, that fix should have been applied on this package as well. Do you want to submit a PR for it?
