### ISSUE TITLE
python-socketio + sanic example

### ISSUE THREAD

**Issue by staticdev** [miguelgrinberg/python-socketio#519]
Hi, I just read the documentation and started with socketio and have some questions:

1) I got confused about [installation for the client](https://python-socketio.readthedocs.io/en/latest/client.html):

I this case I needed:
pip install "python-socketio[asyncio_client]" ?
pip install "python-socketio[sanic]" ?
pip install "python-socketio[asyncio_sanic]" ?

It wasn't quite clear for me.

2) I just read the [documentation about Sanic](https://python-socketio.readthedocs.io/en/latest/server.html#sanic)...

`app = Sanic()` refers to a class imported from socketio or from sanic?

3) Maybe an example in the docs would help.. I didn't find one with sanic on ReadTheDocs and in the https://github.com/miguelgrinberg/python-socketio/tree/master/examples

Thanks a lot.

**Comment by miguelgrinberg** [comment]
> I got confused about installation for the client:

@staticdev the client is standalone, it does not integrate with any frameworks. To use the client inside a Sanic app, run:

    pip install "python-socketio[asyncio_client]"

Where did you see the other options? They don't exist.

> I just read the documentation about Sanic...

You jumped to the server section, so none of that applies to you if you are using the client.

> Maybe an example in the docs would help.. I didn't find one with sanic on ReadTheDocs and in the

There are no framework specific examples. Use the asyncio client examples.
