### ISSUE TITLE
HTTP Basic Authentication?

### ISSUE THREAD

**Issue by 9ukn23nq** [miguelgrinberg/python-socketio#520]
Does SocketIO support authenticating with endpoints which require HTTP basic authentication? I cannot see any indication that it does / does not in documentation.

Thanks!

**Comment by miguelgrinberg** [comment]
Sure, you can check any HTTP headers in the connect handler and decide to accept or reject the client based on that.

**Comment by 9ukn23nq** [comment]
Thanks,

```
def init(server, username=None, password=None):
    headers = {}
    if username:
        headers["Authorization"] = "Basic " + base64.b64encode(f"{username}:{password}".encode()).decode()
    sio.connect(server, headers=headers, namespaces=['/notify'])
```

Appears to work :)

**Comment by miguelgrinberg** [comment]
Oh, right! You were asking about the client, but my answer was for the server. Glad you figured it out anyway. :)
