### ISSUE TITLE
Handle ping or pong action in code.

### ISSUE THREAD

**Issue by Hammer2900** [miguelgrinberg/python-socketio#521]
Question, can i handle ping or pong action in code like i do with connect and disconnect events ?
I paste this code but this is not work.

```
@sio.event
def ping(sid):
    print(sid)
```

**Comment by miguelgrinberg** [comment]
No, there are no ping/pong events. Do you have a use for this? PIng-pong events are internal to the Socket.IO protocol.

**Comment by Hammer2900** [comment]
In my case i try store user session in Redis to use it in other services, like main storage with main interface. I can get socketio id simply get email address from Redis. Problem is if socketio server restart and id don't delete id from Redis... so i need set time to delete record if refresh signal not update this record, that's why i need ping signal. I see that's client make this requests but how it handled... i check code  and understand, this not possible =) then you try check other approach.

**Comment by miguelgrinberg** [comment]
A ping/pong exchange occurs every 25 seconds. It would be overkill for your application to refresh your redis for every user every 25 seconds. Consider that if you have 1000 users connected you would be doing 2400 redis updates per second with your system 100% idle.

To handle the server restart problem you could do a clean up of your redis entries at start up. Besides that you can use the connect and disconnect handlers to add/remove entries from redis as appropriate.
