### ISSUE TITLE
emit() doesn't work from a different file

### ISSUE THREAD

**Issue by 0xBC9** [miguelgrinberg/python-socketio#527]
I'm trying to call emit from within a different file. Here's my files:
server.py:
```
from other_file import a
from aiohttp import web
import socketio

sio = socketio.AsyncServer(logger=True) 
app = web.Application()
sio.attach(app)

@sio.on("Ready")
async def ready(sid):
    await a()

if __name__ == '__main__':
    web.run_app(app, host='localhost', port=2129)
```

other_file.py:
```
from server import sio

async def a():
    await sio.emit("Hi")
```

client.js
```
client = io.connect("http://localhost:2129")

client.on("Hi", () => {
        console.log("Hi");
    });
```

When I have it configured like this and run it, the server logs the message as emitted, but the client console stays empty

`emitting event "Hi" to all [/]`

However if I remove other_file completely and move a() to server.py and have it set up like this

server.py:
```
from other_file import a
from aiohttp import web
import socketio

sio = socketio.AsyncServer(logger=True) 
app = web.Application()
sio.attach(app)

@sio.on("Ready")
async def ready(sid):
    await a()

async def a():
     await sio.emit("Hi")

if __name__ == '__main__':
    web.run_app(app, host='localhost', port=2129)
```

The server logs the message as emitted

`emitting event "Hi" to all [/]`

and the client logs to the console

`Hi`

I wanted to be able to call emit() from outside server.py, but that doesn't seem to work. Could I get some help on what could be happening? Thanks.

**Comment by miguelgrinberg** [comment]
The code that you are showing for the two file approach does not seem to me like it is working code. You have circular dependencies in there that would make that code fail (I think). Any chance you simplified the code too much?

**Comment by 0xBC9** [comment]
Yup, you were right. It was an issue with circular imports. Changing how I imported the different modules fixed the issue. Thanks!
