### ISSUE TITLE
Good way to handle flow control

### ISSUE THREAD

**Issue by bhakta0007** [miguelgrinberg/python-socketio#528]
What is the best way to handle flow control with WebSockets. I am looking at a large file transfer case. Here is what I am currently doing

1. Chunk the files into 10k size chunks
2. Send out 5 chunks, then call sio.sleep(0.01)
3. back to step(2) until EOF

There are a few problems I run it, especially when the file goes larger than 50MB. I see the endpoint disconnects from the server. I have seen different errors (some times an exception "object has no attribute 'call_exception_handler'")

I have  few questions

1. What is the best way to ensure I can do back-to-back messaging while still not letting the connection time-out? I am using an async client)

2. What criteria determine the receiver side buffer size? If there is a way to determine this, I could calculate the amount of data I can send in a burst before getting an ack from the receiver - before sending out the next burst.

3. What is the largest size payload that can be sent on a WebSocket? (I am wondering if I should increase the chunk size from 10k to a larger number. I have tried larger sizes and it works but I am not sure if there is a way to determine the right size).

**Comment by miguelgrinberg** [comment]
Unfortunately I don't have much experience with large file transfers over websocket, but in any case, all these questions that you have apply to the websocket library that you are using more than to the Socket.IO, which just passes packets down to the low-level WS implementation.

Yours is not the only issue related to big transfers. See #479 and #511. This is an area where it appears WS implementations don't do too well.

**Comment by bhakta0007** [comment]
When I install python-socketio client/server, which is the underlying WS library that is used. Is it the EngineIO?

**Comment by miguelgrinberg** [comment]
@bhakta0007 No. For the asyncio client the aiohttp package provides WebSocket support. For the standard client it is the websocket-client package. On the server there are several WebSocket implementations, it really depends on what web server you use. It could be eventlet, gevent-websocket, uWSGI, aiohttp, sanic, Tornado, etc.

**Comment by jeeveeyes** [comment]
@bhakta0007 
Not really related to python-socketio implementation per se, but just wanted to point out that when breaking a bigger message ( a file in your case ) into chunks to be sent over websocket connections , we should be mindful of the problems mentioned here : https://hpbn.co/websocket/#websocket-multiplexing-and-head-of-line-blocking.
