### ISSUE TITLE
How to use call method

### ISSUE THREAD

**Issue by bhakta0007** [miguelgrinberg/python-socketio#529]
I checked the documentation of call (https://python-socketio.readthedocs.io/en/latest/api.html#socketio.Client.call).

Sender (A) invokes the call method with a message to (B). B receives the message. how do B return a response that will be delivered back to A? if I emit something from B, it comes to  A as a regular message (and not as a response to the call)?

**Comment by miguelgrinberg** [comment]
Depends on which server you are using in B. If you are using the Python Socket.IO server, the response is whatever you return from the handler function.

**Comment by bhakta0007** [comment]
I am using Flask socketio server

**Comment by miguelgrinberg** [comment]
@bhakta0007 Okay, my reply above applies then.

**Comment by jeeveeyes** [comment]
@miguelgrinberg , 

If the server is a python-socketio based server, the mechanism of returning values to the client merely by returning the desired data in the handler is in accordance with what is documented here : https://python-socketio.readthedocs.io/en/latest/server.html#event-callbacks. 

>  "the server can provide a list of values that are to be passed on to the callback function, simply by returning them from the handler function..."

Can you please confirm it ?

**Comment by miguelgrinberg** [comment]
@jeeveeyes Yes, this is the method to return arguments to the callback.
