### ISSUE TITLE
Using Python-socketio for video streaming server

### ISSUE THREAD

**Issue by yodaljit** [miguelgrinberg/python-socketio#532]
I'm trying to implement a live video streaming server in python for my Django webapp but can't get a start as to how to implement it. Can you help me with that? I'm using RTCMultiConnection as a WebRTC framework.

**Comment by miguelgrinberg** [comment]
There is no support for WebRTC in the python-socketio server. At least nothing that I have built. So you'll need to find some 3rd party project that implements this, or else add it yourself.
