### ISSUE TITLE
Is monitor_clients supposed to close connected, but inactive clients?

### ISSUE THREAD

**Issue by hstejas** [miguelgrinberg/python-socketio#533]
From the documentation for the server classes

> monitor_clients – If set to True, a background task will ensure inactive clients are closed. Set to False to disable the monitoring task (not recommended). The default is True.

Is this meant for cleaning up disconnected clients? or closing clients which are connected (ping/pong is okay) but there is no other active communication  for some time.

**Comment by miguelgrinberg** [comment]
This is for clients that stop sending pings. As long as the pings are coming at the right interval the client will not be touched.

**Comment by hstejas** [comment]
Thanks for clearing that up.
Is there a way to disconnect clients that are connected (ping/pongs) but there are no messages (maybe something like an idle timeout?).
I see in my sample code that a client can be connected for several days if i forget to close it. Not sure if this leads to increase in memory usage.

**Comment by miguelgrinberg** [comment]
A long term connection does not lead to increase memory usage.

There is no mechanism to disconnect idle clients. Your application could implement this by starting an idle timer and resetting it every time the client sends something. If the timer goes off, then you can disconnect.

**Comment by hstejas** [comment]
Thank you for your reply.
