### ISSUE TITLE
How to view/print  data results  of event callback socket io in python with call function

### ISSUE THREAD

**Issue by pecual** [miguelgrinberg/python-socketio#536]
Here our python code:

```python
loop = asyncio.get_event_loop()
start_timer = None


async def send_ping():
    global start_timer
    start_timer = time.time()
    await sio.emit('ping_from_client')

@sio.event
async def connect():
    print('Connected to server')
    await send_ping()

@sio.event
async def connect():
    print('Connected to server')
    await send_ping()


@sio.event
async def pong_from_server():
    global start_timer
    latency = time.time() - start_timer
    print('latency is {0:.2f} ms'.format(latency * 1000))
    await sio.sleep(1)
    await send_ping()


async def start_server():
    await sio.connect(ListenPort)
    await sio.emit('report-client-register', data={'token': pass_t, 'channelRole': 'client'})
    data = await sio.call('push-broadcast-register', {'token': pass_t})
    print(data)



if __name__ == '__main__':
    loop.run_until_complete(start_server())
```

And here our logs:

08/26/2020 11:13:26 AM Using selector: SelectSelector
08/26/2020 11:13:26 AM Attempting polling connection to http://180.13.1.245:3013/socket.io/?transport=polling&EIO=3
08/26/2020 11:13:26 AM Polling connection accepted with {'sid': 'QD7N-aOsPZDR5XqaAABK', 'upgrades': ['websocket'], 'pingInterval': 25000, 'pingTimeout': 5000}
08/26/2020 11:13:26 AM Engine.IO connection established
08/26/2020 11:13:26 AM Received packet MESSAGE data 0
08/26/2020 11:13:26 AM Attempting WebSocket upgrade to ws://180.13.1.245:3013/socket.io/?transport=websocket&EIO=3
08/26/2020 11:13:26 AM Namespace / is connected
08/26/2020 11:13:26 AM Emitting event "ping_from_client" [/]
08/26/2020 11:13:26 AM Sending packet MESSAGE data 2["ping_from_client"]
08/26/2020 11:13:26 AM WebSocket upgrade was successful
08/26/2020 11:13:26 AM Emitting event "report-client-register" [/]
08/26/2020 11:13:26 AM Sending packet MESSAGE data 2["report-client-register",{"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQiLCJuaWNrIjoiQWxiZXJ0byIsImlhdCI6MTU5ODQyNTcwMiwiZXhwIjoxNTk4NTEyMTAyfQ.96mH6OA8ug31Jcy5zRSqqy7ohEp9PE7P9MDG_u21fFM","channelRole":"client"}]
08/26/2020 11:13:26 AM Emitting event "push-broadcast-register" [/]
08/26/2020 11:13:26 AM Sending packet MESSAGE data 21["push-broadcast-register",{"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQiLCJuaWNrIjoiQWxiZXJ0byIsImlhdCI6MTU5ODQyNTcwMiwiZXhwIjoxNTk4NTEyMTAyfQ.96mH6OA8ug31Jcy5zRSqqy7ohEp9PE7P9MDG_u21fFM"}]
08/26/2020 11:13:26 AM Sending packet PING data None
08/26/2020 11:13:26 AM Received packet PONG data None

The question is:  Why we can't see/print de data result of event callback socket io in python with call function?

**Comment by miguelgrinberg** [comment]
What server are you using? The server needs to send an ACK packet with the results of the call, and that does not appear in your client log.

**Comment by pecual** [comment]
The server runs with LINUX. In the Socket IO server it is implemented
to return data in '' push-broadcast-registers "

**Comment by miguelgrinberg** [comment]
I meant which Socket.IO server you are using, not which operating system. Do you have access to the server? Can you show me the implementation of the `push-broadcast-register` handler?
