### ISSUE TITLE
how to set  socketio server transport = websocket

### ISSUE THREAD

**Issue by 316953425** [miguelgrinberg/python-socketio#537]
I use to example:
**client code:**

```python
import socketio

sio = socketio.Client()

@sio.event
def connect():
    print('connection established')

@sio.event
def my_message(data):
    print('message received with ', data)
    sio.emit('my response', {'response': 'my response'})

@sio.event
def disconnect():
    print('disconnected from server')

sio.connect('http://localhost:5000')
sio.wait()
```

**server code**

```python
import eventlet
import socketio

sio = socketio.Server()
app = socketio.WSGIApp(sio, static_files={
    '/': {'content_type': 'text/html', 'filename': 'index.html'}
})

@sio.event
def connect(sid, environ):
    print('connect ', sid)

@sio.event
def my_message(sid, data):
    print('message ', data)

@sio.event
def disconnect(sid):
    print('disconnect ', sid)

if __name__ == '__main__':
    eventlet.wsgi.server(eventlet.listen(('', 5000)), app)
```

when i change the client code connect funtion to websocket mode via sio.connect('http://localhost:5000',transports='websocket')
,the client can not connect to server,I want to know how to set the server to websocket mode 

Thanks!

**Comment by miguelgrinberg** [comment]
@316953425 Have you considered reading the docs to learn how to do this? https://python-socketio.readthedocs.io/en/latest/api.html#socketio.Client.connect

**Comment by miguelgrinberg** [comment]
Show me the error that you get please.

**Comment by 316953425** [comment]
Hi miguelgrinberg, Thanks for you help.

My os is CentOS Linux release 7.7.1908 (Core)
python version is python3.6
scoketio version is python-socketio (4.6.0)
I run the above code, no error message be print, maybe above code no have print error code.
Could you tell me how to add print error code for debug .

**Comment by 316953425** [comment]
Hi  miguelgrinberg，
via tcpudmp I found when i use sio.connect('http://10.176.48.185:5000',transports='websocket')， no package be sent to server
;when i delete transports='websocket' option , everything is ok

**Comment by miguelgrinberg** [comment]
To add verbose logging change this:

    sio = socketio.Client()

to this:

    sio = socketio.Client(engineio_logger=True, logger=True)

**Comment by 316953425** [comment]
it is ok ， thank for you help
