### ISSUE TITLE
Does the library support use of connecting/binding on unix domain sockets?

### ISSUE THREAD

**Issue by Rahul-RB** [miguelgrinberg/python-socketio#541]
As the question says, is there support for the socketio server to listen on unix domain socket and client to connect to one?
I was not able to find anything in docs. I did find [one issue](https://github.com/miguelgrinberg/python-socketio/issues/55) but that didn't mention any more details.

Can someone please tell me any appropriate place to check this?

**Comment by miguelgrinberg** [comment]
This library does not provide a web server, there is no low-level networking here. This is something that you need to check on the web server that you intend to use with this package.

**Comment by Rahul-RB** [comment]
Ok yes makes sense, thank you
