### ISSUE TITLE
about how to use 

### ISSUE THREAD

**Issue by 316953425** [miguelgrinberg/python-socketio#543]
**client code**

```python
import time
import socketio

sio = socketio.Client()
global aa
aa = 0

@sio.event
def connect():
    print('connection established')

@sio.event
def my_message(data):
    print('message received with ', data)
    sio.emit('my response', {'response': 'my response'})
    aa=1
@sio.event
def disconnect():
    print('disconnected from server')

sio.connect('http://10.176.48.185:5000',transports='websocket')
sio.emit('my_message', {'foo': 'bar'})

while True:
        time.sleep(1)
        print(aa)
        sio.emit('my_message', {'foo1': 'bar'})
```

**server code**

```python
import eventlet
import socketio

sio = socketio.Server()
app = socketio.WSGIApp(sio, static_files={
    '/': {'content_type': 'text/html', 'filename': 'index.html'}
})
app.websocket_enabled=True
@sio.event
def connect(sid, environ):
    print('connect ', sid)

@sio.event
def my_message(sid, data):
    print('message ', data)
    sio.emit('my_message', {'response111': 'my response'})
@sio.event
def disconnect(sid):
    print('disconnect ', sid)

if __name__ == '__main__':
    eventlet.wsgi.server(eventlet.listen(('', 5000)), app)
    print("----------------------")
```

if server want to send message first how to do it ? 
I just started learning ， could you give me a example ?
thanks very much!

**Comment by miguelgrinberg** [comment]
1) global variables in Python have special rules that you are not following. See https://www.w3schools.com/python/gloss_python_global_variables.asp.

2) One way to do it is to use the `emit()` function in the connect handler, so that the client receives a message upon connecting.

**Comment by 316953425** [comment]
Hi miguelgrinberg 
**server code** 
`import eventlet
import socketio

sio = socketio.Server()
app = socketio.WSGIApp(sio, static_files={
    '/': {'content_type': 'text/html', 'filename': 'index.html'}
})
app.websocket_enabled=True
@sio.event
def connect(sid, environ):
    print('connect ', sid)

@sio.event
def my_message(sid, data):
    print('message ', data)
    sio.emit('my_message', {'response111': 'my response'})
@sio.event
def disconnect(sid):
    print('disconnect ', sid)

if __name__ == '__main__':
    eventlet.wsgi.server(eventlet.listen(('', 5000)), app)`
In the server code,if server want to send msg to client at anytime, ow to do it ?
Not when server receive client event，server run event handler to send msg to client 
THanks for you help very much~

**Comment by miguelgrinberg** [comment]
This really depends on your application. Whenever the server wants to send an event it can do it, but you'll need to have some sort of background activity that decides when is the proper moment. See the example app here: https://github.com/miguelgrinberg/python-socketio/blob/master/examples/server/wsgi/app.py#L17 for a background thread that sends to clients.
