### ISSUE TITLE
Server hangs on exit after connecting with AsyncClient

### ISSUE THREAD

**Issue by mpetris** [miguelgrinberg/python-socketio#544]
I have a socket.io server _test2_ that talks to a socket.io server _test1_ via the AsyncClient after receiving an event _my_start_event_ and disconnects from _test1_ after receiving an event _my_stop_event_. After the conversation between _test2_ and _test1_, i. e. after the connect via AsyncClient, I always need a SIGKILL to stop server _test2_. Why is that the case and is there anything I can do to stop normally on SIGINT? 

_test1_ can be stopped normally. _test2_ needs SIGKILL after connection with AsyncClient but can also be stopped normally when not connecting with AsyncClient. The connection from _test2_ to _test1_ seem to be closed just fine and the loop threads seem to exit as well, so I don't understand what keeps server _test2_ from stopping normally. Any help would be appreciated!

Server _test1_:

```python
from aiohttp import web
import socketio

sio = socketio.AsyncServer(cors_allowed_origins="*")
app = web.Application()
sio.attach(app)

@sio.event
def connect(sid, environ):
    print("connect test1 ", sid, environ)

@sio.event
def disconnect(sid):
    print('disconnect test1 ', sid)

if __name__ == '__main__':
    web.run_app(app=app, port=3001)
```

Server _test2_:
```python
from aiohttp import web
import socketio

sio = socketio.AsyncServer(cors_allowed_origins="*")
app = web.Application()
sio.attach(app)
client_sio = socketio.AsyncClient()

@sio.event
def connect(sid, environ):
    print("connect test2 ", sid, environ)

@sio.event
def disconnect(sid):
    print('disconnect test2 ', sid)

@sio.event
async def my_start_event(sid):
    print('my_start_event test2', sid)
    await client_sio.connect('http://localhost:3001')

@sio.event
async def my_stop_event(sid):
    print('my_stop_event test2', sid)
    await client_sio.disconnect()

if __name__ == '__main__':
    web.run_app(app=app, port=3002)
```

Client that initiates the conversation between the two servers:
```python
import asyncio
import socketio


client_sio = socketio.AsyncClient()


async def send_my_event():
    await client_sio.connect('http://localhost:3002')
    await asyncio.sleep(1)
    print("send start event")
    await client_sio.emit('my_start_event')
    await asyncio.sleep(1)
    print("send stop event")
    await client_sio.emit('my_stop_event')
    await asyncio.sleep(1)
    await client_sio.disconnect()


def main():
    loop = asyncio.get_event_loop()
    loop.run_until_complete(send_my_event())


if __name__ == '__main__':
    main()
```

To test this I first start server _test1_ then server _test2_ and then the client script. After the conversation between _test2_ and _test1_ has taken place I try to stop _test2_.

**Comment by mpetris** [comment]
It seems to be the `async_signal_handler` in `engineio/asyncio_client.py` that prevents an exit with SIGINT. It gets added when the client connects unless the flag `async_signal_handler` is set to `True`. So if I block the handler getting added with 
```python
import engineio.asyncio_client

engineio.asyncio_client.async_signal_handler_set = True
```

for server _test2_ then a SIGINT does exit it. 

Note sure why a **client** needs to "Disconnect all active async clients" as the documentation says. In which cases would this be necessary?

**Comment by miguelgrinberg** [comment]
@mpetris Okay, I need to check why this hangs then. The purpose is to do a clean disconnection when the application is interrupted. If you already disconnected your client then this handler should have nothing to do and just return.

**Comment by mpetris** [comment]
@miguelgrinberg Thanks a lot for looking into this!

**Comment by miguelgrinberg** [comment]
@mpetris I have been unable to reproduce this problem with the latest versions of the two Socket.IO packages. Your test2 server breaks on Ctrl-C. It returns a strange runtime error "Event loop stopped before Future completed" that I need to investigate, but the application does stop on SIGINT.

**Comment by mpetris** [comment]
@miguelgrinberg you are right. With the latest versions python-engineio 4.0.0 and python-socketio 5.0.4 Ctrl-C just works fine on the test2 server. I didn't even receive the error you mentioned. Just for the record: the original test was executed with python-engineio 3.13.2 and python-socketio 4.6.0
Thanks for letting me know!
