### ISSUE TITLE
AsyncServer hangs on request to non-default namespace

### ISSUE THREAD

**Issue by Kaveshnikov** [miguelgrinberg/python-socketio#546]
Hello. I try to send an event with the async client to the namespace with custom path at the async server but get TimeoutError.

**Server**
```python
import socketio
from aiohttp import web


class Namespace(socketio.AsyncNamespace):
    async def on_foo(self, sid, payload):
        return payload


if __name__ == '__main__':
    app = web.Application()
    server = socketio.AsyncServer(
        async_mode='aiohttp',
        cors_allowed_origins=[],
        allow_upgrades=True,
    )
    namespace = Namespace(namespace='/qwe')
    server.attach(app, socketio_path='/internal/ws')
    server.register_namespace(namespace)
    web.run_app(app, host='127.0.0.1', port=8080)
```

**Client**
```python
import asyncio

import socketio


async def main():
    client = socketio.AsyncClient(
        reconnection=False,
        logger=True,
        engineio_logger=True,
    )
    url = 'ws://localhost:8080'
    await client.connect(url, socketio_path='internal/ws', transports=['websocket'], namespaces=['/qwe'])

    resp = await client.call('foo', {'data': 'some data'}, namespace='/qwe', timeout=5)
    print('Resp is ', resp)


if __name__ == '__main__':
    asyncio.run(main())

```

**Libs**
aiohttp==3.6.0
python-engineio==3.13.2
python-socketio==4.6.0
websocket-client==0.57.0
websockets==8.1

I see in logs that the client sends frames successfully and the server receives them too, but skips because client is not connected to namespace. Am I doing something wrong? It may be related to #544

**Comment by miguelgrinberg** [comment]
I think the problem is that you are not waiting for the connection to be fully established, which would be at the point where the `connect` handler for the `/qwe` namespace is called.

**Comment by Kaveshnikov** [comment]
What should I do, call asyncio.sleep()?

**Comment by Kaveshnikov** [comment]
asyncio.sleep(1) has helped. Why is connection not fully established after client.connect() call? Why does connect() not wait until it will?

**Comment by miguelgrinberg** [comment]
Sleeping is a bad way of solving this. As I said above, there is a `connect` handler that is invoked on each namespace when the connection is established.

Why it was done this way? Because the Socket.IO protocol is asynchronous in nature, there are many messages that are exchanged between the server and the client until the point the connection is established, it's not a single thing.

**Comment by Kaveshnikov** [comment]
Indeed, sleeping is not a proper solution. Yes, server and client interchange messages with each other during connection to the namespaces but if to use connect handlers I need to implement synchronization between different handlers to proceed main function and it does't look like a handy solution. I mean, if main function need to wait until connections to all namespaces will be established which is not the case in my example of course. What do you think about adding an optional flag to connect() which will indicate if we need to wait all connections to be established?

**Comment by miguelgrinberg** [comment]
Your mistake is thinking in terms of a main function. There is no such thing in an asynchronous system, everything is event-driven. Your main function should just start the connection and then wait.

```python
client = socketio.AsyncClient(
    reconnection=False,
    logger=True,
    engineio_logger=True,
)

async def main():
    url = 'ws://localhost:8080'
    await client.connect(url, socketio_path='internal/ws', transports=['websocket'], namespaces=['/qwe'])
    await client.wait()
```

Then if you need to do something immediately after connection, start a task in the connect handler:

```python
async def my_logic():
    resp = await client.call('foo', {'data': 'some data'}, namespace='/qwe', timeout=5)
    print('Resp is ', resp)

@client.event(namespace='/qwe')
async def connect(sid, environ):
    client.start_background_task(my_logic)
```

> What do you think about adding an optional flag to connect() which will indicate if we need to wait all connections to be established?

It would be awfully complicated, and there are weird situations that would be hard to handle. For example, if you connect to two namespaces and only one of the connections is established.

**Comment by Kaveshnikov** [comment]
Yes, I missed socketio important detail, it is fully event-driven both in sync and async clients. Sorry for that. Than my suggestion with flag is wrong by design.
>  I mean, if main function need to wait until connections to all namespaces will be established

The nature of this problem is rather sync than async so I used main function for it. In the event-driven context I have to make some kind of synchronization between connect events and wait it with timeout. Any way, thanks for the help.
