### ISSUE TITLE
Having multiple websocket connections on the same script

### ISSUE THREAD

**Issue by Jacks349** [miguelgrinberg/python-socketio#547]
Hello! I have a very simple use case where i'm connecting to different ws urls, one thread (i'm using the threading library) for every connection, and then i'll just receive and read messages for every connection. Now, i already have a working example but i wanted to move to another library, so since this one is one of the best and well known, i wanted to do the same thing with Python-SocketIO.

First of all, i'm sorry if the question is out of scope, but how can i create something like that with Python-SocketIO? As i said, i have different connections and for every connection i only have to receive and read messages, and handle errors/disconnections. I see that this library supports AsyncIO, would it be doable by creating a task for every connection?

Thanks in advance, and keep up the awesome work!

**Comment by miguelgrinberg** [comment]
This isn't a WebSocket client, you cannot connect to WS servers with this package. You can only connect to Socket.IO servers.

As far as concurrent connections you can use threads with the standard client, or async tasks with the asyncio client. Both approaches work.

**Comment by Jacks349** [comment]
Thank you a lot! This is very clear. Yes, in this case the servers will be SocketIO servers too, my bad for not making it very clear.
