### ISSUE TITLE
ImportError: cannot import name 'Namespace' from 'socketio' (/app/.heroku/python/lib/python3.8/site-packages/socketio/__init__.py)

### ISSUE THREAD

**Issue by terminate9298** [miguelgrinberg/python-socketio#548]
Server is running fine on Local Machine But getting Error on heroku
This is my Requirements.txt file

click==7.1.2
dnspython==1.16.0
eventlet==0.27.0
Flask==1.1.2
Flask-SocketIO==4.3.1
gcloud==0.17.0
gevent==20.6.2
gevent-websocket==0.10.1
googleapis-common-protos==1.52.0
greenlet==0.4.16
gunicorn==20.0.4
httplib2==0.18.1
itsdangerous==1.1.0
Jinja2==2.11.2
jws==0.1.3
MarkupSafe==1.1.1
monotonic==1.5
netifaces==0.10.6
oauth2client==3.0.0
protobuf==3.13.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycryptodome==3.4.3
Pyrebase==3.0.27
python-dotenv==0.14.0
python-engineio==3.13.2
python-jwt==2.0.1
python-socketio==4.3.0
requests==2.11.1
requests-toolbelt==0.7.0
rsa==4.6
six==1.15.0
socketio==0.2.1
setuptools==50.3.0
Werkzeug==1.0.1
zope.event==4.4
zope.interface==5.1.0

**Comment by terminate9298** [comment]
This is Procfile

`web: gunicorn -k eventlet app:app`

**Comment by miguelgrinberg** [comment]
Uninstall the `socketio` package. That's something else, nothing to do with this package which is called `python-socketio`.

**Comment by terminate9298** [comment]
Thanks ...
That Worked.
