### ISSUE TITLE
Django Implementation requires a http response 

### ISSUE THREAD

**Issue by SHERMANOUKO** [miguelgrinberg/python-socketio#550]
Hi

While trying to use the library in django, I did as below

```
@sio.event
def connect(sid):
    sio.emit('my_response', {'data': 'Connected', 'count': 0}, room=sid)
```

THis however leads to a server error as django requires a httpresponse to be returned. If I include a http response , it fails on the client side with 

`
VM406:1 WebSocket connection to 'ws://localhost:8000/connect' failed: Error during WebSocket handshake: Unexpected response code: 200
`
I am using the django example in the examples folder on this repo

Kindly assist

**Comment by miguelgrinberg** [comment]
@SHERMANOUKO did you make any changes to the example in this repository? The `connect()` function is a Socket.IO handler, Django does not have any visibility into it.

**Comment by SHERMANOUKO** [comment]
No changes on the views file.

How do I open the websocket? In the example it seems that by accessing the default path `views.index` the request heads to the index route on views.py, right?

My backend is an API

**Comment by SHERMANOUKO** [comment]
My frontend is an isolated react app that lives in a different server from the backend. So I treated that react app as being the place where the `static/index.html` file lives then tried to go directly to the connect function but from your comment above it seems that was a wrong approach, right ?

**Comment by miguelgrinberg** [comment]
You aren't being clear. Are you reporting a bug on the Django example, or is this something that happens on your own application, which is modeled after the example?

Did you change the url definitions, for example? I suggest you try the example in its original form, and only start making modifications once you understand how it works. The connection is triggered in the client side, you'll find it in the html template. You can make the same connect call in your react app. You are probably trying to connect via HTTP request, which is not the correct approach.

> Is it possible to have the architecture Im trying to achieve where backend lives separately from frontend ?

Yes, but as I said above, I think you need to familiarize yourself with the technologies you are using. Read the Socket.IO JavaScript client documentation, for example, as you'll need to use that from your app.

**Comment by SHERMANOUKO** [comment]
Yea

I realized that I was trying to connect direct to the `connect` function. It wasnt a bug it was an error I was encountering.

I moved over to a simple html file but realized the cdns werent working well on my app (I still havent figured out why). So I decided to use a react app with the socket.io library. Its currently failing on CORS though I have djangocors headers installed so my first issue is sorted

Thanks for the help

**Comment by SHERMANOUKO** [comment]
I realized handled the CORS issue by reading the API Reference section of the docs. I had initially thought it makes use of the djangocorsheaders CORS setting on the django settings file. I'm closing this out

Once more thanks for the help.
