### ISSUE TITLE
number of clients connected to the socket

### ISSUE THREAD

**Issue by AhmedBhati** [miguelgrinberg/python-socketio#551]
How to find the number of clients connected to socket??
Thanks in advance

**Comment by miguelgrinberg** [comment]
You can keep a count that you update in the connect and disconnect handlers.

**Comment by AhmedBhati** [comment]
Thanks

**Comment by Matheus-Garbelini** [comment]
Hi, is there some public methods to disconnect all the clients connected to the SocketIOServer>

**Comment by miguelgrinberg** [comment]
@Matheus-Garbelini No, there is no option to disconnect everyone, sorry.

**Comment by Matheus-Garbelini** [comment]
@miguelgrinberg thanks. Indeed, after messing around I found an undocumented API for disconnecting a single client.
saving all of them in a list and disconnecting them manually worked.
```Python
    @EventletWorker
    def disconnect_all(self):
        for sid in self.clients_list:
            self.sio.disconnect(sid)
        self.clients_list = []
```

**Comment by miguelgrinberg** [comment]
The `disconnect()` function is documented here: https://flask-socketio.readthedocs.io/en/latest/#flask_socketio.disconnect.

**Comment by miguelgrinberg** [comment]
The disconnect function is documented here: https://python-socketio.readthedocs.io/en/latest/api.html#socketio.Server.disconnect.

**Comment by Matheus-Garbelini** [comment]
oh thanks a lot, @miguelgrinberg for some reason I missed this.
