### ISSUE TITLE
JSONDecodeError when connection to server can not be established.

### ISSUE THREAD

**Issue by galaxog** [miguelgrinberg/python-socketio#553]
When there is a connection issue the returned exception is confusing. Shouldn't the exception say something like server isn't available, or connection failed? I'm currently using version 4.6.0. If you try to use the client to connect to a bogus socket server like http://google.com, you should see the same exception I am seeing.

**Comment by miguelgrinberg** [comment]
Oh, this is odd, I wasn't aware of this. Okay, I'm going to fix it so that you get the intended exception, which should be this:

```
Traceback (most recent call last):
  File "client.py", line 18, in <module>
    sio.connect('http://google.com')
  File "socketio/client.py", line 286, in connect
    six.raise_from(exceptions.ConnectionError(exc.args[0]), None)
  File "<string>", line 3, in raise_from
socketio.exceptions.ConnectionError: Unexpected status code 404 in server response
```

**Comment by miguelgrinberg** [comment]
Fixed in the python-engineio dependency. Can I ask you to install this package from its master branch on GitHub and retest? Thanks!
