### ISSUE TITLE
Update connect_error documentation

### ISSUE THREAD

**Issue by turicfr** [miguelgrinberg/python-socketio#554]
Hello,
I would like to suggest you mention in the documentation that the `connect_error`  handler can get arguments. Now, it is only shown not getting arguments, [here](https://python-socketio.readthedocs.io/en/latest/client.html?highlight=connect_error#defining-event-handlers).

As you stated in issue [#508](https://github.com/miguelgrinberg/python-socketio/issues/508#issuecomment-646352384), there are some cases where this handler can be invoked with multiple or none arguments, depending on the server, and some cases where it can get one argument.

In my opinion, it is worth mentioning this in the documentation as it can lead to confusion and bugs.

**Comment by miguelgrinberg** [comment]
I agree, will improve it.
