### ISSUE TITLE
'module' object has no attribute 'main_thread'

### ISSUE THREAD

**Issue by jayson-valentino** [miguelgrinberg/python-socketio#555]
I'm getting this error running  the Client Example : https://python-socketio.readthedocs.io/en/latest/client.html

Running with raspberrypi, python2.7

Traceback (most recent call last):
  File "client-test.py", line 3, in <module>
    sio = socketio.Client()
  File "/home/pi/.local/lib/python2.7/site-packages/socketio/client.py", line 88, in __init__
    threading.current_thread() == threading.main_thread():
AttributeError: 'module' object has no attribute 'main_thread'

**Comment by miguelgrinberg** [comment]
Python 2.7 is not supported anymore, sorry. Use 3.x.

**Comment by jayson-valentino** [comment]
Noted that. Thanks.
