### ISSUE TITLE
socketio client connect halts for several minutes until a connect_error event is fired 

### ISSUE THREAD

**Issue by jonspieg** [miguelgrinberg/python-socketio#556]
Hi,

This is not a rather rare behavior and is quite hard to reproduce.
 
The problematic scenario is as follows:
The socketio server is down and the client is initiating a connection.
usually I immediately get a connect_error event with "Connection error" (not very informative...).
however, sometimes the connect function will freeze for a long time (up to several minutes) until the connect_error fires with the same "Connection error".

I couldn't find any timeout parameter on client connection.

where can this delay be coming from?

any ideas on how to overcome this?

Thanks

**Comment by miguelgrinberg** [comment]
It's hard for me to speculate without being able to reproduce and see what operation is timing out. Maybe something easy you can try next time you have this is to hit Ctrl-C after you determine that the client is stuck in this long wait. Hopefully the stack trace will give me some ideas.
