### ISSUE TITLE
Client just shutting down silently instead hinting at required 'websocket-python'

### ISSUE THREAD

**Issue by jchwenger** [miguelgrinberg/python-socketio#557]
Hi,

Just noticed on two different machines that when I installed python-socketio and tried to use it on the client side, everything would work, no errors, except my program would just stop instead of waiting 'sio.wait()', and I could not figure out why. I then discovered the `engineio_logger` argument that can be passed to the `Client`, and which told me that I had to install `websocket-python` ([here](https://github.com/websocket-client/websocket-client)). After installing that with conda, everything worked, (and on other machines it must have been included, because I did not have any issue), I'm just surprised that there was no error message, or that it wasn't required in the dependencies...? All done with python 3.7 and Ubuntu 18.04.

**Comment by miguelgrinberg** [comment]
@jchwenger the documentation covers this. The dependencies for the client can be installed with `pip install "python-socketio[client]"`. It's here: https://python-socketio.readthedocs.io/en/latest/client.html#installation.

The websocket client is really optional, since the protocol can work perfectly fine using HTTP long-polling. What I don't understand is the part about the application exiting. It should have worked just fine over long-polling.

**Comment by jchwenger** [comment]
Aha! My apologies for this, thanks for explaining it. The exit must have been because there was a password to access the site, and that seemed to work only over sockets (as in, the format should probably be changed for polling? I can post the code snippet tomorrow if you like.)

**Comment by miguelgrinberg** [comment]
Sure, let me have a look and I'll see if there are any changes I can make to handle this better.

**Comment by jchwenger** [comment]
It's something as simple as that:

```
user_pass = b64encode(b"username:pass").decode("ascii")
url = "https://www.website.com"
sio.connect(url, {"Authorization": "Basic %s" % user_pass})
sio.wait()
```

I have a function

```
@sio.event
def connect():
    print('connected')
```

The app prints 'connected', and then stops. With the deeper logger enabled, it says does not have websocket capabilities, and that long-polling fails.
