### ISSUE TITLE
Can SocketIO run as a standalone server without WSGI or ASGI frameworks?

### ISSUE THREAD

**Issue by tsumarios** [miguelgrinberg/python-socketio#559]
Is it possible to run a standalone SocketIO server in plain Python without using WSGI (or ASGI) applications (that is, without gunicorn, daphne, Flask, uvicorn, and so on)?
I've read the documentation but haven't found any "run" or "listen" methods.

For instance, I'm wondering if you can use something like this:
```python
sio = socketio.Server() # or AsyncServer
sio.listen(3000)
```

In other words, I would like to know if it is possible to reproduce the standalone [Node.js](https://www.npmjs.com/package/socket.io#standalone) version:
```javascript
const io = require('socket.io')();
io.listen(3000);
```

Thanks in advance.

**Comment by miguelgrinberg** [comment]
The Node version uses a web server as a dependency, just like this Python package does. The only difference is that Node incorporates and the web server, while this package allows you to use any web server of your choosing.

If you want a simpler and higher-level approach take a look at the Flask-SocketIO package, which does have a `run()` function. It still requires a web server WSGI web server, but it is started internally when you call the `run()` function.

**Comment by zMrDevJ** [comment]
Hi, many thanks for the reply.
I'll give a look at the Flask-SocketIO as you suggested.
