### ISSUE TITLE
No longer works when trying to use nodejs socket-io 3.0.0. version

### ISSUE THREAD

**Issue by bribrah** [miguelgrinberg/python-socketio#560]
When trying to connect to node-js hosted server that is using sokcket-io 3.0.0 an error is thrown: unexpected response from server

**Comment by miguelgrinberg** [comment]
Yes, this is expected. The Socket.IO 3.0 client uses a new version of the Socket.IO protocol that needs to be implemented. I have an outstanding issue to keep track of that work: https://github.com/miguelgrinberg/python-engineio/issues/195.

**Comment by gltovar** [comment]
Do you happen to know what version of the nodejs server and python client I can target to get up an running while this issue exists?

**Comment by miguelgrinberg** [comment]
@gltovar the latest 2.x Socket.IO JavaScript release should be compatible.

**Comment by minhajsiddiqui** [comment]
It works for me when i pass transports=[websocket]

**Comment by pragdave** [comment]
Perhaps a comment in the README? QAs 5this was my first time using Python, and my first time using JavaScript's socket.io library, it took me a day or so to work out that it wasn't a problem in my code... :)

**Comment by miguelgrinberg** [comment]
Tracking progress in 3.0 support in #571
