### ISSUE TITLE
Fail to reconnect

### ISSUE THREAD

**Issue by aprilmay** [miguelgrinberg/python-socketio#561]
Some exceptions are not caught on reconnect, and the client enters a "dead" state (note that i use asyncio and websocket transport, i'm not sure about other setup).

In my case, it's usually an error with DNS resolution, which raises a aiohttp.client_exceptions.ClientConnectionError.

A quick workaround is to add the relevant exception type in the try/except block of the _connect_websocket method in the asyncio_client.py file (around line 308).

**Comment by aprilmay** [comment]
My bad, the error (and quick fix) is actually in the python-engineio package.

**Comment by miguelgrinberg** [comment]
@aprilmay Yes, that is correct. Would you like to craft the fix yourself?

**Comment by aprilmay** [comment]
Sure. A simple `git diff @~..@`gives:
```
diff --git a/engineio/asyncio_client.py b/engineio/asyncio_client.py
index 62067b0..1a7de0b 100644
--- a/engineio/asyncio_client.py
+++ b/engineio/asyncio_client.py
@@ -306,7 +306,8 @@ class AsyncClient(client.Client):
                     websocket_url + self._get_url_timestamp(),
                     headers=headers)
         except (aiohttp.client_exceptions.WSServerHandshakeError,
-                aiohttp.client_exceptions.ServerConnectionError):
+                aiohttp.client_exceptions.ServerConnectionError,
+                aiohttp.client_exceptions.ClientConnectionError):
             if upgrade:
                 self.logger.warning(
                     'WebSocket upgrade failed: connection error')
```
I'm not familiar with github PRs, but i can learn if you want one.

**Comment by miguelgrinberg** [comment]
Thanks!

> I'm not familiar with github PRs, but i can learn if you want one.

Only if you want to. I can apply the change myself if you are not interested or don't have time.

**Comment by aprilmay** [comment]
Sorry for late reply. It would be nice and more simple if you could apply the patch, then.
Thanks!

**Comment by miguelgrinberg** [comment]
Done

**Comment by aprilmay** [comment]
Thanks!
