### ISSUE TITLE
reliably emitting after connect and before disconnecting

### ISSUE THREAD

**Issue by fruttasecca** [miguelgrinberg/python-socketio#562]
python-engineio==3.13.2  
python-socketio[client]==4.6.0  
Standard python client
Connecting to a single namespace ( connect(server, namespaces=[namespace], transports=["websocket"]))

It seems that currently it is not possible to reliably emit a message right after connecting to a namespace.
Same holds true when emitting a message and then disconnecting right after that, both
by disconnecting in the emit callback or right after the emit call.

It seems to me that this is related to https://github.com/miguelgrinberg/python-socketio/issues/461 and it is expected and correct behavior, is that right?
Is there a suggested way to have this happen reliably?

Thanks

**Comment by miguelgrinberg** [comment]
> It seems that currently it is not possible to reliably emit a message right after connecting to a namespace.

You may want to wait for the server to send a welcome event.

> Same holds true when emitting a message and then disconnecting right after that

Request a callback with your emit, then wait to receive the callback before disconnecting.

**Comment by fruttasecca** [comment]
Thank you for the quick reply.
Could you clarify on what you mean with the answer about disconnecting?

**Comment by miguelgrinberg** [comment]
When you emit an event you can add a `callback` argument set to a callable. The function that you pass will be invoked when the other side acknowledges that it received the event. At that point it is safe to disconnect.

**Comment by fruttasecca** [comment]
I see. That's what I was actually doing. 
I will verify if the issue is related to the server.

**Comment by fruttasecca** [comment]
The disconnect issue was something on our side, while the connect issue was fixed with the suggestion.
Thanks for the info and the quick replies
