### ISSUE TITLE
Not working in socketio v3

### ISSUE THREAD

**Issue by njavilas2015** [miguelgrinberg/python-socketio#563]
server in node v14 

"express": "^4.17.1"
"socket.io": "^3.0.1"

> import fs from 'fs';
> import express from 'express';
> import https from 'https';
> import socket from 'socket.io';
> 
> export const app = express()
> 
> export const server = https.createServer({
>     key: fs.readFileSync('/etc/letsencrypt/live/dominio/privkey.pem'),
>     cert: fs.readFileSync('/etc/letsencrypt/live/dominio/fullchain.pem'),
>     requestCert: false,
> }, app);
> 
> export const io = socket.listen(server)
> 
> server.listen(443, () => {
>     console.log('listening on *:443');
>   
> 
> });

client 

> import socketio
> sio = socketio.Client()
> sio.connect('https://dominio')

> Attempting polling connection to https://dominio/socket.io/?transport=polling&EIO=3
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/insert/.local/lib/python3.8/site-packages/socketio/client.py", line 282, in connect
>     six.raise_from(exceptions.ConnectionError(exc.args[0]), None)
>   File "<string>", line 3, in raise_from
> socketio.exceptions.ConnectionError: Unexpected response from server

**Comment by miguelgrinberg** [comment]
Duplicate: https://github.com/miguelgrinberg/python-socketio/issues/560
