### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 400

### ISSUE THREAD

**Issue by maneesha-reddy** [miguelgrinberg/python-socketio#564]
I've a django socketio as server and reactjs as client
When i'm running both cilent and server,i'm getting error WebSocket connection to 'ws://localhost:8000/socket.io/?EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 400 at client side and "GET /socket.io/?EIO=3&transport=websocket HTTP/1.1" 400 11 at server side

socket.io-client verison-2.3.0
django version-3.1.3

**Comment by miguelgrinberg** [comment]
You need to enable logging on the server to see the reason for the 400 error: https://python-socketio.readthedocs.io/en/latest/server.html#debugging-and-troubleshooting

**Comment by maneesha-reddy** [comment]
http://localhost:3000 is not an accepted origin. I'm getting this from server side

**Comment by maneesha-reddy** [comment]
CORS_ORIGIN_ALLOW_ALL = True 
I added this in django settings even though i'm getting the error

**Comment by miguelgrinberg** [comment]
See the `cors_allowed_origins` option for the `socketio.Server()` class. The CORS configuration that you do in Django does not transfer to Socket.IO.

**Comment by maneesha-reddy** [comment]
sio = socketio.Server(logger=True, engineio_logger=True, cors_allowed_origins='*',async_mode='eventlet')
Now i'm getting "GET /socket.io/?EIO=3&transport=websocket HTTP/1.1" 500 59

**Comment by miguelgrinberg** [comment]
That's a 500, it is a crash in your application code very likely. Look at the stack trace in your terminal to learn more about it.

**Comment by maneesha-reddy** [comment]
Thankyou now it's working when i added the eventlet.wsgi.server(eventlet.listen(('', 8000)), application) in the wsgi file
