### ISSUE TITLE
 timestampParam in client as as optional

### ISSUE THREAD

**Issue by sronmiz** [miguelgrinberg/python-socketio#565]
Hello,
I would like to know if there is an option to add an option to 'cancel' the addition of t paramater (timestampParam) in the client.
In our WSS application we use the t paramater in the url for different purpose.

Thanks.

**Comment by miguelgrinberg** [comment]
The `t` is part of the Socket.IO protocol. It does not matter that your own WS endpoints accepts an argument with this name, because Socket.IO will be hosted on its own endpoint, not on one you provide.

**Comment by sronmiz** [comment]
Thanks Miguel,
When you say it does not matter - there is any way to provide my ws this argument? or do we have to change the name of the expected argument?

**Comment by miguelgrinberg** [comment]
@sronmiz I don't really understand why are you concerned with such an internal aspect of the Socket.IO protocol. You need to use a Socket.IO client and a Socket.IO server. Both know what this `t` argument is used for. If your application also has WebSocket endpoints, those are unrelated to the Socket.IO communication.

**Comment by sronmiz** [comment]
I have understood my problem.
Thanks for your help :)
