### ISSUE TITLE
Howto reuse socket id on reconnect SocketIO

### ISSUE THREAD

**Issue by luffy51k** [miguelgrinberg/python-socketio#569]
Hi everyone, i want override session id (sid) and reuse the sid.  

Reusing socket ids on reconnections with socket.io 2.3.0 supported. By Override **io.engine.generateId**. 

Howto do that with python-socketio?

Help me!

**Comment by miguelgrinberg** [comment]
Overriding the ids is currently not possible. I guess you could maybe figure out a way to do it if you override the `socketio.Server` and `engineio.Server` classes, but it is not going to be straightforward.

**Comment by luffy51k** [comment]
Thank @miguelgrinberg,
