### ISSUE TITLE
Remove event listener

### ISSUE THREAD

**Issue by vladpaul10** [miguelgrinberg/python-socketio#576]
Your question
Hello!
Is there a way to remove event listeners, like
socket.off(event, handler), socket.removeListener, socket.removeAllListeners, socket.removeEventListener?

**Comment by vladpaul10** [comment]
Answer:

https://github.com/miguelgrinberg/Flask-SocketIO/issues/1423

Can be closed

**Comment by FifthHour** [comment]
Hi there,

It appears the socketio.Client has a dictionary attribute of ``handlers`` which can be adjusted to remove handlers. @miguelgrinberg can advise if this will have unintended consequences, but it is working fine for basic event handler management in my code.

Outline of the approach I've taken is:

``sio = socketio.Client()``
``# event handlers created here``
``# now access handler attribute and edit:``
``sio.handlers['/'].pop['handler_name_to_remove']``

Miguel, I apologise if this is mistaken.

Many thanks

Ben
