### ISSUE TITLE
python-engineio dependancies

### ISSUE THREAD

**Issue by wilson3q** [miguelgrinberg/python-socketio#579]
when use pip install python-socketio packages, i got the error below:

`python-socketio 5.0.0 requires python-engineio<4,>=3.13.0, but you have python-engineio 4.0.0 which is incompatible.`

but actually python-socketio v5 only works with python-engineio v4, not v3...right?

please help to fix this error.

**Comment by miguelgrinberg** [comment]
Yes, sorry, I forgot to update the dependency when I release this new version yesterday. Fix is coming up in a few minutes.

**Comment by miguelgrinberg** [comment]
Fixed in 5.0.1.

**Comment by wilson3q** [comment]
Good job! Keep up the good work!


Thanks!
