### ISSUE TITLE
Could not use websocket transport in linux docker

### ISSUE THREAD

**Issue by ZegWe** [miguelgrinberg/python-socketio#580]
```python
sio.connect('http://0.0.0.0:8080', transports=['websocket'])
```
It works on my **MacOS** laptop but it doesn't work in a linux **docker**.
It just can't connect to server(using aiohttp) and **exit automatically, with no error raised**.

I test the code in the docs and it doesn't work either

server:
```python
from aiohttp import web
import socketio

sio = socketio.AsyncServer()
app = web.Application()
sio.attach(app)

@sio.event
def connect(sid, environ):
    print("connect ", sid)

@sio.event
async def chat_message(sid, data):
    print("message ", data)
    await sio.emit('reply', room=sid)

@sio.event
def disconnect(sid):
    print('disconnect ', sid)

if __name__ == '__main__':
    web.run_app(app)
```
client:
```python
import socketio

sio = socketio.Client()

@sio.event
def connect():
    print('connection established')

@sio.event
def my_message(data):
    print('message received with ', data)
    sio.emit('my response', {'response': 'my response'})

@sio.event
def disconnect():
    print('disconnected from server')

sio.connect('http://localhost:8080', transports=['websocket'])
sio.wait()
```

**Comment by miguelgrinberg** [comment]
See the troubleshooting section of the docs.

For the client: https://python-socketio.readthedocs.io/en/latest/client.html#debugging-and-troubleshooting.
For the server: https://python-socketio.readthedocs.io/en/latest/server.html#debugging-and-troubleshooting

The logs will hopefully help understand what the issue is.

**Comment by ZegWe** [comment]
I turned the logger on it shows that websocket-client didn't installed. I wrongly thought that it would be installed automatically when Python-socketio were installing just like on macos
sry to bother you

**Comment by miguelgrinberg** [comment]
Yeah, this is in the docs, to install the client dependencies you have to use either `python-socketio[client]` or `python-socketip[async_client]`.

https://python-socketio.readthedocs.io/en/latest/client.html#installation
