### ISSUE TITLE
TypeError: send() got an unexpected keyword argument 'binary

### ISSUE THREAD

**Issue by razdahan** [miguelgrinberg/python-socketio#582]
Hi,
I installed today the flask-socketio on a new system, and I get this error when the client socketio tries to connect.
this still works on my other machine and I cannot understand why it won't work on the new one,
same code, and same versions.

my code doesn't have much in it, it's just the basic connect function from the tutorial.

Flask-socketio==4.3.1
python-scoketio==4.6.0

**Comment by tmello01** [comment]
Experiencing this same bug in code that was previously working in production. Simply running `socketio.emit("event", 5)` causes this error for me.

**Comment by miguelgrinberg** [comment]
You have incorrect dependencies. Uninstall flask-socketio, python-socketio and python-engineio and then run `pip install flask-socketio` to bring the correct set of dependencies.

**Comment by razdahan** [comment]
Thank you for the quick reply! 
Worked perfectly!
This happened because I installed python-socketio sepertly?

**Comment by miguelgrinberg** [comment]
Yes, that would do it.
