### ISSUE TITLE
cannnot be installed in python3.5 because  bidict==0.21.0 cannot be installed in python3.5

### ISSUE THREAD

**Issue by huangganggui** [miguelgrinberg/python-socketio#589]
could not find a version that satisfies the requirement bidict>=0.21.0 (from python-socketio>=2.1.0->flask-socketio==4.0.0->-r requirements.txt

https://pypi.org/project/bidict/

**Comment by miguelgrinberg** [comment]
I do not support Python 3.5, there's been four major releases of Python since then so at this time support is for 3.6+.

**Comment by kjellLa** [comment]
Well, I am running Python 3.7 and I have the same problem.

**Comment by miguelgrinberg** [comment]
@kjellLa bidict supports Python 3.7.

**Comment by lukelu0520** [comment]
It's weird. We are using Python 2.7 and still get `ERROR: No matching distribution found for bidict>=0.21.0 (from python-socketio)`

**Comment by kjellLa** [comment]
I found a solution in https://github.com/miguelgrinberg/python-socketio/issues/578 but I am not sure what did do the trick (played around with many of the good tips I found there). It is likely it was when I run pip install flask_socketio==4.3.2 but not sure.

**Comment by miguelgrinberg** [comment]
@lukelu0520 that's not weird. Python 2.7 has long been out of maintenance. I stopped supporting that version of Python long ago. Upgrade to Python 3.
