### ISSUE TITLE
Django application return 401 error

### ISSUE THREAD

**Issue by PatharrajA** [miguelgrinberg/python-socketio#595]
While using Django authenticated application return 401 error.

Python Code:

sio = socketio.Server(async_mode=async_mode, cookie=True,
                      cors_allowed_origins='*', logger=True, engineio_logger=True)

![image](https://user-images.githubusercontent.com/33256824/102966054-1b533600-4515-11eb-93aa-45eca636717c.png)

Client using react js. React application also send token .

import socketIOClient from "socket.io-client";

const socket = socketIOClient(
    appConstants.SOCKET_URL,
    {
        rejectUnauthorized: false,
        extraHeaders: {
            authorization: 'JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyMSwidXNlcm5hbWUiOiJwYXRoYXJyYWpAaW50ZWxsZWN0eXguY29tIiwiZXhwIjoxNjA4NzI1MjQ1LCJlbWFpbCI6InBhdGhhcnJhakBpbnRlbGxlY3R5eC5jb20ifQ.T8cY5X02OfidUfJj0jK83aez3IAYzEhw7cAkxE2UwnQ'
        }
    }
);

**Comment by miguelgrinberg** [comment]
You seem to have a mix of incompatible packages. The python-socketio and python-engineio need to be of compatible releases. Check the version compatibility table and fix this, then let me know if any problems remain.

**Comment by PatharrajA** [comment]
Django using versions:

python-engineio==4.0.0
python-socketio==4.6.0
Django == 3.0.8

socket.io-client: "^3.0.4

i have tried different django application without authenticated mechnicasam its working fine. But authenticated Django application only have 401 issue.

Authenticated Django application call below method after only error will return

@sio.event
def connect(sid, environ):
    sio.emit('establish', {'data': 'Connected', 'count': 0})

**Comment by PatharrajA** [comment]
Thank you its working fine
