### ISSUE TITLE
Horizontal Scaling with Redis as Storage Backend

### ISSUE THREAD

**Issue by jsenecal** [miguelgrinberg/python-socketio#6]
Hello there,

I'm about to step in to contributing to that project but needed to know what were your plans first.

In the docs you say:
>A limitation in the current release of the Socket.IO server is that because the clients are randomly assigned to different server processes, any form of broadcasting is not supported. A storage backend that enables multiple processes to share information about clients is currently in development to address this important limitation.

So my proposed solution to that is to implement that storage backend using Redis PUBSUB.
Many others have seen this as the go-to way of doing multi-processing and it has the advantage of offering horizontal scaling. (An example of this can be found [HERE](https://codesachin.wordpress.com/2015/06/27/redis-node-js-socket-io-event-driven-subscription-based-broadcasting/) with NodeJS)

**Comment by miguelgrinberg** [comment]
Yes, I'm actually working on this myself. Redis pubsub is also my first choice, but I want to ensure other backends can also be used in the future.

**Comment by miguelgrinberg** [comment]
@jsenecal a simple, initial implementation of the redis backend for horizontal scaling is committed to branch `v1.0` in this repository.

**Comment by gamella** [comment]
@miguelgrinberg Great works! I really want this feature. Can you share the schedule of v1.0?

**Comment by miguelgrinberg** [comment]
I don't have a strict timeline. The code is working fairly well, but needs more testing. I'm in the process of writing the documentation and unit tests now, so it's coming soon.

**Comment by gamella** [comment]
Cool!

**Comment by miguelgrinberg** [comment]
This feature is implemented in version 0.8 of this package.
