### ISSUE TITLE
emitting raw json string

### ISSUE THREAD

**Issue by tsoernes** [miguelgrinberg/python-socketio#600]
is that possible? if not, i would like to make a feature request for that.

**Comment by miguelgrinberg** [comment]
You can emit JSON (as a dict or list), and you can emit strings. What else do you need that these use cases can't handle?

**Comment by tsoernes** [comment]
Emitting JSON, as string, and then receiving it as an object in the
javascript frontend

**Comment by miguelgrinberg** [comment]
If you send a string, you get a string on the JS side. If you send a dict, you get an object. If you send a list, you get an array. I don't see a need to support string to object, that seems confusing.

**Comment by tsoernes** [comment]
I just want to bypass the JSON encoder.

**Comment by miguelgrinberg** [comment]
You have to options. Either configure your own custom JSON encoder, or else send a string and manually decode to JSON on the other end.

**Comment by cyberlan3** [comment]
Helpful. Thank you.
