### ISSUE TITLE
How to emit in such case?

### ISSUE THREAD

**Issue by kamalpandey** [miguelgrinberg/python-socketio#601]
I have file upload functionality.

```
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/3.0.4/socket.io.min.js"></script>

<script type="text/javascript" charset="utf-8">
      var socket = io.connect('http://' + document.domain + ':' + location.port);
      
      socket.on('connect', function(msg) {
        socket.emit('long-running-event', {data: 'Socket connected!'});
      });


      socket.on('processing-finished', function (data) {
        console.log("RECEIVED")
      });

    </script>
```

```
from flask_socketio import SocketIO, emit

@socketio.on('long-running-event')
def my_event(message):
  print(message['data'])


@app.route('/uploader', methods=['POST'])
def upload_file():
  uploaded_file = request.files['file']
  filename = secure_filename(uploaded_file.filename)
  if filename != '':
    job = Process(target=task,  args=(filename, uploaded_file))
    job.start()
    flash("File is successfully uploaded", "success")
    return redirect(url_for("index"))
  else:
     return redirect(url_for("upload_view"))

```

Background task
```

def task(filename, uploaded_file):
  time.sleep(6)

  file_state_machine = FileStateMachine(uploaded_file)
  file_state_machine.file_upload()

  with app.test_request_context('/'):
    socketio.emit('processing-finished', {'data': 'finished processing'})


```

```
 file_state_machine.file_upload()
```

will trigger file_upload,  uploaded file format conversion, some file processing, csv generation, upload to s3 and delete local file and is working fine.
but socket.io is not emitting after all task is finished.
Is there any way i can make it work or i should follow different approach.
This is my first time with python and flask so help is appreciated

**Comment by miguelgrinberg** [comment]
Your background task is in another process, that's not going to work. Try using a background thread instead, which you can start with the `socketio.start_background_task()` function.

Also and as a side note, you are using a test request context in your task. That's a fake context that does not refer to any client. The only reason a request context is needed by this extension is to know who the client is. Since a test request context doesn't have that, it would be the same to not have a context.

**Comment by kamalpandey** [comment]
Thank you @miguelgrinberg  I managed to get it working with thread.
But I didn't get your second suggestion. Could you help me? My use case was just to refresh the browser once the background task is completed so that the list gets updated. I am new to this one. Thanks!!

**Comment by miguelgrinberg** [comment]
> But I didn't get your second suggestion

All I was saying is that a test request context has no place in application code, it is supposed to be used in unit tests.

**Comment by kamalpandey** [comment]
@miguelgrinberg Thank you so much.
```
def task(filename, app):
  time.sleep(6)
  with app.app_context():
    file_state_machine = FileStateMachine(filename)
    file_state_machine.file_process()
```
Is this okay?

I need to access the config variables in file_state_machine.

**Comment by miguelgrinberg** [comment]
Yes, that is okay.

**Comment by kamalpandey** [comment]
Thank you so much @miguelgrinberg.
