### ISSUE TITLE
I have two Questions sir 

### ISSUE THREAD

**Issue by PUNEET-8** [miguelgrinberg/python-socketio#604]
I am doing Python Django Project using React Front end

1. I want to emit to a particular socket Id , through this I am getting the error 
    ` Code:--   sio.to(socket).emit('my_response', {'data': 'You are Deleted'});`

     *** AttributeError: 'AsyncServer' object has no attribute 'to'***
     

2. Unable to import from other files 
       ```
        from .models import *
        import asyncio
        
        import uvicorn
        
        import socketio, pdb
        import pickle
```

    Getting the error 
  ***   from .models import *
ModuleNotFoundError: No module named '__main__.models'; '__main__' is not a package
****

**Here Below the Overall script of Web socket** 

 
[#!/usr/bin/env python
from .models import *
import asyncio

import uvicorn

import socketio, pdb
import pickle

sio = socketio.AsyncServer(async_mode='asgi', cors_allowed_origins="*")
app = socketio.ASGIApp(sio)
background_task_started = False
users = {}

async def background_task():
    """Example of how to send server generated events to clients."""
    count = 0
    while True:
        await sio.sleep(10)
        count += 1
        # io.to(socketid).emit('message', 'for your eyes only');
        pdb.set_trace()
        await sio.emit('my_response', {'data': 'Server generated event'})

@sio.on('login')
async def login(sid, message):
    global users
    users[sid] = int(message['userId'])
    print("Login users", users)
    filename = 'dogs'
    outfile = open(filename,'wb')
    pickle.dump(users,outfile)
    outfile.close()
    await sio.emit('my_response', {'data': ''}, room=sid)

@sio.on('my_broadcast_event')
async def test_broadcast_message(sid, message):
    await sio.emit('my_response', {'data': message['data']})

@sio.on('join')
async def join(sid, message):
    sio.enter_room(sid, message['room'])
    await sio.emit('my_response', {'data': 'Entered room: ' + message['room']},
                   room=sid)

@sio.on('leave')
async def leave(sid, message):
    sio.leave_room(sid, message['room'])
    await sio.emit('my_response', {'data': 'Left room: ' + message['room']},
                   room=sid)

@sio.on('close room')
async def close(sid, message):
    await sio.emit('my_response',
                   {'data': 'Room ' + message['room'] + ' is closing.'},
                   room=message['room'])
    await sio.close_room(message['room'])

@sio.on('my_room_event')
async def send_room_message(sid, message):
    await sio.emit('my_response', {'data': message['data']},
                   room=message['room'])

@sio.on('disconnect request')
async def disconnect_request(sid):
    global users
    del users[sid];
    print("AFter logout", users)
    await sio.disconnect(sid)

@sio.on('connect')
async def test_connect(sid, environ):
    global background_task_started
    if not background_task_started:
        sio.start_background_task(background_task)
        background_task_started = True
    await sio.emit('my_response', {'data': 'Connected', 'count': 0}, room=sid)

@sio.on('disconnect')
def test_disconnect(sid):
    print('Client disconnected')

if __name__ == '__main__':
    uvicorn.run(app, host='0.0.0.0', port=5000)](`url`)

**Comment by miguelgrinberg** [comment]
> I want to emit to a particular socket Id , through this I am getting the error

You are using the JavaScript documentation and applying it to the Python server. Use the python-socketio documentation, the JavaScript and Python implementations are different.

> Unable to import from other files

That is unrelated to this project, you need to fix your project to import your modules correctly.

**Comment by PUNEET-8** [comment]
Sir one last Question , How can I emit the event from outside of Socket i.o context  (means from other file). I tried many ways but didn't succeed

**Comment by miguelgrinberg** [comment]
There is no restrictions on emitting from different files. You need to be more specific.

**Comment by PUNEET-8** [comment]
ok sir, from next time onward i will be more specific, 
this time last final question 
I want to emit from server to server , But No error comes and no response is printed on Client side 
Here below is my models.py
```
from registration.socket import *
@receiver(models.signals.post_delete, sender=Driverprofile)
def delete_user_object(sender, instance, *args, **kwargs):
    print("Driver going to delete")
    instance.user.profile.delete()
    loop = asyncio.new_event_loop()

    loop.run_until_complete(user_removed(instance.user.id))
    loop.close()
    instance.user.delete()
```


 
#!/usr/bin/env python
# from .models import *
import asyncio

import uvicorn

import socketio, pdb
import pickle
# from registration.models import *

sio = socketio.AsyncServer(async_mode='asgi', cors_allowed_origins="*")
app = socketio.ASGIApp(sio)
background_task_started = False
users = {}

async def background_task():
    """Example of how to send server generated events to clients."""
    count = 0
    while True:
        await sio.sleep(10)
        count += 1
        # io.to(socketid).emit('message', 'for your eyes only');
        # pdb.set_trace()
        await sio.emit('my_response', {'data': 'Server generated event'})


@sio.on('login')
async def login(sid, message):
    global users
    users[sid] = int(message['userId'])
    print("Login users", users)
    filename = 'dogs'
    outfile = open(filename,'wb')
    pickle.dump(users,outfile)
    outfile.close()
    await sio.emit('my_response', {'data': ''}, room=sid)


@sio.on('my_broadcast_event')
async def test_broadcast_message(sid, message):
    await sio.emit('my_response', {'data': message['data']})


@sio.on('join')
async def join(sid, message):
    sio.enter_room(sid, message['room'])
    await sio.emit('my_response', {'data': 'Entered room: ' + message['room']},
                   room=sid)


@sio.on('leave')
async def leave(sid, message):
    sio.leave_room(sid, message['room'])
    await sio.emit('my_response', {'data': 'Left room: ' + message['room']},
                   room=sid)


@sio.on('close room')
async def close(sid, message):
    await sio.emit('my_response',
                   {'data': 'Room ' + message['room'] + ' is closing.'},
                   room=message['room'])
    await sio.close_room(message['room'])


@sio.on('my_room_event')
async def send_room_message(sid, message):
    await sio.emit('my_response', {'data': message['data']},
                   room=message['room'])


@sio.on('disconnect request')
async def disconnect_request(sid):
    global users
    del users[sid];
    print("AFter logout", users)
    await sio.disconnect(sid)


@sio.on('connect')
async def test_connect(sid, environ):
    global background_task_started
    if not background_task_started:
        sio.start_background_task(background_task)
        background_task_started = True
    await sio.emit('my_response', {'data': 'Connected', 'count': 0}, room=sid)


@sio.on('disconnect')
def test_disconnect(sid):
    print('Client disconnected')

@sio.event
async def user_removed(userId):
    # global users
    infile = open('/home/nhz/Desktop/sprint/registration/dogs','rb')
    new_dict = pickle.load(infile)
    socketIds = [] 
    for key, value in new_dict.items():
        if userId == value:
            # return key
            socketIds.append(key)
    for i in socketIds:
        print("KL", i)
        await sio.emit('my_response', {'data': 'You are deleted by admin Session logged out', 'count': 0}, room=i)

if __name__ == '__main__':
    uvicorn.run(app, host='0.0.0.0', port=5000)

But when I debugged user_removed method no error comes , and No response will be get in client side (You are deleted by admin Session logged Out)   , I think this is the wrong way to emit an event from server to server. Please help sir

**Comment by miguelgrinberg** [comment]
The `@receiver` decorator is not from this package, so I don't understand what you are showing me. Also when you say "I want to emit from server to server" that is really not possible. Emits are sent from a client to the server or viceversa. Two servers cannot communicate with Socket.IO.

**Comment by PUNEET-8** [comment]
Sorry sir for disturbing you again and again, 
I just want to call an event from the other file from where i can send the socket id as an argument , and then in our socket context I want to send a message to that socket id. In above example Receiver is nothing but When the particular user delete then that function will be call, inside that function I want to call the socket event

**Comment by miguelgrinberg** [comment]
You can't call a socket event from inside the server, that's not what Socket.IO is for.
