### ISSUE TITLE
Sending a message to multiple rooms

### ISSUE THREAD

**Issue by nkgsv** [miguelgrinberg/python-socketio#605]
Is it possible to send (emit) a message to multiple rooms in such a way that if a client is a member of two rooms then he gets the message only once?

In the Socket.IO Node.js server this can be done [as follows](https://socket.io/docs/v2/rooms/):
```js
io.to('room1').to('room2').to('room3').emit('some event');
```

However `socketio.emit` [seems to accept](https://github.com/miguelgrinberg/python-socketio/blob/b418af4c53619305c0b91a040e40fc7f3b907a74/socketio/base_manager.py#L152) only one `room` as argument.

**Comment by miguelgrinberg** [comment]
Yes, that's the way it is now. You can do a for-loop and emit to each of your rooms individually.

**Comment by nkgsv** [comment]
This is what I am doing for the moment, a for-loop emitting to each of the rooms individually.
But the downside is that if a recipient is in two rooms at the same time then he gets the message twice.
Is it possible to rule out this "multiple delivery" effect?

I am thinking to append some identifier (unique for all rooms) to the message when sending it from the server and the client should filter the incoming messages by this identifier, so that only one message with a specific identifier is processed.
But I don't like the idea of sending the same data to one client twice. Therefore I would prefer to use a built-in solution if it exists. It would be OK to use some internals - actually I am using flask-socketio, if this matters.

**Comment by miguelgrinberg** [comment]
There is nothing internally or externally that will assemble a list of clients across multiple rooms removing duplicates. The functionality isn't there at all at this time, you are actually the first person ever to suggest this as a feature.

**Comment by nkgsv** [comment]
I think this feature would be useful, and moreover it would be coherent with the [Node.js implementation](https://socket.io/docs/v2/rooms#Joining-and-leaving).

In fact I would like to propose the following implementation for the case when the client list is stored in an in-memory structure:

```python3
class ExtendedBaseManager(BaseManager):
    def emit(self, event, data, namespace, room=None, skip_sid=None,
             callback=None, **kwargs):
        """Emit a message to a single client, a room, a list of rooms 
        or all the clients connected to the namespace.

        If a list of rooms is given then every socket that is at least
        in one of the rooms will get the event once (even if the socket
        is in two or more rooms)"""
        if namespace not in self.rooms:
            return
        
        if not isinstance(room, list):
            room = [room]

        to_rooms = set()
        for r in room:
            if r in self.rooms[namespace]:
                to_rooms.add(r)
        if len(to_rooms) == 0:
            return
            
        if not isinstance(skip_sid, list):
            skip_sid = [skip_sid]
        
        recipients = set()
        for r in to_rooms:
            recipients.update(self.get_participants(namespace, r))
        
        for sid in recipients:
            if sid not in skip_sid:
                if callback is not None:
                    id = self._generate_ack_id(sid, namespace, callback)
                else:
                    id = None
                self.server._emit_internal(sid, event, data, namespace, id)
```
Then the SocketIO server can be started via
```python3
import socketio
sio = socketio.Server(client_manager=ExtendedBaseManager())
```
or (in the case of `flask_socketio`)
```python3
from flask_socketio import SocketIO
sio = SocketIO(app, async_mode, client_manager=ExtendedBaseManager())
```
Once this is done, a message can be sent to multiple rooms as follows:
```python3
sio.emit('some_event', data={'hello': 'world'}, room=['room1', 'room2'], namespace='namespace')
```

Of course, this is limited to the case when the client list is stored in an in-memory structure.

**Comment by miguelgrinberg** [comment]
Right, unfortunately I cannot do it this way because it introduces a difference in how single and multiple servers are implemented. When I look at this I'll have to find a solution that also works for multi-server deployments.
