### ISSUE TITLE
Connection auth data not getting captured

### ISSUE THREAD

**Issue by jextrevor** [miguelgrinberg/python-socketio#606]
I'm creating a socketio.AsyncServer that runs through tornado. I've got some code to log info about an auth event:

```
@sio.event
async def connect(sid, environ, auth):
    print('connect ', sid, auth)
```

However, whenever I try to connect to the server, I get this error:
```
ERROR:engineio.server:message async handler error
Traceback (most recent call last):
  File "/home/trevor/simcard/server/env/lib/python3.9/site-packages/engineio/asyncio_server.py", line 447, in _trigger_event
    ret = await self.handlers[event](*args)
  File "/home/trevor/simcard/server/env/lib/python3.9/site-packages/socketio/asyncio_server.py", line 555, in _handle_eio_message
    await self._handle_connect(eio_sid, pkt.namespace)
  File "/home/trevor/simcard/server/env/lib/python3.9/site-packages/socketio/asyncio_server.py", line 445, in _handle_connect
    success = await self._trigger_event('connect', namespace, sid,
  File "/home/trevor/simcard/server/env/lib/python3.9/site-packages/socketio/asyncio_server.py", line 521, in _trigger_event
    ret = await self.handlers[namespace][event](*args)
TypeError: connect() missing 1 required positional argument: 'auth'
```

It looks like it's not passing through the auth somehow. If I remove the auth parameter in the connect callback then I have no issues.
I am willing to help make the necessary changes and make a PR - I just don't really know where the actual issue is.

For reference, I'm using Python 3.9.1 on Arch Linux, and this is my requirements.txt:
```
bidict==0.21.2
python-engineio==4.0.0
python-socketio==5.0.4
tornado==6.1
```

As the client, I'm using the Node.JS `socket.io-client` library, version 3.0.4. I'm connecting using this code:
```
const io = require('socket.io-client')
const socket = io('http://localhost:3000', {
    auth: {
        'test': 'test'
    }
})
```

Thanks in advance.

**Comment by miguelgrinberg** [comment]
The problem is that you are looking at the `latest` version of the documentation, which reflects the master branch, but you are using code that is slightly older than that, which matches the `stable` version of the documentation.

This `auth` argument is new and will appear in the next release, it does not exist in the current version of the package.

**Comment by jextrevor** [comment]
Ah, I see now, thanks for your quick reply!

**Comment by wzying58** [comment]
I have encountered the same error message when running a small app on chainlit
https://docs.chainlit.io/get-started/pure-python

I'm quite new to chainlit, what does the error mean in this context?
