### ISSUE TITLE
Socketio Python client always disconnects after a short while

### ISSUE THREAD

**Issue by Nathan1258** [miguelgrinberg/python-socketio#607]
I have this 'hub' that connects to my server via socket io. This 'hub' is based off Python and my server is written in JavaScript.

I don't have the exact timings as it's never the same each time, but after a while my 'hub' client will disconnect from my server. 

Due to the nature of my project, I have no idea how many emits/requests that will be performed daily. That said, sometimes there will be no emits/requests to the server via the 'hub' client as it only sends out requests on the user's action. So yes, there will be times of inactivity.

I have read somewhere that socket.io supports heartbeat messages to keep the connection alive, no matter what or how long, which sends a ping pong packet every so often automatically without any configuration on my part, I am yet to see this feature work, if it is a thing in this wrapper?

Is there something I am missing or? I have searched everywhere so some links or info would be great!

**Comment by miguelgrinberg** [comment]
Look over the troubleshooting section of the docs to learn how to enable logging for your client. Then leave the client running with logs until it fails, so that we can see what was the reason for the disconnection.

**Comment by Nathan1258** [comment]
I have done that already, if you'd like to see the logs? Sorry I shoud've probably provided it. Two seconds and I will fetch them....it's on a server somewhere that I am yet to remember

**Comment by joshkinabrew** [comment]
@miguelgrinberg I'm running in to this same issue too. Running 5.0.4 for python-socketio and 4.0.0 for python-engineio.

Never had an issue until we upgraded to 5.0.4 on the python end (server I connect to is nodejs)

logs here:

```
Unexpected error receiving packet: "[Errno 11] Resource temporarily unavailable", aborting
Waiting for write loop task to end
Exiting write loop task
Engine.IO connection dropped
Connection failed, new attempt in 1.19 seconds
Exiting read loop task
Attempting polling connection to <snip my server>
Polling connection accepted with {'sid': 'W7FAnHApEjXfhxmAAAAk', 'upgrades': ['websocket'], 'pingInterval': 5000, 'pingTimeout': 30000}
Engine.IO connection established
Sending packet MESSAGE data 0
Attempting WebSocket upgrade to <snip my server>
WebSocket upgrade was successful
Reconnection successful
Received packet MESSAGE data 0{"sid":"n0jt11yD0ySmtShuAAAl"}
Namespace / is connected
Emitting event "myevent" [/]
```

Thanks for all you do!

**Comment by miguelgrinberg** [comment]
@joshkinabrew and did you upgrade your server as well? The Socket.IO protocol has been through a backwards incompatible upgrade recently. If you upgrade the client side you also have to upgrade the server to match.

**Comment by joshkinabrew** [comment]
@miguelgrinberg yes, sorry I forgot to mention that. We are on 3.1.0 of the JS library.

**Comment by miguelgrinberg** [comment]
@joshkinabrew I'm not really sure. The "resource temporarily unavailable" occurs when a non-blocking socket buffer is full I think, I would not have expected this error to occur in the client unless a) you are using the asyncio client, and b) things get backed up for some reason. Does this match your situation?

**Comment by joshkinabrew** [comment]
@miguelgrinberg I'm not using the async client, no.

regarding getting backed up, I'm unsure how I would find that out. I have a JS client running with no issues, it's just the Python side having issues. We're using Python 3.8 if that helps. The Python client end is on a cellular connection and the JS client end is using a wired connection. 

Is there a way I can tell when the buffer gets full? is there an adjustable size for the buffer?

**Comment by Nathan1258** [comment]
I haven't been working in my project for a bit and just saw this again (completely forgot). For my Python client, I am just using the simple python-socketio module, two simple lines of code:

```
sio.connect(<server url>)
sio.wait()
```

**Comment by miguelgrinberg** [comment]
This error is generated by the WebSocket library, when it is waiting for data to arrive. You can see the call to `ws.recv()` here: https://github.com/miguelgrinberg/python-engineio/blob/master/engineio/client.py#L606.

The python-engineio package is handling this error in the best possible way, which is to end the connection and then reconnect. Unfortunately the websocket-client package appears to be a bit quiet right now, so I'm not sure what else I can do to figure this out. Maybe it is time for me to look for another websocket library...

**Comment by Nathan1258** [comment]
Any reason why it doesn't reconnect when it ends the connections then? 

I would've thought it would be some kind of memory buffer error so I looked into it myself but you know more than me so 😂

**Comment by miguelgrinberg** [comment]
@Nathan1258 you are hijacking an issue from someone else and assuming I have the context for your case, which I don't. If you look above, the logs from the OP clearly show that the client is reconnecting.

**Comment by Nathan1258** [comment]
It was my issue to begin with. I was just confused to what you recently put about the web socket connecting and reconnecting. My logs are the same, I can provide them if need be.

**Comment by miguelgrinberg** [comment]
@Nathan1258 Oh, sorry you are right this was your issue. The problem is that you did not provide any logs, the other person did. You are claiming that your logs are the same, yet you ask why your client does not reconnect. The logs from this other person show a successful reconnection, so there is an inconsistency in what you are saying.

```
Engine.IO connection dropped
Connection failed, new attempt in 1.19 seconds
Attempting polling connection to <snip my server>
Polling connection accepted with {'sid': 'W7FAnHApEjXfhxmAAAAk', 'upgrades': ['websocket'], 'pingInterval': 5000, 'pingTimeout': 30000}
Engine.IO connection established
```

So yes, I think you need to provide your own logs if you have an issue with the reconnections.

**Comment by Nathan1258** [comment]
Yes sorry, bit of a mixup. I confused myself as I haven't been developing my project that uses this module hence why I haven't sent any logs - I forgot too lol. 

In regards to the other persons logs. I am in the same boat, with exactly the same logs. My client does reconnect after disconnecting, but the way I have prodced my program will not allow a reconnection to my server after it has connected once after boot. So my only work around right now (without rewriting all my connection code) is to reboot the device the code is running on to reset my programs volatile config, run the boot subroutine of my program again which in turn allows a new connection to my server.

Here are my logs:

    Exiting write loop task
    Engine.IO connection dropped
    Connection failed, new attempt in 1.11 seconds
    Exiting read loop task
    Attempting polling connection to <pingserver>
    Polling connection accepted with {'sid': sid', 'upgrades': ['websocket'], 'pingInterval': ping, 'pingTimeout': pingtimeout}
    Engine.IO connection established

Excuse the placeholders, this is a log from a question that I had on stackoverflow a while ago (same issue though)

Thanks!

**Comment by miguelgrinberg** [comment]
> but the way I have prodced my program will not allow a reconnection to my server after it has connected once

Okay, so this is a problem in your client or your server then? The Socket.IO protocol is designed with the reconnection feature, you can't expect a connection to be rock solid, problems always occur from time to time.

If you are asking how to prevent the problem that causes the disconnection I have already explained that this is happening down in the WebSocket layer. This package is just handling the error in the best possible way, which is to reconnect.

**Comment by Nathan1258** [comment]
> This package is just handling the error in the best possible way, which is to reconnect.

Would this be a normal thing to do with all WebSocket packages? What would be the best case scenario in your eyes if you were to make a WebSocket package?

So the only real solution here - in my case anyway - is to redesign my system to allow reconnections after the first inital connection to the server? I suppose I was stupid enough to design it this way. As you said, disconnections can occur, the internet is not perfect.

I shall leave this open for the other chap to hopefully find his solution, however.

**Comment by miguelgrinberg** [comment]
> Would this be a normal thing to do with all WebSocket packages?

This is a normal thing to do across the board, it is not limited to WebSocket. This package relies on a number of dependencies. If any failures occur in these dependencies I can't just let the failure happen. Instead I reset everything, start a new connection and hope for the best.

The problem is that this WebSocket package now appears to be unmaintained, which means that if this is in fact a bug that needs to be fixed there then the fix may take very long to be made if it is made at all. The reconnection is a sort of workaround, that allows your application to continue working in spite of the problem, but of course, you have to be prepared to handle those reconnects.
