### ISSUE TITLE
Django Application resolve api sequance way

### ISSUE THREAD

**Issue by PatharrajA** [miguelgrinberg/python-socketio#608]
Hi,

I have integrated python-socket.io with my Django rest application. After integration, my Django application became very slow and the socket.io is not working in asynchronous mode.

I'm using **eventlet** in socket.io to implement async mode which is causing slowness to the Django application.

Please refer the below code and let me know if anything I'm missing here to access the socket.io with django in an asynchronous way.

**wsgi.py:**

import os

from django.core.wsgi import get_wsgi_application
import socketio

from common.services.socket_service.socket_service import sio

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'taxi_server.settings')

application = get_wsgi_application()

application = socketio.WSGIApp(sio, application)

import eventlet
import eventlet.wsgi
eventlet.wsgi.server(eventlet.listen(('', 8000)), application)

**Socket.py** 

async_mode = None
sio = socketio.Server(async_mode=async_mode, ping_timeout=10000,
                      cors_allowed_origins='*')

**Comment by miguelgrinberg** [comment]
I'm not clear on what you are saying is causing slowness. Is it eventlet or Socket.IO?

**Comment by PatharrajA** [comment]
while using eventlet with Socket.io running server as synchronous way.

Kindly suggest any other async method to work server as asynchronous.

**Comment by miguelgrinberg** [comment]
The only two that are available for a Django app are eventlet and gevent. They are pretty similar, so I don't expect switching between them will give you much of a difference. I would instead look into your own code, which may not be doing things in a way that is compatible with async frameworks.
