### ISSUE TITLE
Python 2 compatibility broken

### ISSUE THREAD

**Issue by FlyingDiver** [miguelgrinberg/python-socketio#611]
v5.0.0 added a requirement for `bidict>=0.21.0`.  The last bidict version that supports Python 2 is 0.18.3.

Was this intentional?  The changelog doesn't mention this.

**Comment by miguelgrinberg** [comment]
Python 2 support was dropped long ago, well before this change.

**Comment by miguelgrinberg** [comment]
@magnus-rovco I missed that, thanks. I have removed Py2 now, so next build will have this corrected.
