### ISSUE TITLE
Callbacks lost when reconnecting

### ISSUE THREAD

**Issue by jsexauer** [miguelgrinberg/python-socketio#612]
I am calling the `call` function of the SocketIO client and the response from the `call` will take a long time to come return (about 1 hour).  As such, I am passing `timeout=None` to force the connection to stay open and wait this long time.  However, if the client looses contact during that timeframe, and successfully reconnects, the callback is lost and the following warning shows up:

> Unknown callback received, ignoring.

Looking through the code for client.py, it appears that when `_handle_eio_disconnect` is called, it clears the `callbacks` dictionary.  However, when the reconnect is established, the contents of the dictionary are never rebuilt.

https://github.com/miguelgrinberg/python-socketio/blob/eabcc4679bc283acdb9f87022ef1e0e82c48497e/socketio/client.py#L626-L639

**Comment by miguelgrinberg** [comment]
The Socket.IO protocol is not designed to have callbacks survive a reconnect, because the `sid` is going to change. I recommend that you use a normal emit to send your result and keep track of `sid` changes by handling the `connect` and `disconnect` event handlers.

**Comment by jsexauer** [comment]
Ok, thank you
