### ISSUE TITLE
Unable to connect to python-socketio with Android kotlin

### ISSUE THREAD

**Issue by ajju10** [miguelgrinberg/python-socketio#613]
I'm using the official Java socket.io client to connect to python-socketio backend with my Kotlin android app. 

I'm using the latest version of both libraries so I don't think there are any compatibility issues. 

The client never tries to connect to the server and no error messages are logged as well.

I think the server/client completely ignores each other.

Looking forward for some solution.

**Comment by miguelgrinberg** [comment]
> so I don't think there are any compatibility issues.

The Socket.IO protocol went through major changes just weeks ago, so I wouldn't be so sure.

Unfortunately I don't have an easy way to test the Java/Android client, and I don't track compatibility against it, so I suggest you ask the developer of this library regarding version compatibility and check that against the information in the documentation of this project.

**Comment by ajju10** [comment]
Thanks for your response. It's probably an issue of the Java library. I will look into it.

**Comment by IuraGaitur1** [comment]
@ajju10 did you manage to find versions that work together?

**Comment by ajju10** [comment]
@IuraGaitur1 It was probably the issue with the incompatibility between client and server and that's why I wasn't able to get it working.

The java-socketio client library maintainer was probably busy and so I abandoned the project for the time being and used plain websocket instead.
