### ISSUE TITLE
client timeout error on emit

### ISSUE THREAD

**Issue by deepthought-dev** [miguelgrinberg/python-socketio#616]
I am receiving a timeout error when attempting to emit an event to a nodejs socket.io server namespace. There are no issues when the client connects to the server and the namespace, but for some reason the server does not detect emitted events from the python client (there is no issue when this is done from nodejs socket.io-client). The package versions are: python-socketio 4.6.0, python-engineio 3.14.2, socket.io (nodejs) 2.3.0. 
```py
import socketio

class Resource(ApiClient):
    def __init__(self):
        self.sio_client = socketio.Client()
        self.sio_client.connect(self.base_url, headers={
            'Authorization': 'Bearer {}'.format(self.api_key)
         }, namespaces=['/resource/']) # no issues connecting to server

    def upload(self, data: list):
        self.sio_client.emit(event='upload', data=data, namespace='/resource/') # gives timeout error after 60 seconds. 
```
Thanks

**Comment by miguelgrinberg** [comment]
It would be useful to see logs for your client, and the stack trace please.

**Comment by deepthought-dev** [comment]
```
Traceback (most recent call last):
  File "/home/user/Desktop/code/resources.py", line 45, in <module>
    d.upload(file_path='/home/user/Desktop/test.txt')
  File "/home/user/Desktop/code/resources.py", line 29, in upload
    self.sio_client.call(event='upload', data={'data':[1,2,3,4,5]}, namespace='/resource/')
  File "/home/planetgazer8360/.local/lib/python3.8/site-packages/socketio/client.py", line 402, in call
    raise exceptions.TimeoutError()
socketio.exceptions.TimeoutError
```
I reran the code with
```py
self.sio_client = socketio.Client(logger=True, engineio_logger=True)
```
but there is no logging output to the terminal

**Comment by miguelgrinberg** [comment]
@deepthought-dev that is really not possible, unless you have something that suppresses logs. There are actually several log lines that should appear when the connection is established. Try one of the simple examples in this repository if you want to see what the logging should be.

**Comment by deepthought-dev** [comment]
I'm sorry, I just solved the issue. The problem was that I imported socketio and defined ```sio = socketio.Client()``` (which was not being used) in an internal file  that was imported by the code above, and for some reason that stopped events from emitting, in addition to suppressing the logs. I removed those two lines and the code is working well. Thanks for your help.

**Comment by deepthought-dev** [comment]
It seems that the code is yet not working well. The logging is working, however it seems that the emitting only works occasionally (previously it did not at all), as I have reran the code multiple times and it the majority of times the server does not receive the event.
This is the client log when the server does not receive the event:
```
Attempting polling connection to http://0.0.0.0:2024/socket.io/?transport=polling&EIO=3
Polling connection accepted with {'sid': 'amWsuAtEqllzFWUGAAAG', 'upgrades': ['websocket'], 'pingInterval': 25000, 'pingTimeout': 5000}
Engine.IO connection established
Received packet MESSAGE data 0
Namespace / is connected
Sending packet MESSAGE data 0/resource/
Attempting WebSocket upgrade to ws://0.0.0.0:2024/socket.io/?transport=websocket&EIO=3
WebSocket upgrade was successful
Sending packet PING data None
Emitting event "upload" [/resource/]
Sending packet MESSAGE data 2/resource/,["upload",{"data":[1,2,3,4,5]}]
Received packet MESSAGE data 0/resource/,
Namespace /resource/ is connected
Received packet PONG data None
```
When the server receives the event:
```
Attempting polling connection to http://0.0.0.0:2024/socket.io/?transport=polling&EIO=3
Polling connection accepted with {'sid': 'hmVEvclB4tZe_QN6AAAF', 'upgrades': ['websocket'], 'pingInterval': 25000, 'pingTimeout': 5000}
Engine.IO connection established
Received packet MESSAGE data 0
Namespace / is connected
Sending packet MESSAGE data 0/resource/
Attempting WebSocket upgrade to ws://0.0.0.0:2024/socket.io/?transport=websocket&EIO=3
WebSocket upgrade was successful
Sending packet PING data None
Received packet MESSAGE data 0/resource/,
Emitting event "upload" [/resource/]
Sending packet MESSAGE data 2/resource/,["upload",{"data":[1,2,3,4,5]}]
Namespace /resource/ is connected
Received packet PONG data None
```
I reran the code multiple times and the logs for each case are consistently the same, the difference seems to be the order in which part of the log is output:
Server does not receive event:
```
Emitting event "upload" [/resource/]
Sending packet MESSAGE data 2/resource/,["upload",{"data":[1,2,3,4,5]}]
Received packet MESSAGE data 0/resource/,
```
Server receives event:
```
Received packet MESSAGE data 0/resource/,
Emitting event "upload" [/resource/]
Sending packet MESSAGE data 2/resource/,["upload",{"data":[1,2,3,4,5]}]
```

**Comment by miguelgrinberg** [comment]
The `0/resource/` is the namespace connection packet. In the bad case you are emitting on the namespace before it is connected. You have to wait until the connect handler is invoked before emitting.

**Comment by deepthought-dev** [comment]
I see, though I cannot understand how this can technically happen as in the code the client connects to the server in __init__ before emitting the event in the upload function, unless for some reason there isn't enough time to connect and it tries to emit before it has finished connecting. Anyways, I found a solution to the problem by adding a time.sleep(1) between the client connecting to the server and emitting the event, the server now receives the event without issues.

**Comment by miguelgrinberg** [comment]
The connection is asynchronous. The `connect()` call initiates it, but the connection isn't finalized until your connect event handler fires up. This is an area that I hope I'll be able to improve in a future release, as this generates some confusion, but this is how the connection works at this time.
