### ISSUE TITLE
How to deploy socketio with django on nginx gunicorn/uwsgi

### ISSUE THREAD

**Issue by TimaBuldzer** [miguelgrinberg/python-socketio#623]
Hi, is there any tutorial or guide to properly launch python socketion with django on nginx gunicorn/uwsgi server? I have tried those at official documentation, but not successful.

**Comment by miguelgrinberg** [comment]
The documentation is up to date and correct, as far as I know. What problem did you have?

**Comment by TimaBuldzer** [comment]
> The documentation is up to date and correct, as far as I know. What problem did you have?

I dont know how to make it work, maybe there is some guide or tutorial step by step?

**Comment by miguelgrinberg** [comment]
The documentation for this package assumes that you understand how to use nginx/gunicorn/uwsgi work, but there are tons of tutorials out there, including my own Flask Mega-Tutorial. I suggest you learn how to deploy a simple Flask app using a tutorial, then come back to the Socket.IO docs to learn the specific configurations that need to be changed from a standard deployment.

**Comment by TimaBuldzer** [comment]
> The documentation for this package assumes that you understand how nginx/gunicorn/uwsgi work, but there are tons of tutorials out there, including my own Flask Mega-Tutorial. I suggest you learn how to deploy a simple Flask app using a tutorial, then come back to the Socket.IO docs to learn the specific configurations that need to be changed from a standard deployment.

Thanks for your tutorial 'Flask Mega-Tutorial' i did it :)
