### ISSUE TITLE
client and server verify for websocket transport help

### ISSUE THREAD

**Issue by bhastin** [miguelgrinberg/python-socketio#626]
Referencing #484 

Does http_session allow for **websocket** transport to work where both client and server verify?

Currently I am passing in http_session with an initialized requests.session that has the client certificates. SSL/TLS communication with client and server verify only seems to work for polling transport. Is that correct or is there a better example on how to do it?

I get "ssl.SSLError: [SSL: SSL_HANDSHAKE_FAILURE] ssl handshake failure" when upgrade is attempted, so it defaults to **polling** transport.

This is how I am using http_session:
```
http_session = requests.Session()
http_session.cert = ('/path/to/client.cert', '/path/to/client.key')

sio = socketio.Client(
    logger=True,
    engineio_logger=True,
    http_session=http_session,
    ssl_verify=CA_BUNDLE_PATH
)
```

**Comment by miguelgrinberg** [comment]
@bhastin there is currently no support for a custom CA bundle. The ssl_verify argument is either `True` or `False`. I think your passing of a CA bundle somehow works with HTTP, but this is not a setting that is currently being considered in the way you are using it, so it isn't copied from the HTTP session to the WebSocket client.

**Comment by bhastin** [comment]
It works because `ssl_verify` value is passed to engineio_options, and python-engineio passes the string to the requests.Session()'s request method which accepts `verify` as a string /path/to/certfile 

```
:param verify: (optional) Either a boolean, in which case it controls whether we verify
            the server's TLS certificate, or a string, in which case it must be a path
            to a CA bundle to use. Defaults to ``True``. When set to
            ``False``, requests will accept any TLS certificate presented by
            the server, and will ignore hostname mismatches and/or expired
            certificates, which will make your application vulnerable to
            man-in-the-middle (MitM) attacks. Setting verify to ``False`` 
            may be useful during local development or testing.
```
Source https://github.com/psf/requests/blob/8c211a96cdbe9fe320d63d9e1ae15c5c07e179f8/requests/sessions.py#L503

```python3
def _send_request(
            self, method, url, headers=None, body=None,
            timeout=None):  # pragma: no cover
        if self.http is None:
            self.http = requests.Session()
        try:
            return self.http.request(method, url, headers=headers, data=body,
                                     timeout=timeout, verify=self.ssl_verify)
```
Source https://github.com/miguelgrinberg/python-engineio/blob/c181e8563edf1586eb3f2baacaf4f2c26b1a2593/engineio/client.py#L520

### UPDATE

I was able to get **websocket** transport to work for mutual tls/ssl secure connections!

To get verify to work for the client, I used the following websocket-client environment variable:

```
export WEBSOCKET_CLIENT_CA_BUNDLE='/path/to/ca-bundle.crt'
```
Or by using Python code:
```
os.environ["WEBSOCKET_CLIENT_CA_BUNDLE"] = '/path/to/ca-bundle.crt'
```

**Comment by miguelgrinberg** [comment]
@bhastin Good workaround. I'll keep this open as a reminder to look into expanding this to configure the CA bundle directly.

**Comment by miguelgrinberg** [comment]
The [documentation](https://python-socketio.readthedocs.io/en/latest/client.html#tls-ssl-support) shows examples of how to set the CA bundle.
