### ISSUE TITLE
Question: how to create multiple client socket.io connections to the same url?

### ISSUE THREAD

**Issue by RomanKisilenko** [miguelgrinberg/python-socketio#629]
We have multiple servers behind load balancer. 

At some point single server is not capable handling load from our client.

So in order to balance load we need to create multiple connections to the same load balancer url which will eventually be routed to several physical servers. 

How we can achieve this with python-socketio AsyncClient?

**Comment by miguelgrinberg** [comment]
This is something that you need to configure in your load balancer, the client cannot do this unless you connect to different URLs.

**Comment by RomanKisilenko** [comment]
The LB is configured. 

I mean that even if I invoke AsyncClient.connect twice, I still get single connect event in python-socketio meaning that there is still single underlying physical connection for both AsyncClient connections.

So you mean that it is not possible to establish two physical connections to the same URL in python-socketio, correct?

Could you point me to a place in code where this behaviour is coded, so that we can alter us for our use case?

**Comment by miguelgrinberg** [comment]
Maybe I did not understand what you want to do. If all you want is to make two or more connections from the same script, then just create one `Client` or `AsyncClient` object for each of the connections, and call `connect()` on all of them with the same URL. Is this what you need?

**Comment by RomanKisilenko** [comment]
Sorry for confusion, we realised that creating multiple clients indeed works. The problem was in our code. Thank you for your help!
