### ISSUE TITLE
is it possible to use this in asyncio?

### ISSUE THREAD

**Issue by LoganDark** [miguelgrinberg/python-socketio#63]
I want to integrate this into an asynchronous program, when the `on_ready` event is called I want to call coroutines on socket events. is that possible?

**Comment by miguelgrinberg** [comment]
Not at this time. Unfortunately I haven't spent enough time to figure out how to make this project work for asyncio without having to rewrite most of the code in async format. I haven't given up, though.

**Comment by dfee** [comment]
@miguelgrinberg is that answer still accurate in light of https://github.com/channelcat/sanic/issues/356

**Comment by miguelgrinberg** [comment]
I missed this, yeah. This project now supports asyncio, with aiohttp and sanic. The aiohttp support includes long-polling and websocket. For sanic, there is only long-polling at this time, but support for websocket will become available as soon as the sanic guys release my websocket PR (https://github.com/channelcat/sanic/pull/469).
