### ISSUE TITLE
Enhancement: add the ability to remove event listeners.

### ISSUE THREAD

**Issue by AbdallahAlhaddad** [miguelgrinberg/python-socketio#630]
#### The problem:
As in [#576](https://github.com/miguelgrinberg/python-socketio/issues/576) 
`socket.off(event, handler)`, `socket.removeListener`, `socket.removeAllListeners`, `socket.removeEventListener` are not implemented in `python-socketio`.

#### Useful usecase(s) if implemented:
- It can be useful if we want to give the client the ability to toggle a specific functionality during runtime.

#### Proposed solution: 
- Implementing them in `python-socketio`.

#### workaround for now:
- extending `AsyncClient` class.
- I've implemented `removeAllListeners` with functionality that is as close as possible to the original [`JS socket.io removeAllListeners`](https://socket.io/docs/v3/listening-to-events/#socket-removeAllListeners-eventName)    (for now as it satisfies my project needs):
```python
import socketio

class CustomClient(socketio.AsyncClient):
    def __init__(self) -> None:
        super().__init__()

    def removeAllListeners(self, event_name=None, namespace=None) -> None:
        print("Handlers before remove:\n {}\n\n".format(self.handlers))
        if not event_name:
            if not namespace:
                print("no event name or namespace given, removing all events")
                self.handlers = {}
            else:
                print("no event name is given, removing all events from the specified namespace")
                del self.handlers[namespace]
        else:
            if not namespace:
                print('event name is given, but no namespace, deleting "{}" event from all namespaces'.format(event_name))
                for ns in self.handlers:
                    if event_name in self.handlers[ns]:
                        print("event '{}' found in '{}' namespace, deleting...".format(event_name, ns))
                        del self.handlers[ns][event_name]
            else:
                print('deleting "{}" event from "{}" namespace...'.format(event_name, namespace))
                del self.handlers[namespace][event_name]
        print("\n\nHandlers after remove:\n {}".format(self.handlers))



# usage:
sio = CustomClient()
sio.removeAllListeners("event_name") # delete a specific event in all namespace(s)
sio.removeAllListeners(event_name='name',namespace='/chat') # delete a specific event in a specific namespace
sio.removeAllListeners(namespace='/') #delete all event listeners for "/" namespace

```

**Comment by miguelgrinberg** [comment]
The `on()` and `off()` way of setting up event handlers is very common in JavaScript. It isn't however very Python when you have event handlers that are set up as decorated functions, so I don't really see how to fit this feature while keeping everything nice an Pythonic. 

> It can be useful if we want to give the client the ability to toggle a specific functionality during runtime.

Removing a handler would not only remove the feature for a specific client, it would remove it for everybody. I recommend that you add settings or state to your application to decide when your handlers need to be active or inactive. Dynamically adding/removing handlers is not a great pattern, in my opinion.

**Comment by miguelgrinberg** [comment]
I didn't mean anything too sophisticated, just a simple state:

```python
@sio.event
def great_feature(sid, data):
    if can_user_run_great_feature(sid):
        # do the work here
```

The state that keeps track of which users can or cannot run a given feature can be stored in the user session, for example.
