### ISSUE TITLE
unsupported version even when downgrading/upgrading

### ISSUE THREAD

**Issue by wtfRexx** [miguelgrinberg/python-socketio#637]
currently using: 

Flask-SocketIO==5.0.1
python-engineio==4.0.0
python-socketio==5.0.4

and https://cdnjs.cloudflare.com/ajax/libs/socket.io/3.1.1/socket.io.js

yet it still does not work..

"The client is using an unsupported version of the Socket.IO or Engine.IO protocols"

and yes ive tried looking through threads here and trying the solutions

another edit: it works locally but not on server which is the issue

also we get> "https://neine.com is not an accepted origin." 
i think this not accepted origin is the main problem, is this because the https protocol and binding the socketio server to the same address and port as the python web server?

**Comment by miguelgrinberg** [comment]
Did you configure your origins? This is about the CORS policy in web browsers. Add a `cors_allowed_origins='https://neine.com'` argument to your server configuration to indicate that connections from this origin should be accepted.

**Comment by wtfRexx** [comment]
> Did you configure your origins? This is about the CORS policy in web browsers. Add a `cors_allowed_origins='https://neine.com'` argument to your server configuration to indicate that connections from this origin should be accepted.

oh yeah works great thank you!
