### ISSUE TITLE
http://127.0.0.1:5000 is not an accepted origin.

### ISSUE THREAD

**Issue by viktorstrand** [miguelgrinberg/python-socketio#639]
Does anyone know what this error is and how to fix it?
<img width="632" alt="Skärmbild 2021-02-15 110755" src="https://user-images.githubusercontent.com/46597051/107946790-cde1cb00-6f91-11eb-9dd7-47c4cdb728e3.png">

**Comment by miguelgrinberg** [comment]
Your client is connecting from a different origin. Set `cors_allowed_origins='http://localhost:5000'` in your server to allow connections from this origin.

**Comment by viktorstrand** [comment]
@miguelgrinberg Thank you! Solved my problem

**Comment by viktorstrand** [comment]
@miguelgrinberg How do I do that? I am very new to socketio and web servers overall.

**Comment by miguelgrinberg** [comment]
This is an option that you provide when you create a Server object. It's passed as an argument. See the docs if you need more information.
