### ISSUE TITLE
Can connect to server but cannot send or emit.

### ISSUE THREAD

**Issue by viktorstrand** [miguelgrinberg/python-socketio#641]
I am able connect to the server but when I try to send or emit nothing happens. Does anyone know what might be causing this issue?
<img width="577" alt="Skärmbild 2021-02-17 155751" src="https://user-images.githubusercontent.com/46597051/108222379-08399c80-7139-11eb-9fc6-7f0f3c348c54.png">
<img width="392" alt="Skärmbild 2021-02-17 155825" src="https://user-images.githubusercontent.com/46597051/108222387-08d23300-7139-11eb-8c02-8ffbefcdbf31.png">

**Comment by miguelgrinberg** [comment]
Please provide logs for your client and your server to help in troubleshooting this problem. See the section on debugging and troubleshooting in the documentation if you don't know how to generate logs.

**Comment by viktorstrand** [comment]
@miguelgrinberg I am using flask-socketio with a java-script client and the documentation does not seem to match with my code

**Comment by viktorstrand** [comment]
Nvm i solved it
