### ISSUE TITLE
tornado class based handler -howto?

### ISSUE THREAD

**Issue by ali96343** [miguelgrinberg/python-socketio#648]
Event based hanler (from docs) works with tornado  beatiful.
But,  how to write class based handler for tornado server ?
thank you

**Comment by miguelgrinberg** [comment]
Do you want to write the Socket.IO handlers in a class format? Have you seen the class-based namespaces in the documentation? https://python-socketio.readthedocs.io/en/latest/server.html#class-based-namespaces

**Comment by ali96343** [comment]
sio = socketio.AsyncServer(async_mode='tornado')
    class SioHandler(socketio.AsyncNamespace):
.......
    sio.register_namespace(SioHandler('/test'))
#----------------------------------------------
tornado-url (r"/socket.io/", SioHandler )
connect string  const socket = io('http://localhost:8000/test');
----------------
 Thanks for the quick response
Unfortunately, it doesn't work.
I must be doing something wrong.

**Comment by miguelgrinberg** [comment]
What is it that doesn't work exactly? What error(s) do you get?

**Comment by ali96343** [comment]
with event based python-client messages:

Namespace / is connected
Namespace /chat is connected
Namespace /test is connected

with class-based python client-messages:

Created socketio client
Attempting polling connection to http://localhost:8000/socket.io/?transport=polling&EIO=4
HTTP GET request to http://localhost:8000/socket.io/?transport=polling&EIO=4&t=1614890190.9337695 failed with error HTTPConnectionPool(host='localhost', port=8000): Read timed out. (read timeout=5).
Traceback (most recent call last):
  File "./sio-client.py", line 17, in <module>
    sio.connect('http://localhost:8000/socket.io/', namespaces=['/','/chat', '/test'])
  File "/home/w3p/set1/env/lib/python3.7/site-packages/socketio/client.py", line 284, in connect
    raise exceptions.ConnectionError(exc.args[0]) from None
socketio.exceptions.ConnectionError: Connection refused by the server

~

**Comment by miguelgrinberg** [comment]
I'm confused. The code you shown at the top is for a Socket.IO server. The logs that you have right above this message are for a client. Can you also include logs for the server please?

**Comment by ali96343** [comment]
"code above" is  sio-client messages   for event-based-sio-handler  - some lines skipped
code in tornado:
sio= socketio.AsynServer(  async_mode="tornado", logger=True, engine_io.logger=True  )
With these parameters I see server messages for the event-based-sio-handler
and I don't see any server messages for class-based-sio-handler
The only message from the client is connection refused (see log above)

**Comment by miguelgrinberg** [comment]
> and I don't see any server messages for class-based-sio-handler

That is actually not possible. If the server is rejecting the connection it should log some information about it.

**Comment by ali96343** [comment]
test example with message
Server initialized for tornado.

`import tornado.ioloop
import tornado.web
import socketio

# tornado 6.03 , python-socketio 5.0.4
"""
@sio.event
async def connect(sid, environ):
        print('sio: connect ', sid)

@sio.event
async def disconnect(sid):
        print('sio: disconnect ', sid)

@sio.on('on_message')
async def echo(sid, data):
        print('sio: from client: ', data)
        await sio.emit("from_echo", data)
"""

class SioHandler(socketio.AsyncNamespace):
    def on_connect(self, sid, environ):
        print("connect!")
        pass

    def on_disconnect(self, sid):
        print("disconnect!")
        pass

    async def on_my_event(self, sid, data):
        print("sio: from client: ", data)
        await self.emit("my_response", data)


class MainHandler(tornado.web.RequestHandler):
    def get(self):
        self.write("Hello, world")

def make_app():
    sio = socketio.AsyncServer(async_mode="tornado", logger=True, engineio_logger=True)
    sio.register_namespace(SioHandler())
    return tornado.web.Application(
        [
            (r"/", MainHandler),
            # (r"/socket.io/", socketio.get_tornado_handler(sio) )
            (r"/socket.io/", SioHandler),
        ],
        debug=True,
        autoreload=False,
    )


if __name__ == "__main__":
    app = make_app()
    app.listen(8888)
    tornado.ioloop.IOLoop.current().start()
`

**Comment by miguelgrinberg** [comment]
What is this?

```
# (r"/socket.io/", socketio.get_tornado_handler(sio) )
(r"/socket.io/", SioHandler),
```

You seem to be confusing Socket.IO handlers with Tornado handlers. The first of the above two lines is the correct one, regardless of how you implement your Socket.IO handlers.

**Comment by ali96343** [comment]
this is the registration of the class-based-handler SioHandler
for now i wrote
        [
            (r"/", MainHandler),
            (r"/socket.io/", SioHandler),
        ],
----------------
Messages
 from server:       Server initialized for tornado.
frpm client:         Connection refused by the server,

**Comment by ali96343** [comment]
next attempt
    sio = socketio.AsyncServer(async_mode="tornado", logger=True, engineio_logger=True)
    sio.register_namespace(SioHandler(namespace='/'))
    return tornado.web.Application(
        [
            (r"/", MainHandler),
        ],

server messages
Server initialized for tornado.
WARNING:tornado.access:404 GET /socket.io/?transport=polling&EIO=4&t=1614961945.4421256 (127.0.0.1) 3.32ms

client message
.ConnectionError: Unexpected status code 404 in server response

**Comment by ali96343** [comment]
all works!!! THANK YOU!!!!!

   sio = socketio.AsyncServer(async_mode="tornado", logger=True, engineio_logger=True)
    sio.register_namespace(SioHandler(namespace='/'))
    return tornado.web.Application(
        [
            (r"/", MainHandler),
            (r"/socket.io/", socketio.get_tornado_handler(sio) ),
        ],
