### ISSUE TITLE
Feature request: Postgres PubSubManager

### ISSUE THREAD

**Issue by lefnire** [miguelgrinberg/python-socketio#649]
Would love to see a PostgresManager (similar to RedisManager) using PG's LISTEN/NOTIFY. Sample dedicated Flask module at https://github.com/revmischa/socketio_pg. For us using PG as our RDBMS anyway, would remove the need for hosting Redis.

**Comment by miguelgrinberg** [comment]
The `PubSubManager` classes are not too complex to write, and they do not need to be shipped with this package, they can be imported from your own application or from another package. I'm already maintaining too many of these classes, so I'm not sure I'll be up to writing even more, but that shouldn't stop you if this is important for your project.

**Comment by lefnire** [comment]
Fair enough, thanks for the response.

**Comment by hanayashiki** [comment]
I can contribute to this! Do you want to add this to features?

**Comment by miguelgrinberg** [comment]
Feel free to publish this as a separate package in your own. I'm not going to add more integrations at this time.

**Comment by mgd722** [comment]
@hanayashiki Did you ever write a package for this? I'd be interested as well!

**Comment by hanayashiki** [comment]
> @hanayashiki Did you ever write a package for this? I'd be interested as well!

https://pypi.org/project/socketio-pg-manager/
