### ISSUE TITLE
Server "eio_sid" error when entering client into a room in non-default namespace

### ISSUE THREAD

**Issue by sd-zhang** [miguelgrinberg/python-socketio#650]
For python-socketio v5, there is an error when trying to enter a client into a room when the namespace parameter is non-default.

Following are the server and client code used to isolate this situation:

**Server**
```
import socketio
from aiohttp import web

sio = socketio.AsyncServer(async_mode='aiohttp')
app = web.Application()
sio.attach(app)

@sio.event
async def connect(sid, environ):
    print("connect ", sid)
    sio.enter_room(sid=sid, room='test_room', namespace='/test_ns')
    await sio.emit('message', data='ping', room='test_room', namespace='/test_ns')

if __name__ == '__main__':
    web.run_app(app=app, port=6000)
```

**Client**
```
import asyncio
import socketio

sio = socketio.AsyncClient()

@sio.event
async def connect():
    print('connection established')

@sio.event(namespace='/test_ns')
async def message(data):
    print(data)

async def main():
    await sio.connect('http://localhost:6000')
    await sio.wait()

if __name__ == '__main__':
    asyncio.run(main())
```

Traceback eventually ends up here:
` File "[redacted]\venv\lib\site-packages\socketio\base_manager.py", line 115, in enter_room
    eio_sid = self.rooms[namespace][None][sid]
KeyError: None`

**Probable Cause**
I believe the error is caused by two functions.

1. The enter_room() function in socketio/server.py (line 389 as of time of writing), which calls enter_room() in base_manager, does not have an input for eio_sid. This causes eio_sid in the enter_room() function in base_manager to always default to None.
2. This means that lines 114-115 is always triggered:

```
if eio_sid is None:
    eio_sid = self.rooms[namespace][None][sid]
```

In the example, the namespace to be accessed would be '/test_ns', which does not exist self.rooms, thus causing the KeyError.

**The Fix**
I believe that the namespace to be accessed when `eio_sid is None` should be '/'. Replacing `eio_sid = self.rooms[namespace][None][sid]` with `eio_sid = self.rooms['/'][None][sid]` resolved the issue.

**Comment by miguelgrinberg** [comment]
This error should be handled better, so that is why I consider this a bug, but what would be the purpose of putting the user in a room under a namespace they are not connected to? The correct handling of this would be to return an error, since the client will never receive notifications from this room.

**Comment by sd-zhang** [comment]
Right. Agreed that this error should be handled better.
The error occurs in the case that the client is connected to the namespace as well. For example:

**Server**
```
@sio.event
async def connect(sid, environ):
    print("connect ", sid)
    await sio.sleep(5)
    sio.enter_room(sid=sid, room='test_room', namespace='/test_ns')

@sio.event(namespace='/test_ns')
async def connect(sid, environ):
    print("connect ", sid)
    await sio.emit('message', data='ping', room='test_room', namespace='/test_ns')
```

***Client***
```
async def main():
  await sio.connect('http://localhost:6000', namespaces=['/', '/test_ns'])
  await sio.wait()
```

For my application, the default namespace is used by the server to funnel some specific client information before deciding which rooms in certain namespaces they should be entered into. This was a lazy design choice on my part because the default namespace was always guaranteed to exist in V4.

It seems that in V5, the server can only enter clients into a room in a specified namespace if the enter_room() is called within an event triggered in that namespace. i.e.

***OK***
```
@sio.event(namespace='/test_ns')
async def connect(sid, environ):
    sio.enter_room(sid=sid, room='test_room', namespace='/test_ns')
```

***Not OK***
```
@sio.event
async def connect(sid, environ):
    sio.enter_room(sid=sid, room='test_room', namespace='/test_ns')
```

If this is the intended design, then I will rework my application so it conforms to this requirement.

**Comment by miguelgrinberg** [comment]
Well, the namespaces do not get connected together, the handshake to get each connected happens separately. So one of the namespaces is going to connect before the other, and if you refer to a namespace that hasn't been connected yet you'll also get this error, since the server has no way to know the client will soon ask to be connected to it.

**Comment by sd-zhang** [comment]
Makes sense. It's also because the same client has different sids in different namespaces, so looking up eio_sid fails from using the sid from a different namespace.

No problem though, I think having more isolation is for the better. I'll update my application to avoid this error. Thanks for the explanation!
