### ISSUE TITLE
Releasing new version

### ISSUE THREAD

**Issue by flipstone42** [miguelgrinberg/python-socketio#664]
Hi,

I need to use a feature that's in master (client auth) but not yet in a published release. Please could you publish a new version to PyPI, or if this is not immediately possible, give me a rough ETA of when you expect this to happen? Thanks!

**Comment by miguelgrinberg** [comment]
Why don't you install the master branch direct from git? I don't currently have an ETA for the next release, there are several open bugs & enhancements.

**Comment by flipstone42** [comment]
I wouldn't be happy doing that in production code, but that should be enough to unblock me for the meantime. Thanks for the suggestion 👍
