### ISSUE TITLE
Unexpected status code 403 using python-socketio 4.6.1 on connection

### ISSUE THREAD

**Issue by DanielVip3** [miguelgrinberg/python-socketio#665]
I am working with socket.io v4 - I know, we should update but we can't do it soon.
I don't know what happened, but until recently everything was working; but lately, all our clients (which use python-socketio 4.6.1) stopped working and thrown this error on connection:

```
Traceback (most recent call last):
  File "C:\Users\Censored\Projects\test.py", line 22, in <module>
    sio.connect('https://api.animeworld.tv/')
  File "C:\Python39\lib\site-packages\socketio\client.py", line 286, in connect
    six.raise_from(exceptions.ConnectionError(exc.args[0]), None)
  File "<string>", line 3, in raise_from
socketio.exceptions.ConnectionError: Unexpected status code 403 in server response
```

even though everything works perfectly using Node.js's socket.io-client (version 4.0.1). The same error appears using python-socketio 3.0.0 and 4.0.1.

What could the problem be? It doesn't seem to refer to a mismatched version of server and client versions.

Thanks.

**Comment by miguelgrinberg** [comment]
Your server is returning 403. Have you asked the people in charge of the server about it?

**Comment by DanielVip3** [comment]
I am in charge of the server too; I know about the forbidden status, but as you can read in the post, other clients based in Node.js work perfectly

> everything works perfectly using Node.js's socket.io-client (version 4.0.1)

The server uses NestJS's socket.io platform and the request handling is practically equal for all requests coming from all clients.
So I asked if it could be a problem related to the client's connection request; is there something which, being different from JS' socket.io-client, can cause a forbidden status code?

**Comment by miguelgrinberg** [comment]
@DanielVip3 I'm not sure how I can help with this. You should determine why the server is returning 4xx errors first. Only once you have that information we can discuss if the client has a problem.

**Comment by DanielVip3** [comment]
Probably it's really a server error, I'm inspecting further. I'll close the issue until further notice about a client problem.
