### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by onnokort** [miguelgrinberg/python-socketio#668]
Hi Miguel,

about 36h ago, I have sent you an email describing a minor-to-medium security issue with python-socketio (and python-engineio), I would like to have confirmation that you have received it. I hope it did not end up in your spam folder.

Best,

Onno

**Comment by miguelgrinberg** [comment]
I don't have it. A search for the word "security" in my spam folder does not bring up anything either.

**Comment by onnokort** [comment]
Hmm, weird. I just (2..3 min ago) sent you another eMail. GPG encrypted. It likely didn't turn up under any keywords as that was GPG-encrypted as well.

**Comment by miguelgrinberg** [comment]
I did find your second email attempt in the spam folder last night, but haven't had time to look at it yet.

**Comment by onnokort** [comment]
Alright thanks, I just wanted to make sure it reached you.

**Comment by miguelgrinberg** [comment]
@onnokort FYI a response should be in your inbox.

**Comment by onnokort** [comment]
Got it, thanks. You should have meanwhile gotten one more mail from me and one carbon copy. (In case it got lost again, but I will assume from now on that your spam filter knows about me.)

**Comment by miguelgrinberg** [comment]
@onnokort Yes, I did get them now. Thanks.
