### ISSUE TITLE
Packet.encode() omits trailing comma for namespaces

### ISSUE THREAD

**Issue by oback** [miguelgrinberg/python-socketio#671]
Hi,

In Packet.encode() `needs_comma` is ignored if `self.id` and `data` are both None. If a namespace is used and there is no data, the encoded packet might look something like `1/namespace`, without a trailing comma.

However, the [socket.io-protocol readme](https://github.com/socketio/socket.io-protocol) defines the comma as part of the message:
```
<packet type>[<# of binary attachments>-][<namespace>,][<acknowledgment id>][JSON-stringified payload without binary]
```
This is further backed up by the examples, i.e. in the `DISCONNECT` example: `1/admin,`. The same behaviour can be seen in socket.io.js encodeAsString(), where the comma is always appended (if the namespace is not empty and not `/`).

It seems like a small change that would simplify packet.py, but I don't know whether other parts of the code depend on the current behaviour.

**Comment by miguelgrinberg** [comment]
Oh wow, yeah, I missed that little detail. You are correct, the implement is simpler! Thanks.
