### ISSUE TITLE
Production deployment with django with multiple socketio servers

### ISSUE THREAD

**Issue by exxplorer** [miguelgrinberg/python-socketio#678]
Hi,

Thanks for such great work and maintenance Miguel :)

1. Using your django example, I can run `python manage.py runserver` with eventlet + nginx. I guess this also work for production, given the code in `examples/server/wsgi/django_example/socketio_app/management/commands/runserver.py` ? Or should I run something else ?

2. Looking into scale up, I tried uwsgi + nginx. Currently hitting this kind of error:
```
NHlZk1SSeDuVH0YSAAAI: Unexpected error "'utf-8' codec can't decode byte 0xb4 in position 0: invalid start byte", closing connection
```
making the socketio **binary** data doesn't seem to work (audio, etc.). So uwsgi seems out for me. My (shortened) config is like this:
```
[uwsgi]
module = myapp.wsgi:application
env = DJANGO_SETTINGS_MODULE=myapp.settings
env = LANG=en_US.UTF-8
master = True
strict = True
single-interpreter = True
http-socket = 127.0.0.1:3000
processes = 4
#harakiri = 20
http-websockets = True
vacuum = True
min-worker-lifetime = 1800
max-worker-lifetime = 21600
max-worker-lifetime-delta = 300
listen = 4096

```
Not quite sure this is uwsgi issue or python-socketio issue. Please enlighten me.

3. Now I'm looking into using multiple single-worker gunicorn instances - each listening on a port - and sticky load-balanced by nginx. The thing is, I'm not quite confident of running multiple instances of django atm - mostly because I don't know how to handle the states of connected clients between django instances besides syncing into database (quite costly). And probably other issues I need to investigate too. Other people have done this so I guess it is possible.

4. I just found out this : https://socket.io/docs/v4/using-multiple-nodes/#Sticky-load-balancing. Upstream says WS works fine without sticky session, only HTTP requires it. It seems not correct for python-socketio ? Will try this after writing this test but just want to bring this up.

5. Rewrite my django app with ASGI - in the hope of the async servers might have better deployment - is a bit out of the question for me atm even though I like it better.

Do you have any suggestions ? I think I have to go production with single-worker eventlet (as in 1.) for now. And maybe consider option 3. later.

Many thanks.

**Comment by miguelgrinberg** [comment]
1. The Django example in this repository uses a custom `runserver` command that would work for production, as long as you use eventlet or gevent. Gunicorn or uWSGI would also work (see documentation for examples).
2. You don't seem to be using gevent in your uWSGI configuration. That is required, see the docs for a working example.
3. Running multiple instances of Django is the most common deployment method (when not using Socket.IO). The database is how the instances sync. Why are you concerned about it?
4. That discussion in the reference Socket.IO implementation does apply to Python as well. If you disable long-polling, then you don't need sticky sessions.
5. ASGI will give you more or less the same scalability as eventlet. Both are async frameworks, they are fairly similar.

Using a single eventlet worker will give you very good scalability. I would start with that, keeping the door open to adding more if/when needed.

**Comment by exxplorer** [comment]
1. Cool. Thanks for the confirmation.

2. Wow I missed `gevent = ` in uwsgi.ini file.
With that added in, I'm still seeing the utf-8 decode issue along with another greenlet error - which both happen only a few times, then it got fine. This is during the time where client connects to server and send a small binary data. Tried with 5-6 recent version of gevent and latest uwsgi : https://paste.ubuntu.com/p/ZWFxWmNGsV/. This is the error log : https://paste.ubuntu.com/p/cz4DH3d6FB/. Paste here for web crawler.

```
[pid: 158789|app: 0|req: 4/6] 127.0.0.1 () {36 vars in 584 bytes} [Tue May  4 17:08:21 2021] GET /socket.io/?transport=websocket&EIO=4&t=1620122901.0182283 => generated 175 bytes in 30794 msecs (HTTP/1.1 101) 4 headers in 187 bytes (2 switches on core 999)
ayqazgpNDpYUpD4LAAAI: Sending packet OPEN data {'sid': 'ayqazgpNDpYUpD4LAAAI', 'upgrades': [], 'pingTimeout': 5000, 'pingInterval': 25000}
ayqazgpNDpYUpD4LAAAI: Received request to upgrade to websocket
ayqazgpNDpYUpD4LAAAI: Upgrade to websocket successful
ayqazgpNDpYUpD4LAAAI: Received packet MESSAGE data 0
emitting event "IDENTIFY" to zI7MCvqAt51kv1U_AAAJ [/]
ayqazgpNDpYUpD4LAAAI: Sending packet MESSAGE data 2["IDENTIFY"]
ayqazgpNDpYUpD4LAAAI: Sending packet MESSAGE data 0{"sid":"zI7MCvqAt51kv1U_AAAJ"}
ayqazgpNDpYUpD4LAAAI: Unexpected error "'utf-8' codec can't decode byte 0xb7 in position 0: invalid start byte", closing connection
[pid: 158789|app: 0|req: 5/7] 127.0.0.1 () {36 vars in 584 bytes} [Tue May  4 17:08:53 2021] GET /socket.io/?transport=websocket&EIO=4&t=1620122933.0794008 => generated 148 bytes in 568 msecs (HTTP/1.1 101) 4 headers in 187 bytes (2 switches on core 999)
Traceback (most recent call last):
VfQjVkv-vvYQwWSIAAAE: Sending packet OPEN data {'sid': 'VfQjVkv-vvYQwWSIAAAE', 'upgrades': [], 'pingTimeout': 5000, 'pingInterval': 25000}
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/venv/lib/python3.8/site-packages/engineio/async_drivers/gevent_uwsgi.py", line 55, in select_greenlet_runner
    select([fd], [], [])[0]
  File "/venv/lib/python3.8/site-packages/gevent/select.py", line 175, in select
    sel_results = _original_select(rlist, wlist, xlist, 0)
OSError: [Errno 9] Bad file descriptor
VfQjVkv-vvYQwWSIAAAE: Received request to upgrade to websocket
2021-05-04T10:08:54Z <Greenlet at 0x7f781b919e10: select_greenlet_runner(6, <gevent._gevent_cevent.Event object at 0x7f781b424)> failed with OSError

VfQjVkv-vvYQwWSIAAAE: Upgrade to websocket successful
VfQjVkv-vvYQwWSIAAAE: Received packet MESSAGE data 0
emitting event "IDENTIFY" to s5f5euKr0m6kt2AsAAAF [/]
VfQjVkv-vvYQwWSIAAAE: Sending packet MESSAGE data 2["IDENTIFY"]
VfQjVkv-vvYQwWSIAAAE: Sending packet MESSAGE data 0{"sid":"s5f5euKr0m6kt2AsAAAF"}
VfQjVkv-vvYQwWSIAAAE: Unexpected error "'utf-8' codec can't decode byte 0x87 in position 0: invalid start byte", closing connection
[pid: 158788|app: 0|req: 3/8] 127.0.0.1 () {36 vars in 582 bytes} [Tue May  4 17:08:54 2021] GET /socket.io/?transport=websocket&EIO=4&t=1620122934.573706 => generated 148 bytes in 548 msecs (HTTP/1.1 101) 4 headers in 187 bytes (2 switches on core 999)
Traceback (most recent call last):
HIzbEYm2nF2a4P3-AAAK: Sending packet OPEN data {'sid': 'HIzbEYm2nF2a4P3-AAAK', 'upgrades': [], 'pingTimeout': 5000, 'pingInterval': 25000}
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/venv/lib/python3.8/site-packages/engineio/async_drivers/gevent_uwsgi.py", line 55, in select_greenlet_runner
    select([fd], [], [])[0]
  File "/venv/lib/python3.8/site-packages/gevent/select.py", line 175, in select
    sel_results = _original_select(rlist, wlist, xlist, 0)
OSError: [Errno 9] Bad file descriptor
HIzbEYm2nF2a4P3-AAAK: Received request to upgrade to websocket
2021-05-04T10:08:56Z <Greenlet at 0x7f781a098040: select_greenlet_runner(7, <gevent._gevent_cevent.Event object at 0x7f781a093)> failed with OSError

HIzbEYm2nF2a4P3-AAAK: Upgrade to websocket successful
HIzbEYm2nF2a4P3-AAAK: Received packet MESSAGE data 0
emitting event "IDENTIFY" to PMFkWHtoHiUiZK41AAAL [/]
HIzbEYm2nF2a4P3-AAAK: Sending packet MESSAGE data 2["IDENTIFY"]
HIzbEYm2nF2a4P3-AAAK: Sending packet MESSAGE data 0{"sid":"PMFkWHtoHiUiZK41AAAL"}
HIzbEYm2nF2a4P3-AAAK: Received packet MESSAGE data <binary>
received event "SUCCESS" from PMFkWHtoHiUiZK41AAAL [/]
emitting event "SUCCESS_ACK" to PMFkWHtoHiUiZK41AAAL [/]
HIzbEYm2nF2a4P3-AAAK: Sending packet MESSAGE data 2["SUCCESS_ACK","OK"]
9BldcN-xea-ZF9mEAAAC: Sending packet PING data None
9BldcN-xea-ZF9mEAAAC: Received packet PONG data 
9BldcN-xea-ZF9mEAAAC: Sending packet PING data None
9BldcN-xea-ZF9mEAAAC: Received packet PONG data 
9BldcN-xea-ZF9mEAAAC: Sending packet PING data None
9BldcN-xea-ZF9mEAAAC: Received packet PONG data 
9BldcN-xea-ZF9mEAAAC: Sending packet PING data None
9BldcN-xea-ZF9mEAAAC: Received packet PONG data 
9BldcN-xea-ZF9mEAAAC: Sending packet PING data None
9BldcN-xea-ZF9mEAAAC: Received packet PONG data 
9BldcN-xea-ZF9mEAAAC: Sending packet PING data None
9BldcN-xea-ZF9mEAAAC: Received packet PONG data 

```

Looks pretty much like this : https://github.com/miguelgrinberg/Flask-SocketIO/issues/1076. But both my client + server are on the same host.
And maybe this too : https://github.com/miguelgrinberg/Flask-SocketIO/issues/909#issuecomment-474741107.


3. Hah I was not aware of that. Thanks for the hint. Might be a good way out for me. Do you have a walkthrough or example somewhere I could reference ? Search results all pointed to multiple instances of `different` django app. Many thanks.

4. Cool ! If I use pure WS, then I can go with single multiple-worker gunicorn instance, like `-w 4` ? Will try.

5. Great ! No need to rewrite.

I think I'm pretty close to give up on uwsgi + gevent (eventhough I like them) at 3. and going back to testing sing/multi-worker gunicorn with eventlet.

**Comment by exxplorer** [comment]
Thanks a lot. Hopefully this might help someone.

**Comment by exxplorer** [comment]
I have got some new findings:

2. I have overcome the utf-8 issue by encode the binary data in base64 string. Decoding the base64 string at the socketio Server event function, I have got the original binary data.

Another issue is : if I use more than 1 uwsgi worker like `processes = 2`, it starts becoming flaky - sometimes the socketio Server receives the base64 data, sometimes doesn't. So it feels very much that multi workers don't work.

**Comment by exxplorer** [comment]
Hi @miguelgrinberg,

Speaking of 2. :

Do you have an example of how to make multiple eventlet workers to exchange events/data with each other ? Possibly using redis as a queue manager ?

Reading this : https://github.com/miguelgrinberg/Flask-SocketIO/issues/47#issuecomment-258754425, I understand that it is not possible ?

What I try to achieve is : 

client1 connects : `{ "id": "client1", data: "data" }`  ---> nginx balances ---> eventlet-worker1:3000
client2 connects : `{ "id": "client2", data: "data" }`  ---> nginx balances ---> eventlet-worker2:4000
---- later in time ---
client1 wants to client2 `{ "id": "client1", "data": data, "target": "client2"}` ---> nginx ---> eventlet-worker1:3000 ---> redis queue ---> eventlet-worker2:4000 (because eventlet-worker2 is currently connected to client2)

Do you think this is possible with python-socketio ? I have read the docs but still don't quite understand how redis manager works with python-socketio. Thanks.

**Comment by miguelgrinberg** [comment]
@exxplorer do any of the example applications in this repository give you the utf-8 error?

And for the 2 worker situation, can you be more specific about the flakyness? Logs would help me understand what you mean by that. See the troubleshooting section of the docs if you don't know how to get logs.

If you want your workers to share data that is something you have to implement on your own. The message queue that you connetct to the workers allow emits and broadcasts to work regardless of which worker is connected to each client, but if you need anything beyond that it is up to you to implement an IPC solution.

**Comment by exxplorer** [comment]
I mean it looks like uwsgi's business for not being able to deal with binary data - I just wanted to update that in case somebody finds this thread. python-socketio works just fine.

I already enabled `logger=debug, engineio_logger=debug` on both the client and server sides from the beginning. The flakyness is like this. My js client sends events to uwsgi+gevent then it forwards to other clients, some times there are socketio logs like 
```
emitting event "eventX" to sid123 [/]
```
which is normal, right ? But some times there is no log like this at all. And this only happens for >1 workers.



> The message queue that you connetct to the workers allow emits and broadcasts to work regardless of which worker is connected to each client

This is still good for my case I think. The broadcast message may look like this:
` {"from": "client1", "to": "client2", "data": data}`. Any server who are not connected to client2 could just discard this message. Agreed that is some additional load generated.
Alright I just found this code :
https://github.com/miguelgrinberg/python-socketio/blob/master/socketio/pubsub_manager.py
https://github.com/miguelgrinberg/python-socketio/blob/master/socketio/redis_manager.py

Trying to do this.

**Comment by miguelgrinberg** [comment]
> I mean it looks like uwsgi's business for not being able to deal with binary data

The best way for me to test this possible problem is to have code that I can run here that reproduces this. If you have a moment, take one of the examples in this repository (something under examples/server, maybe one of the fiddle examples) and make the necessary changes to reproduce this message. Then give me the details of what you changed and how you are running the code.

> But some times there is no log like this at all. And this only happens for >1 workers.

Unfortunately an informal description of the problem does not help me. By far the most common problem when the emit log is missing is that the application isn't calling emit due to a bug. What I need to see is the section of code that emits, and the corresponding logs while that code executed. You may want to add some prints on the application side if you think that will help me understand the logs better.

> his is still good for my case I think. The broadcast message may look like this:
{"from": "client1", "to": "client2", "data": data}.

I don't understand this. What is this for?

> Trying to do this.

Trying to do what? I suspect you do not fully understand how this is supposed to work with multiple workers. There is nothing for you to do, other than configure the message queue.

**Comment by exxplorer** [comment]
OK. I finally understand how python-socketio server**s** + redis queue work. Thanks.

**Comment by exxplorer** [comment]
> Trying to do what? I suspect you do not fully understand how this is supposed to work with multiple workers. There is nothing for you to do, other than configure the message queue.

Yes I didn't quite understand how the redis queue work with multi servers.
I just make a simple example and using class PubSubManager:emit() - then I realized how it works. Here is my sample code:

```
#!/usr/bin/env python3

import sys
import socketio
import eventlet
import eventlet.wsgi

if sys.argv[1] == "server":
    eventlet.monkey_patch()

    port = int(sys.argv[2])

    mgr = socketio.RedisManager("redis://127.0.0.1:6379/0")
    server = socketio.Server(async_mode="eventlet",
                             client_manager=mgr,
                             logger=True, engineio_logger=True)
    app = socketio.WSGIApp(server)

    common_room = "common_room"

    @server.event
    def client_connected(sid):
        server.enter_room(sid, common_room)
        print(f"Server at {port} got client {sid} connected")
        mgr.emit(event="_broadcasting", room=common_room,
                 # skip_sid=sid,
                 data={
                     "from": sid,
                     "server": f":{port}",
                 }
                 )

    eventlet.wsgi.server(eventlet.listen(("", port)), app)

if sys.argv[1] == "client":
    port = int(sys.argv[2])
    client = socketio.Client(reconnection=True,
                             logger=True, engineio_logger=True,
                             )

    @client.event
    def _broadcasting(data):
        print(f"Client connected to server at {port} got message {data}")

    while not client.connected:
        client.connect(f"http://127.0.0.1:{port}",
                       transports=["websocket"], namespaces=["/"]
                       )
        client.sleep(0.5)
        client.emit(event="client_connected")

```
The log of the first server : `python app.py server 4000`

```
VV7Xw3TADAU9FsGiAAAB is entering room common_room [/]
Server at 5000 got client VV7Xw3TADAU9FsGiAAAB connected
pubsub message: emit
1PDMWB7A8qwmeoZoAAAA: Sending packet MESSAGE data 2["_broadcasting",{"from":"VV7Xw3TADAU9FsGiAAAB","server":":5000"}]
pubsub message: emit
1PDMWB7A8qwmeoZoAAAA: Sending packet MESSAGE data 2["_broadcasting",{"from":"kI5CD1QYkipXd5JeAAAB","server":":4000"}]

```

The log of the first client : `python app.py client 4000`

```
Emitting event "client_connected" [/]
Sending packet MESSAGE data 2["client_connected"]
Received packet MESSAGE data 2["_broadcasting",{"from":"VV7Xw3TADAU9FsGiAAAB","server":":5000"}]
Received event "_broadcasting" [/]
Client connected to server at 5000 got message {'from': 'VV7Xw3TADAU9FsGiAAAB', 'server': ':5000'}
Received packet MESSAGE data 2["_broadcasting",{"from":"kI5CD1QYkipXd5JeAAAB","server":":4000"}]
Received event "_broadcasting" [/]
Client connected to server at 5000 got message {'from': 'kI5CD1QYkipXd5JeAAAB', 'server': ':4000'}

```

**Comment by exxplorer** [comment]
So, when client1 and client2 connect to my servers at ports 4000,5000 respectively, their sid will be saved in database, not in per-server memory. Or add client1 to room1, client2 to room2.

When client wants to sends a message to client2, server1 will use `mgr.emit(room=room2)` to send the message to redis, which will forward to server2, then it will forward to room2, aka. client2.

So it seems that's the flow to my understanding.

**Comment by miguelgrinberg** [comment]
@exxplorer you are overcomplicating things. Have you read the documentation?

There is nothing for you to do with the `mgr` object, just pass it when you create the server and that's it. When you need to emit, use `server.emit()`.

Your servers should not be addressed by their individual port, the client should not need to know this information. Normally you'll want a load balancer in front of your workers, and your clients connect to it instead of to the servers directly.

Read the documentation, there is a lot of information on deployment solutions.

**Comment by exxplorer** [comment]
> @exxplorer you are overcomplicating things. Have you read the documentation?
> 
> There is nothing for you to do with the `mgr` object, just pass it when you create the server and that's it. When you need to emit, use `server.emit()`.

Ah hah. `server.emit()` does the job. I have the docs a thousand times, might still miss or misundestand other things :D Sorry :D

> 
> Your servers should not be addressed by their individual port, the client should not need to know this information. Normally you'll want a load balancer in front of your workers, and your clients connect to it instead of to the servers directly.
> 
> To emit to a client, just add `to=sid` in the emit call. No need to add sids, ports or other things in your application-level messaging.
> 

Right, agreed. Will keep that in mind. I made above code just to get myself undestand how this redis queue work. So please ignore the port thinggy.

**Comment by exxplorer** [comment]
Only until I got my workers working fine with redis manager queue, I found this explanation :)
https://stackoverflow.com/questions/60909094/is-there-a-socketio-client-to-connect-to-the-supported-message-brokers-in-python

Everything makes sense for me now. Thanks a lot !
