### ISSUE TITLE
client authentication 

### ISSUE THREAD

**Issue by njavilas2015** [miguelgrinberg/python-socketio#679]
Hello, good afternoon, I am working with an environment where I need to authenticate with the server by sending a token, I cannot send the authentication with the python client

import socketio

sio = socketio.Client()

sio.connect("https://api.insertmendoza.com.ar", auth={'token': 1234})

print(sio.connected)

Unexpected keyword argument 'auth' in method call

**Comment by miguelgrinberg** [comment]
What version of python-socketio do you have? This is a fairly recent addition.

**Comment by njavilas2015** [comment]
sorry I forgot to attach it

Requirement already satisfied: python-socketio in /home/insert/.local/lib/python3.8/site-packages (5.1.0)
Requirement already satisfied: bidict>=0.21.0 in /home/insert/.local/lib/python3.8/site-packages (from python-socketio) (0.21.2)
Requirement already satisfied: python-engineio>=4 in /home/insert/.local/lib/python3.8/site-packages (from python-socketio) (4.0.1)

**Comment by njavilas2015** [comment]
# auth
            if 'Authorization' not in headers and self.http.auth is not None:
                if not isinstance(self.http.auth, tuple):  # pragma: no cover
                    raise ValueError('Only basic authentication is supported')
                basic_auth = '{}:{}'.format(
                    self.http.auth[0], self.http.auth[1]).encode('utf-8')
                basic_auth = b64encode(basic_auth).decode('utf-8')
                headers['Authorization'] = 'Basic ' + basic_auth
I'm checking the engineio code and I see that I can send you through header, is this correct?

**Comment by njavilas2015** [comment]
Thanks I have updated to version 5.2.1 it working!!
