### ISSUE TITLE
Are there plans to implement catch all listeners?

### ISSUE THREAD

**Issue by foonwong** [miguelgrinberg/python-socketio#681]
Hi, thanks for the great package!
Are there plans to implement catch all listeners like the JS socketio?
https://socket.io/docs/v3/listening-to-events/#Catch-all-listeners

**Comment by miguelgrinberg** [comment]
This is currently possible if you use a class based namespace. All events are sent to the namespace's `trigger_event()` method, which dispatches it to the corresponding `on_<event_name>()` method. If you override `trigger_event()` you can have access to all events, regardless of having an event defined or not.

I'm open to add a catch-all that is function based as well, but it is not high in my priority list right now.

**Comment by foonwong** [comment]
Thank you. I'll check out the class namespace override.
