### ISSUE TITLE
Connection fails with "400: Unsupported upgrade request", possibly an Nginx misconfiguration

### ISSUE THREAD

**Issue by max-l** [miguelgrinberg/python-socketio#686]
I am using the socket.io javascript client with version:  

`"socket.io-client": "^3.1.2",`

And on the python side  : 

```
python-engineio==4.1.0
python-socketio==5.0.4
uvicorn==0.13.4
```

The connection attemps are failing with the return 

`400:  "Unsupported upgrade request."`

The request sent from the browser are: 

curl 'http://localhost:9004/socket.io/?EIO=4&transport=polling&t=NbcVN2X' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"' \
  -H 'Accept: */*' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: http://localhost:9004/' \
  -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8,fr;q=0.7' \
  --compressed

I have an Nginx instance in the middle, and I suspect it is causing the problem, because if I send the same CURL request directly to the python server (instead of through Nginx), I get the response : 

`0{"sid":"3PAgAppFeoBEiwAsAAAG","upgrades":["websocket"],"pingTimeout":20000,"pingInterval":25000}`

On the JavaScript (socket.io) client side, the connection is made with: 

`const socket = io(location.protocol + '//' + document.domain + ':' + location.port + "/drypipe")`

Here are my Nginx rules: 

```
    location /socket.io {

      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $host;
      proxy_pass   $scheme://127.0.0.1:5000;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }

    location /sockjs-node {

      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $host;
      proxy_pass   $scheme://127.0.0.1:5000;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }

    location /drypipe {

      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $host;
      proxy_pass   $scheme://127.0.0.1:5000;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }

**Comment by miguelgrinberg** [comment]
See the troubleshooting section of the documentation to learn how to enable logs. Once you have logs enabled, capture a session that includes a failed connection and share it here.

**Comment by max-l** [comment]
I turned on logging as specified in the troubleshooting section:

```
sio = socketio.AsyncServer(async_mode='asgi', logger=True, engineio_logger=True)

app = socketio.ASGIApp(
    sio,
    other_asgi_app=App(),
    static_files={
        "/main.js": map_static_file("dist/main.js"),
        "/main.js.map": map_static_file("dist/main.js.map")
    }
)
```

And I get no logs when I hit Nginx, but if I hit the python socketio sever, I get the following logs: 

yi9a528tMpvmlsw7AAAA: Sending packet OPEN data {'sid': 'yi9a528tMpvmlsw7AAAA', 'upgrades': ['websocket'], 'pingTimeout': 20000, 'pingInterval': 25000}
yi9a528tMpvmlsw7AAAA: Sending packet PING data None


Which seems to confirm that Nginx config is at fault...

```
curl 'http://192.168.9.75/socket.io/?EIO=4&transport=polling&t=Nbczx7w' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' \
  -H 'Accept: */*' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36' \
  -H 'Referer: http://192.168.9.75/' \
  -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8,fr;q=0.7' \
  --compressed \
  --insecure


```

**Comment by miguelgrinberg** [comment]
Your nginx file is forwarding requests to port 5000. Your curl example uses 9004. If that is not the problem, then I suggest you debug this from the nginx side, I really don't know how to help since the Python side isn't being hit with requests.

**Comment by max-l** [comment]
Port 9004 is the port of webpack's reverse proxy that I removed early on in the troubleshooting, id didn't change anything unfortunately.

I now have only nginx in the middle.


This request: 

```
curl 'http://192.168.9.75/socket.io/?EIO=4&transport=polling&t=Nbd2iwR' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' \
  -H 'Accept: */*' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36' \
  -H 'Referer: http://192.168.9.75/' \
  -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8,fr;q=0.7' \
  --compressed \
  --insecure

```
Gives this in the access log: 

```
tail -f /var/log/nginx/access.log

192.168.9.1 - - [13/May/2021:18:44:18 +0000] "GET /socket.io/?EIO=4&transport=polling&t=Nbd2pSJ HTTP/1.1" 400 39 "http://192.168.9.75/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36"
```
And nothing in the error log:  /var/log/nginx/error.log

**Comment by miguelgrinberg** [comment]
As I said before, nginx is not my project, I don't really know what to suggest, and I don't even know what you have in your configuration. My documentation includes a working configuration that I personally tested. Maybe start from that? I don't have anything else to suggest, sorry.

**Comment by max-l** [comment]
Sorry for bringing issues not originating from your project ! 

I have turned on debug log of uvicorn, and it appenears that it (uvicorn) could be interacting with Nginx in a weird way, here's what univorn logging show with log_level=debug: 

```
INFO:     Uvicorn running on http://127.0.0.1:5000 (Press CTRL+C to quit)
WARNING:  Unsupported upgrade request.
WARNING:  Unsupported upgrade request.
WARNING:  Unsupported upgrade request.
...
```

So Uvicorn **IS** getting the request from Nginx, and sending  **HTTP/1.1 400 Bad Request**  to Nginx

The strange thing, is that removing Nginx from the middle fixes the problem....

**Comment by max-l** [comment]
The problem is with uvicorn AND Nginx together, 

The request 
`
b'GET /socket.io/?EIO=4&transport=polling&t=NbdM_lp HTTP/1.1\r\nConnection: Upgrade\r\nHost: 192.168.9.75\r\nPragma: no-cache\r\nCache-Control: no-cache\r\nAccept: */*\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36\r\nReferer: http://192.168.9.75/\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-GB,en-US;q=0.9,en;q=0.8,fr;q=0.7\r\n\r\n'

`

Ends up hitting this "Unsupported upgrade request" condition : 

```
    def handle_upgrade(self, event):
        upgrade_value = None
        for name, value in self.headers:
            if name == b"upgrade":
                upgrade_value = value.lower()

        if upgrade_value != b"websocket" or self.ws_protocol_class is None:
            msg = "Unsupported upgrade request."
            self.logger.warning(msg)
            reason = STATUS_PHRASES[400]
            headers = [
                (b"content-type", b"text/plain; charset=utf-8"),
                (b"connection", b"close"),
            ]
```
It appears python-socketio is not involved, sorry ! 

I'll continue my investigation and perhaps solicitate the uvicorn guys ! ;-)

**Comment by max-l** [comment]
Ok, the problem was with the Nginx config after all... I was able to fix it with the following more sophisticated config : 


```
  server {
    listen 80;
    client_max_body_size 4G;

    server_name _;

    location / {
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_redirect off;
      proxy_buffering off;
      proxy_pass http://127.0.0.1:5000;
    }
  }

  map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
  }


```

**Comment by miguelgrinberg** [comment]
Who is making this last request? It is not the same as the curl examples you shown previously, not even close. The last request is bad, so Uvicorn is correct in rejecting it. Appears to be a WebSocket request upgrade, but it is incomplete.
