### ISSUE TITLE
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 16 (char 15)

### ISSUE THREAD

**Issue by sangramdogra** [miguelgrinberg/python-socketio#693]
Hi All,

Running app.py using cmd (python app.py) gives json decoder error and is not sending video from server. Below is the screenshot for the same:
![image](https://user-images.githubusercontent.com/69067551/119770044-433a3180-bed9-11eb-8bac-0d420af4d8a3.png)
I am using client side socket io version as per the compatibility 3.0.5 and flask socketio version: 5.0.3 rest is same code as repo.

**Comment by miguelgrinberg** [comment]
See the troubleshooting section of the documentation to learn how to enable details logs. Then add your logs to this issue. Thanks.

**Comment by sangramdogra** [comment]
Thanks this is done. Thanks for the help :) Miguel
