### ISSUE TITLE
Question: How to run the socketio client?

### ISSUE THREAD

**Issue by TechStudent11** [miguelgrinberg/python-socketio#694]
Hello there! I built a chat app using Flask-SocketIO and I am trying to build a bot for it. I decided to use this module for the client module. I needed it for real-time sending and receiving. Now I am at the part where I need to run it. I couldn't find any information on the docs.

My Bot Code:
```python
import socketio

class Bot(object):
    _CHAT_URL = "<my flask-socketio server>"
    room_code = None

    def __init__(self, bot_username):
        self.bot_username = bot_username

        self.sio = socketio.Client()
        self.sio.connect(self._CHAT_URL)

        self.sio.on('message', self._on_message)

    def _on_message(self, **kwargs):
        if not self.room_code:
            raise Exception("Room Code Variable (room_code) not found.")
        
        self.on_message(**kwargs)

    def on_message(self, json):
        pass

    def send_message(self, message_json):
        self.sio.emit('message', message_json)

    def run(self):
        pass
```

So my question, how do I run the client from the run method?

**Comment by miguelgrinberg** [comment]
The documentation has a complete example here: https://python-socketio.readthedocs.io/en/latest/intro.html#client-examples. There is also several examples that are ready to run in this repository. Have you seen these?

**Comment by TechStudent11** [comment]
@miguelgrinberg no not yet. Thanks!

**Comment by TechStudent11** [comment]
So I just need to use:
```python
sio.wait()
```
to run?

**Comment by miguelgrinberg** [comment]
The client runs asynchronously. The wait method just holds the main thread until the client disconnects.

**Comment by TechStudent11** [comment]
@miguelgrinberg oh.. okay

**Comment by TechStudent11** [comment]
@miguelgrinberg Alright so I got it to run, the problem is, is that it will not run the function that is supposed to run when a message is received. But I'll create a separate issue for that. Thanks for the help!
