### ISSUE TITLE
SocketIO Client function not running event is called. 

### ISSUE THREAD

**Issue by TechStudent11** [miguelgrinberg/python-socketio#695]
I created a previous issue, so you probably know what is happening. I have created a chat app using Flask SocketIO and am now trying to create a bot API for it. For some reason, the function that should be called when a message is being received isn't running. I can obviously send a message from the chat app UI and from the Bot. But it won't even detect that.

My Bot Code:
```python
import socketio

class Bot(object):
    _CHAT_URL = "<socketio server>"
    room_code = None

    def __init__(self, bot_username="Bot"):
        self.bot_username = bot_username

        self.sio = socketio.Client(logger=True, engineio_logger=True)

        @self.sio.event
        def message(json):
            self._on_message(json)

        self.sio.connect(self._CHAT_URL)

        self.on_init()

    def _on_message(self, **kwargs):
        if not self.room_code:
            raise Exception("Room Code Variable (room_code) not found.")
        
        self.on_message(**kwargs)

    def on_message(self, json):
        pass

    def send_message(self, message_json):
        self.sio.emit('message', {
            'username': self.bot_username,
            'room_code': self.room_code,
            **message_json
        })

    def run(self):
        self.sio.wait()

    def on_init(self):
        pass
```

My Bot Client Code:
```python
# 'pycord' is the name of the chat app and module where the bot is. You cannot install this. This is on my local machine.
import pycord

class MyBot(pycord.Bot):
    room_code = "1"

    def on_init(self):
       self.send_message({
           'message': "Hey!"
       })

    def on_message(self, json):
        print(json)

MyBot().run()
```

**Comment by miguelgrinberg** [comment]
Have you used the examples I pointed you at in the other issue? Those are intended to help developers learn how to use this package. The documentation also includes a troubleshooting section. Sorry, but I can't really debug this code for you, it's not even something I can run.

**Comment by TechStudent11** [comment]
@miguelgrinberg yes I have looked at it. I have used the troubleshooting section as you said. Nothing unusual pops up. It's finee. I'll try to fix it myself. Thanks for your time!
