### ISSUE TITLE
Received packet MESSAGE data 4"No cookie in header" - Connection to namespace / was rejected - 

### ISSUE THREAD

**Issue by sebek88** [miguelgrinberg/python-socketio#696]
Hello,

I am writing a client based on python-socketio which connects to a [frontail](https://github.com/mthenw/frontail) server. I want an action to be triggered (as defined in def line) every time a log line appears in the frontail server. 
I have managed to get everything working IF the frontail server runs without authentication (i.e. frontail random_log_file.log). 
My problem is that when I add Basic Authentication options in the frontail server and try to pass authorization headers in sio.connect, no action is triggered and basically no connection seems to happen (connect event does not print anything). 
The frontail server is spawned with the following command: 

```
frontail -U Username -P Password random_log_file.log
```

The debugging info printed when running the client is as follows:

 ```
user@debian:~/$ python3 socio.py 
INFO:__main__:Created socketio client
INFO:engineio.client:Attempting polling connection to http://127.0.0.1:9001/socket.io/?transport=polling&EIO=3
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:9001
DEBUG:urllib3.connectionpool:http://127.0.0.1:9001 "GET /socket.io/?transport=polling&EIO=3&t=1622450468.049636 HTTP/1.1" 200 99
INFO:engineio.client:Polling connection accepted with {'sid': 'tom9miKjUL2LUv3EAAAL', 'upgrades': ['websocket'], 'pingInterval': 25000, 'pingTimeout': 5000}
INFO:socketio.client:Engine.IO connection established
INFO:engineio.client:Attempting WebSocket upgrade to ws://127.0.0.1:9001/socket.io/?transport=websocket&EIO=3
INFO:engineio.client:WebSocket upgrade was successful
INFO:engineio.client:Sending packet PING data None
INFO:engineio.client:Received packet MESSAGE data 4"No cookie in header"
INFO:socketio.client:Connection to namespace / was rejected
INFO:engineio.client:Received packet PONG data None
```

The source code is fairly simple, based on the [readthedocs](https://python-socketio.readthedocs.io/en/latest/) pages and is the following:

```python
import logging
import socketio
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)

sio = socketio.Client(logger=True, engineio_logger=True)
logger.info('Created socketio client')

@sio.event
def connect():
    print("This is a message")
    logger.info('connected to the server')

@sio.event
def disconnect():
    logger.info('disconnected from the server')

@sio.event(namespace='/3035bb5b9bf7535252f5b3c08ef30083')
def line(data):
    do_something_else_here
    print("Nothing gets printed here")
    logger.info('Nothing happens here')

if __name__ == '__main__':

    sio.connect('http://127.0.0.1:9001/', headers={'Authorization': 'Basic VXNlcm5hbWU6UGFzc3dvcmQ='}, namespaces=['/3035bb5b9bf7535252f5b3c08ef30083'])
    print('my sid is', sio.sid)

    sio.wait()
    #sio.sleep(5)
    #sio.disconnect()
```
Namespace shown in the source code is an MD5 hash, based on the log file (or files) arguments that are given to the frontail server. It can be viewed from the server's source code in the browser.

Everything works fine if Authentication is removed from the server and headers are removed from the client. Any idea why adding Authorization headers in the client, breaks the functionality.
Moreover adding the "auth" parameter as mentioned [here](https://python-socketio.readthedocs.io/en/latest/api.html) doesn't seem to work either.
Versions of both server and client have been checked based on the version compatibility chart and everything seems ok.
Any help would be appreciated.

**Comment by miguelgrinberg** [comment]
The "No cookie on header" error comes from the server: https://github.com/mthenw/frontail/blob/44ff51a618022138574257a50adeecb6a71e3a61/index.js#L101. So my guess is that you are not authenticating in the way this server expects. You do not seem to be sending any cookies.

**Comment by sebek88** [comment]
Sorry did not have time to post an update here earlier. You were absolutely right about the error. 
It was solved by adding a HEAD request (to get the required cookie), before calling sio.connect with that cookie value.
I am closing this issue.
