### ISSUE TITLE
How to remove spesific listener?

### ISSUE THREAD

**Issue by rayhanmf30** [miguelgrinberg/python-socketio#709]
I've tried to remove spesific listener, does anyone have a solution?

```python
@sio.on('event-name')
def eventName(data):
    if(data == True):
        @sio.on('sub-event-name')
        def subEventName(msg):
            print(msg)
    else:
        # TODO: Remove listener sub-event-name
```

**Comment by miguelgrinberg** [comment]
@rayhanmf30 this package is not designed with the idea of adding/removing event handlers dynamically. The handlers are supposed to be set before starting the server, and they remain fixed.

**Comment by rayhanmf30** [comment]
can i replace the listener function?

**Comment by rayhanmf30** [comment]
@sio.on('event-name')
def eventName(data):
    if(data == True):
        @sio.on('sub-event-name')
        def subEventName(msg):
            print(msg)
    else:
        @sio.on('sub-event-name')
        def subEventName(msg):
            pass
            
This is work from me
Thank you for responding @miguelgrinberg

**Comment by miguelgrinberg** [comment]
@rayhanmf30 your solution breaks if you use multiple worker processes, you will be forced to always use a single server.
