### ISSUE TITLE
Raise an Exception when we reach max client reconnection_attempts

### ISSUE THREAD

**Issue by tomharvey** [miguelgrinberg/python-socketio#757]
**Is your feature request related to a problem? Please describe.**
After the max reconnection attempts I get a log output, but nothing else actionable.

**Describe the solution you'd like**
raise an Exception which I can catch and close the rest of the loops in my program (ASyncClient)

or

make the client's `attempt_count` attribute readable. But exception is preferable - maybe that exception is optionally raisable.

**Describe alternatives you've considered**
monkey patching the whole _handle_reconnect is a lot.
raising an error in the connect_error handler - but that disallows any reconnection attempts.

**Additional context**
This is while using the asyncclient

**Comment by miguelgrinberg** [comment]
Where would the exception be raised though? This is all happening in the background, not as a result of your application code calling a specific function. I'll look into this, I don't deny that it can be handled in a better way, but I'm not sure raising an exception is a good option for this.

**Comment by tomharvey** [comment]
Thanks for the quick response. Is there a common approach to handling this? Once max retries is exhausted I’d like to close my app.

**Comment by miguelgrinberg** [comment]
What are you doing in your main thread? The `sio.wait()` should return when the retries are exhausted. I was actually thinking that if I'm going to raise an exception it's going to be on the call to `wait()`.

**Comment by tomharvey** [comment]
That suggestion works perfectly thanks
