### ISSUE TITLE
exiting thread

### ISSUE THREAD

**Issue by blaisezzz** [miguelgrinberg/python-socketio#76]
Hi,

I would like to understand how to gracefully exit the background thread you use in your example.

Thanks!

**Comment by miguelgrinberg** [comment]
Just let the function end, either by reaching the bottom, or with the `return` keyword.

**Comment by blaisezzz** [comment]
I want to be able to terminate the thread from outside of the function

**Comment by miguelgrinberg** [comment]
The thread needs to voluntarily exit. From the outside you can send a signal to tell the thread to exit, and that would be a condition in the loop. For example, you can do it with an Event object:

    exit_event = Event()

    def thread():
        while not exit_event.is_set():
            # do some work here

So then when you want the thread to end, just call `exit_event.set()` from any other thread, and then wait for the thread to end on its own, maybe with a `thread.join()` call.

**Comment by blaisezzz** [comment]
I was creating a thread manager to manage starting() and exiting() of threads on needed basis. It was helpful to see how it is done in python. Thanks friend.
