### ISSUE TITLE
Live video streaming

### ISSUE THREAD

**Issue by blaisezzz** [miguelgrinberg/python-socketio#77]
Hi,

Is it possible to try to use python-socketio for live video streaming ?

**Comment by miguelgrinberg** [comment]
Only if you write the code that emits the video on the server, and the code that plays the video on the client. To my knowledge there is no protocol to send video over Socket.IO.

**Comment by blaisezzz** [comment]
I am still learning so it is nice to know what's possible and what's not. What is the maximum size of data that can be emit out per transfer ?

**Comment by miguelgrinberg** [comment]
I don't think there is a maximum size per packet. Or better said, the maximum is so large that for practical purposes it is the same to consider it infinite.

**Comment by blaisezzz** [comment]
What's more expensive. To emit out at the frequency of 2 seconds of 10kb data, or emit out 200kb every 10 seconds ? Can I assume it is cheaper to emit 200kb every 10 seconds ?

**Comment by miguelgrinberg** [comment]
It may be marginally cheaper to emit 10 seconds worth of data in terms of processing less packets, though I don't think sending every 2 seconds is going to be terrible either. You should consider that if you send every 10 seconds, then your video on the client is going to play at least 10 seconds late.

**Comment by blaisezzz** [comment]
I was finding calling socketio.emit() from server side twice one after another was not working smoothly. I am not sure if it was me or not.

**Comment by nvs-abhilash** [comment]
So, to be clear there is no possible way of using `socketio` to stream video content from client to server and from server to client in a real time scenario?

**Comment by miguelgrinberg** [comment]
Yes, there is, but you have to code it yourself. Socket.IO is a general purpose communication framework, it does not have any specific support for video, but nothing prevents you from sending video frames as binary packets.
