### ISSUE TITLE
background_task not awaited in sanic example

### ISSUE THREAD

**Issue by dfee** [miguelgrinberg/python-socketio#78]
I'm getting a fairly generic warning when running the example code's echo after loading [app.py](https://github.com/miguelgrinberg/python-socketio/blob/master/examples/sanic/app.py#L29)

```
/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py:362: RuntimeWarning: coroutine 'background_task' was never awaited                     │
  self._ready.clear()
```

**Comment by miguelgrinberg** [comment]
I assume this happens when you stop the server?

**Comment by dfee** [comment]
Actually it's happening on startup (ignore what I'd said in my previous comment):

```
python-socketio/examples/sanic on master via env [I] ➔ python app.py
2017-03-07 13:20:19,016: INFO: Goin' Fast @ http://127.0.0.1:8000
/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap_external.py:82: RuntimeWarning: coroutine 'background_task' was never awaited
  return _os.stat(path)
Task was destroyed but it is pending!
task: <Task pending coro=<background_task() running at app.py:13>>
2017-03-07 13:20:19,042: INFO: Starting worker [96559]
```

**Comment by miguelgrinberg** [comment]
This is now fixed.

**Comment by dfee** [comment]
@miguelgrinberg thanks for taking care of this. Did you fix this in a particular commit? I'd like to see what changed.

**Comment by miguelgrinberg** [comment]
You can see the change in this commit: https://github.com/miguelgrinberg/python-socketio/commit/2582f286f592c881fefeed0b639edecd41d81e4c

**Comment by dfee** [comment]
Thanks. I'm new to Sanic, so this exposed an API I wasn't previously familiar with. http://sanic.readthedocs.io/en/latest/sanic/blueprints.html#start-and-stop
