### ISSUE TITLE
Socket client sending default origin in header, how to overwrite or remove origin from header in request?

### ISSUE THREAD

**Issue by mnj93** [miguelgrinberg/python-socketio#784]
I am using socket client for python and it is sending origin in header same as ws URL, because of which connection is failing as we have a check on origin. Is there a way to overwrite/remove the origin header from the request?

**Comment by miguelgrinberg** [comment]
The Python client does not send an Origin header. Maybe the WebSocket package that you are using sends it, it's definitely not coming from this package.

**Comment by mnj93** [comment]
Thanks for the quick response, can you help me with how I can check the WebSocket package being used? I just downloaded this package using the pip3 command.

**Comment by miguelgrinberg** [comment]
There are a few websocket packages that are supported, none of which are installed by default. You must have installed it yourself. What do you have installed in your virtual environment?

**Comment by mnj93** [comment]
I used `pip3 install "python-socketio[client]"` this command to install the package, installed nothing else manually. Is there any way to check if I have any WebSocket package installed? I don't have much experience with python and its package manager so I don't know how I can check.

**Comment by miguelgrinberg** [comment]
@mnj93 You must be using the [websocket-client](https://github.com/websocket-client/websocket-client) package. Check to make sure you have it installed.

**Comment by mnj93** [comment]
@miguelgrinberg yes it's using [websocket-client,](https://github.com/websocket-client/websocket-client) this was installed by `pip3 install "python-socketio[client]"` command only. Is there any way I can rewrite/remove this default origin header?

**Comment by miguelgrinberg** [comment]
I don't know. This header must be inserted by the websocket client on its own. I have to say that an origin header with the same origin as the connection URL shouldn't be a problem, so for the reason they must be adding it to all requests. But I don't really know for sure.

**Comment by mnj93** [comment]
Okay got it, websocket-client provides an option to overwrite origin and other headers [check here](https://websocket-client.readthedocs.io/en/latest/examples.html#setting-common-header-values) but I guess we can't pass these options from socket io client to websocket-client as of now. 
To make it work for now I will have to add server URL as the origin on socket.io server. 
Thanks for your help @miguelgrinberg .

**Comment by jvpernis** [comment]
I just encountered the same issue in one of our setups as well. I have NGINX as a reverse proxy in front of a Flask-SocketIO server. Only HTTPS traffic is allowed, so naturally, we don't include any HTTP origins. There would be no issue if the Origin header included by websocket-client used the HTTPS scheme, but for some reason it uses HTTP. The JavaScript font-end client has no issues connecting to the Flask-SocketIO server.

I have used the following snippet to connect my client:
```python
sio = socketio.Client()
sio.connect("wss://<domain>")
```

Oddly enough, this issue doesn't appear when using the `asyncio` client:
```python
sio = socketio.AsyncClient()
await sio.connect("wss://<domain>")
```

The issue also doesn't occur when specifically using the polling transport:
```python
sio = socketio.Client()
sio.connect("https://<domain>", transports="polling")
```

As mentioned by @mnj93, the websocket-client package includes an option to suppress the `Origin` header. When manually patching the python-engineio package, I was finally able to setup the connection with my client.  I added the following line in the `_connect_websocket()` method in `client.py`:
```python
extra_options['suppress_origin'] = True
```

Do you have any suggestions on how to get this working with the synchronous client using the websockets transport?

Here are the relevant package versions I have used:
```
python-engineio==4.3.1
python-socketio==5.5.1
websocket-client==1.2.3
requests==2.27.1
```

**Comment by miguelgrinberg** [comment]
@jvpernis wouldn't this be a bug in the ws client?

**Comment by jvpernis** [comment]
Thanks for the quick reply! I agree, I have created [websocket-client#787](https://github.com/websocket-client/websocket-client/issues/787) for this bug in the `websocket-client` package.   

You mentioned:
> There are a few websocket packages that are supported

I couldn't find any references to these other packages which I could try out. Do you know where I can find which other packages are supported?

**Comment by miguelgrinberg** [comment]
@jvpernis for the client side the other websocket package is the one used in the async side, which is aiohttp. The server uses a few more, but that does not apply in this context, I think.
