### ISSUE TITLE
Callback Documentation

### ISSUE THREAD

**Issue by dfee** [miguelgrinberg/python-socketio#79]
I was having a hard time figuring out how to get client callbacks working (RPC style). After a short struggle I figured out how to respond to an individual request:

```
@sio.on('reverse', namespace='/test/')
async def reverse(sid, message):
    return {'data': message[::-1]}
```

and the javascript (sorry, it's ES6 style):

```
onMyEvent = () => {
    this.socket.emit(
        'reverse',
        {'data': 'howdy'},
        response => alert(`Responded with: ${response.data}`)
    );
}
```

I don't know how the inverse is supposed to work, though. I imagine it has something to do with the `callback` argument in the [`AsyncManager`](http://python-socketio.readthedocs.io/en/latest/#socketio.AsyncManager.emit). Can you explain?

**Comment by miguelgrinberg** [comment]
Yes. If you pass a `callback` argument, the function will be called with the arguments provided by the client when it acknowledge the event. How the client performs this depends on the client. For the JavaScript client, here is an example:

    socket.on('myevent', function(data, callback) {
        // handle event here
        callback('abc', 123);
    });

You would then get a call on your callback with arguments `'abc', 123`.

Hope this helps!

**Comment by dfee** [comment]
Very helpful. Thanks!

I was thrown off when looking at the tests for this package – the callback referenced is the string `cb`. I found some more documentation [here](http://python-socketio.readthedocs.io/en/latest/#callbacks) that provided additional insight:
> The socketio.Server.emit() method has an optional callback argument *that can be set to a callable*

**Comment by miguelgrinberg** [comment]
Unit tests are not always a good model to follow. Often things are simplified, like in the case of a callback, when I just need to make sure whatever the caller passes is preserved, I don't really need a real callback, anything will do.
