### ISSUE TITLE
Accessing underlying app when using AsyncServer

### ISSUE THREAD

**Issue by dfee** [miguelgrinberg/python-socketio#80]
With the current implementation, the `app` that `socketio.AsyncServer` attaches to is unavailable in `on` method calls.

For example, when using python-socketio with sanic, we're unable to access the request object (which provides access to `request.app`).

```
# in __init__.py file
from myproj.sio import sio
...
sio.attach(app)


# in sio.py
@sio.on('my event')
def test_message(sid, message):
    return app.config['my_setting']
```

I've manually resorted to calling `sio.app = app` to access the app instance. But I'm wondering if you had a reason for not providing `AsyncServer.app`?

**Comment by miguelgrinberg** [comment]
Well, `app` is a global variable, so why don't you just access it as such?

**Comment by dfee** [comment]
I'm actually creating `app` in a function during startup, so it's not available to import. It's also not in my `globals()`…

**Comment by miguelgrinberg** [comment]
Sure, that makes sense.

It's really more than the `app` that you may need, the `request` object is really what should be exposed, and from there you should be able to get to the app, information about the client, etc.

I tried to keep this package framework agnostic, that is why I'm not sure exposing the app or a request object is a good idea. Flask, for example, has the app, the request, a session object, and the "g" object, so doing `sio.app` and/or `sio.request` is not enough. I actually created Flask-SocketIO, which builds on top of this package and adds the Flask specific bits.

I guess I need to think about it. If I can come up with a way to support exposing the framework context in a framework independent way I would be okay with adding it.

**Comment by 3mp3ri0r** [comment]
> I've manually resorted to calling sio.app = app to access the app instance. But I'm wondering if you had a reason for not providing AsyncServer.app?

How to call `sio.app` when I use class-based namespace?

**Comment by miguelgrinberg** [comment]
The request object from Sanic can be obtained as follows:

    sio.environ[sid]['sanic.request']

where `sid` references the desired client.
