### ISSUE TITLE
Connection is always closed when using WebSocket

### ISSUE THREAD

**Issue by mckelvin** [miguelgrinberg/python-socketio#81]
I find the issue while using the native `WebSocket`:

```javascript
// code to reproduce
s = new WebSocket("ws://localhost:5001/ws/api")
s.send('echo') // !VM607:1 WebSocket is already in CLOSING or CLOSED state.
```

Somehow the issue doesn't happen on `socketio`:

```javascript
// code works well
$.getScript("https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.5/socket.io.min.js")
s = io.connect("ws://localhost:5001/ws/api")
s.send('echo')
```

The server is just a simple demo using `flask-socketio` and `gevent-websocket`, I don't why this happened only when using the `WebSocket`.

**Comment by miguelgrinberg** [comment]
Socket.IO is not compatible with WebSocket. If you use a Socket.IO server, you need to connect with a Socket.IO client.
