### ISSUE TITLE
Horizontal scaling and publishing to a SID

### ISSUE THREAD

**Issue by dfee** [miguelgrinberg/python-socketio#82]
The notes on horizontal scaling say (**emphasis mine**):
> If multiple Socket.IO servers are connected to the same message queue, **they automatically communicate with each other and manage a combined client list**, without any need for additional configuration. When a load balancer such as nginx is used, **this provides virtually unlimited scaling capabilities for the server**.

I'm concerned that emit'ing to "SID rooms" is expensive. Here's my scenario where I'm handling and transforming the pub/sub of events for individual clients:
* two clients subscribe to an event: `user:1:updated` and one request fields: `[id, name]` where the other requests `[id, name, location, friends: {id, name}]`
* i can manage the relationship between SIDs and event subscriptions at the process level
* when publishing the data to a SID room, other processes are notified of the message even if they're not hosting the SID (right?).

This reflects the current approach of GraphQL subscription frameworks (specific clients can request specific formats). My understanding then is that if I have 20k clients evenly split across 4 processes all subscribed to 1 event, each process will emit 5k messages, and be interrupted by irrelevant data 15k times.

I'm looking at the [`AsyncRedisManager`](https://github.com/miguelgrinberg/python-socketio/blob/master/socketio/asyncio_redis_manager.py#L72) and the [`Server`](https://github.com/miguelgrinberg/python-socketio/blob/master/socketio/server.py#L220) that [`AsyncServer`](https://github.com/miguelgrinberg/python-socketio/blob/master/socketio/asyncio_server.py#L108) subclasses from.

If I understand this right, SocketIO is unable to scale horizontally when publishing primarily to SIDs with the current implementation. Is this right?

**Comment by dfee** [comment]
Perhaps with the approach I mentioned above, the responsibility of scaling PubSub horizontally falls on my back, not yours.

I.e. if I were to exclusively publish to SID rooms rather than public rooms, then using a distributed PubSub for SocketIO doesn't make sense, and I should use the default `AsyncManager` instead of `AsyncRedisManager`. I would then need to worry about handling my event PubSub instead.

**Comment by miguelgrinberg** [comment]
Sid rooms are not treated as a special case right now, but they should. An interesting optimization would be to lock all sid rooms so that members cannot be added or removed, and then there wouldn't be a need to broadcast those emits to all the other nodes, since we are guaranteed that there is a single client in each of those rooms.

**Comment by miguelgrinberg** [comment]
I doubt I will ever implement this, since now the `ignore_queue` option in the `emit()` can be used to bypass the slow queue operation.

**Comment by basedav** [comment]
I would be interested in implementing this. I am not using the room feature to emit to specific groups of clients (I manage various groups of client sids in the app logic instead).

For context, my game uses python socketio servers as the communication endpoint for game actions made by clients. I am running separate servers for bot clients and human clients; the bot clients play the game very quickly and generate tens of thousands of game state updates every second that must be emitted to the clients across the bot servers.

I am using a single redis server as the client manager on every server and I want to lessen the load experienced by the human server reading through all the messages that are meant for bot clients; for reference my human server container is a consistent 95%+ load with no human players actually playing the game. I could just horizontally scale redis but this doesn't address the bottleneck in horizontally scaling the socketio servers.

I propose addressing this by simply having separate pubsub channels per sid (room). I'm not sure how expensive this will be for Kafka or RabbitMQ topics, but for redis pubsub, [channels strings are stored in a hash table with the value being a set of clients subscribed to that channel](https://making.pusher.com/redis-pubsub-under-the-hood/). So emitting an event to a particular sid (channel) will be constant time on average instead of always being linear in the number of servers and also loading every server subscribed to the single `'socketio'` channel.

Please let me know what you think and any guidance on how to best implement this since right now the pubsub manager seems to lock in the idea of a single channel. Thanks!

**Comment by miguelgrinberg** [comment]
Maybe I do not understand fully your situation, but why don't you pass a different channel name when you create your redis client manager? https://github.com/miguelgrinberg/python-socketio/blob/master/socketio/redis_manager.py#L31-L32.

**Comment by basedav** [comment]
The name of the channel isn't the issue. The main problem is that every message is consumed by every server which we want to avoid. Ideally the message would go straight to the correct server, which this solution accomplishes with multiple channels, each server only subscribed to the channels which correspond to the sids connected to it.

Does this make more sense?

**Comment by miguelgrinberg** [comment]
Still have questions.

If these two groups of clients (bots & humans) never interact with each other, why don't you use two separate servers, or maybe use a single server, but set the redis channel to `socketio-bots` in the bot servers and `socketio-humans` in the human servers?

**Comment by basedav** [comment]
This is a reasonable compromise for my particular case but still doesn't scale well while also introducing more self management. I'll try to demonstrate.

I actually don't want the bot and human distinction to matter; using separate `socketio-bots` and `socketio-humans` channels would eliminate the bot message load on the human server but not the bot message load on the bot servers that particular bots aren't connected to. For example, my game has 4 players per game; if I have 8 bot servers then every single bot message would be consumed/processed by 4 servers that the 4 bots playing the game are certainly not connected to, and if each of the 4 bots playing the game are connected to different bot servers, that is 7 servers consuming a message not targeted at any of its clients.

Then you could say, "just have separate channels for every server", but this would require maintaining a sid to channel mapping and separate `AsyncRedisManager`s for each channel (e.g. my bot service would query for the bot's sid's channel and then choose which `AsyncRedisManager` to `.emit` the bot's game action on). Orchestrating this stuff manually isn't that bad now that I think about it, but this ought to be integrated into the pubsub managers themselves to actually facilitate meaningful horizontal scaling

Let me know what you think.

**Comment by miguelgrinberg** [comment]
First of all, you are starting from the assumption that you know on which server each player is. This is not typical, in most cases clients are randomly assigned a server. If you know on which server your client is, then you can just do the emit on that server using the option to skip the message queue.

For the "normal" case where you have servers behind a load balancer, you really don't know where each client is, as this is determined by the load balancer. Sending a message to a single client (or to a room) requires every server checking if it knows the recipient. The case that I said above to the OP that could be optimized is when there is an emit to a user room, and the server in which the emit is issued is the one where that client is hosted. In that case going out to the message queue is unnecessary. But for this to be possible user rooms need to be treated specially, they need to be marked as such, and you should not be able to add/remove participants from them.

**Comment by basedav** [comment]
I'm not sure what you mean by "do the emit on that server..." since I am emitting from an external process? The emit message must be sent to some message queue and consumed by the appropriate server right?

Knowing which server each player is connected to is precisely what using separate pubsub channels per sid implicitly accomplishes. Servers will only consume messages from channels which correspond to sids which are connected to it.

**Comment by miguelgrinberg** [comment]
> Knowing which server each player is connected to is precisely what using separate pubsub channels per sid implicitly accomplishes.

So if each server hosts 5000 clients you want the server to listen on 5000 different channels, while each of the other servers also listen on their own set of 5000ish clients? Does sound too good to me, but regardless, I think you should be able to implement a pubsub client manager subclass that does this. The tricky part would be enforcing that these sid-based rooms are locked.

**Comment by basedav** [comment]
Yes. As I said earlier I'm not sure how expensive this will be for other message queues but for [redis pubsub](https://making.pusher.com/redis-pubsub-under-the-hood/), the clients for each channel are stored in a hash table from channel to a set of clients and each client stores a hash table of it's subscribed channels. Which part doesn't sound too good?

And yes already have something implemented with [aioredis's multi producer single consumer receiver](https://aioredis.readthedocs.io/en/v1.3.0/mpsc.html#aioredis.pubsub.Receiver). I just overwrote the `asyncio_redis_manager.py` but perhaps I can make a subclass of it for a pr? Here's the class.

```python
class AsyncRedisManager(AsyncPubSubManager):  # pragma: no cover
    """Redis based client manager for asyncio servers.

    This class implements a Redis backend for event sharing across multiple
    processes. Only kept here as one more example of how to build a custom
    backend, since the kombu backend is perfectly adequate to support a Redis
    message queue.

    To use a Redis backend, initialize the :class:`Server` instance as
    follows::

        server = socketio.Server(client_manager=socketio.AsyncRedisManager(
            'redis://hostname:port/0'))

    :param url: The connection URL for the Redis server. For a default Redis
                store running on the same host, use ``redis://``.  To use an
                SSL connection, use ``rediss://``.
    :param channel: The channel name on which the server sends and receives
                    notifications. Must be the same in all the servers.
    :param write_only: If set ot ``True``, only initialize to emit events. The
                       default of ``False`` initializes the class for emitting
                       and receiving.
    """
    name = 'aioredis'

    def __init__(self, url='redis://localhost:6379/0', channel='socketio',
                 write_only=False, logger=None):
        if aioredis is None:
            raise RuntimeError('Redis package is not installed '
                               '(Run "pip install aioredis" in your '
                               'virtualenv).')
        (
            self.host, self.port, self.password, self.db, self.ssl
        ) = _parse_redis_url(url)
        self.redis = None
        self.mpsc = None
        # stores channels to subscribe to so redis connection can
        # continue to be created lazily
        self._pre_listen_channels = set()
        super().__init__(channel=channel, write_only=write_only, logger=logger)

    async def connect(self, sid, namespace):
        super().connect(sid, namespace)
        if not self.write_only:
            if not self.mpsc:
                self._pre_listen_channels.add(sid)
            else:
                await self.redis.subscribe(self.mpsc.channel(sid))
    
    async def disconnect(self, sid, namespace):
        super().disconnect(sid, namespace)
        if not self.write_only:
            if self.redis and self.mpsc:
                await self.redis.unsubscribe(sid)
            else:
                self._pre_listen_channels.remove(sid)

    async def _publish(self, data):
        retry = True
        while True:
            try:
                try:
                    return await self.redis.publish(
                        data.get('sid') or data.get('room'),
                        pickle.dumps(data)
                    )
                except AttributeError:
                    self.redis = await aioredis.create_redis_pool(
                        (self.host, self.port), db=self.db,
                        password=self.password, ssl=self.ssl
                    )
            except (aioredis.RedisError, OSError):
                if retry:
                    self._get_logger().error('Cannot publish to redis... '
                                             'retrying')
                    self.pub = None
                    retry = False
                else:
                    self._get_logger().error('Cannot publish to redis... '
                                             'giving up')
                    break

    async def _listen(self):
        # _thread whiles on this
        retry_sleep = 1
        while True:
            try:
                try:
                    while await self.mpsc.wait_message():
                        return (await self.mpsc.get())[1]
                except AttributeError:
                    if not self.redis:
                        self.redis = await aioredis.create_redis_pool(
                            (self.host, self.port), db=self.db,
                            password=self.password, ssl=self.ssl
                        )
                    self.mpsc = aioredis.pubsub.Receiver()
                    if self._pre_listen_channels:
                        await redis.subscribe(*[self.mspc.channel(channel) for channel in self._pre_listen_channels])
            except (aioredis.RedisError, OSError):
                self._get_logger().error('Cannot receive from redis... '
                                         'retrying in '
                                         '{} secs'.format(retry_sleep))
                self.sub = None
                await asyncio.sleep(retry_sleep)
                retry_sleep *= 2
                if retry_sleep > 60:
                    retry_sleep = 60
```

**Comment by miguelgrinberg** [comment]
Your code is incomplete, I think:

- Custom rooms don't seem to be implemented. You assume there is a channel for each room, but only sid rooms are initialized so that the server listens on them.
- Broadcasts to everyone do not appear to be supported either.
- I mentioned this before, the sid rooms currently do not prevent changes. They should be locked to make this feature robust.

As much optimized Redis is, there's got to be a cost to having potentially large numbers of channels. As an implementation it seems

**Comment by basedav** [comment]
Thanks I'll make this a subclass and address the issues you pointed out before making a pr. Thanks!
