### ISSUE TITLE
Client background thread doesn't stop after Timeout

### ISSUE THREAD

**Issue by goyzhang** [miguelgrinberg/python-socketio#821]
If I am right there are some background threads/tasks to handle incoming message. While I am calling :
```python
try:
    v = sio.call('get_v, 'data',  timeout=5)
except socketio.exceptions.TimeoutError as e:
    print("error")
finally:
    sio.disconnect()
#main thread exit here, but the python process doesn't
```
Assume that the sever will return after 10s, I will have to wait for 10s **with or without** `sio.disconnect()` for the python process to end. It seems some background threads are preventing the process from terminating. In case of timeout, why does it have to wait? Or is there anyway to abort those non-daemon threads?

I'm running the latest client on a windows PC.

**Comment by miguelgrinberg** [comment]
I adapted one of the examples in this repository to do what you are doing, and I don't really see this problem. My client exits after 5 seconds.

**Comment by goyzhang** [comment]
Hi @miguelgrinberg , I tried again, both client and sever on windows, but still the same result, could you check: [gist](https://gist.github.com/goyzhang/eccaf1fcbe095f745455ddbbf0784014)
Here is my output from the client:
```
04:48 : call()
04:49 : timeout throw
04:49 : disconnect()
04:58 : end, process end
```
see it hangs for 9 seconds after 1 seconds timeout.

**Comment by miguelgrinberg** [comment]
You can't use `time.sleep()` in an async application, as it blocks the async loop and prevents the communication with clients to happen. Replace the sleep with `socketio.sleep()` which is async compatible.

**Comment by goyzhang** [comment]
OK, in fact I have no control over the server. The sleep is just for demo,  both server and client are sync app,  in practice, it accesses some hardware resource sync. The problem is my client just can't exit after timeout, even when the main thread ends. if I remove `disconnect`, and the main thread reaches the end, then the python process freezes. Is there any way to configure the `daemon` thread to just let it die with after main thread ends?

**Comment by miguelgrinberg** [comment]
@goyzhang a graceful disconnect is not an atomic operation, it requires first disconnecting the namespace(s) you are connected to, and then disconnecting the base Engine.IO connection. I have not added a "force" option to disconnect, but I think that makes sense to avoid depending on servers that aren't responsive.

**Comment by miguelgrinberg** [comment]
I'm still unable to reproduce this delay with the provided code examples, so I'm going to close.
