### ISSUE TITLE
RateLimiting middleware

### ISSUE THREAD

**Issue by ttamg** [miguelgrinberg/python-socketio#823]
Great package Miguel.  And the video tutorial is very clear as always.  Such nice simple tutorials.   Thanks as always for such a great solution.  I'm loving writing socket.io apps using python-socketio

## Feature request - middleware / rate-limiting

I've been looking for a simple way to implement basic user-level rate limiting on some or all of the socket.io events using this package.  

In my setup I'm running **python-socketio** together with a **fastapi** app that sits alongside, and it's working very nicely indeed so far.  I'm using the `AsgiApp` variant.

### Rate limiting on socket-io

There are some javascript solutions around socket.io that support rate limiting such as [here](https://github.com/animir/node-rate-limiter-flexible/wiki/Overall-example#websocket-single-connection-prevent-flooding)

### Nice rate limiting implementations for Flask and FastAPI

In Flask and FastAPI for the classic request-response cycles there are some nice limiting packages that use decorators.  I'd love to use or replicate these.  The FastAPI port of the Flask package is called **slowapi** [here](https://github.com/laurentS/slowapi). As this requires the request object to work I expect it won't work with socket-io but I haven't hacked around yet.

### Python-engineio middleware?

I've had a look over at your **python-engineio** package also and in particular the [middleware](https://github.com/miguelgrinberg/python-engineio/blob/main/src/engineio/middleware.py) and also the [AsgiApp](https://github.com/miguelgrinberg/python-engineio/blob/main/src/engineio/async_drivers/asgi.py)

Not yet clear to me where I would hook in middleware, but seems to me it should hang off of `AsgiApp`.  Is that correct?

## My ask ...

1) Is extending the middleware capabilities or allowing middleware plugins something you have already considered as a feature in **python-socketio** or are middleware features something you see being separate from this core package in principle?

2) If I have somehow in my research completely missed an implementation of Python socket.io rate limiting then please feel free to point me in the right direction.  

Thanks!

**Comment by miguelgrinberg** [comment]
Regarding item 1, given that the `AsgiApp` instance is a fully compliant ASGI application, wouldn't it be possible to chain a third party ASGI rate limiter middleware? The chain would be something like this:

    Uvicorn (or similar) ---> ASGI rate limiter ---> Socket.IO's AsgiApp

If you need the rate limiting logic to be inserted in between AsgiApp and the actual Socket.IO server, then you should be able to subclass `AsgiApp` and do the work in the subclass, I think.

And for 2, I'm not aware of any rate limiting package that is specific to Python's Socket.IO.

**Comment by ttamg** [comment]
Thanks Miguel.  I will take a look
