### ISSUE TITLE
Server is sending acknowledgement even if event is not registered

### ISSUE THREAD

**Issue by Kromzem** [miguelgrinberg/python-socketio#824]
Hello :)

I encountered for my opinion strange behaviour. I have a client who is sends out an event which is unknown to the server. But instead of returning nothing, the server returns an acknowledgement byte, so that the callback of the client gets triggered. 

I tried the same behaviour with the nodejs version of socketio and there everything works as expected.

So my question is now:
Is this a configuration I could do or is this intended behaviour or could it even be a bug?

I'm running the latest version: 5.5.0
I'm using AsyncServer with aiohttp.

Thanks in advance for an answer 😄

**Comment by miguelgrinberg** [comment]
You are correct, the server acknowledges the event even when there is no handler. This might be a misinterpretation of the standard on my part. I'll check the reference JS implementation to see how it handles this and do the same. Thanks.
