### ISSUE TITLE
hello, I want to know how to send msg that from rabbitmq to client with python socketio, can give me a example? thanks a lot

### ISSUE THREAD

**Issue by flyyabelle** [miguelgrinberg/python-socketio#825]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Logs**
Please provide relevant logs from the server and the client. On the Python server and client, add the `logger=True` and `engineio_logger=True` arguments to your `Server()` or `Client()` objects to get logs dumped on your terminal. If you are using the JavaScript client, see [here](https://socket.io/docs/logging-and-debugging/) for how to enable logs.

**Additional context**

**Comment by miguelgrinberg** [comment]
This is an issue board, it is not the right place to ask questions. Please write a discussion with your question and add more details about what you want to do.
