### ISSUE TITLE
Emitting events to clients stops working

### ISSUE THREAD

**Issue by lsapan** [miguelgrinberg/python-socketio#826]
**Describe the bug**
This is a bit of a nasty bug I've been trying to diagnose over the last month or two. I've been desperately trying to come up with reproduction steps, but so far haven't had any luck. What I do have, though, is a great deal of information about the symptoms. I'm hoping you may be able to help point me in the right direction so I can provide more information to you.

For a bit of context about the application: I have several python-socketio instances deployed that push out events to clients throughout the day. The events are generated from a Django app that utilizes a `RedisManager` in `write_only` mode. The python-socketio side is fully async, and uses an `AsyncRedisManager`. The python-socketio instances are deployed in ASGI mode, running via a `UnicornWorker` class on gunicorn.

After a few weeks, I started observing that certain connected clients were not receiving messages. After a bit of diagnosing, I identified that, of the 3 python-socketio instances running, 1 of them was causing the issue. Clients connecting to that instance could connect, emit events (**and receive responses**), as well as send/receive heartbeat messages, but they were not receiving events emitted from the server itself.

I initially blamed it on a possible disconnection between that python-socketio instance and redis, but with further diagnostics I was able to see that _any_ calls to `emit`, even local ones from within the namespace, are not delivered. To illustrate this point, I added this method to my namespace:

```
async def on_log(self, sid, msg):
    logger.warn(f'[Message from "{sid}"] {msg}')
    await self.emit(Event.LOG, data=msg, room=sid)
```

On clients connected to a functioning python-socketio instance, emitting a `log` received a response from the server as expected:
<img width="1272" alt="working" src="https://user-images.githubusercontent.com/3203257/144475516-6dffeb7f-8a68-4181-bf87-173bfb27b967.png">

However, on the python-socketio instance experiencing this issue, nothing was sent back to the client.

I can confirm that the instance _did indeed_ get the event from the client though, because the `logger.warn()` was being called:
<img width="600" alt="Screen Shot 2021-12-02 at 11 36 27 AM" src="https://user-images.githubusercontent.com/3203257/144475770-a23bb04d-54a1-4952-94e2-39ba34d04dea.png">

The thing that is particularly interesting about this is that returning data from an event on the server _does still work_. When the frontend clients connect, they emit an event which always receives a response from the server. Even when emitting an event to a python-socketio instance with this issue, that always gets delivered. So it seems to specifically be something about the `emit` process that is breaking down.

This issue generally starts happening to an instance after a few days. I've seen it happen as soon as 1 day after a container being created, and as long as a few weeks.

This is everything I can think of right now. If you have _any_ insight at all as to what I could do to further investigate, please let me know. I know this is a difficult ask because there aren't any repro steps, but I'm hoping with your full understanding of the system you may have some ideas. Thank you so much!

**To Reproduce**
None yet, see above

**Expected behavior**
Emitted messages should not stop getting delivered.

**Logs**
I am going to redeploy with additional logging enabled. Nothing was in the normal logs.

**Additional context**
I'm using uvloop, and I initially thought it could've been an outdated version of it causing issues. I've since upgraded `uvloop` to 0.16.0 and the issue still happens.

Full versions are below:
```
python-socketio==5.4.1
aioredis==1.3.1
hiredis==2.0.0
websockets==9.1  # Temporarily pinned to 9.1 until the closing issue is fixed (https://github.com/aaugustin/websockets/issues/1072)
gunicorn==20.1.0
uvicorn[standard]==0.15.0
uvloop==0.16.0
```

**Comment by miguelgrinberg** [comment]
How do you handle load-balancing between your socketio instances?

**Comment by lsapan** [comment]
@miguelgrinberg thanks for the quick reply! They're deployed to a Kubernetes cluster behind an AWS ALB. Each connection is round robin'd to one of the three python-socketio instances.

I should note that long polling is disabled, so there's no upgrade happening there. It's just one websocket connection that stays connected to the same instance.

I also want to clarify that the heartbeats back and forth between the client and the server still happen, even when this bug is happening, and the server is still receiving the events emitted from the client, so it seems like the connection itself is fine.

Happy to answer any other questions you have!

**Comment by miguelgrinberg** [comment]
The only explanation for this behavior I can come up with is that the connection from the instance to Redis must be breaking, in a way that isn't detected (the redis managers are supposed to reconnect if they lose the connection). The logs are going to be necessary to make progress with this, I'm afraid.

**Comment by lsapan** [comment]
@miguelgrinberg that's what I assumed as well, but the fact that the `await self.emit(Event.LOG, data=msg, room=sid)` within the instance didn't work really surprised me. I could be wrong but from quickly glancing at the code, it looks like `_emit_internal` would end up getting called directly by the manager, without having to go through redis (since the client is talking to this server).

If that's the case, wouldn't that remove redis from the equation entirely?

**Comment by miguelgrinberg** [comment]
@lsapan all emits go through redis by default. You have to add the `ignore_queue=True` option if you want an emit to be handled locally while the server is configured to use a message queue.

**Comment by lsapan** [comment]
@miguelgrinberg ahh okay, thank you for clarifying that! I'll do more digging and will report back when I have better logs. Hopefully soon but it could be a few weeks. Thanks again!

**Comment by lsapan** [comment]
@miguelgrinberg Thanks for your patience! The issue just happened again and I was able to run more diagnostics, as well as check the detailed logs from socketio/engineio.

It doesn't look like it is the redis connection, as it turns out the socketio instance **doesn't completely start failing**. It apparently is something where the socketio instance starts messing up specific connections. For example, I was able to connect to the failing instance a few times, and it would _sometimes_ work properly, and other times would not. This means that (unless the instance is using multiple redis connections behind the scenes), it's actually still connected to redis.

That said, I was able to get a bit more information. I updated the `on_log` handler I mentioned last time to do a bit more:
```python 
async def on_log(self, sid, msg):
    logger.warn(f'[Message from "{sid}"] {msg}')
    await self.server.emit(Event.LOG, data=f'Queue: {msg}', room=sid)
    await self.server.emit(Event.LOG, data=f'Ignore Queue: {msg}', room=sid, ignore_queue=True)
    return {'log': f'Returned {msg}'}
```

When emitting to the failing instance, the result was:
<img width="596" alt="Screen Shot 2021-12-10 at 4 45 53 PM" src="https://user-images.githubusercontent.com/3203257/145645274-48cda1c7-0187-4ebb-8b59-f9857ff6bc5d.png">

So as you can see, using `ignore_queue` does indeed allow the message to be received. This is bizarre as we've already established that the server is still connected to redis.

That brings me to the logs. I checked out this instance's logs and I can actually see it sending data to the majority of its clients! I can also explicitly see it ping/pong'ing my connection, but **not** sending the other data to it.

For reference, here are the logs from one of my connections that was not working:
```
dRRs5ijbZhAZfAy8AB36: Sending packet OPEN data {'sid': 'dRRs5ijbZhAZfAy8AB36', 'upgrades': [], 'pingTimeout': 20000, 'pingInterval': 25000}
dRRs5ijbZhAZfAy8AB36: Received request to upgrade to websocket
dRRs5ijbZhAZfAy8AB36: Upgrade to websocket successful
dRRs5ijbZhAZfAy8AB36: Received packet MESSAGE data 0
dRRs5ijbZhAZfAy8AB36: Sending packet MESSAGE data 0{"sid":"HYnKFWTBXI3oZlU_AB37"}
dRRs5ijbZhAZfAy8AB36: Sending packet PING data None
dRRs5ijbZhAZfAy8AB36: Received packet PONG data 
dRRs5ijbZhAZfAy8AB36: Sending packet PING data None
dRRs5ijbZhAZfAy8AB36: Received packet PONG data 
dRRs5ijbZhAZfAy8AB36: Sending packet PING data None
dRRs5ijbZhAZfAy8AB36: Received packet PONG data 
dRRs5ijbZhAZfAy8AB36: Sending packet PING data None
dRRs5ijbZhAZfAy8AB36: Received packet PONG data 
dRRs5ijbZhAZfAy8AB36: Sending packet PING data None
dRRs5ijbZhAZfAy8AB36: Received packet PONG data 
dRRs5ijbZhAZfAy8AB36: Sending packet PING data None
dRRs5ijbZhAZfAy8AB36: Received packet PONG data 
dRRs5ijbZhAZfAy8AB36: Sending packet PING data None
dRRs5ijbZhAZfAy8AB36: Received packet PONG data 
dRRs5ijbZhAZfAy8AB36: Sending packet PING data None
dRRs5ijbZhAZfAy8AB36: Received packet PONG data 
dRRs5ijbZhAZfAy8AB36: Sending packet PING data None
dRRs5ijbZhAZfAy8AB36: Received packet PONG data 
dRRs5ijbZhAZfAy8AB36: Received packet MESSAGE data 21["log","hey"]
dRRs5ijbZhAZfAy8AB36: Sending packet MESSAGE data 2["log","Ignore Queue: hey"]
dRRs5ijbZhAZfAy8AB36: Sending packet MESSAGE data 31[{"log":"Returned hey"}]
dRRs5ijbZhAZfAy8AB36: Sending packet PING data None
dRRs5ijbZhAZfAy8AB36: Received packet PONG data 
...
```

No errors or other messages appear around the connection of `dRRs5ijbZhAZfAy8AB36` (or anywhere for that fact), so it looks like everything happened exactly as it should have. That said, `dRRs5ijbZhAZfAy8AB36` is explicitly left out of anything that is being broadcast.

I sent out a test message further down in the logs, and you can see the instance broadcasting to other connected clients:
```
pubsub message: emit
pubsub message: emit
_EMuH6yPL6NHy5hKABM4: Sending packet MESSAGE data 2["test_message",1]
WgrRduKJ8HqoX74NABnQ: Sending packet MESSAGE data 2["test_message",1]
k_AahGaz6oy9_gskABJu: Sending packet MESSAGE data 2["test_message",1]
c_F3Ieh_lpfilFv5ABsz: Sending packet MESSAGE data 2["test_message",1]
t_sMP2orKAzioJXMABK2: Sending packet MESSAGE data 2["test_message",1]
...
```

However, `dRRs5ijbZhAZfAy8AB36` is never sent to. But there's still ping/pongs for it afterwards, so the instance knows that it is still there.

Finally, here's the server logs from emitting the `log` event:
```
dRRs5ijbZhAZfAy8AB36: Received packet MESSAGE data 21["log","hey"]
dRRs5ijbZhAZfAy8AB36: Sending packet MESSAGE data 2["log","Ignore Queue: hey"]
dRRs5ijbZhAZfAy8AB36: Sending packet MESSAGE data 31[{"log":"Returned hey"}]
dRRs5ijbZhAZfAy8AB36: Sending packet PING data None
dRRs5ijbZhAZfAy8AB36: Received packet PONG data 
```

Again, it mysteriously drops the message that isn't ignoring the queue.

Any idea how this could be happening?

**Comment by miguelgrinberg** [comment]
Do you have the complete log file?

**Comment by lsapan** [comment]
@miguelgrinberg yep, just emailed it to you! 👍

**Comment by miguelgrinberg** [comment]
The logfile that you sent me appears to be incomplete. If I search the log for `Queue:` or `Ignore Queue:` or `Message from` I get zero hits. These are the messages that you are sending or logging in your `on_log()` function, so why aren't they in the logfile?

**Comment by lsapan** [comment]
@miguelgrinberg sorry I mentioned it in the email but I should've here as well - I dumped that log file before emitting the `log` event. I sent out the test messages, dumped the log file, and then emitted the event while tailing the container in real time.

**Comment by miguelgrinberg** [comment]
Okay, but then I don't have the emit that supposedly skipped this client logged anywhere, because I guess this was emitted from another instance, and I haven't even seen the code for this emit. Do you have the code and logs for the emit?

**Comment by lsapan** [comment]
@miguelgrinberg ah yes, I emitted the test messages from a Django management command:

```python
import logging
import time

from django.core.management import BaseCommand

from sockets.constants import Event, Room
from xyz.socketio import external_sio

logger = logging.getLogger(__name__)


class Command(BaseCommand):
    def add_arguments(self, parser):
        parser.add_argument('--count', type=int, default=100)
        parser.add_argument('--delay', type=float, default=1.0)

    def handle(self, *args, **kwargs):
        for i in range(kwargs['count']):
            value = i + 1
            logger.info(f'Emitting {value}')
            external_sio.emit(Event.TEST, data=value, room=Room.GENERAL)
            time.sleep(kwargs['delay'])
```

I invoked it with:
```
./manage.py send_test_messages --delay 0.01 --count 10
```

As you can see, it simply emits a test event to all connected clients in the `general` room. If you look at the raw logs I emailed to you, you can see that `dRRs5ijbZhAZfAy8AB36` was in the general room because it was assigned `HYnKFWTBXI3oZlU_AB37 ` as an sid, which was then added to that room:
```
dRRs5ijbZhAZfAy8AB36: Sending packet MESSAGE data 0{"sid":"HYnKFWTBXI3oZlU_AB37"}
... (7 lines or so) ...
HYnKFWTBXI3oZlU_AB37 is entering room general [/]
```

**Comment by miguelgrinberg** [comment]
Take a look at sid `Ck-BKjuxEvRNfQUmAB2q`. This is the first connection that appears in your logfile. This seems to be a healthy connection for a while, but then suddenly the server stops sending PING packets to this client. Any idea why?

The only theory I have is that your logfile is incomplete. This client should have continued the ping/pong exchanges, or should have been disconnected due to becoming unresponsive, but it just vanished from the logs.

**Comment by lsapan** [comment]
@miguelgrinberg that's definitely interesting, and I suppose it is possible that Kubernetes dropped a log somewhere (though it'd be strange). However, you'll notice that I thankfully sent 10 test messages out when I ran that command.

I wrote a quick script to sanity check the test message logs:
```python
import re

test_regex = re.compile(r'(?P<sid>.*): Sending packet MESSAGE data 2\[\"test_message\",(?P<test_idx>\d+)\]')

messages = {i: set() for i in range(1, 11)}

with open('socketio_logs.txt') as f:
    for line in f:
        if match := test_regex.match(line):
            messages[int(match.group('test_idx'))].add(match['sid'])

for idx, message in messages.items():
    print(f'Number of SIDs in message {idx}: {len(message)}')
    print(message == messages[1])
```

It looks for the test message lines, and keeps track of which message index was sent to each sid. Then it prints out the number of distinct sids for each message, as well as whether the set of sids matches the first message. Here's the output:
```
Number of SIDs in message 1: 72
True
Number of SIDs in message 2: 72
True
Number of SIDs in message 3: 72
True
Number of SIDs in message 4: 72
True
Number of SIDs in message 5: 72
True
Number of SIDs in message 6: 72
True
Number of SIDs in message 7: 72
True
Number of SIDs in message 8: 72
True
Number of SIDs in message 9: 72
True
Number of SIDs in message 10: 72
True
```

All 10 messages were broadcast to the exact same 72 sids, so I think it's unlikely that `dRRs5ijbZhAZfAy8AB36` coincidentally was dropped from the log messages all 10 times.

As for the vanishing `Ck-BKjuxEvRNfQUmAB2q` connection, I think there's two possibilities:
1. Kubernetes dropped that log line
2. Something could've possibly gone awry in the instance to cause it to stop tracking this client? I don't think it is outside the realm of possibility since we are dealing with an instance that is experiencing issues.

Regardless of `Ck-BKjuxEvRNfQUmAB2q` though, these logs (thanks to the 10 message redundancy) still illustrate the following:
1. The socketio instance placed the client into the `general` room
2. The instance received an emit to send out a message to all its clients in the `general` room (as seen by the fact that it sent out the 72 messages each time)
3. The instance explicitly did not send the message to the client, despite it knowing that they are in the general room

Also a little irrelevant, but it's worth noting that this is happening to an instance with very few clients connected. This happened during off-peak hours when very few folks were online.

Let me know if there's any other information I can provide you with!

**Comment by miguelgrinberg** [comment]
You seem to be concerned about proving that there is an issue. The problem is that proof of the issue does not really help me understand what the problem is.

The fact is, your log indicates that a) either your logging system is dropping information or b) this instance is malfunctioning in a very strange way that goes beyond emits being ignored. I just followed the first 10 clients, and here is what happened to each of them:

- `BKjuxEvRNfQUmAB2q`: disappeared after it returned a PONG message
- `782vE8dJ9OHFzX84AB2s`: did not respond and the server disconnected it (this is an expected outcome)
- `_24RhnW3Y8t0A0U8ABva`: disappeared while a PING was outstanding
- `EinBABaLkWCWsXBqAB2u`: disappeared while a PING was outstanding
- `nm3P0LroLVLCwWGABvc`: disappeared while a PING was outstanding
- `i_kthZya7iX4nZ2GABve`: disappeared after it returned a PONG message
- `sW0nwo7CR9DQpFHeAB2w`: disappeared after it returned a PONG message
- `9qMT7_E2Az6YjlD7AB2y`: did not respond and the server disconnected it
- X3IGx21A93funOdVABvg`: gracefully disconnected by the server
- QjKQNttbkk_BYU2xABx7`: disappeared after it returned a PONG message

So we have only three of the first 10 clients in the logging window with a known outcome. The other seven just vanished. How is this possible? You seem to be dismissing this as unimportant, but I disagree, your issue with emits is likely part of a larger problem that is related to this, and that I still fail to understand.

**Comment by miguelgrinberg** [comment]
Another odd thing for you to comment on. The `sid` numbers generated by this package are somewhat sequential. Looking at the last four characters, those are a number that grows sequentially, encoded in base64.

Still looking at those first 10 clients in your log, the first ends with `AB2q` for the connection sid, and `AB2r` for the namespace sid. The 2nd client uses `AB2s` and `AB2t`. The expected would be that the 3rd client would be `AB2u` and `AB2v`, but somehow that is the 4rd client, while the 3rd is on a different sequence. That to me suggests that this log does not come from a single instance, you have a mixed log from more than one Socket.IO instance here.

**Comment by lsapan** [comment]
My apologies for the misunderstanding! You're right, I was trying to prove that there's an issue because I was concerned you would (understandably) think there's something going wrong outside of the library. This is an incredibly strange issue so I wouldn't blame you for being skeptical haha.

Thank you for your follow up message - you reminded me that I am indeed looking at logs from multiple instances, despite being the logs from a single container. I forgot that I used 4 gunicorn workers per container. So that _does_ mean that it could be (and likely is) redis, and that one of the workers within the container is losing that connection.

In that case though, it's bizarre that the disconnections are missing in the logs as you pointed out.

I can look into using an alternative logging driver to ensure that nothing is getting lost. In the meantime, do you have any suggestions to verify that it truly is the redis connection being lost? Perhaps adding something into the manager code that polls redis for a live connection?

**Comment by lsapan** [comment]
Just adding a note here that the next time it happens, I can inspect the active redis connections to see if one of them has dropped:

```
redis-cli client list | grep " sub=1"
```

There's normally 12, so if I see any less than that then I at least know one of them is gone.

**Comment by miguelgrinberg** [comment]
The listening thread for the redis managers only catch `RedisError` exceptions ([here)(https://github.com/miguelgrinberg/python-socketio/blob/main/src/socketio/asyncio_redis_manager.py#L74)). If this package were to raise an exception outside of this umbrella one, then it would not be handled, and the listening thread would just stop running. If we trust that your logs will include unhandled exceptions, then whatever happened should be in the log.

Not saying this is the problem, but upon reviewing this code I think it makes sense for me to add a handler for all other exceptions as well.

**Comment by lsapan** [comment]
Yeah that makes total sense sense. I have a hunch that the reason I'm not seeing the unhandled exception is because it's actually happening well ahead of when it is being noticed, and by the time it's noticed it's already truncated from the logs.

I'm going to set up a process that monitors the redis connections and notifies me as soon as the connections drop below 12 so I can grab the logs immediately. Hopefully we'll have our culprit soon 😄

Thanks for responding on a weekend by the way! I hope you enjoy the rest of it!

**Comment by lsapan** [comment]
@miguelgrinberg Hope you've been well! This issue has happened twice since I rolled out the connection check, but both times actually still showed 12 active redis connections. With that said, it does indeed appear to be a breakdown somewhere with redis because I can see in the logs that there are only 3 instances receiving the pubsub message instead of the 4 that should be:
```
pubsub message: emit
pubsub message: emit
pubsub message: emit
```

I confirmed 4 appear on the other, working instances.

With this in mind, I was surprised there were still 12 active connections, so I checked the number of active subscribers to the `socketio` channel:
```
redis-cli pubsub numsub socketio
1) "socketio"
2) (integer) 12
```

So evidently, the connection is still subscribed, but it isn't processing messages. I wouldn't completely rule out the possibility that there's an `aioredis` issue, especially since I'm still on v1 of the library. I'm going to try upgrading it to v2 after the holidays, but wanted to see if you had any other ideas in the meantime that could be causing the messages to stop being handled on the python-socketio side.

For what it's worth, no exceptions are being raised. I can confirm this not just from the logs, but also from Sentry. I tried manually killing one of the redis connections, and saw the logged error pop up in both the logs and Sentry, but there aren't any unhandled exceptions on the socketio side of things.

**Comment by miguelgrinberg** [comment]
@lsapan not sure what else to suggest. I really have no mileage on the async redis library, either version 1 or 2, so I don't know how reliable it is for serious work. If it would be possible for you to rewrite in traditional Python, then using the standard redis client, which a lot of people use and seems very robust, might be a good idea.

**Comment by lsapan** [comment]
Closing as this appears to be an issue with the aioredis client. The issue popped up again so I killed the connection from redis, and it didn't reconnect. Here's hoping aioredis 2 fixes the issue. Thank you so much for all of your help! I'll follow up once I get some data from aioredis 2 just in case anyone stumbles across this in the future.
