### ISSUE TITLE
socketio_path doesn't handle absolute path

### ISSUE THREAD

**Issue by hsmade** [miguelgrinberg/python-socketio#83]
app = web.Application(loop=loop)
    sio.attach(app, socketio_path='/ws/socket.io')

Results in:
    websocket_1       | INFO:aiohttp.access:172.20.0.10 - - [13/Mar/2017:15:17:31 +0000] "GET /ws/socket.io/?EIO=3&transport=polling&t=Lh8Fkkb HTTP/1.1" 404 14 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/56.0.2924.76 Chrome/56.0.2924.76 Safari/537.36"

I found that, for this to work, I needed to drop the leading '/'. Can you please handle this (probably very common) use case in the code?

**Comment by miguelgrinberg** [comment]
Yeah, I agree, this should work either way.
