### ISSUE TITLE
WinError 10035 on Client connection

### ISSUE THREAD

**Issue by mcosta-vv** [miguelgrinberg/python-socketio#839]
Hello, i receive random [WinError 10035] error and the socket io client is disconnected when connect from python client to nodejs server.

The client: [python]
python-engineio==4.3.0
python-socketio==5.5.0

The server [nodejs]
engineIO: 4.1.1
socketIO: 3.1.2

With nodejs client works fine:
node v16.13.1
socket.io-client@4.4.0

Python Logs:
Received ack [/mt/api/rt/v1]
Received packet PING data
Sending packet PONG data
Unexpected error receiving packet: "[WinError 10035] No se puede completar de forma inmediata una operación de desbloqueo de socket", aborting
Waiting for write loop task to end
Exiting write loop task
Engine.IO connection dropped
Connection failed, new attempt in 0.88 seconds
Exiting read loop task
Attempting WebSocket connection to wss://192.168.69.14:8443/socket.io/?transport=websocket&EIO=4
WebSocket connection accepted with {'sid': '07OyWAGHsngYowTuAAEs', 'upgrades': [], 'pingInterval': 10000, 'pingTimeout': 5000}
Engine.IO connection established
Sending packet MESSAGE data 0/mt/api/rt/v1,
Received packet MESSAGE data 0/mt/api/rt/v1,{"sid":"gQKnXUhRySGLWhW-AAEt"}
Namespace /mt/api/rt/v1 is connected
Emitting event "sub-notification" [/mt/api/rt/v1]
Sending packet MESSAGE data 2/mt/api/rt/v1,1["sub-notification",{"session":***********","topics":["EVENT"],"subtopics":{"EVENT":{"whitelist":["DEVICE_LPR_PLATE_FOUND"]}}}]
Reconnection successful
Received packet MESSAGE data 3/mt/api/rt/v1,1[{"status":"error","statusCode":400,"message":"status code: 403, status message: Forbidden","meta":{"code":-80,"name":"INVALID_SESSION"}}]
Received ack [/mt/api/rt/v1]
Received packet PING data
Sending packet PONG data
Received packet PING data
Sending packet PONG data
Received packet PING data
Sending packet PONG data
Unexpected error receiving packet: "[WinError 10035] No se puede completar de forma inmediata una operaci▒n de desbloqueo de socket", aborting
Waiting for write loop task to end
Exiting write loop task
Engine.IO connection dropped
Connection failed, new attempt in 1.14 seconds
Exiting read loop task
Attempting WebSocket connection to wss://192.168.69.14:8443/socket.io/?transport=websocket&EIO=4
WebSocket connection accepted with {'sid': 'GX04O-yrSsGlvjEhAAEu', 'upgrades': [], 'pingInterval': 10000, 'pingTimeout': 5000}
Engine.IO connection established
Sending packet MESSAGE data 0/mt/api/rt/v1,
Received packet MESSAGE data 0/mt/api/rt/v1,{"sid":"PeuyoWsx36OzK8r4AAEv"}
Namespace /mt/api/rt/v1 is connected
Emitting event "sub-notification" [/mt/api/rt/v1]

**Comment by miguelgrinberg** [comment]
@mcosta-vv I'm not really sure, as this seems to be a peculiarity of the Windows networking. Do you see the same issue if you run your client under Ubuntu/WSL?

Do you see this error with any of the client and server examples in this repository? If the error only occurs on your client, then we should try to determine how this client is different from the example ones I provide here.

**Comment by mcosta-vv** [comment]
Hi Miguel, thanks for your time.
I think that the problem is related with engineio version, i do some tests in Windows 10 machine.
Using engineio 3.x seems to work fine and using v4.x fails randomly.

ENV 1 -> FAIL
python-engineio==4.3.0
python-socketio==5.5.0
#  19x WinError 10035 in 3 hours running

ENV 2 -> OK
python-engineio==3.14.2
python-socketio==4.6.1
#  NO WinError 10035 in 3 hours running

ENV 3 -> OK
python-engineio==3.14.2
python-socketio==5.0.0
#  NO WinError 10035 in 3 hours running

ENV 4 -> FAIL
python-engineio==4.3.0
python-socketio==5.1.0
#  14x WinError 10035 in 3 hours running


ENV 5 -> FAIL
python-engineio==4.3.0
python-socketio==5.0.4
#  11x WinError 10035 in 3 hours running

**Comment by miguelgrinberg** [comment]
You have completely ignored my questions.

**Comment by mcosta-vv** [comment]
Hi, for the tests i use this code:
https://github.com/miguelgrinberg/python-socketio/blob/main/examples/client/threads/fiddle_client.py
with this modification: sio = socketio.Client(engineio_logger=True,ssl_verify=False)

Finally i can test in Linux enviroment and works fine:

Linux Mint Debian -> OK
Python 3.6.8
engineio 4.3.0
socketio 5.5.0

Ubuntu -> OK 
Python 3.8.10
engineio 4.3.0
socketio 5.5.0

**Comment by miguelgrinberg** [comment]
Does the error occur on Windows when using my fiddle example?

**Comment by mcosta-vv** [comment]
Yes, i tried this in some Windows 10 devices, and always reports the error.

**Comment by miguelgrinberg** [comment]
Unfortunately I'm not sure how I can help. The Socket.IO client does not use non-blocking sockets, so I don't really know why you are getting this error, unless it is a bug in the websocket-client package that I'm using. I wouldn't be surprised, as most packages have less testing on Windows than on Unix (mine included, not trying to blame anyone here, just stating a fact).

**Comment by mcosta-vv** [comment]
Thanks, for now i solve the problem using this packages:
python-engineio==3.14.2
python-socketio==4.6.1

**Comment by miguelgrinberg** [comment]
When you use the older release, is the client connecting via websocket as well, it is it connecting with long polling?

**Comment by mcosta-vv** [comment]
websocket

**Comment by miguelgrinberg** [comment]
I'm really confused then, because nothing major has changed between those two releases in terms of the WebSocket client.

**Comment by miguelgrinberg** [comment]
Please reopen if you have any new information to add.
