### ISSUE TITLE
transports was set up 'websocket'，show 'error during WebSocket handshake: Unexpected response code: 400'

### ISSUE THREAD

**Issue by larry-dev** [miguelgrinberg/python-socketio#84]
i use sanic 0.41
python3.5

**Comment by miguelgrinberg** [comment]
Sanic does not support websocket at this point. I contributed this feature actually, and it already landed on master, but it has not been released yet.

**Comment by larry-dev** [comment]
i try it.bug still failed.
`Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 785, in uvloop.loop.__uv_stream_on_read_impl (uvloop/loop.c:76261)
  File "uvloop/handles/stream.pyx", line 559, in uvloop.loop.UVStream._on_read (uvloop/loop.c:73531)
  File "/Volumes/macsource/01-Project/03-Pyvirtual/ykfast/lib/python3.5/site-packages/sanic/server.py", line 132, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 174, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2781)
httptools.parser.errors.HttpParserUpgrade: 587`

**Comment by miguelgrinberg** [comment]
@larry-dev Try adding `app.enable_websocket()` after the app object is created. This should have happened automatically, not sure why it didn't in your case.

**Comment by larry-dev** [comment]
sanic have not enable_websocket()

**Comment by larry-dev** [comment]
It is supported by default

**Comment by miguelgrinberg** [comment]
https://github.com/channelcat/sanic/blob/master/sanic/app.py#L210

**Comment by larry-dev** [comment]
thx, i see.  sanic 0.4.1 have not enable_websocket

**Comment by dfee** [comment]
@miguelgrinberg have you tried using socket.io with the master release of sanic? I just upgraded from `0.4.1` to `master` because I needed some new methods defined [here](https://github.com/channelcat/sanic/blob/master/sanic/request.py).

When running the app, I'm getting the following error:
```WARNI 2017-03-22 18:01:00,426 [engineio:148][MainThread] Invalid session 22112a6bdbc846d898b677aab083de33?EIO=3
```

On the browser side I'm getting this error:
```
http://localhost:3000/socket.io/?EIO=3&transport=polling&t=LhugZI9&sid=0bb89442bbaa488da3e0dcb4ffca749b Failed to load resource: the server responded with a status of 400 (Bad Request)
localhost/:1 WebSocket connection to 'ws://localhost:3000/socket.io/?EIO=3&transport=websocket&sid=0bb89442bbaa488da3e0dcb4ffca749b' failed: WebSocket is closed before the connection is established.
http://localhost:3000/socket.io/?EIO=3&transport=polling&t=LhugZIG&sid=0bb89442bbaa488da3e0dcb4ffca749b Failed to load resource: the server responded with a status of 400 (Bad Request)
http://localhost:3000/socket.io/?EIO=3&transport=polling&t=LhugZIb&sid=0bb89442bbaa488da3e0dcb4ffca749b Failed to load resource: the server responded with a status of 400 (Bad Request)
```

I'm logging `app.websocket_enabled` before and after adding the route, and python-socketio is successfully enabling the websocket.

**Comment by miguelgrinberg** [comment]
I have tested it just a few days ago, but given that this is unreleased software and everything was working. I actually contributed the websocket support myself, so I made sure everything was in order. But you are right, today, something appears broken.

Their master branch build is broken as well, so I'm not going to spend time on this until they straighten things out.

**Comment by dfee** [comment]
In that case, thanks for giving me a sanity check. And, I'm glad I alerted you to an integration check prior to the 0.5 release :)
