### ISSUE TITLE
I am trying to integrate rasa bot to a website and the auth error is coming

### ISSUE THREAD

**Issue by HarshMagiya7** [miguelgrinberg/python-socketio#852]
**Describe the bug**
<html>
	<body>
		"<div id="rasa-chat-widget" data-websocket-url="http://localhost:5005/"></div>"
		<script src="https://unpkg.com/@rasahq/rasa-chat" type="application/javascript"></script>
	</body>
</html>

The above code is available on rasa website which i am using to integrate the chatbot to a website
 
Rasa Version      :         2.8.16
Minimum Compatible Version: 2.8.9
Rasa SDK Version  :         2.8.3
Rasa X Version    :         None
Python Version    :         3.6.8
Operating System  :         Windows-10-10.0.19041-SP0
Python 3.6.8

connect async handler error
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\engineio\asyncio_server.py", line 423, in _trigger_event
    ret = await self.handlers[event](*args)
  File "c:\program files\python36\lib\site-packages\socketio\asyncio_server.py", line 519, in _handle_eio_connect
    return await self._handle_connect(sid, '/')
  File "c:\program files\python36\lib\site-packages\socketio\asyncio_server.py", line 419, in _handle_connect
    self.environ[sid])
  File "c:\program files\python36\lib\site-packages\socketio\asyncio_server.py", line 501, in _trigger_event
    ret = await self.handlers[namespace][event](*args)
TypeError: connect() missing 1 required positional argument: 'auth' 

this is the error i see on command prompt

and this error is shown in inspect
rasa-chat:2 
        
       GET http://localhost:5005/socket.io/?EIO=4&transport=polling&t=Nvdoisu net::ERR_CONNECTION_REFUSE
![Screenshot (19)](https://user-images.githubusercontent.com/97886782/149766165-bd949d4e-95dd-4a02-91ec-f6c219e42939.png)
D

**Comment by miguelgrinberg** [comment]
It seems your client is sending `auth` information with the connection request, so you must add an `auth` argument to your connect event handler to accept this data.

It appears I have not included proper documentation on this optional `auth` argument, which is fairly recent in the Socket.IO specification. I will add that.

**Comment by HarshMagiya7** [comment]
Hey sorry but I have not understood much from your comment 
I have added the image of the code as it was not visible in the text

**Comment by miguelgrinberg** [comment]
Your Python connect handler needs to have an `auth` argument.

**Comment by miguelgrinberg** [comment]
@HarshMagiya7 Maybe you don't realize this, but I'm the maintainer of the python-socketio package, so I can only assist from the side of that package. I can't possibly know how you can fix this from the client-side. Basically your client and your server aren't fully compatible. I gave you some pointers regarding a change that might help in the Python server, if you need help with the client then unfortunately I cannot help.

**Comment by HarshMagiya7** [comment]
Hey Sorry yes I understand 
Thanks for you help

**Comment by miguelgrinberg** [comment]
The documentation includes the `auth` parameter now. Closing.
