### ISSUE TITLE
AsyncClient fails where Client succeeds

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [miguelgrinberg/python-socketio#869]
I have a Flask app that is running flask_socketio (and a REST API using flask_smorest) and I can connect and receive messages using the following code:

```python
import socketio

sio = socketio.Client()

@sio.event
def connect():
    print('connection established')

@sio.on("projects")
def my_message(data):
    print('message received with ', data)

@sio.event
def disconnect():
    print('disconnected from server')

sio.connect('http://127.0.0.1:7524')
sio.wait()
```

This seems to work just fine, but I need it to be non-blocking. I was thinking about using a thread, but I noticed there is an `AsyncClient`, so I attempted that:

```python
import asyncio
import socketio

sio = socketio.AsyncClient(logger=True, engineio_logger=True)

@sio.event
async def connect():
    print('connection established')

@sio.on("projects")
async def my_message(data):
    print('message received with ', data)

@sio.event
async def disconnect():
    print('disconnected from server')

async def main():
    await sio.connect('http://localhost:7524')
    await sio.wait()

asyncio.run(main())
```

However, this fails, showing the following output:

```
Signal handler is unsupported
aiohttp not installed -- cannot make HTTP requests!
Traceback (most recent call last):
  File "C:\Users\Luke\Documents\temp1.py", line 27, in <module>
    asyncio.run(main())
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\Luke\Documents\temp1.py", line 24, in main
    await sio.connect('http://localhost:7524')
  File "C:\Users\Luke\Documents\repos\NymusApi\.venv\Lib\site-packages\socketio\asyncio_client.py", line 163, in connect
    raise exceptions.ConnectionError(
socketio.exceptions.ConnectionError: One or more namespaces failed to connect
```

I am quite confused by the `aiohttp not installed`, as I have verified that it is installed, but just to be sure I reinstalled all packages to a new virtual environment, but the error persists.

**Comment by miguelgrinberg** [comment]
First of all, the `Client` class is multithreaded. Instead of calling `sio.wait()`, you can just go on about your business on the main thread and everything will work just fine.

The `aiohttp` error I cannot explain. Try opening a shell and doing `import aiohttp`. That's what I do in the client, and if that raises an `ImportError` you end up with the error message in the log.

**Comment by Anti-Distinctlyminty** [comment]
Hi Miguel, thank you for reply so promptly. 
The `aiohttp` error was my fault - I added an incorrect path to `sys.path`.
I was unaware that I could just drop the `sio.wait()` and that `Client` is multithreaded so that is good to know. 
May I ask, is it recommended to the asyncio approach over multithreading? My use case is that I'm running this inside a `PySide2.QtObject` that is then moved to its own `QtThread`, and I am unsure if that could cause any complications.

**Comment by miguelgrinberg** [comment]
@Anti-Distinctlyminty there is no universal answer. I normally use async libraries when the base application is async, and regular ones for non-async apps. It is possible to mix sync with async if you are careful, but I prefer to avoid the complications of doing that.

**Comment by zhouhuirun2015** [comment]
same problem when use 5.11.1, namespaces should equals empty array: namespaces=[], besides, AsyncClient still crash:
![image](https://github.com/miguelgrinberg/python-socketio/assets/15274287/eb931e24-d756-4499-83ae-056969ec1edd)

**Comment by zhouhuirun2015** [comment]
> same problem when use 5.11.1, namespaces should equals empty array: namespaces=[], besides, AsyncClient still crash: ![image](https://private-user-images.githubusercontent.com/15274287/309950557-eb931e24-d756-4499-83ae-056969ec1edd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MDM2MjYsIm5iZiI6MTcwOTYwMzMyNiwicGF0aCI6Ii8xNTI3NDI4Ny8zMDk5NTA1NTctZWI5MzFlMjQtZDc1Ni00NDk5LTgzYWUtMDU2OTY5ZWMxZWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDAxNDg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyZTU2MjZjM2Y4NWM0YjgwY2FlZThkOWQ3ODAzN2JhMTA3ZDRiODdhYzdjYjY3NDZjYTkzMmYyMzQ3ZjU1OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BorG79I8Edf2TxOkqy5wfxzW0J_YwHAHKxWOXBle1qY)

it test ok when use python server/client, but crash when use python client5.11.1 and java server netty-socket.io 2.0.8
