### ISSUE TITLE
aioredis:Waiter future is already done <Future cancelled>

### ISSUE THREAD

**Issue by larry-dev** [miguelgrinberg/python-socketio#87]
write logics at the "disconnect".
sio.sleep(2) already is ok.
but aioredis not normal.

**Comment by miguelgrinberg** [comment]
When you report an error, please provide the full stack trace. That provides additional context that helps me in figuring out how the error occurred.

**Comment by larry-dev** [comment]
sorry,It has no more error messages.
here's my code.
`
def setup_socket_io(app):
    """
    socket.io初始化
    :param app: 项目上下文
    :return:
    """

    redis_address = str.format('redis://{}:{}/1', app['config']['redis']['host'], app['config']['redis']['port'])
    mgr = socketio.AsyncRedisManager(redis_address)
    sio = socketio.AsyncServer(async_mode='aiohttp', client_manager=mgr)

    sio.attach(app)

    user = UserLogic(app)
    game_logic = GameLogic(app)

    @sio.on('disconnect')
    async def disconnect(sid):
        result=await user.logout(sid)
        print(result,"==============")
`

`
class UserLogic:
    def __init__(self, app):
        self.app = app
        self.user = User(self.app)

    async def logout(self, sid):
        with await self.app['redis'] as redis:
            count = await redis.zcount(REDIS_KEY['RT_USER_ZSET_TIME'])
        return count
`

**Comment by miguelgrinberg** [comment]
The message that you are getting is not an error, it is a debug message. Is anything working incorrectly?

**Comment by larry-dev** [comment]
`print(result,"==============")`  is not work;
but i upgrade aiohttp2.0.1 and python-engineio1.3.1
it's all right now.
