### ISSUE TITLE
after using 'skip_id', i can't accept data

### ISSUE THREAD

**Issue by larry-dev** [miguelgrinberg/python-socketio#88]
```
sio.enter_room(sid, msg['Room'])
await sio.emit("join", ResultFactory(user_list, home_list, my_list, game, info.__dict__), room=sid)
await sio.emit('join', ResultFactory(info.__dict__), room=msg['Room'],skip_sid=sid)
```
This time ago can not receive any data.

**Comment by larry-dev** [comment]
![wx20170324-115339](https://cloud.githubusercontent.com/assets/18585750/24280059/c0aabd14-1088-11e7-9438-13c70072ba91.png)

remove 'skip_sid'
![wx20170324-115415](https://cloud.githubusercontent.com/assets/18585750/24280064/cdb0276a-1088-11e7-8df5-85522a97f445.png)

**Comment by larry-dev** [comment]
i want to notice everyone in the room except myself.
can i do?

**Comment by miguelgrinberg** [comment]
I can't reproduce this here. 

I took the `app.py` example in this repository (from the sanic folder), and added `skip_sid=sid` to room broadcasts. I see no problems here.

Can you provide a short example that reproduces this problem?

**Comment by larry-dev** [comment]
after using 'socketio.AsyncRedisManager(redis_address)' 

first open app.html is ok,but press "F5" refresh page. 
This time ago can not receive any data.

**Comment by larry-dev** [comment]
[归档.zip](https://github.com/miguelgrinberg/python-socketio/files/867214/default.zip)

**Comment by larry-dev** [comment]
Can you reproduce?

**Comment by miguelgrinberg** [comment]
Sorry, I'm doing too many things at once and I dropped the ball on this.

I just tested your example and was able to reproduce the problem. The error only occurs when you send a message to only one client, and also include that client in the skip_sid argument, which basically means nothing should be sent. This condition wasn't well handled in the code. I will have a fix up in a few minutes.

**Comment by miguelgrinberg** [comment]
@larry-dev Can I ask you to retest with release 1.7.4? Let me know if that still gives you problems.

**Comment by larry-dev** [comment]
@miguelgrinberg  I try to use '1.7.4'.  The problem has been solved.  thanks very much.
