### ISSUE TITLE
AsyncServer.start_background_task fails on aiohttp 3.8

### ISSUE THREAD

**Issue by ezio-melotti** [miguelgrinberg/python-socketio#881]
When running `AsyncServer.start_background_task` on `aiohttp` `3.8` (both `3.8.0` or `3.8.1`), the server fails with a `RuntimeWarning: coroutine 'background_task' was never awaited` error, but the same code works fine on `3.7.4`.

This is a minimal [reproducer based on the example in the repo](https://github.com/miguelgrinberg/python-socketio/blob/main/examples/server/aiohttp/app.py):
```py
import socketio

from aiohttp import web

sio = socketio.AsyncServer(async_mode='aiohttp')
app = web.Application()
sio.attach(app)

async def background_task():
    print('background_task called', flush=True)
    while True:
        print('emitting test-event and sleeping 1s...')
        await sio.emit('test-event', 'test')
        await sio.sleep(1)

if __name__ == '__main__':
    sio.start_background_task(background_task)
    web.run_app(app)
```

After installing `aiohttp` `3.7.4` with `pip install aiohttp==3.7.4`, the server works and the output is:
```
# python3 bgtask.py 
background_task called
emitting test-event and sleeping 1s...
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
emitting test-event and sleeping 1s...
```

After installing `aiohttp` `3.8.1` with `pip install aiohttp==3.8.1`, the server fails with the output:
```
# python3 bgtask.py 
/usr/local/lib/python3.9/abc.py:123: RuntimeWarning: coroutine 'background_task' was never awaited
  return _abc_subclasscheck(cls, subclass)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Task was destroyed but it is pending!
task: <Task pending name='Task-1' coro=<background_task() running at /bgtask.py:9>>
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
```

I'm not sure if this is an issue with `python-socketio` or a bug in `aiohttp` itself.  Regardless, I thought it would be useful to report it here since other `python-socketio` users might run in the same problem.

`aiohttp` `3.8` might have introduced a backward incompatible change that requires an update to `python-socketio`. If you can verify that this is indeed an issue with `aiohttp`, and possibly even figure out the cause of the problem, we can then report it upstream.

This was tested with `python-socketio` `5.5.2` on Python 3.9.10.

**Comment by miguelgrinberg** [comment]
Have you considered that this might be your own issue? You are launching an async function before the web framework, which controls the async loop is created. More than likely aiohttp is creating their own loop, so the default loop used when you started the task goes away and that causes the message that you are seeing.

**Comment by ezio-melotti** [comment]
Thanks for the quick reply!  That might explain why it's not working, however there are still three issues:
* `web.run_app(app)` is blocking, so the `start_background_task` call can't be moved afterwards.
* The same code work fine with `aiohttp` `3.7`, so either `python-socketio` is not compatible with `3.8` and should be updated, or `3.8` introduced a bug that they should fix.
* If it's not a bug with `3.8`, [the example I followed for the reproducer](https://github.com/miguelgrinberg/python-socketio/blob/main/examples/server/aiohttp/app.py#L82-L83) is no longer valid for `3.8` and should be updated.

**Comment by miguelgrinberg** [comment]
Yes, I agree, that example needs to be updated so that it is compatible with the newer aiohttp. I'll look into that.

**Comment by miguelgrinberg** [comment]
This is actually the change in aiohttp that relates to this: https://github.com/aio-libs/aiohttp/pull/5572

**Comment by miguelgrinberg** [comment]
The solution is to use an application factory function to start the background task:

```python
async def init_app():
    sio.start_background_task(background_task)
    return app

if __name__ == '__main__':
    web.run_app(init_app())
```

**Comment by ezio-melotti** [comment]
Thanks!  I verified that this solution works with `aiohttp` version `3.8.1`, `3.8.0`, and `3.7.4`.
