### ISSUE TITLE
Disconnect event not triggered

### ISSUE THREAD

**Issue by dfee** [miguelgrinberg/python-socketio#89]
I'm using the polling method exclusively (a limitation of Sanic v0.4), and I'm not seeing disconnect events when I "turn off" my brower's connection or call `socket.disconnect()` in the browser. I'm also not able to get disconnect working from the server side (though the debug message print).

```
import socketio

sio = socketio.AsyncServer(async_mode='sanic')

@sio.on('disconnect_me', namespace='/api')
async def disconnect(sid, message):
    print('disconnecting you')
    sio.manager.disconnect(sid, '/api')

@sio.on('disconnect', namespace='/api')
def disconnect(sid):
    print('disconnecting')
    sio.registry.manager.unregister_session(sid)
```

Is this because the session is polling? Or, am I doing something wrong?

**Comment by dfee** [comment]
Ah, I believe it's because `disconnect` needs to be an async method.

**Comment by miguelgrinberg** [comment]
Yes. The disconnect method is async, so you need to await it.

Regarding receiving a disconnect when the client closes the browser, note that when long polling is used, the server does not immediately detect disconnects, it will instead wait for a while and declare the client disconnected when it does not receive any requests in a while (typically 60 seconds, but this can be changed in the `AsyncServer` constructor.

Also note that you will get WebSocket support if you use the current master branch of sanic.

**Comment by dfee** [comment]
I still can't seem to get the `sio.manager.disconnect(sid, namespace)` bit to work, but that's of less interest to me now (I was using it for debugging).

As for websocket support on master: thanks for the heads up. I'll wait until a stable is released though, because I want to pin to a version for release.

**Comment by miguelgrinberg** [comment]
Oh, yeah, that's not right. Use `await sio.disconnect(sid)`. There shouldn't be a need for you to call methods in the manager object, those are used internally.

**Comment by dfee** [comment]
How would I disconnect the socket on the server side then?

**Comment by dfee** [comment]
Nevermind, I see that it'd just be `sio.disconnect(sid, namespace)` not `sio.manager.disconnect(sid, namespace)`

**Comment by miguelgrinberg** [comment]
What I said above:

```python
@sio.on('disconnect_me', namespace='/api')
async def disconnect(sid, message):
    print('disconnecting you')
    sio.disconnect(sid, namespace='/api')
```
