### ISSUE TITLE
No way to set custom event id

### ISSUE THREAD

**Issue by Diniboy1123** [miguelgrinberg/python-socketio#891]
**Describe the bug**
I would expect that `emit()` accepts a packet id param that can define the packet's id. The message I would need to send starts with `42["` within my browser, but with python-socketio its always 2 instead of 42 and I couldn't figure out a way to pass my own value:

`Sending packet MESSAGE data 2["`

**To Reproduce**
Not much to add here, docs doesn't suggest that this feature exists

**Expected behavior**
I would expect such param to exist.

**Logs**
Not relevant to my setup, general issue.

**Additional context**
Not relevant.

**Comment by miguelgrinberg** [comment]
@Diniboy1123 Is anything broken? You seem to have a misunderstanding regarding how this package works. This is a high-level package, you do not need to know or worry about how messages are encoded, all that is done for you. If you are interested in encoding your own messages, then use a plain WebSocket server or client and write your own encoded messages on it to communicate with the other party.

Also, I suggest you read the Engine.IO and Socket.IO protocols if you are interested in understanding the internals of Socket.IO. The "4" that you claim is missing is the `MESSAGE` constant printed in the log that you shared. This is defined in the Engine.IO protocol, not Socket.IO.

**Comment by Diniboy1123** [comment]
Yeah, I am sorry, I figured. I also figured that it's coming from engine.io logging. Though the message ID is definitely not what the original browser client sends and thus the message is not being interpreted. I will investigate further.
