### ISSUE TITLE
Logic for reconnect delay looks incorrect

### ISSUE THREAD

**Issue by c0state** [miguelgrinberg/python-socketio#893]
**Describe the bug**

The delay logic `delay += self.randomization_factor * (2 * random.random() - 1)` at https://github.com/miguelgrinberg/python-socketio/blob/1fb7a76575426dd58a5e9c0e01646302ccc96188/src/socketio/asyncio_client.py#L465 seems incorrect, both for the async and non-async clients. 

`2 * random.random() - 1` could be negative, which would result in *reducing* the delay.

**To Reproduce**
n/a

**Expected behavior**
The delay should only increase, not decrease.

**Logs**
From one of our clients that utilize this library.
```
Mar 15 18:09:55 python3[354]: Connection failed, new attempt in 1.24 seconds
Mar 15 18:09:55 python3[354]: INFO:socketio.client:Connection failed, new attempt in 1.24 seconds
Mar 15 18:09:55 python3[354]: Engine.IO connection dropped
Mar 15 18:09:55 python3[354]: INFO:socketio.client:Engine.IO connection dropped
Mar 15 18:09:55 python3[354]: DEBUG:__main__:on_disconnect
Mar 15 18:09:55 python3[354]: Connection failed, new attempt in 1.24 seconds
Mar 15 18:09:55 python3[354]: INFO:socketio.client:Connection failed, new attempt in 1.24 seconds
Mar 15 18:09:55 python3[354]: packet queue is empty, aborting
Mar 15 18:09:55 python3[354]: ERROR:engineio.client:packet queue is empty, aborting
Mar 15 18:09:55 python3[354]: Engine.IO connection dropped
Mar 15 18:09:55 python3[354]: INFO:socketio.client:Engine.IO connection dropped
Mar 15 18:09:55 python3[354]: DEBUG:__main__:on_disconnect
Mar 15 18:09:55 python3[354]: Connection failed, new attempt in 0.91 seconds
Mar 15 18:09:55 python3[354]: INFO:socketio.client:Connection failed, new attempt in 0.91 seconds
Mar 15 18:09:55 python3[354]: packet queue is empty, aborting
Mar 15 18:09:55 python3[354]: ERROR:engineio.client:packet queue is empty, aborting
Mar 15 18:09:55 python3[354]: Engine.IO connection established
Mar 15 18:09:55 python3[354]: INFO:socketio.client:Engine.IO connection established
Mar 15 18:09:55 python3[354]: Reconnection successful
```

**Additional context**
n/a

**Comment by miguelgrinberg** [comment]
What are the values of `reconnection_delay` and `randomization_factor` that you are using?

**Comment by c0state** [comment]
> What are the values of `reconnection_delay` and `randomization_factor` that you are using?

We're using the defaults. But irrespective of that, the delay logic is potentially incorrect no? Unless I'm misreading things...

**Comment by miguelgrinberg** [comment]
The expression that you highlighted can be negative. That is by design. With default values, that is going to be a random value between -0.5 and +0.5, which is added to the delay, which is 1 for the first retry and doubles there after.

So I think it should go as follows:

- first retry will have a delay of 0.5 to 1.5.
- second retry will be between 1.5 and 2.5.
- third retry will be between 3.5 and 4.5.
- fourth and subsequent retries will delay between 4.5 and 5.5 (the max delay caps at 5)

I don't understand why your delays aren't doubling. Any idea why?

**Comment by c0state** [comment]
Ah OK I see, I misread the logic before. I believe it's not doubling because of the issue I alluded to above. The server is dropping the connection so the python-socketio client is trying again a new and thus uses a timeout in the 0.5 - 1.5 second range.

**Comment by c0state** [comment]
Actually, I take it back. It doesn't look like our app crashed but it looks like it tried to connect again from scratch instead of going through the reconnect logic. I think that's essentially why the delay didn't "double" in the log snippet above. We're using a node based server with socket io 2.x with v4.x of this library (or whatever Ubuntu LTS focal supplies). Hard to tell what caused this but I think it's some latent bug due to the older server version.

**Comment by miguelgrinberg** [comment]
How can I reproduce this here?

**Comment by c0state** [comment]
> How can I reproduce this here?

I'll report back if we find out more but it's been hard to pinpoint on our end.
