### ISSUE TITLE
pin aio-pika

### ISSUE THREAD

**Issue by dimastbk** [miguelgrinberg/python-socketio#897]
In aio-pika, sync context manager of Incoming Message was deprecated in 5.0.0 (mosquito/aio-pika#193) and was removed in 7.0.0 (mosquito/aio-pika#436).

Maybe pin aio-pika<7 or change [asyncio_aiopika_manager.py#L96](https://github.com/miguelgrinberg/python-socketio/blob/main/src/socketio/asyncio_aiopika_manager.py#L96) to use an async context manager and pin aio-pika>=5.

**Comment by miguelgrinberg** [comment]
I would prefer to update the code to work with the latest version of this dependency. Would you like to submit a PR with this change?
