### ISSUE TITLE
Upgrade to bidict 0.22 to benefit from huge performance boost

### ISSUE THREAD

**Issue by danlg** [miguelgrinberg/python-socketio#905]
In order to benefit from the huge performance improvement of bidict in version 0.22 which is key to python-socketio server for broadcasting messaging, it would be worth upgrading to bidict version 0.22 https://bidict.readthedocs.io/en/main/changelog.html
It will mean the end of support for Python 3.6, which reached end of life on 2021-12-23.
__
Optimize updating an empty bidict with another bidict. In a microbenchmark on Python 3.10, this now performs 60-75% faster.

Optimize [copy()](https://bidict.readthedocs.io/en/main/api.html#bidict.BidictBase.copy). In a microbenchmark on Python 3.10, this now performs 10-20x faster.

Optimize rolling back [failed updates to a bidict](https://bidict.readthedocs.io/en/main/basic-usage.html#updates-fail-clean) in the case that the number of items passed to the update call can be determined to be larger than the bidict being updated. Previously this rollback was O(n) in the number of items passed. Now it is O(1), i.e. unboundedly faster.

Optimize [bidict.BidictBase.__contains__()](https://bidict.readthedocs.io/en/main/api.html#bidict.BidictBase.__contains__) (the method called when you run key in mybidict). In a microbenchmark on Python 3.10, this now performs over 3-10x faster in the False case, and at least 50% faster in the True case.

Optimize [bidict.BidictBase.__eq__()](https://bidict.readthedocs.io/en/main/api.html#bidict.BidictBase.__eq__) (the method called when you run mybidict == other). In a microbenchmark on Python 3.10, this now performs 15-25x faster for ordered bidicts, and 7-12x faster for unordered bidicts.

Optimize [equals_order_sensitive()](https://bidict.readthedocs.io/en/main/api.html#bidict.BidictBase.equals_order_sensitive). In a microbenchmark on Python 3.10, this now performs 2x faster for ordered bidicts and 60-90% faster for unordered bidicts.

Optimize the [MappingView](https://docs.python.org/3/library/collections.abc.html#collections.abc.MappingView) objects returned by [bidict.OrderedBidict.keys()](https://bidict.readthedocs.io/en/main/api.html#bidict.OrderedBidict.keys), [bidict.OrderedBidict.values()](https://bidict.readthedocs.io/en/main/api.html#bidict.OrderedBidict.values), and [bidict.OrderedBidict.items()](https://bidict.readthedocs.io/en/main/api.html#bidict.OrderedBidict.items) to delegate to backing dict_keys and dict_items objects if available, which are much faster in CPython. For example, in a microbenchmark on Python 3.10, orderedbi.items() == d.items() now performs 30-50x faster.
__

**Comment by miguelgrinberg** [comment]
Did bidict introduce breaking changes with this upgrade that they released? Because this package needs to change only if they did. In that case, would you be willing to submit the required changes in a PR? Thanks.
