### ISSUE TITLE
Multiple Listeners for Single Event

### ISSUE THREAD

**Issue by StormSurge95** [miguelgrinberg/python-socketio#906]
In the javascript version of socketio, it is possible to set multiple listeners to the same socket event; as well as setting a listener to only respond to an event once. I think it'd be nice to reflect this feature within python if at all possible.

**Comment by miguelgrinberg** [comment]
This creates some unpredictability that I prefer to avoid. For example: do all the handlers for an event run in parallel? Do they run one after another? In which order?

If you implement this yourself by having a single event handler that calls all these actions you want to happen, then you have full control and can implement the concurrency model explicitly. I'm not saying I'm full against it, but there needs to be a Pythonic solution for this feature to be included.

**Comment by StormSurge95** [comment]
Ah I hadn't thought about the unpredictability. Imo the best solution would be a complete mimicry of the nature of how javascript operates multiple listeners; however, I have no idea how it does that so I can't really offer a good solution in that regard.

**Comment by miguelgrinberg** [comment]
I disagree. JavaScript does things in a way that is familiar to JavaScript developers. I do not know to alienate Python developers by making this project too JAvaScripty.

I mean, in JavaScript there is a very well established tradition of setting up event listeners, you can add and remove at any time, and as you pointed out, also have multiple handlers. Python does not have any of this. I've decided to take a Pythonic approach and use decorated event handlers, which is the most familiar pattern in this language for event handlers.

**Comment by StormSurge95** [comment]
That makes sense. I'm still extremely amateur when it comes to developing full-scale projects like this. The only other solution I can think of would be to allow functionality of lists of handlers; and then have them operate in whatever order they are in the list. If an event passes data, that data is provided to each handler in the list for that particular event. For the regular client, handlers could operate one after another; and for the async client, handlers could be async and started one after another and operate conurrently. I'm sure there's issues I can't think of with this solution; but maybe it would work (or at the very least be something I could do myself as you suggested earlier).

**Comment by miguelgrinberg** [comment]
I think the majority of cases can be handled with a single event handler that does all the things that you want to do:

```python
@sio.event
def my_event(data):
    do_thing_1()
    do_thing_2()
    do_thing_3()
```

Is this solution insufficient for your needs?

**Comment by StormSurge95** [comment]
Just a slight bit. The issue is that I I may need `do_thing_1()` to happen every time while I only need `do_thing_2()` to happen when I first start and only need `do_thing_3()` after a specific type of request. I did find a bit of a workaround though by simply having all of my handlers be within scope of the class at large (as opposed to within scope of a single function) and setting/resetting handlers as necessary. It may not be super efficient, but at least it works (so far).

**Comment by miguelgrinberg** [comment]
This package does not have the ability to remove handlers either. Another thing that is very familiar to JavaScript developers, but unusual in Python.

**Comment by miguelgrinberg** [comment]
@vpmartin you can easily implement this in your application using the observer pattern. There are many implementations of this pattern available for Python.
