### ISSUE TITLE
can you use this without all the webserver stuff?

### ISSUE THREAD

**Issue by LoganDark** [miguelgrinberg/python-socketio#94]
I want to run the socket.io server by itself without a webserver.

**Comment by miguelgrinberg** [comment]
A Socket.IO server is a web server, it works on the same protocols as a regular web server (HTTP and WebSocket).

You don't need to create regular HTTP routes if you don't want to, but you do need the server component to run the Socket.IO logic.

**Comment by LoganDark** [comment]
I just want to do for example connecting to the server and communicating, no webpages or anything

**Comment by miguelgrinberg** [comment]
That's fine, all you need is a Socket.IO client, and there are clients for pretty much any language.

**Comment by LoganDark** [comment]
you misunderstand my intention

i mean running a SERVER BY ITSELF where absolutely nothing is running except socketio server, no webpages or anything

**Comment by miguelgrinberg** [comment]
A server running by itself does nothing. You need clients that connect and communicates with the server. What kind of client are you thinking in using? This has nothing to do with HTML/CSS/JavaScript, I'm asking about Socket.IO client here.

**Comment by LoganDark** [comment]
FFS!

I'm going to run a server, and use a client in a STANDALONE SEPARATE APP to connect to it remotely????

What does it take to make you understand?

**Comment by LoganDark** [comment]
(no offense)

**Comment by LoganDark** [comment]
like a server without the middleware or whatever it's called. throw flask out and use the server by itself, how do I do that?

**Comment by LoganDark** [comment]
how would I do it? (I know how to set up the client I mean the server).

**Comment by miguelgrinberg** [comment]
Can you answer my question, please? What Socket.IO client do you plan on using?

And BTW, what does Flask have to do with this? Where did I talk about Flask? That's not even a dependency of this package.

**Comment by LoganDark** [comment]
@miguelgrinberg idk why I said flask, I saw it somewhere related to here.

anyway, what does the client have to do with this? i'm using the official socket.io one,for webpages

**Comment by LoganDark** [comment]
yeah, here https://github.com/miguelgrinberg/python-socketio/pull/91

**Comment by miguelgrinberg** [comment]
The examples use Flask, aiohttp, or sanic to serve the client application to the web browser. You clearly don't need that, so if you use one of those examples to start from, just delete all the stuff that serves HTML and JavaScript to the client.

To initialize this package without having a web framework do it as follows:

    sio = socketio.Server()
    app.wsgi_app = socketio.Middleware(sio)

**Comment by LoganDark** [comment]
`app` is the most ambiguous variable I've ever seen without any imports.

**Comment by miguelgrinberg** [comment]
Then go ahead and change it on your application. I won't be mad.

**Comment by LoganDark** [comment]
What are you changing though? Does it have to be in some object named `app`, if so, what do I import? :(

I have no idea what to do here, your code can't be run by itself and I don't know what to add.

**Comment by miguelgrinberg** [comment]
You are not really being very clear, I'm having a hard time understanding what the problem is. In the example above, `app` is a variable. You can call it `my_app`, or whatever else you want. It's not an import, that's your WSGI application,

**Comment by LoganDark** [comment]
WSGI application? Is that a socketio thing? What do I import to get a WSGI application?

**Comment by LoganDark** [comment]
Can you give me complete code instead of a snippet, because I have no idea what to do with that snippet you gave me.

**Comment by miguelgrinberg** [comment]
WSGI is a Python standard for web applications. The snippet I gave you is how you would modify one of the examples in this repository (in the examples/wsgi directory) to not have a dependency on Flask.

**Comment by blunket** [comment]
As general advice for success in life, @LoganDark I'm not sure why you'd be replying as if the person you're asking for help is an idiot...

**Comment by LoganDark** [comment]
Sorry.
