### ISSUE TITLE
One more "packet queue is empty" (probably network-related)

### ISSUE THREAD

**Issue by aboev** [miguelgrinberg/python-socketio#940]
**Describe the bug**
After a (suspected) network problem, AsyncClient fails to reconnect properly:
- AsyncClient thinks it re-connected,
- Server thinks that AsyncClient disconnected,
- AsyncClient throws "packet queue is empty" without throwing "disconnect" event or exception

**To Reproduce**
Hard to reproduce, it happened 2-3 times during several months.
Still trying to find steps to reproduce in a stable manner.

**Expected behavior (in my understanding)**
- AsyncClient should throw "disconnect" event
- AsyncClient should raise exception when "packet queue is empty" occurs 

**Logs**
Due to very rare occurrence, I could not gather engineio_logger logs, but I have application logs:
Client logs
```
[04:54:35] Disconnected from Server
[04:54:44] Connected to Server
packet queue is empty, aborting
```

Server logs
```
[04:54:30] Disconnect from Client
[04:55:10] New connect from Client
[04:55:55] Disconnect from Client
```

**Additional context**
Server versions:
python-engineio==4.3.1
python-socketio==5.5.2

Client versions
python-engineio==4.3.2
python-socketio==5.6.0

The client is running on a different physical network via internet.
Also, I am simultaneously running another AsyncClient on the same local network as Server - there is absolutely no impact to the second client.

**Comment by miguelgrinberg** [comment]
The logs that you are providing are insufficient. First of all, you are showing mostly logs that your own application produces, without any of the regular logging output from the engineio and socketio packages. All the output needs to be included. Second, based on the `sid`, it should be possible to track a client, both in the client and the server logs, seeing the connection, disconnection and anything that happened in between.

**Comment by aboev** [comment]
Ok, finally I managed to reproduce the problem in a controlled manner.
While running the code below, I periodically blocked network traffic between Client and Server.
At some point, client thinks it managed to reconnect (see line 85 in client.log), but in fact there is no connection.

Server code:
```python
import socketio
from aiohttp import web

sio = socketio.AsyncServer(logger=True)
app = web.Application()
sio.attach(app)

@sio.on('connect')
async def connect(sid, environ):
    print('%s connected' % sid)

@sio.on('msg')
async def msg(sid, data):
    print(data)

@sio.on('disconnect')
async def disconnect(sid):
    print('%s disconnected' % sid)

if __name__ == '__main__':
    web.run_app(app)
```
Client code:
```python
import socketio
from aiohttp import web

sio = socketio.AsyncServer(logger=True)
app = web.Application()
sio.attach(app)

@sio.on('connect')
async def connect(sid, environ):
    print('%s connected' % sid)

@sio.on('msg')
async def msg(sid, data):
    print(data)

@sio.on('disconnect')
async def disconnect(sid):
    print('%s disconnected' % sid)

if __name__ == '__main__':
    web.run_app(app)
(venv) root@express:/data/dev/socket-test# cat client.py 
import asyncio
import socketio

sio = socketio.AsyncClient(logger = True, engineio_logger=True)

@sio.on('connect')
async def connect():
    print('connected')

@sio.on('disconnect')
async def disconnect():
    print('disconnected from server')

async def main():
    while True:
        try:
            if sio.connected:
                await asyncio.sleep(5)
            else:
                await sio.connect('http://127.0.0.1:8080')
        except:
            pass

if __name__ == '__main__':

    loop = asyncio.get_event_loop()
    result = loop.run_until_complete(main())
```
Logs:
[client.log](https://github.com/miguelgrinberg/python-socketio/files/8974690/client.log)
[server.log](https://github.com/miguelgrinberg/python-socketio/files/8974691/server.log)

I guess the problem is caused by `await sio.connect()` inside while loop, right?

**Comment by aboev** [comment]
What I mean by

> in fact there is no connection

network link is restored, client switched backed to connected state (`sio.connected == True`), but the server does not receive any messages and considers client as disconnected.

**Comment by miguelgrinberg** [comment]
If you are going to implement your own reconnection logic, then you should disable the reconnections that are carried out internally. You can't have both the internal reconnection thread and your loop calling connect at the same time.

**Comment by aboev** [comment]
> You can't have both the internal reconnection thread and your loop calling connect at the same time.

Thanks, I didn't know that!
