### ISSUE TITLE
Django Admin CSS doesn't show up when using python-socketio

### ISSUE THREAD

**Issue by MK272008** [miguelgrinberg/python-socketio#943]
**Describe the bug**
Although I have integrated python-socketio successfully with Django (using gevent), the Django Admin's CSS doesn't load whenever I open it.

**To Reproduce**
1. Integrate python-socketio with Django using `eventlet` or `gevent`
2. Open the django admin

**Expected behavior**
Django admin should have remained the same as it was before integrating socketio

**Logs**
```
Not Found: /static/admin/css/base.css
127.0.0.1 - - [24/Jun/2022 15:00:33] "GET /static/admin/css/base.css HTTP/1.1" 404 2737 0.004986
Not Found: /static/admin/css/nav_sidebar.css
127.0.0.1 - - [24/Jun/2022 15:00:33] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 404 2758 0.002973
Not Found: /static/admin/js/nav_sidebar.js
127.0.0.1 - - [24/Jun/2022 15:00:33] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 404 2752 0.002992
Not Found: /static/admin/css/dashboard.css
127.0.0.1 - - [24/Jun/2022 15:00:33] "GET /static/admin/css/dashboard.css HTTP/1.1" 404 2752 0.002991
Not Found: /static/admin/css/responsive.css
127.0.0.1 - - [24/Jun/2022 15:00:33] "GET /static/admin/css/responsive.css HTTP/1.1" 404 2755 0.002992
```

**Comment by MK272008** [comment]
Yes, this is the code:
```
import os
import socketio
import eventlet

from django.core.wsgi import get_wsgi_application
from messaging.views import sio

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "server.settings")

django_app = get_wsgi_application()
application = socketio.WSGIApp(sio, django_app)

eventlet.wsgi.server(eventlet.listen(('', 8000)), application)
```

**Comment by miguelgrinberg** [comment]
@MK272008 Have you configured your static files root appropriately? The code looks correct, my only guess is that you haven't created a static files directory and collected your files on it.

**Comment by MK272008** [comment]
I had already tried that, but it also doesn't work.
Btw i fixed the issue. I made some changes to it and it worked.
```
import os
from django.core.wsgi import get_wsgi_application
import socketio
import eventlet
import eventlet.wsgi
from django.contrib.staticfiles.handlers import StaticFilesHandler
from messaging.views import sio

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "server.settings")
django_app = StaticFilesHandler(get_wsgi_application())
application = socketio.Middleware(sio, wsgi_app=django_app, socketio_path='socket.io')

eventlet.wsgi.server(eventlet.listen(('', 8000)), application)
```

**Comment by miguelgrinberg** [comment]
My understanding is that the `StaticFilesHandler` is used by the development server, to avoid having to collect the static files in the static root directory. This actually confirms what I was saying, your static file configuration is incorrect.

**Comment by MK272008** [comment]
Thanks for helping me by spending your precious time. Really mean that.
