### ISSUE TITLE
async and thread/process executor delays emit responses

### ISSUE THREAD

**Issue by lmk-savvi** [miguelgrinberg/python-socketio#95]
Hi there,

I have this code which is run during a handler for an event:

```
    async def run_blocking_task(self, method=None, fn=None, *args, **kwargs):
        if method is None:
            method = 'process'
        if fn is None:
            log.error("No function passed to `run_blocking_task`!")
            return None
        executor = self.executors.get(method)
        loop = asyncio.get_event_loop()
        func = partial(fn, *args, **kwargs)
        return await loop.run_in_executor(executor, func)
```

From the code that calls it:

```
executor = query_config.get('executor')
r = await self.run_blocking_task(executor, query_handler, query, params, sid=sid, typ=typ, query_config=query_config)
await reply(resp)
```

I am finding that other events are handled and replies are made (at least according to the logs), however they do not arrive back at the socket.io client(s) until the task that is run via the executor has finished!

I would appreciate some help with this, thanks in advance :-)

**Comment by miguelgrinberg** [comment]
I'm not sure I understand what the problem is.

If you have something like this:

    r = await self.run_blocking_task(executor, query_handler, query, params, sid=sid, typ=typ, query_config=query_config)
    await sio.emit('foo', my_data)

This "foo" event will not go out to the client until the task running in the executor completes. That's perfectly normal. If you want to start the task in the executor, without blocking the remaining of your event handler, then do it like this:

    loop.call_soon(functools.partial(self.run_blocking_task, executor, query_handler, query, params, sid=sid, typ=typ, query_config=query_config))
    await sio.emit('foo', my_data)

Hope this helps. If the problem is not this, then please give me more details.

**Comment by lmk-savvi** [comment]
Hi Miguel,

Thanks for the reply. I'm okay with the delayed response, however the issue I was having was that other responses from other events were also not arriving at the socket.io client(s), until I did something like:

```
    # Run the potentially long-running operation and response in a task
    async def reply_task():
            try:
                query_handler = query_config['handler']

                is_blocking = query_config.get('blocking', True)
                if not is_blocking:
                    r = query_handler(query, params, sid=sid, typ=typ, query_config=query_config)
                else:
                    executor = query_config.get('executor')
                    r = await self.run_blocking_task(executor, query_handler, query, params, sid=sid, typ=typ, query_config=query_config)
                resp = {"ctx": ctx, "type": "success", "data": r}
            except Exception as error:
                log.exception("Exception")
                await reply({"ctx": ctx, "type": "fail", "error": "error running query", "reason": str(error)})
            else:
                await reply(resp)

        # we must split the possible long running query and reply into a separate task, otherwise SIO responses are delayed to the client.
        task = asyncio.get_event_loop().create_task(reply_task())
        
        # end of function
```

**Comment by miguelgrinberg** [comment]
I see. I think I understand now. Each client has a single event queue. Events from the queue are processed one after another. If one event takes very long, then the events that come after it will be delayed. Sounds like this is the problem you wanted to avoid.

For the eventlet/gevent servers, I've added the `async_handlers=True` option when you create the `Server` object, which basically runs all event handlers in separate threads. This can sometimes cause race conditions and other problems, but on the other side, allows any handler to run for as long as it wants, and other events are processed regardless of that.

I'll keep this issue open as a remind to add `async_handlers` to the Asyncio server.

**Comment by lmk-savvi** [comment]
Hi Miguel,

Thanks for the explanation, looks like I'll have to keep the work-around for the time being!

Cheers,
Lucas
