### ISSUE TITLE
C# how to call Python socket IO interface

### ISSUE THREAD

**Issue by zhuya1996** [miguelgrinberg/python-socketio#953]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Logs**
Please provide relevant logs from the server and the client. On the Python server and client, add the `logger=True` and `engineio_logger=True` arguments to your `Server()` or `Client()` objects to get logs dumped on your terminal. If you are using the JavaScript client, see [here](https://socket.io/docs/logging-and-debugging/) for how to enable logs.

**Additional context**

**Comment by miguelgrinberg** [comment]
I don't use the C# client, so I cannot give you advice on it. Maybe ask the maintainers of the client that you are using.
