### ISSUE TITLE
Does it only support Python client connection? How do other programming languages connect

### ISSUE THREAD

**Issue by zhuya1996** [miguelgrinberg/python-socketio#954]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Logs**
Please provide relevant logs from the server and the client. On the Python server and client, add the `logger=True` and `engineio_logger=True` arguments to your `Server()` or `Client()` objects to get logs dumped on your terminal. If you are using the JavaScript client, see [here](https://socket.io/docs/logging-and-debugging/) for how to enable logs.

**Additional context**

**Comment by miguelgrinberg** [comment]
You can use any client that you like. Can I ask to stop writing issues on this package? If you have a question use the discussion board. Thanks.
