### ISSUE TITLE
Retro compatibility python 3.6 lost after update 5.7 

### ISSUE THREAD

**Issue by rodolfosouza** [miguelgrinberg/python-socketio#959]
just for information:

After this commit, the retro compatibility from 3.6 was lost
https://github.com/miguelgrinberg/python-socketio/commit/4b697815c3da4574fca8b759d21a4e0800dafc50

ERROR: module 'asyncio' has no attribute 'create_task'"

**Comment by miguelgrinberg** [comment]
I'm not supporting 3.6 anymore. See the change log for details.
