### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by jusce17** [miguelgrinberg/python-socketio#976]
**How to Install**
The current [documentation ](https://python-socketio.readthedocs.io/en/latest/intro.html)does not point how to install it and might be confused for newcomers 

**Required packages**
In the current documentation, in the [example section](https://python-socketio.readthedocs.io/en/latest/intro.html#server-examples) if a beginner is following it, he/she will face `ModuleNotFoundError` errors for the docs uses modules that weren't previous marked has required.

**Suggestion**

Perhaps before/after the Version compatibility we could show what it takes to have it up and running (a.k.a the requirements)

TIA

**Comment by miguelgrinberg** [comment]
There is installation documentation already. You must have missed it.

https://python-socketio.readthedocs.io/en/latest/client.html#installation
https://python-socketio.readthedocs.io/en/latest/server.html#installation

**Comment by jusce17** [comment]
Awesome @miguelgrinberg ,

I started reading from[ Getting Started Page](https://python-socketio.readthedocs.io/en/latest/intro.html#) and the examples show up before the links you just sent. Thanks.

I will close this  then, but would be nice if we could throw some docstring in the functions just to clarify them (even more). 😀
