### ISSUE TITLE
Client  doesn't receive emits from Thread

### ISSUE THREAD

**Issue by ivellios** [miguelgrinberg/python-socketio#99]
Is this package Thread-safe? I have code like:

```python
# in controller.py file
class Controller():
    def run_me(self):
        self.sio.emit('log', data = "Starting game")
        return

    def __init__(self, sio):
        self.sio = sio

    def startThread(self):
        t = threading.Thread(target = self.run_me, )
        t.start()
        return t

# app.py file
sio = socketio.Server(logger=True)
rc = Controller(sio)

@sio.on('ping')
def ping(sid):
    sio.emit('pong', data = "PING_PONG")

@sio.on('start')
def startGame(sid):
    #sio.emit('log', data = 'Going into thread') # that makes emit in thread working, but without this it gets broken.
    rc.startThread()
```

And in client there's a simple:
```javascript
  $('#start').click(function(e){
    e.preventDefault();
    socket.emit('start');
  });

  socket.on('pong', function(a) {
    console.log(a);
  });

  socket.on('log', function(a) {
    console.log(a);
  });
```

When I use PING in client, it logs in cosole PING_PONG. But when I emit `start` it doesn't emit log to client. And there's more: ping stops working too. In my server sio logs, there's info, that the messages are sent, but client seems not receiving it. 

Is it possible, that Thread is somehow breaking the connection?

Also: If I uncomment the line of emit before starting thread, it works fine SOMETIMES. Right now it does not. 

I have also tried to have run_me as a separate function and pass sio as an argument:

```python
def run_me(sio):
    sio.emit('log', data = "Starting game")
    return

class Controller():
    def __init__(self, sio):
        self.sio = sio

    def startThread(self):
        t = threading.Thread(target = run_rooms, args = [self.sio])
        t.start()
        return t
```
But the result is the same...

**Comment by ivellios** [comment]
Do you have any working example of sio working inside Threads?

**Comment by ivellios** [comment]
So what worked for me was switching to threading mode as documented here:
http://python-socketio.readthedocs.io/en/latest/#standard-threading-library

I was using `eventlet` before.

**Comment by miguelgrinberg** [comment]
If you are using eventlet, you have to use green threads. Regular threads are not compatible. To make matters easy, I have included a `start_background_thread` function, that starts your thread using the appropriate mode, according to the selected async mode.

Using threading is not a good solution. Performance is not that great, because there is no websocket support. I would look into making things work with either eventlet or gevent.

**Comment by ivellios** [comment]
@miguelgrinberg - thanks for explanation. Are you able to provide simple example with `start_background_thread` so I know how to use it properly?

**Comment by miguelgrinberg** [comment]
Here is one: https://github.com/miguelgrinberg/python-socketio/blob/master/examples/wsgi/app.py#L31

**Comment by ivellios** [comment]
Well, it doesn't seem to work with `eventlet`. When I start it with `threading` mode and `start_background_task` it works fine. But with `eventlet` sio in threaded task  communicate with server via socket, but again it seems not to emit to my website - event though debug says so. In my console logs no evidence of that.

I have my Controller in separate file, so I create it, pass sio, then set it as an argument for `start_background_task(run_rooms, sio = self.sio)`. 

I assume, eventlet somehow disconnects website socket. 

I also tried gevent from the example, and the effect is the same.

**Comment by miguelgrinberg** [comment]
> communicate with server via socket

Do you mean that you create socket connection and pass information through it? Sockets is another area where async frameworks need specialized functions, because the sockets in the standard library are blocking. See http://eventlet.net/doc/patching.html.

**Comment by ivellios** [comment]
I wrote it wrong. My Thread uses sio from main app file to emit signal to browser client of course. But though it shows in the console log, it never gets into browser. With classic Threads it works fine.

**Comment by miguelgrinberg** [comment]
Can you show me the console output for both the threading and eventlet cases?

**Comment by ivellios** [comment]
Thanks for the answers. I did some changes in the code to fit it with your example and `eventlet` emits get through to the browser, but I have an error in dev tools and console:

```
WebSocket connection to 'ws://localhost:5000/socket.io/?EIO=3&transport=websocket&sid=a6db68f0044a4714aff0e752950d8994' failed: Invalid frame header
```

And in server console:
```
Traceback (most recent call last):
  File "/home/user/.virtualenvs/project/local/lib/python2.7/site-packages/eventlet/wsgi.py", line 507, in handle_one_response
    result = self.application(self.environ, start_response)
  File "/home/user/.virtualenvs/project/local/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/user/.virtualenvs/project/local/lib/python2.7/site-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/user/.virtualenvs/project/local/lib/python2.7/site-packages/socketio/server.py", line 353, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/user/.virtualenvs/project/local/lib/python2.7/site-packages/engineio/server.py", line 261, in handle_request
    environ, start_response)
  File "/home/user/.virtualenvs/project/local/lib/python2.7/site-packages/engineio/socket.py", line 89, in handle_get_request
    start_response)
  File "/home/user/.virtualenvs/project/local/lib/python2.7/site-packages/engineio/socket.py", line 136, in _upgrade_websocket
    return ws(environ, start_response)
  File "/home/user/.virtualenvs/project/local/lib/python2.7/site-packages/engineio/async_eventlet.py", line 19, in __call__
    return super(WebSocketWSGI, self).__call__(environ, start_response)
  File "/home/user/.virtualenvs/project/local/lib/python2.7/site-packages/eventlet/websocket.py", line 127, in __call__
    self.handler(ws)
  File "/home/user/.virtualenvs/project/local/lib/python2.7/site-packages/engineio/socket.py", line 142, in _websocket_handler
    if hasattr(ws, attr) and hasattr(ws.attr, 'settimeout'):
AttributeError: 'RFC6455WebSocket' object has no attribute 'attr'
```

Didn't have them before though. But I think it shouldn't happen anyway.
My files are:

## app.py

```python
from flask import Flask, render_template, url_for, jsonify
import socketio
from config import FlaskConfig
from controller import Controller

sio = socketio.Server(logger=True, async_mode='eventlet')
app = Flask(__name__)
app.wsgi_app = socketio.Middleware(sio, app.wsgi_app)
app.config.from_object('config.FlaskConfig')
rc = Controller(sio)

@app.route('/')
def index():
    """ Main admin website """
    return render_template('index.html')

#####
## SocketIO - Web Sockets Server
#####

@sio.on('connect')
def connect(sid, environ):
    """ Just checking if that works """
    sio.emit('log', data = "Connected")
    pass

@sio.on('start')
def startGame(sid):
    sio.emit('log', data = "Starting game...")
    rc.startThread()

if __name__ == '__main__':
    import eventlet
    import eventlet.wsgi
    eventlet.wsgi.server(eventlet.listen(('', 5000)), app)
```

## controller.py

```python
class Controller():
    def run_me(self):
        self.sio.emit('log', data = "In controller starting game")
        return

    def __init__(self, sio):
        self.sio = sio

    def startThread(self):
        t = self.sio.start_background_task(self.run_me)
        return t
```

## js file
```javascript
$(document).ready(function(){
  // SOCKET.IO
  namespace = '/';
  var socket = io.connect('//' + document.domain + ':' + location.port + namespace);

  // setup connection with sockets
  socket.on('connect', function() {
    // console.log('connected');
  });

  socket.on('log', function(e) {
    console.log('DEBUG:' + e);
  });
});
```

Also I tried gevent, but it doesn't work and gives me similar error:
```
Traceback (most recent call last):
  File "/home/user/.virtualenvs/project/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 936, in handle_one_response
    self.run_application()
  File "/home/user/.virtualenvs/project/local/lib/python2.7/site-packages/geventwebsocket/handler.py", line 75, in run_application
    self.run_websocket()
  File "/home/user/.virtualenvs/project/local/lib/python2.7/site-packages/geventwebsocket/handler.py", line 52, in run_websocket
    list(self.application(self.environ, lambda s, h, e=None: []))
  File "/home/user/.virtualenvs/project/local/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/user/.virtualenvs/project/local/lib/python2.7/site-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/user/.virtualenvs/project/local/lib/python2.7/site-packages/socketio/server.py", line 353, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/user/.virtualenvs/project/local/lib/python2.7/site-packages/engineio/server.py", line 261, in handle_request
    environ, start_response)
  File "/home/user/.virtualenvs/project/local/lib/python2.7/site-packages/engineio/socket.py", line 89, in handle_get_request
    start_response)
  File "/home/user/.virtualenvs/project/local/lib/python2.7/site-packages/engineio/socket.py", line 136, in _upgrade_websocket
    return ws(environ, start_response)
  File "/home/user/.virtualenvs/project/local/lib/python2.7/site-packages/engineio/async_gevent.py", line 43, in __call__
    return self.app(self)
  File "/home/user/.virtualenvs/project/local/lib/python2.7/site-packages/engineio/socket.py", line 142, in _websocket_handler
    if hasattr(ws, attr) and hasattr(ws.attr, 'settimeout'):
AttributeError: 'WebSocketWSGI' object has no attribute 'attr'
Tue May  9 09:27:52 2017 {'REMOTE_PORT': '60856', 'HTTP_HOST': 'localhost:5000', 'REMOTE_ADDR': '::ffff:127.0.0.1', (hidden keys: 30)} failed with AttributeError
```

**Comment by ivellios** [comment]
And also after about 5-6 minutes I get `Session is disconnected` from engineio :( Any idea, how I can keep it up? Just emit something from time to time?

```
Traceback (most recent call last):
  File "/home/user/.virtualenvs/project/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/user/.virtualenvs/project/lib/python2.7/site-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/user/.virtualenvs/project/lib/python2.7/site-packages/socketio/server.py", line 353, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/user/.virtualenvs/project/lib/python2.7/site-packages/engineio/server.py", line 268, in handle_request
    self.disconnect(sid)
  File "/home/user/.virtualenvs/project/lib/python2.7/site-packages/engineio/server.py", line 202, in disconnect
    self._get_socket(sid).close()
  File "/home/user/.virtualenvs/project/lib/python2.7/site-packages/engineio/server.py", line 411, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'
```

**Comment by miguelgrinberg** [comment]
@ivellios there was a small bug in a release I did last night. I have corrected it now. Please upgrade python-engineio to the latest release, that will solve the `AttributeError: 'RFC6455WebSocket' object has no attribute 'attr'` error.

**Comment by ivellios** [comment]
@miguelgrinberg - upgrade helped, and now I found the issue. So When I run this thread it works fine, but when my `run_me` method has also endless loop, emit never reaches the browser client. So if my method is:

```python
    def run_me(self):
        sleep(2)
        self.sio.emit('log', data = "In controller starting game")
        while True:
            sleep(1)
```
In logs from Flask I have `emitting event "log" to all [/]`, but my browser doesn't show it. When I remove `while` loop it shows up. Should I somehow `dispatch` sio.emits in the loop or something? I tried adding some code and `returns` and when I return from method it hits the browser.

**Comment by miguelgrinberg** [comment]
@ivellios Is your `sleep` function the one from Python? That's not compatible with async frameworks, because it is blocking. Try using `socketio.sleep()` instead, or course, you can use the `eventlet.sleep()` function directly if you prefer.

**Comment by ivellios** [comment]
@miguelgrinberg - you're right, `socketio.sleep` helps. But right now I think the issue is with `pyserial` which seems to break socket and thus the thread never gets emits. I have to stay with classic threads for now, but still fight with that. I suppose you don't have experience with `pyserial` + your `python-socketio`.

**Comment by miguelgrinberg** [comment]
I'm not familiar with pyserial's internals. If it uses threads or any other blocking modules from the standard library, then it's a problem for eventlet. You may want to try monkey patching the standard library, that replaces several blocking functions in the library with non-blocking equivalents that are compatible with eventlet. To monkey patch, do this at the top your main script, above any other imports:

    import eventlet
    eventlet.monkey_patch()

If that does not work, then I guess a more detailed analysis of what calls pyserial makes that are blocking is going to be necessary, to see how those can be replaced with non-blocking versions.

**Comment by ivellios** [comment]
`monkey_patch` may be little dirty hack, but that works fine for now :) I used `sio.sleep` but now switched to `eventlet.sleep()` - especially as I found to make `monkey_patch` work I have to run empty sleep before (weird, but works).

Anyway: thanks for your help! I appreciate it!

**Comment by pedroth** [comment]
Thanks, this post help me solve this [one](https://stackoverflow.com/questions/55572868/flask-socket-io-doesnt-work-when-emitting-from-thread)
